Repository DevExpress/devextreme-documentation, pull requests merged in 2021-07, with the labels that each got.

#2500 TreeView id: add description
  api-reference/_hidden/dxTreeViewItem/id.md
Labels: 21_1, cherry-pick

#2501 TreeView id: add description (#2500)
  api-reference/_hidden/dxTreeViewItem/id.md
Labels: 21_2, cherry-pick

#2502 Fix a typo in theme.md
  api-reference/10 UI Components/BaseWidget/1 Configuration/theme.md
Labels: 21_1

#2511 Remove code example from Integration with Push Services
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/30 Integration with Push Services.md
Labels: 20_2

#2512 Remove code example from Integration with Push Services
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/30 Integration with Push Services.md
Labels: 21_1, cherry-pick

#2513 Remove code example from Integration with Push Services
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/30 Integration with Push Services.md
Labels: 21_2, cherry-pick

#2505 Fix T1009903 - DataGrid - Search in a header filter doesn't work if postProcess is used
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/30 Change the Generated Data Source.md
Labels: 20_2

#2520 Fix T1009903 - DataGrid - Search in a header filter doesn't work if postProcess is used (#2505)
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/30 Change the Generated Data Source.md
Labels: 21_2, cherry-pick

#2519 Fix T1009903 - DataGrid - Search in a header filter doesn't work if postProcess is used (#2505)
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/30 Change the Generated Data Source.md
Labels: 21_1, cherry-pick

#2514 DataViz: Add missing Vue and React examples
  concepts/05 UI Components/Chart/99 Client-Side Exporting and Printing/05 API.md
  concepts/05 UI Components/PieChart/03 Data Binding/23 Bind Series to Data/05 Directly.md
  concepts/05 UI Components/PieChart/03 Data Binding/23 Bind Series to Data/10 Using a Series Template.md
Labels: 20_2

#2521 DataViz: Add missing Vue and React examples (#2514)
  concepts/05 UI Components/Chart/99 Client-Side Exporting and Printing/05 API.md
  concepts/05 UI Components/PieChart/03 Data Binding/23 Bind Series to Data/05 Directly.md
  concepts/05 UI Components/PieChart/03 Data Binding/23 Bind Series to Data/10 Using a Series Template.md
Labels: 21_1, cherry-pick

#2522 DataViz: Add missing Vue and React examples (#2514)
  concepts/05 UI Components/Chart/99 Client-Side Exporting and Printing/05 API.md
  concepts/05 UI Components/PieChart/03 Data Binding/23 Bind Series to Data/05 Directly.md
  concepts/05 UI Components/PieChart/03 Data Binding/23 Bind Series to Data/10 Using a Series Template.md
Labels: 21_2, cherry-pick

#2510 Add Vue and React examples to themes.current(themeName)
  api-reference/50 Common/utils/ui/themes/current(themeName).md
Labels: 20_2

#2528 Add Vue and React examples to themes.current(themeName) (#2510)
  api-reference/50 Common/utils/ui/themes/current(themeName).md
Labels: 21_1, cherry-pick

#2529 Add Vue and React examples to themes.current(themeName) (#2510)
  api-reference/50 Common/utils/ui/themes/current(themeName).md
Labels: 21_2, cherry-pick

#2524 Add demo links to Popup API reference
  api-reference/10 UI Components/dxOverlay/1 Configuration/closeOnOutsideClick.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/contentTemplate.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/position.md
  api-reference/10 UI Components/dxOverlay/3 Methods/hide().md
  api-reference/10 UI Components/dxOverlay/3 Methods/show().md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/showTitle.md
  api-reference/10 UI Components/dxPopup/1 Configuration/title.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/location.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/options.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/toolbar.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/toolbarItems.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/widget.md
  api-reference/10 UI Components/dxPopup/1 Configuration/visible.md
Labels: 20_2

#2515 Add demo links to Form API reference
  api-reference/10 UI Components/dxForm/1 Configuration/colCount.md
  api-reference/10 UI Components/dxForm/1 Configuration/customizeItem.md
  api-reference/10 UI Components/dxForm/1 Configuration/items.md
  api-reference/10 UI Components/dxForm/1 Configuration/labelLocation.md
  api-reference/10 UI Components/dxForm/1 Configuration/minColWidth.md
  api-reference/10 UI Components/dxForm/1 Configuration/readOnly.md
  api-reference/10 UI Components/dxForm/1 Configuration/showColonAfterLabel.md
  api-reference/10 UI Components/dxForm/1 Configuration/showValidationSummary.md
  api-reference/10 UI Components/dxForm/1 Configuration/width.md
  api-reference/10 UI Components/dxForm/3 Methods/itemOption(id_option_value).md
  api-reference/10 UI Components/dxForm/5 Item Types/ButtonItem/buttonOptions.md
  api-reference/10 UI Components/dxForm/5 Item Types/ButtonItem/cssClass.md
  api-reference/10 UI Components/dxForm/5 Item Types/ButtonItem/horizontalAlignment.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/caption.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/colSpan.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/cssClass.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/itemType.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/items.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/colSpan.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/cssClass.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/dataField.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorOptions.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorType.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/helpText.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/label.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/itemType.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabPanelOptions.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/items.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/tabs.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/title.md
Labels: 20_2

#2535 Add demo links to Form API reference
  api-reference/10 UI Components/dxForm/1 Configuration/colCount.md
  api-reference/10 UI Components/dxForm/1 Configuration/customizeItem.md
  api-reference/10 UI Components/dxForm/1 Configuration/items.md
  api-reference/10 UI Components/dxForm/1 Configuration/labelLocation.md
  api-reference/10 UI Components/dxForm/1 Configuration/minColWidth.md
  api-reference/10 UI Components/dxForm/1 Configuration/readOnly.md
  api-reference/10 UI Components/dxForm/1 Configuration/showColonAfterLabel.md
  api-reference/10 UI Components/dxForm/1 Configuration/showValidationSummary.md
  api-reference/10 UI Components/dxForm/1 Configuration/width.md
  api-reference/10 UI Components/dxForm/3 Methods/itemOption(id_option_value).md
  api-reference/10 UI Components/dxForm/5 Item Types/ButtonItem/buttonOptions.md
  api-reference/10 UI Components/dxForm/5 Item Types/ButtonItem/cssClass.md
  api-reference/10 UI Components/dxForm/5 Item Types/ButtonItem/horizontalAlignment.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/caption.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/colSpan.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/cssClass.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/itemType.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/items.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/colSpan.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/cssClass.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/dataField.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorOptions.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorType.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/helpText.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/label.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/itemType.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabPanelOptions.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/items.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/tabs.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/title.md
  includes/common-link-configurewidget.md
Labels: 21_1, cherry-pick

#2537 Add demo links to List API reference
  api-reference/10 UI Components/CollectionWidget/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxList/1 Configuration/collapsibleGroups.md
  api-reference/10 UI Components/dxList/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxList/1 Configuration/itemDragging.md
  api-reference/10 UI Components/dxList/1 Configuration/itemTemplate.md
  api-reference/10 UI Components/dxList/1 Configuration/items/items.md
  api-reference/10 UI Components/dxList/1 Configuration/keyExpr.md
  api-reference/10 UI Components/dxList/1 Configuration/onItemDeleted.md
  api-reference/10 UI Components/dxList/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxList/1 Configuration/pageLoadMode.md
  api-reference/10 UI Components/dxList/1 Configuration/repaintChangesOnly.md
  api-reference/10 UI Components/dxList/1 Configuration/searchEnabled.md
  api-reference/10 UI Components/dxList/1 Configuration/searchExpr.md
  api-reference/10 UI Components/dxList/1 Configuration/searchMode.md
  api-reference/10 UI Components/dxList/1 Configuration/selectedItemKeys.md
  api-reference/10 UI Components/dxList/1 Configuration/showSelectionControls.md
Labels: 20_2

#2565 Add links to HtmlEditor API reference
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/mediaResizing/mediaResizing.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/toolbar/toolbar.md
  api-reference/_hidden/dxHtmlEditorToolbarItem/acceptedValues.md
  api-reference/_hidden/dxHtmlEditorToolbarItem/options.md
Labels: 21_1

#2570 Add links to HtmlEditor API reference (#2565)
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/mediaResizing/mediaResizing.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/toolbar/toolbar.md
  api-reference/_hidden/dxHtmlEditorToolbarItem/acceptedValues.md
  api-reference/_hidden/dxHtmlEditorToolbarItem/options.md
Labels: 21_2, cherry-pick

#2573 Remove the contents of Section 508
  concepts/Common/Accessibility/Section 508/10 Summary Table - Voluntary Product Accessibility Template.md
  concepts/Common/Accessibility/Section 508/20 Section 1194.22 Web-based Intranet and Internet information and applications.md
  concepts/Common/Accessibility/Section 508/30 Section 1194.31 Functional Performance Criteria.md
  concepts/Common/Accessibility/Section 508/40 Section 1194.41 Information, Documentation and Support.md
  concepts/Common/Accessibility/Section 508/Section 508.md
Labels: 20_2

#2575 Remove the contents of Section 508 (#2573)
  concepts/Common/Accessibility/Section 508/10 Summary Table - Voluntary Product Accessibility Template.md
  concepts/Common/Accessibility/Section 508/20 Section 1194.22 Web-based Intranet and Internet information and applications.md
  concepts/Common/Accessibility/Section 508/30 Section 1194.31 Functional Performance Criteria.md
  concepts/Common/Accessibility/Section 508/40 Section 1194.41 Information, Documentation and Support.md
  concepts/Common/Accessibility/Section 508/Section 508.md
Labels: 21_2, cherry-pick

#2576 Remove ASP.NET content from the Apply a Theme article
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
Labels: 20_2

#2577 Remove ASP.NET content from the Apply a Theme article (#2576)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
Labels: 21_1, cherry-pick

#2578 Remove ASP.NET content from the Apply a Theme article (#2576) (#2577)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
Labels: 21_2, cherry-pick

#2580 TreeView: Fix DocIssues about selection methods
  api-reference/10 UI Components/dxTreeView/1 Configuration/selectNodesRecursive.md
  api-reference/10 UI Components/dxTreeView/3 Methods/getSelectedNodeKeys().md
  api-reference/10 UI Components/dxTreeView/3 Methods/getSelectedNodes().md
Labels: 20_2

#2581 TreeView: Fix DocIssues about selection methods (#2580)
  api-reference/10 UI Components/dxTreeView/1 Configuration/selectNodesRecursive.md
  api-reference/10 UI Components/dxTreeView/3 Methods/getSelectedNodeKeys().md
  api-reference/10 UI Components/dxTreeView/3 Methods/getSelectedNodes().md
Labels: 21_1, cherry-pick

#2582 TreeView: Fix DocIssues about selection methods (#2580)
  api-reference/10 UI Components/dxTreeView/1 Configuration/selectNodesRecursive.md
  api-reference/10 UI Components/dxTreeView/3 Methods/getSelectedNodeKeys().md
  api-reference/10 UI Components/dxTreeView/3 Methods/getSelectedNodes().md
Labels: 21_2, cherry-pick

#2583 Use tools v7
  package.json
Labels: 21_2

#2585 PieChart: Add a couple of Vue and React exampls
  concepts/05 UI Components/Chart/10 Series/40 Access a Series Using the API.md
  concepts/05 UI Components/Chart/14 Series Points/25 Access a Series Point Using the API.md
  concepts/05 UI Components/PieChart/10 Series/45 Access a Point Using the API.md
Labels: 20_2

#2586 PieChart: Add a couple of Vue and React exampls (#2585)
  concepts/05 UI Components/Chart/10 Series/40 Access a Series Using the API.md
  concepts/05 UI Components/Chart/14 Series Points/25 Access a Series Point Using the API.md
  concepts/05 UI Components/PieChart/10 Series/45 Access a Point Using the API.md
Labels: 21_1, cherry-pick

#2587 PieChart: Add a couple of Vue and React exampls (#2585)
  concepts/05 UI Components/Chart/10 Series/40 Access a Series Using the API.md
  concepts/05 UI Components/Chart/14 Series Points/25 Access a Series Point Using the API.md
  concepts/05 UI Components/PieChart/10 Series/45 Access a Point Using the API.md
Labels: 21_2, cherry-pick

#2588 Fix a PivotGrid demo link
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/sortBySummaryField.md
Labels: 20_2

#2589 Fix a PivotGrid demo link
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/sortBySummaryField.md
Labels: 21_1, cherry-pick

#2590 Fix a PivotGrid demo link
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/sortBySummaryField.md
Labels: 21_2, cherry-pick

#2584 Switch back to 6.4.4 tools
  package.json
Labels: 21_2

#2571 Fix the dateSerializationFormat description
  api-reference/10 UI Components/GridBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateSerializationFormat.md
  includes/uiwidgets-ref-dateSerializationFormat.md
Labels: 20_2

#2595 Fix the dateSerializationFormat description (#2571)
  api-reference/10 UI Components/GridBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateSerializationFormat.md
  includes/uiwidgets-ref-dateSerializationFormat.md
Labels: 21_1, cherry-pick

#2596 Fix the dateSerializationFormat description (#2571)
  api-reference/10 UI Components/GridBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateSerializationFormat.md
  includes/uiwidgets-ref-dateSerializationFormat.md
Labels: 21_2, cherry-pick

#2572 Getting Started with FAB: Remove background-color from embedded examples
  applications/GettingStartedWith/FloatingActionButton/HandleScreenTransitions/index.css
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.css
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.html
  applications/GettingStartedWith/FloatingActionButton/SingleAction/index.css
  applications/GettingStartedWith/FloatingActionButton/SingleAction/index.html
Labels: 20_2

#2606 Getting Started with FAB: Remove background-color from embedded examples (#2572)
  applications/GettingStartedWith/FloatingActionButton/HandleScreenTransitions/index.css
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.css
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.html
  applications/GettingStartedWith/FloatingActionButton/SingleAction/index.css
  applications/GettingStartedWith/FloatingActionButton/SingleAction/index.html
Labels: 21_1, cherry-pick

#2607 Getting Started with FAB: Remove background-color from embedded examples (#2572)
  applications/GettingStartedWith/FloatingActionButton/HandleScreenTransitions/index.css
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.css
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.html
  applications/GettingStartedWith/FloatingActionButton/SingleAction/index.css
  applications/GettingStartedWith/FloatingActionButton/SingleAction/index.html
Labels: 21_2, cherry-pick

#2618 Describe --bootstrap-version parameter for devextreme-cli (#2616)
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/10 Command-Line Arguments.md
Labels: 21_1, cherry-pick

#2533 Add demo links to DateBox API reference
  api-reference/10 UI Components/Widget/1 Configuration/disabled.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/applyValueMode.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/disabled.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/disabledDates.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/max.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/min.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/placeholder.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/showClearButton.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/type.md
Labels: 20_2

#2608 Update the Potentially Vulnerable API article
  api-reference/10 UI Components/CollectionWidget/1 Configuration/noDataText.md
  api-reference/10 UI Components/GridBase/1 Configuration/noDataText.md
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/noDataText.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/noDataText.md
  api-reference/10 UI Components/dxMap/1 Configuration/markers/tooltip/text.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/html.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/noDataText.md
  api-reference/50 Common/Object Structures/dxSchedulerAppointment/html.md
  api-reference/50 Common/utils/ui/dialog/alert(messageHtml_title).md
  api-reference/50 Common/utils/ui/dialog/confirm(messageHtml_title).md
  api-reference/50 Common/utils/ui/dialog/custom(options).md
  api-reference/_hidden/CollectionWidgetItem/html.md
  api-reference/_hidden/GridBaseColumn/encodeHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/customizeTooltip.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/markers[].tooltip.text.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/messageHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/noDataText.md
  includes/dataviz-customize-tooltip-return.md
Labels: 20_2

#2627 Update the Potentially Vulnerable API article (#2608)
  api-reference/10 UI Components/CollectionWidget/1 Configuration/noDataText.md
  api-reference/10 UI Components/GridBase/1 Configuration/noDataText.md
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/noDataText.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/noDataText.md
  api-reference/10 UI Components/dxMap/1 Configuration/markers/tooltip/text.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/html.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/noDataText.md
  api-reference/50 Common/Object Structures/dxSchedulerAppointment/html.md
  api-reference/50 Common/utils/ui/dialog/alert(messageHtml_title).md
  api-reference/50 Common/utils/ui/dialog/confirm(messageHtml_title).md
  api-reference/50 Common/utils/ui/dialog/custom(options).md
  api-reference/_hidden/CollectionWidgetItem/html.md
  api-reference/_hidden/GridBaseColumn/encodeHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/customizeTooltip.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/markers[].tooltip.text.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/messageHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/noDataText.md
  includes/dataviz-customize-tooltip-return.md
Labels: 21_1, cherry-pick

#2629 Update the Potentially Vulnerable API article (#2608)
  api-reference/10 UI Components/CollectionWidget/1 Configuration/noDataText.md
  api-reference/10 UI Components/GridBase/1 Configuration/noDataText.md
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/noDataText.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/noDataText.md
  api-reference/10 UI Components/dxMap/1 Configuration/markers/tooltip/text.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/html.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/noDataText.md
  api-reference/50 Common/Object Structures/dxSchedulerAppointment/html.md
  api-reference/50 Common/utils/ui/dialog/alert(messageHtml_title).md
  api-reference/50 Common/utils/ui/dialog/confirm(messageHtml_title).md
  api-reference/50 Common/utils/ui/dialog/custom(options).md
  api-reference/_hidden/CollectionWidgetItem/html.md
  api-reference/_hidden/GridBaseColumn/encodeHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/customizeTooltip.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/markers[].tooltip.text.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/messageHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/noDataText.md
  includes/dataviz-customize-tooltip-return.md
Labels: 21_2, cherry-pick

#2630 Fix T1016254: DataGrid - refresh() updates data rows
  api-reference/10 UI Components/GridBase/3 Methods/refresh().md
  api-reference/10 UI Components/GridBase/3 Methods/refresh(changesOnly).md
Labels: 20_2

#2631 Fix T1016254: DataGrid - refresh() updates data rows (#2630)
  api-reference/10 UI Components/GridBase/3 Methods/refresh().md
  api-reference/10 UI Components/GridBase/3 Methods/refresh(changesOnly).md
Labels: 21_1, cherry-pick

#2632 Fix T1016254: DataGrid - refresh() updates data rows (#2630)
  api-reference/10 UI Components/GridBase/3 Methods/refresh().md
  api-reference/10 UI Components/GridBase/3 Methods/refresh(changesOnly).md
Labels: 21_2, cherry-pick

#2633 Fix T1016225: Code snippets are shown incorrectly
  concepts/05 UI Components/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
Labels: 20_2

#2634 Fix T1016225: Code snippets are shown incorrectly (#2633)
  concepts/05 UI Components/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
Labels: 21_1, cherry-pick

#2635 Fix T1016225: Code snippets are shown incorrectly (#2633)
  concepts/05 UI Components/TreeView/20 Expand and Collapse Nodes/05 Using the API.md
Labels: 21_2, cherry-pick

#2591 TreeView: add the "getting started" article
  applications/GettingStartedWith/TreeView/index.css
  applications/GettingStartedWith/TreeView/index.html
  applications/GettingStartedWith/TreeView/index.js
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/00 Getting Started with TreeView.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/02 Create a TreeView.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/05 Bind the TreeView to Data.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/10 Customize Node Appearance.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/30 Search Data.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/50 Select Records.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/60 Enable Node Drag & Drop.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/70 Enhance Performance on Large Datasets.md
Labels: 21_1

#2636 TreeView: add "getting started"
  applications/GettingStartedWith/TreeView/index.css
  applications/GettingStartedWith/TreeView/index.html
  applications/GettingStartedWith/TreeView/index.js
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/00 Getting Started with TreeView.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/02 Create a TreeView.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/05 Bind the TreeView to Data.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/10 Customize Node Appearance.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/30 Search Data.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/50 Select Records.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/60 Enable Node Drag & Drop.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/70 Enhance Performance on Large Datasets.md
Labels: 20_2, cherry-pick

#2637 TreeView: add "getting started"
  applications/GettingStartedWith/TreeView/index.css
  applications/GettingStartedWith/TreeView/index.html
  applications/GettingStartedWith/TreeView/index.js
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/00 Getting Started with TreeView.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/02 Create a TreeView.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/05 Bind the TreeView to Data.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/10 Customize Node Appearance.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/30 Search Data.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/50 Select Records.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/60 Enable Node Drag & Drop.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/70 Enhance Performance on Large Datasets.md
Labels: 21_2, cherry-pick

#2628 Add tags to framework-related articles
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/40 Angular Components/10 Getting Started/02 Create a DevExtreme Application.md
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/Add DevExtreme to an Angular CLI Application.md
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/04 Using Webpack/Using Webpack.md
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/05 Using Ionic/Using Ionic.md
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/06 Using Rollup/Using Rollup.md
  concepts/40 Angular Components/20 Component Configuration Syntax/Component Configuration Syntax.md
  concepts/40 Angular Components/30 Application Template/00 Application Template.md
  concepts/40 Angular Components/40 Common Features/05 Server-Side Rendering/00 Server-Side Rendering.md
  concepts/40 Angular Components/40 Common Features/10 Tree Shaking.md
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/20 Add DevExtreme to an ASP.NET Core Angular Application.md
  concepts/40 Angular Components/70 Visual Studio Integration/50 Scaffold an Angular Component.md
  concepts/40 Angular Components/80 Supported Versions.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/50 React Components/02 Create a DevExtreme Application.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/00 Add DevExtreme to a React Application.md
  concepts/50 React Components/20 State Management/0 State Management.md
  concepts/50 React Components/40 Component Configuration Syntax/00 Component Configuration Syntax.md
  concepts/50 React Components/50 Application Template/00 Application Template.md
  concepts/50 React Components/70 TypeScript Support.md
  concepts/50 React Components/80 Supported Versions.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/55 Vue Components/02 Create a DevExtreme Application.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/00 Add DevExtreme to a Vue Application.md
  concepts/55 Vue Components/20 Component Configuration Syntax/Component Configuration Syntax.md
  concepts/55 Vue Components/50 Application Template/00 Application Template.md
  concepts/55 Vue Components/70 TypeScript Support.md
  concepts/55 Vue Components/80 Supported Versions.md
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/00 Add DevExtreme to a jQuery Application.md
  concepts/58 jQuery Components/20 Component Configuration Syntax/01 Create and Configure a Component.md
  concepts/58 jQuery Components/20 Component Configuration Syntax/Component Configuration Syntax.md
  concepts/58 jQuery Components/80 Supported Versions.md
Labels: 20_2

#2642 Add tags to framework-related articles (#2628)
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/40 Angular Components/10 Getting Started/02 Create a DevExtreme Application.md
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/Add DevExtreme to an Angular CLI Application.md
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/04 Using Webpack/Using Webpack.md
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/05 Using Ionic/Using Ionic.md
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/06 Using Rollup/Using Rollup.md
  concepts/40 Angular Components/20 Component Configuration Syntax/Component Configuration Syntax.md
  concepts/40 Angular Components/30 Application Template/00 Application Template.md
  concepts/40 Angular Components/40 Common Features/05 Server-Side Rendering/00 Server-Side Rendering.md
  concepts/40 Angular Components/40 Common Features/10 Tree Shaking.md
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/20 Add DevExtreme to an ASP.NET Core Angular Application.md
  concepts/40 Angular Components/70 Visual Studio Integration/50 Scaffold an Angular Component.md
  concepts/40 Angular Components/80 Supported Versions.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/50 React Components/02 Create a DevExtreme Application.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/00 Add DevExtreme to a React Application.md
  concepts/50 React Components/20 State Management/0 State Management.md
  concepts/50 React Components/40 Component Configuration Syntax/00 Component Configuration Syntax.md
  concepts/50 React Components/50 Application Template/00 Application Template.md
  concepts/50 React Components/70 TypeScript Support.md
  concepts/50 React Components/80 Supported Versions.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/55 Vue Components/02 Create a DevExtreme Application.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/00 Add DevExtreme to a Vue Application.md
  concepts/55 Vue Components/20 Component Configuration Syntax/Component Configuration Syntax.md
  concepts/55 Vue Components/50 Application Template/00 Application Template.md
  concepts/55 Vue Components/70 TypeScript Support.md
  concepts/55 Vue Components/80 Supported Versions.md
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/00 Add DevExtreme to a jQuery Application.md
  concepts/58 jQuery Components/20 Component Configuration Syntax/01 Create and Configure a Component.md
  concepts/58 jQuery Components/20 Component Configuration Syntax/Component Configuration Syntax.md
  concepts/58 jQuery Components/80 Supported Versions.md
Labels: 21_2, cherry-pick

#2643 Add tags to framework-related articles (#2628)
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/40 Angular Components/10 Getting Started/02 Create a DevExtreme Application.md
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/Add DevExtreme to an Angular CLI Application.md
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/04 Using Webpack/Using Webpack.md
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/05 Using Ionic/Using Ionic.md
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/06 Using Rollup/Using Rollup.md
  concepts/40 Angular Components/20 Component Configuration Syntax/Component Configuration Syntax.md
  concepts/40 Angular Components/30 Application Template/00 Application Template.md
  concepts/40 Angular Components/40 Common Features/05 Server-Side Rendering/00 Server-Side Rendering.md
  concepts/40 Angular Components/40 Common Features/10 Tree Shaking.md
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/20 Add DevExtreme to an ASP.NET Core Angular Application.md
  concepts/40 Angular Components/70 Visual Studio Integration/50 Scaffold an Angular Component.md
  concepts/40 Angular Components/80 Supported Versions.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/50 React Components/02 Create a DevExtreme Application.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/00 Add DevExtreme to a React Application.md
  concepts/50 React Components/20 State Management/0 State Management.md
  concepts/50 React Components/40 Component Configuration Syntax/00 Component Configuration Syntax.md
  concepts/50 React Components/50 Application Template/00 Application Template.md
  concepts/50 React Components/70 TypeScript Support.md
  concepts/50 React Components/80 Supported Versions.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/55 Vue Components/02 Create a DevExtreme Application.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/00 Add DevExtreme to a Vue Application.md
  concepts/55 Vue Components/20 Component Configuration Syntax/Component Configuration Syntax.md
  concepts/55 Vue Components/50 Application Template/00 Application Template.md
  concepts/55 Vue Components/70 TypeScript Support.md
  concepts/55 Vue Components/80 Supported Versions.md
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/00 Add DevExtreme to a jQuery Application.md
  concepts/58 jQuery Components/20 Component Configuration Syntax/01 Create and Configure a Component.md
  concepts/58 jQuery Components/20 Component Configuration Syntax/Component Configuration Syntax.md
  concepts/58 jQuery Components/80 Supported Versions.md
Labels: 21_1, cherry-pick

#2650 Add approaches for MenuConfig.xml
  MenuConfig.xml
Labels: 21_1

#2651 Add approaches for MenuConfig.xml
  MenuConfig.xml
Labels: 21_2, cherry-pick

#2653 Fix validation
  api-reference/10 UI Components/dxAccordion/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedIndex.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedItem.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedItemKeys.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedItems.md
  api-reference/10 UI Components/dxAccordion/4 Events/selectionChanged.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/fieldChooser/layout.md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/child(direction_fieldValue).md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/field(area).md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/grandTotal(direction).md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/slice(field_value).md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/layout.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/excelExporter/exportPivotGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/viz/viz.md
  concepts/05 UI Components/PivotGrid/020 Fields and Areas/20 Areas.md
  concepts/05 UI Components/PivotGrid/040 Summaries/Summaries.md
  concepts/05 UI Components/PivotGrid/050 Grouping/020 Data Grouping/Data Grouping.md
  concepts/05 UI Components/PivotGrid/080 Filtering/020 Filtering in the UI.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/50 Select Nodes.md
  concepts/60 Themes and Styles/20 SVG-Based Components Customization/SVG-Based Components Customization.md
  concepts/Common/Localization/20 Right-to-Left Support.md
Labels: 20_2

#2644 Support validation docs
  .github/workflows/nodejs.yml
  api-reference/10 UI Components/dxAccordion/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedIndex.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedItem.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedItemKeys.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedItems.md
  api-reference/10 UI Components/dxAccordion/4 Events/selectionChanged.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxGantt/3 Methods/exportToPdf(options).md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/fieldChooser/layout.md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/child(direction_fieldValue).md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/field(area).md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/grandTotal(direction).md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/slice(field_value).md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/layout.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/excelExporter/exportPivotGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/viz/viz.md
  api-reference/_hidden/DataChange/index.md
  api-reference/_hidden/DataChange/pageIndex.md
  concepts/05 UI Components/PivotGrid/020 Fields and Areas/20 Areas.md
  concepts/05 UI Components/PivotGrid/040 Summaries/Summaries.md
  concepts/05 UI Components/PivotGrid/050 Grouping/020 Data Grouping/Data Grouping.md
  concepts/05 UI Components/PivotGrid/080 Filtering/020 Filtering in the UI.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/50 Select Nodes.md
  concepts/05 UI Components/zz Common/10 Data Visualization Widgets/90 Charts - End-User Interaction/6 Zooming and Scrolling/01 Using dxRangeSelector.md
  concepts/05 UI Components/zz Common/10 Data Visualization Widgets/90 Charts - End-User Interaction/6 Zooming and Scrolling/03 Using the Scroll Bar.md
  concepts/60 Themes and Styles/20 SVG-Based Components Customization/SVG-Based Components Customization.md
  concepts/Common/Localization/20 Right-to-Left Support.md
  package.json
Labels: 21_1
