Repository DevExpress/devextreme-documentation, pull requests merged in 2021-08, with the labels that each got.

#2649 Support validation docs
  .github/workflows/nodejs.yml
  api-reference/10 UI Components/dxAccordion/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedIndex.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedItem.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedItemKeys.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/selectedItems.md
  api-reference/10 UI Components/dxAccordion/4 Events/selectionChanged.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxGantt/3 Methods/exportToPdf(options).md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/fieldChooser/layout.md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/child(direction_fieldValue).md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/field(area).md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/grandTotal(direction).md
  api-reference/10 UI Components/dxPivotGrid/5 Summary Cell/slice(field_value).md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/layout.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/excelExporter/exportPivotGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/viz/viz.md
  api-reference/_hidden/DataChange/index.md
  api-reference/_hidden/DataChange/pageIndex.md
  concepts/05 UI Components/PivotGrid/020 Fields and Areas/20 Areas.md
  concepts/05 UI Components/PivotGrid/040 Summaries/Summaries.md
  concepts/05 UI Components/PivotGrid/050 Grouping/020 Data Grouping/Data Grouping.md
  concepts/05 UI Components/PivotGrid/080 Filtering/020 Filtering in the UI.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/50 Select Nodes.md
  concepts/05 UI Components/zz Common/10 Data Visualization Widgets/30 Data Formatting/22 Numeric Formats.md
  concepts/05 UI Components/zz Common/10 Data Visualization Widgets/30 Data Formatting/24 Date-Time Formats.md
  concepts/05 UI Components/zz Common/10 Data Visualization Widgets/30 Data Formatting/25 Currency Formats.md
  concepts/05 UI Components/zz Common/10 Data Visualization Widgets/30 Data Formatting/26 Custom Format.md
  concepts/05 UI Components/zz Common/10 Data Visualization Widgets/90 Charts - End-User Interaction/6 Zooming and Scrolling/01 Using dxRangeSelector.md
  concepts/05 UI Components/zz Common/10 Data Visualization Widgets/90 Charts - End-User Interaction/6 Zooming and Scrolling/03 Using the Scroll Bar.md
  concepts/60 Themes and Styles/20 SVG-Based Components Customization/SVG-Based Components Customization.md
  concepts/Common/Localization/20 Right-to-Left Support.md
  package.json
Labels: 21_2, cherry-pick

#2686 Avoid not LDML patterns in documentation
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: 21_2

#2718 Avoid not LDML patterns in documentation (#2686)
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: 21_1, cherry-pick

#2720 Avoid not LDML patterns in documentation (#2686)
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: 20_2, cherry-pick

#2719 Scheduler: currentView should be in the View Switcher (#2695)
  api-reference/10 UI Components/dxScheduler/1 Configuration/currentView.md
Labels: 21_1, cherry-pick

#2721 Scheduler: currentView should be in the View Switcher (#2695)
  api-reference/10 UI Components/dxScheduler/1 Configuration/currentView.md
Labels: cherry-pick, 21_2

#2732 Fix T1023119 - Chart - Ellipsis does not work for labels when they are rotated
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/textOverflow.md
Labels: 20_2

#2733 Fix T1023119 - Chart - Ellipsis does not work for labels when they are rotated (#2732)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/textOverflow.md
Labels: 21_1, cherry-pick

#2734 Fix T1023119 - Chart - Ellipsis does not work for labels when they are rotated (#2732)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/textOverflow.md
Labels: cherry-pick, 21_2

#2742 Remove void return values
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/stateStoring/customSave.md
  api-reference/_hidden/GridBaseColumn/headerFilter/dataSource.md
Labels: 21_1

#2743 Remove void return values (#2742)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/stateStoring/customSave.md
  api-reference/_hidden/GridBaseColumn/headerFilter/dataSource.md
Labels: cherry-pick, 21_2

#2747 Fix T1023221 - Chart - Module '".../devextreme/viz/export"' has no default export
  concepts/05 UI Components/Funnel/99 Client-Side Exporting and Printing/05 API.md
  concepts/05 UI Components/PieChart/99 Client-Side Exporting and Printing/05 API.md
  concepts/05 UI Components/Sankey/99 Client-Side Exporting and Printing/05 API.md
Labels: 20_2

#2748 Fix T1023221 - Chart - Module '".../devextreme/viz/export"' has no default export (#2747)
  concepts/05 UI Components/Funnel/99 Client-Side Exporting and Printing/05 API.md
  concepts/05 UI Components/PieChart/99 Client-Side Exporting and Printing/05 API.md
  concepts/05 UI Components/Sankey/99 Client-Side Exporting and Printing/05 API.md
Labels: 21_1, cherry-pick

#2749 Fix T1023221 - Chart - Module '".../devextreme/viz/export"' has no default export (#2747)
  concepts/05 UI Components/Funnel/99 Client-Side Exporting and Printing/05 API.md
  concepts/05 UI Components/PieChart/99 Client-Side Exporting and Printing/05 API.md
  concepts/05 UI Components/Sankey/99 Client-Side Exporting and Printing/05 API.md
Labels: cherry-pick, 21_2

#2760 Scheduler scrollTo: add details for the 2nd parameter
  api-reference/10 UI Components/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
Labels: 20_2

#2768 Scheduler scrollTo: add details for the 2nd parameter (#2760)
  api-reference/10 UI Components/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
Labels: 21_1, cherry-pick

#2769 Scheduler scrollTo: add details for the 2nd parameter (#2760)
  api-reference/10 UI Components/dxScheduler/3 Methods/scrollTo(date_group_allDay).md
Labels: cherry-pick, 21_2
