Repository DevExpress/devextreme-documentation, pull requests merged in 2021-09, with the labels that each got.

#2778 Fix T1019675 - Update Data - Array.push is not tracked in Vue 3
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
Labels: 20_2

#2782 Fix T1019675 - Update Data - Array.push is not tracked in Vue 3 (#2778)
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
Labels: 21_1, cherry-pick

#2783 Fix T1019675 - Update Data - Array.push is not tracked in Vue 3 (#2778)
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
Labels: cherry-pick, 21_2

#2781 Angular SSR: Describe DxServerModule
  concepts/40 Angular Components/40 Common Features/05 Server-Side Rendering/00 Server-Side Rendering.md
  concepts/40 Angular Components/40 Common Features/05 Server-Side Rendering/01 Cache Requests on the Server.md
Labels: 21_2

#2784 Store: Fill in empty descriptions
  api-reference/30 Data Layer/Store/1 Configuration/onLoaded.md
  api-reference/30 Data Layer/Store/3 Methods/byKey(key).md
Labels: 21_2

#2626 Grids toolbar: add description
  api-reference/10 UI Components/dxDataGrid/1 Configuration/toolbar.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onToolbarPreparing.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/toolbar.md
  api-reference/_hidden/dxDataGridToolbar/dxDataGridToolbar.md
  api-reference/_hidden/dxDataGridToolbar/items.md
  api-reference/_hidden/dxDataGridToolbarItem/dxDataGridToolbarItem.md
  api-reference/_hidden/dxDataGridToolbarItem/name.md
  api-reference/_hidden/dxTreeListToolbar/dxTreeListToolbar.md
  api-reference/_hidden/dxTreeListToolbar/items.md
  api-reference/_hidden/dxTreeListToolbarItem/dxTreeListToolbarItem.md
  api-reference/_hidden/dxTreeListToolbarItem/name.md
  images/DataGrid/icons/toolbar_groupPanel.png
  images/DataGrid/icons/toolbar_searchPanel.png
  images/DataGrid/toolbar.png
  images/treelist/toolbar.png
  includes/grids-toolbar.md
Labels: 21_2

#2791 Scheduler: Fix recurring appointment DocIssues
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowDragging.md
  api-reference/50 Common/Object Structures/dxSchedulerAppointment/recurrenceRule.md
Labels: 20_2

#2792 Scheduler: Fix recurring appointment DocIssues (#2791)
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowDragging.md
  api-reference/50 Common/Object Structures/dxSchedulerAppointment/recurrenceRule.md
Labels: 21_1, cherry-pick

#2793 Scheduler: Fix recurring appointment DocIssues (#2791)
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowDragging.md
  api-reference/50 Common/Object Structures/dxSchedulerAppointment/recurrenceRule.md
Labels: cherry-pick, 21_2

#2802 Fix T961284 - DevExtreme is not a framework
  api-reference/50 Common/utils/utils/utils.md
  concepts/70 Data Binding/5 Data Layer/0 Overview.md
Labels: 20_2

#2804 Fix T961284 - DevExtreme is not a framework (#2802)
  api-reference/50 Common/utils/utils/utils.md
  concepts/70 Data Binding/5 Data Layer/0 Overview.md
Labels: 21_1, cherry-pick

#2805 Fix T961284 - DevExtreme is not a framework (#2802)
  api-reference/50 Common/utils/utils/utils.md
  concepts/70 Data Binding/5 Data Layer/0 Overview.md
Labels: cherry-pick, 21_2

#2808 Fix T894281 - Update Data Layer illustration
  images/PhoneJS/scheme-data-layer.png
Labels: 21_1, cherry-pick

#2809 Fix T894281 - Update Data Layer illustration
  images/PhoneJS/scheme-data-layer.png
Labels: cherry-pick, 21_2

#2807 Fix T894281 - Update Data Layer illustration
  images/PhoneJS/scheme-data-layer.png
Labels: 20_2

#2806 Fix T929137 - DateBox jQuery Example - Div id in html and javascript code is not the same
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/10 Set the DateBox Type.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/13 Set the Accepted Date Range.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/15 Set the Value.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/20 Handle the Value Change Event.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/25 Disable Specific Dates.md
Labels: 20_2

#2810 Fix T929137 - DateBox jQuery Example - Div id in html and javascript …
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/10 Set the DateBox Type.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/13 Set the Accepted Date Range.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/15 Set the Value.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/20 Handle the Value Change Event.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/25 Disable Specific Dates.md
Labels: 21_1, cherry-pick

#2811 Fix T929137 - DateBox jQuery Example - Div id in html and javascript …
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/10 Set the DateBox Type.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/13 Set the Accepted Date Range.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/15 Set the Value.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/20 Handle the Value Change Event.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/25 Disable Specific Dates.md
Labels: cherry-pick, 21_2

#2812 Fix T1027330 - Grammar - change the article from 'an' to 'a'
  api-reference/10 UI Components/Component/3 Methods/resetOption(optionName).md
  api-reference/10 UI Components/Errors and Warnings/E2103.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/columns/columns.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/commonSeriesSettings/commonSeriesSettings.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/minRange/minRange.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0014.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0016.md
  api-reference/_hidden/GridBaseColumn/lookup/allowClearing.md
  api-reference/_hidden/dxFilterBuilderField/lookup/allowClearing.md
  concepts/05 UI Components/PivotGrid/020 Fields and Areas/30 API/30 Get or Set Field Properties.md
  concepts/05 UI Components/PivotGrid/040 Summaries/30 Custom Summaries.md
  concepts/05 UI Components/PolarChart/10 Visual Elements/050 Axes/03 Axes.md
  concepts/05 UI Components/zz Common/15 Advanced/40 3rd-Party Frameworks Integration API/20 Change Component Properties and Handle Events.md
  concepts/70 Data Binding/5 Data Layer/9 Getters And Setters/1 Getter And Setter Calling Options.md
Labels: 20_2

#2813 Fix T1027330 - Grammar - change the article from 'an' to 'a'
  api-reference/10 UI Components/Component/3 Methods/resetOption(optionName).md
  api-reference/10 UI Components/Errors and Warnings/E2103.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/columns/columns.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/commonSeriesSettings/commonSeriesSettings.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/minRange/minRange.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0014.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0016.md
  api-reference/_hidden/GridBaseColumn/lookup/allowClearing.md
  api-reference/_hidden/dxFilterBuilderField/lookup/allowClearing.md
  concepts/05 UI Components/PivotGrid/020 Fields and Areas/30 API/30 Get or Set Field Properties.md
  concepts/05 UI Components/PivotGrid/040 Summaries/30 Custom Summaries.md
  concepts/05 UI Components/PolarChart/10 Visual Elements/050 Axes/03 Axes.md
  concepts/05 UI Components/zz Common/15 Advanced/40 3rd-Party Frameworks Integration API/20 Change Component Properties and Handle Events.md
  concepts/70 Data Binding/5 Data Layer/9 Getters And Setters/1 Getter And Setter Calling Options.md
Labels: 21_1, cherry-pick

#2814 Fix T1027330 - Grammar - change the article from 'an' to 'a'
  api-reference/10 UI Components/Component/3 Methods/resetOption(optionName).md
  api-reference/10 UI Components/Errors and Warnings/E2103.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/columns/columns.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/commonSeriesSettings/commonSeriesSettings.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/minRange/minRange.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0014.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0016.md
  api-reference/_hidden/GridBaseColumn/lookup/allowClearing.md
  api-reference/_hidden/dxFilterBuilderField/lookup/allowClearing.md
  concepts/05 UI Components/PivotGrid/020 Fields and Areas/30 API/30 Get or Set Field Properties.md
  concepts/05 UI Components/PivotGrid/040 Summaries/30 Custom Summaries.md
  concepts/05 UI Components/PolarChart/10 Visual Elements/050 Axes/03 Axes.md
  concepts/05 UI Components/zz Common/15 Advanced/40 3rd-Party Frameworks Integration API/20 Change Component Properties and Handle Events.md
  concepts/70 Data Binding/5 Data Layer/9 Getters And Setters/1 Getter And Setter Calling Options.md
Labels: cherry-pick, 21_2

#2815 Fix T1026739 - Objects or functions should be outside the rendering function in React
  concepts/50 React Components/40 Component Configuration Syntax/26 Event Handling.md
  concepts/50 React Components/40 Component Configuration Syntax/31 Callback Functions.md
  concepts/50 React Components/40 Component Configuration Syntax/60 Call Methods.md
  concepts/50 React Components/40 Component Configuration Syntax/75 DevExtreme Validation Features.md
Labels: 20_2

#2816 Fix T1026739 - Objects or functions should be outside the rendering function in React (#2815)
  concepts/50 React Components/40 Component Configuration Syntax/26 Event Handling.md
  concepts/50 React Components/40 Component Configuration Syntax/31 Callback Functions.md
  concepts/50 React Components/40 Component Configuration Syntax/60 Call Methods.md
  concepts/50 React Components/40 Component Configuration Syntax/75 DevExtreme Validation Features.md
Labels: 21_1, cherry-pick

#2817 Fix T1026739 - Objects or functions should be outside the rendering function in React (#2815)
  concepts/50 React Components/40 Component Configuration Syntax/26 Event Handling.md
  concepts/50 React Components/40 Component Configuration Syntax/31 Callback Functions.md
  concepts/50 React Components/40 Component Configuration Syntax/60 Call Methods.md
  concepts/50 React Components/40 Component Configuration Syntax/75 DevExtreme Validation Features.md
Labels: cherry-pick, 21_2

#2803 Fix T948324 - adjustOnZoom help topic references a non relevant demo
  api-reference/10 UI Components/dxChart/1 Configuration/adjustOnZoom.md
Labels: 20_2

#2818 Fix T948324 - adjustOnZoom help topic references a non relevant demo (#2803)
  api-reference/10 UI Components/dxChart/1 Configuration/adjustOnZoom.md
Labels: 21_1, cherry-pick

#2819 Fix T948324 - adjustOnZoom help topic references a non relevant demo (#2803)
  api-reference/10 UI Components/dxChart/1 Configuration/adjustOnZoom.md
Labels: cherry-pick, 21_2

#2829 Grids ColumnChooser sortOrder: description
  api-reference/10 UI Components/GridBase/1 Configuration/columnChooser/sortOrder.md
Labels: 21_2

#2832 Describe AnimationState
  api-reference/50 Common/Object Structures/animationConfig/from.md
  api-reference/50 Common/Object Structures/animationConfig/to.md
  api-reference/_hidden/AnimationState/AnimationState.md
  api-reference/_hidden/AnimationState/left.md
  api-reference/_hidden/AnimationState/opacity.md
  api-reference/_hidden/AnimationState/position.md
  api-reference/_hidden/AnimationState/scale.md
  api-reference/_hidden/AnimationState/top.md
Labels: 21_2

#2836 Fix T1028280 - Update note in DataGrid.onRowUpdating
  api-reference/10 UI Components/GridBase/1 Configuration/onRowUpdating.md
Labels: 20_2

#2835 Fix T1028285 - CustomStore.load - All links on the list refer to the same page
  api-reference/30 Data Layer/CustomStore/1 Configuration/load.md
Labels: 20_2

#2847 Fix T1028285 - CustomSotre.load - All links on the list refer to the same page (#2835)
  api-reference/30 Data Layer/CustomStore/1 Configuration/load.md
Labels: 21_1, cherry-pick

#2848 Fix T1028285 - CustomSotre.load - All links on the list refer to the …
  api-reference/30 Data Layer/CustomStore/1 Configuration/load.md
Labels: cherry-pick, 21_2

#2845 Fix T1028280 - Update note in DataGrid.onRowUpdating (#2836)
  api-reference/10 UI Components/GridBase/1 Configuration/onRowUpdating.md
Labels: 21_1, cherry-pick

#2846 Fix T1028280 - Update note in DataGrid.onRowUpdating (#2836)
  api-reference/10 UI Components/GridBase/1 Configuration/onRowUpdating.md
Labels: cherry-pick, 21_2

#2849 PivotGrid: Specify restrictions imposed by the paginate property
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowExpandAll.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowSortingBySummary.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/allowExpandAll.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/allowSortingBySummary.md
Labels: 20_2

#2852 PivotGrid: Specify restrictions imposed the paginate property (#2849)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowExpandAll.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowSortingBySummary.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/allowExpandAll.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/allowSortingBySummary.md
Labels: 21_1, cherry-pick

#2853 PivotGrid: Specify restrictions imposed the paginate property (#2849)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowExpandAll.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowSortingBySummary.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/allowExpandAll.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/allowSortingBySummary.md
Labels: cherry-pick, 21_2

#2854 Export to Excel: Fix ExcelJS reference
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data to Excel.md
Labels: 20_2

#2859 Export to Excel: Fix ExcelJS reference (#2854)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data to Excel.md
Labels: cherry-pick, 21_2

#2858 Export to Excel: Fix ExcelJS reference (#2854)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data to Excel.md
Labels: 21_1, cherry-pick

#2851 DataGrid buttons[].disabled: add description
  api-reference/_hidden/dxDataGridColumnButton/disabled.md
  api-reference/_hidden/dxTreeListColumnButton/disabled.md
Labels: 21_2

#2869 Fix T1029657 - Change "Options" to "Properties" in See Also
  api-reference/10 UI Components/Component/3 Methods/option().md
  api-reference/10 UI Components/Component/3 Methods/option(optionName).md
  api-reference/10 UI Components/Component/3 Methods/option(optionName_optionValue).md
  api-reference/10 UI Components/Component/3 Methods/option(options).md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Form/20 Change Properties at Runtime/05 Form Properties.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Sankey/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
Labels: 20_2

#2870 Fix T1029657 - Change "Options" to "Properties" in See Also (#2869)
  api-reference/10 UI Components/Component/3 Methods/option().md
  api-reference/10 UI Components/Component/3 Methods/option(optionName).md
  api-reference/10 UI Components/Component/3 Methods/option(optionName_optionValue).md
  api-reference/10 UI Components/Component/3 Methods/option(options).md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Form/20 Change Properties at Runtime/05 Form Properties.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Sankey/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
Labels: 21_1, cherry-pick

#2871 Fix T1029657 - Change "Options" to "Properties" in See Also (#2869)
  api-reference/10 UI Components/Component/3 Methods/option().md
  api-reference/10 UI Components/Component/3 Methods/option(optionName).md
  api-reference/10 UI Components/Component/3 Methods/option(optionName_optionValue).md
  api-reference/10 UI Components/Component/3 Methods/option(options).md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Form/20 Change Properties at Runtime/05 Form Properties.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Sankey/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
Labels: cherry-pick, 21_2

#2863 Fix format docissues
  api-reference/10 UI Components/BaseGauge/1 Configuration/scale/label/format.md
  api-reference/10 UI Components/BaseGauge/5 Indicator Types/CommonIndicator/text/format.md
  api-reference/10 UI Components/BaseWidget/1 Configuration/tooltip/format.md
  api-reference/10 UI Components/dxBarGauge/1 Configuration/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/crosshair/horizontalLine/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/crosshair/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/crosshair/verticalLine/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/label/format.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/format.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/groupItems/valueFormat.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/valueFormat.md
  api-reference/10 UI Components/dxFunnel/1 Configuration/label/format.md
  api-reference/10 UI Components/dxPieChart/5 Series Types/CommonPieChartSeries/label/format.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/argumentAxis/label/format.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/valueAxis/label/format.md
  api-reference/10 UI Components/dxPolarChart/5 Series Types/CommonPolarChartSeries/label/format.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/label/format.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/marker/label/format.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/sliderMarker/format.md
  api-reference/10 UI Components/dxSliderBase/1 Configuration/label/format.md
  api-reference/10 UI Components/dxSliderBase/1 Configuration/tooltip/format.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/format.md
  api-reference/50 Common/Object Structures/format/currency.md
  api-reference/50 Common/Object Structures/format/formatter.md
  api-reference/50 Common/Object Structures/format/parser.md
  api-reference/50 Common/Object Structures/format/precision.md
  api-reference/50 Common/Object Structures/format/type.md
  api-reference/_hidden/GridBaseColumn/format.md
  api-reference/_hidden/dxFilterBuilderField/format.md
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: 20_2

#2877 Fix format docissues
  api-reference/10 UI Components/BaseGauge/1 Configuration/scale/label/format.md
  api-reference/10 UI Components/BaseGauge/5 Indicator Types/CommonIndicator/text/format.md
  api-reference/10 UI Components/BaseWidget/1 Configuration/tooltip/format.md
  api-reference/10 UI Components/dxBarGauge/1 Configuration/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/crosshair/horizontalLine/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/crosshair/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/crosshair/verticalLine/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/label/format.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/format.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/groupItems/valueFormat.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/valueFormat.md
  api-reference/10 UI Components/dxFunnel/1 Configuration/label/format.md
  api-reference/10 UI Components/dxPieChart/5 Series Types/CommonPieChartSeries/label/format.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/argumentAxis/label/format.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/valueAxis/label/format.md
  api-reference/10 UI Components/dxPolarChart/5 Series Types/CommonPolarChartSeries/label/format.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/label/format.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/marker/label/format.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/sliderMarker/format.md
  api-reference/10 UI Components/dxSliderBase/1 Configuration/label/format.md
  api-reference/10 UI Components/dxSliderBase/1 Configuration/tooltip/format.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/format.md
  api-reference/50 Common/Object Structures/format/currency.md
  api-reference/50 Common/Object Structures/format/formatter.md
  api-reference/50 Common/Object Structures/format/parser.md
  api-reference/50 Common/Object Structures/format/precision.md
  api-reference/50 Common/Object Structures/format/type.md
  api-reference/_hidden/GridBaseColumn/format.md
  api-reference/_hidden/dxFilterBuilderField/format.md
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: cherry-pick, 21_2

#2876 Fix format docissues
  api-reference/10 UI Components/BaseGauge/1 Configuration/scale/label/format.md
  api-reference/10 UI Components/BaseGauge/5 Indicator Types/CommonIndicator/text/format.md
  api-reference/10 UI Components/BaseWidget/1 Configuration/tooltip/format.md
  api-reference/10 UI Components/dxBarGauge/1 Configuration/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/crosshair/horizontalLine/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/crosshair/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/crosshair/verticalLine/label/format.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/label/format.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/format.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/groupItems/valueFormat.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/valueFormat.md
  api-reference/10 UI Components/dxFunnel/1 Configuration/label/format.md
  api-reference/10 UI Components/dxPieChart/5 Series Types/CommonPieChartSeries/label/format.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/argumentAxis/label/format.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/valueAxis/label/format.md
  api-reference/10 UI Components/dxPolarChart/5 Series Types/CommonPolarChartSeries/label/format.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/label/format.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/marker/label/format.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/sliderMarker/format.md
  api-reference/10 UI Components/dxSliderBase/1 Configuration/label/format.md
  api-reference/10 UI Components/dxSliderBase/1 Configuration/tooltip/format.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/format.md
  api-reference/50 Common/Object Structures/format/currency.md
  api-reference/50 Common/Object Structures/format/formatter.md
  api-reference/50 Common/Object Structures/format/parser.md
  api-reference/50 Common/Object Structures/format/precision.md
  api-reference/50 Common/Object Structures/format/type.md
  api-reference/_hidden/GridBaseColumn/format.md
  api-reference/_hidden/dxFilterBuilderField/format.md
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: 21_1, cherry-pick

#2868 Fix T1030086 - DataGrid - focusedRowIndex is not specific to focusedRowEnabled
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowIndex.md
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowKey.md
Labels: 20_2

#2886 Fix T1030086 - DataGrid - focusedRowIndex is not specific to focusedRowEnabled (#2868)
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowIndex.md
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowKey.md
Labels: 21_1, cherry-pick

#2887 Fix T1030086 - DataGrid - focusedRowIndex is not specific to focusedRowEnabled (#2868)
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowIndex.md
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowKey.md
Labels: cherry-pick, 21_2

#2890 GridBaseColumn: hide lookup.calculateCellValue
  api-reference/_hidden/calculateCellValue.md
Labels: 21_1

#2891 GridBaseColumn: hide lookup.calculateCellValue (#2890)
  api-reference/_hidden/calculateCellValue.md
Labels: cherry-pick, 21_2

#2895 Fix T1031746 - DataGrid.state() - Typo in the code snippet
  api-reference/10 UI Components/GridBase/3 Methods/state().md
Labels: 21_1

#2896 Fix T1031746 - DataGrid.state() - Typo in the code snippet (#2895)
  api-reference/10 UI Components/GridBase/3 Methods/state().md
Labels: 20_2, cherry-pick

#2897 Fix T1031746 - DataGrid.state() - Typo in the code snippet (#2895)
  api-reference/10 UI Components/GridBase/3 Methods/state().md
Labels: cherry-pick, 21_2

#2898 Fix T1031744 - Column Reordering API - Typo in the code snippet
  concepts/05 UI Components/DataGrid/15 Columns/25 Column Reordering/10 API.md
  concepts/05 UI Components/TreeList/10 Columns/25 Column Reordering/10 API.md
Labels: 20_2

#2899 Fix T1031744 - Column Reordering API - Typo in the code snippet
  concepts/05 UI Components/DataGrid/15 Columns/25 Column Reordering/10 API.md
  concepts/05 UI Components/TreeList/10 Columns/25 Column Reordering/10 API.md
Labels: 21_1, cherry-pick

#2900 Fix T1031744 - Column Reordering API - Typo in the code snippet
  concepts/05 UI Components/DataGrid/15 Columns/25 Column Reordering/10 API.md
  concepts/05 UI Components/TreeList/10 Columns/25 Column Reordering/10 API.md
Labels: cherry-pick, 21_2

#2901 Fix T1030290 - Specify that totalCount method always returns -1 if paging is disabled
  api-reference/10 UI Components/dxDataGrid/3 Methods/totalCount().md
Labels: 20_2

#2909 Fix T1030290 - Specify that totalCount method always returns -1 if paging is disabled (#2901)
  api-reference/10 UI Components/dxDataGrid/3 Methods/totalCount().md
Labels: 21_1, cherry-pick

#2910 Fix T1030290 - Specify that totalCount method always returns -1 if paging is disabled (#2901)
  api-reference/10 UI Components/dxDataGrid/3 Methods/totalCount().md
Labels: cherry-pick, 21_2

#2916 Fix T1031593 - A minor improvement in the note about CSV export
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  includes/uiwidgets-grids-export-csv.md
Labels: 21_1

#2918 Fix T1031593 - A minor improvement in the note about CSV export (#2916)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  includes/uiwidgets-grids-export-csv.md
Labels: cherry-pick, 21_2

#2884 Enhance bindChart parameters description
  api-reference/10 UI Components/dxPivotGrid/3 Methods/bindChart(chart_integrationOptions).md
Labels: 21_2

#2919 HtmlEditor: Describe getText return value
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getText(index_length).md
Labels: 21_1

#2922 HtmlEditor: Describe getText return value (#2919)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getText(index_length).md
Labels: cherry-pick, 21_2

#2921 Enhance bindChart parameters description (#2884)
  api-reference/10 UI Components/dxPivotGrid/3 Methods/bindChart(chart_integrationOptions).md
Labels: 21_1, cherry-pick

#2917 Fix Popup.restorePosition
  api-reference/10 UI Components/dxPopup/1 Configuration/restorePosition.md
Labels: 21_2

#2935 Getting Started tutorials: Add installation note
  concepts/05 UI Components/Button/00 Getting Started with Button/00 Getting Started with Button.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/00 Getting Started with DataGrid.md
  concepts/05 UI Components/Form/01 Getting Started with Form/00 Getting Started with Form.md
  concepts/05 UI Components/List/00 Getting Started with List/00 Getting Started with List.md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/00 Getting Started with Popup.md
  concepts/05 UI Components/Scheduler/00 Getting Started with Scheduler/00 Getting Started with Scheduler.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/00 Getting Started with SelectBox.md
  concepts/05 UI Components/TabPanel/01 Getting Started with TabPanel/00 Getting Started with TabPanel.md
  concepts/05 UI Components/TagBox/00 Getting Started with TagBox/00 Getting Started with TagBox.md
  concepts/05 UI Components/TreeList/00 Getting Started with TreeList/00 Getting Started with TreeList.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/00 Getting Started with TreeView.md
Labels: 20_2

#2936 Getting Started tutorials: Add installation note
  concepts/05 UI Components/Button/00 Getting Started with Button/00 Getting Started with Button.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/00 Getting Started with DataGrid.md
  concepts/05 UI Components/Form/01 Getting Started with Form/00 Getting Started with Form.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
  concepts/05 UI Components/List/00 Getting Started with List/00 Getting Started with List.md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/00 Getting Started with Popup.md
  concepts/05 UI Components/Scheduler/00 Getting Started with Scheduler/00 Getting Started with Scheduler.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/00 Getting Started with SelectBox.md
  concepts/05 UI Components/TabPanel/01 Getting Started with TabPanel/00 Getting Started with TabPanel.md
  concepts/05 UI Components/TagBox/00 Getting Started with TagBox/00 Getting Started with TagBox.md
  concepts/05 UI Components/TreeList/00 Getting Started with TreeList/00 Getting Started with TreeList.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/00 Getting Started with TreeView.md
Labels: 21_1, cherry-pick

#2937 Getting Started tutorials: Add installation note
  concepts/05 UI Components/Button/00 Getting Started with Button/00 Getting Started with Button.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/00 Getting Started with DataGrid.md
  concepts/05 UI Components/Form/01 Getting Started with Form/00 Getting Started with Form.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
  concepts/05 UI Components/List/00 Getting Started with List/00 Getting Started with List.md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/00 Getting Started with Popup.md
  concepts/05 UI Components/Scheduler/00 Getting Started with Scheduler/00 Getting Started with Scheduler.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/00 Getting Started with SelectBox.md
  concepts/05 UI Components/TabPanel/01 Getting Started with TabPanel/00 Getting Started with TabPanel.md
  concepts/05 UI Components/TagBox/00 Getting Started with TagBox/00 Getting Started with TagBox.md
  concepts/05 UI Components/TreeList/00 Getting Started with TreeList/00 Getting Started with TreeList.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/00 Getting Started with TreeView.md
Labels: cherry-pick, 21_2

#2938 Remove TreeView - Overview
  api-reference/10 UI Components/dxMenu/1 Configuration/adaptivityEnabled.md
  api-reference/10 UI Components/dxTreeView/dxTreeView.md
  concepts/05 UI Components/TreeView/00 Overview.md
Labels: 20_2

#2939 Remove TreeView - Overview (#2938)
  api-reference/10 UI Components/dxMenu/1 Configuration/adaptivityEnabled.md
  api-reference/10 UI Components/dxTreeView/dxTreeView.md
  concepts/05 UI Components/TreeView/00 Overview.md
Labels: 21_1, cherry-pick

#2940 Remove TreeView - Overview (#2938) (#2939)
  api-reference/10 UI Components/dxMenu/1 Configuration/adaptivityEnabled.md
  api-reference/10 UI Components/dxTreeView/dxTreeView.md
  concepts/05 UI Components/TreeView/00 Overview.md
Labels: cherry-pick, 21_2
