Repository DevExpress/devextreme-documentation, pull requests merged in 2021-12, with the labels that each got.

#3205 File Manager - Fix beforeSubmit description
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Remote/1 Configuration/beforeSubmit.md
Labels: 21_2

#3209 DataSource: fix an Angular code snippet
  api-reference/30 Data Layer/DataSource/1 Configuration/Configuration.md
Labels: 21_2

#3210 DataSource: fix an Angular code snippet
  api-reference/30 Data Layer/DataSource/1 Configuration/Configuration.md
Labels: cherry-pick, 22_1

#3211 DataSource: Fix an Angular code snippet
  api-reference/30 Data Layer/DataSource/1 Configuration/Configuration.md
Labels: 21_1, cherry-pick

#3217 Fix groupCellTemplate docissues (#1452)
  api-reference/_hidden/dxDataGridColumn/groupCellTemplate.md
Labels: 21_1, cherry-pick

#3219 Fix groupCellTemplate docissues (#1452)
  api-reference/_hidden/dxDataGridColumn/groupCellTemplate.md
Labels: cherry-pick, 22_1

#3220 Charts Resolve Overlapping: Fix a Vue code snippet
  concepts/05 UI Components/Chart/15 Point Labels/10 Resolve Overlapping.md
Labels: 21_2

#3222 Charts Resolve Overlapping: Fix a Vue code snippet
  concepts/05 UI Components/Chart/15 Point Labels/10 Resolve Overlapping.md
Labels: cherry-pick, 22_1

#3221 Charts Resolve Overlapping: Fix a Vue code snippet
  concepts/05 UI Components/Chart/15 Point Labels/10 Resolve Overlapping.md
Labels: 21_1, cherry-pick

#3231 Popup: Describe empty fields in resizing events
  api-reference/10 UI Components/dxPopup/1 Configuration/onResize.md
  api-reference/10 UI Components/dxPopup/1 Configuration/onResizeEnd.md
  api-reference/10 UI Components/dxPopup/1 Configuration/onResizeStart.md
Labels: 21_2

#3232 Popup: Describe empty fields in resizing events (#3231)
  api-reference/10 UI Components/dxPopup/1 Configuration/onResize.md
  api-reference/10 UI Components/dxPopup/1 Configuration/onResizeEnd.md
  api-reference/10 UI Components/dxPopup/1 Configuration/onResizeStart.md
Labels: 21_1, cherry-pick

#3233 Popup: Describe empty fields in resizing events (#3231)
  api-reference/10 UI Components/dxPopup/1 Configuration/onResize.md
  api-reference/10 UI Components/dxPopup/1 Configuration/onResizeEnd.md
  api-reference/10 UI Components/dxPopup/1 Configuration/onResizeStart.md
Labels: cherry-pick, 22_1

#3235 Overlays: Fix the shading property description
  api-reference/10 UI Components/dxOverlay/1 Configuration/shading.md
Labels: 21_2

#3237 Overlays: Fix the shading property description
  api-reference/10 UI Components/dxOverlay/1 Configuration/shading.md
Labels: 21_1, cherry-pick

#3234 Popover and Tooltip: Fix target description
  api-reference/10 UI Components/dxPopover/1 Configuration/target.md
  includes/uiwidgets-ref-target.md
Labels: 21_2

#3238 Overlays: Fix the shading property description (#3235)
  api-reference/10 UI Components/dxOverlay/1 Configuration/shading.md
Labels: cherry-pick, 22_1

#3240 Popover and Tooltip: Fix target description (#3234)
  api-reference/10 UI Components/dxPopover/1 Configuration/target.md
  includes/uiwidgets-ref-target.md
Labels: cherry-pick, 22_1

#3239 Popover and Tooltip: Fix target description (#3234)
  api-reference/10 UI Components/dxPopover/1 Configuration/target.md
  includes/uiwidgets-ref-target.md
Labels: 21_1, cherry-pick

#3241 TextEditors and Form: Add note for labelMode
  api-reference/10 UI Components/dxForm/1 Configuration/labelMode.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/labelMode.md
Labels: 21_2

#3247 TextEditors and Form: Add note for labelMode (#3241)
  api-reference/10 UI Components/dxForm/1 Configuration/labelMode.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/labelMode.md
Labels: cherry-pick, 22_1

#3252 Overlays: Fix height and width description
  api-reference/10 UI Components/dxOverlay/1 Configuration/height.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/width.md
Labels: 21_2

#3253 Overlays: Fix height and width description (#3252)
  api-reference/10 UI Components/dxOverlay/1 Configuration/height.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/width.md
Labels: cherry-pick, 22_1

#3254 Overlays: Fix height and width description (#3252)
  api-reference/10 UI Components/dxOverlay/1 Configuration/height.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/width.md
Labels: 21_1, cherry-pick

#3269 Popup Getting Started: fix resizeEnabled link
  concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Resize the Popup.md
Labels: 21_2

#3272 Drop-down Editors: fix a content link
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/dropDownOptions.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/dropDownOptions.md
Labels: 21_2

#3271 Popup Getting Started: fix resizeEnabled link (#3269)
  concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Resize the Popup.md
Labels: cherry-pick, 22_1

#3273 Drop-down Editors: fix a content link
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/dropDownOptions.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/dropDownOptions.md
Labels: 21_1, cherry-pick

#3274 Drop-down Editors: fix a content link (#3272)
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/dropDownOptions.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/dropDownOptions.md
Labels: cherry-pick, 22_1

#3281 Button: extend description of the behavior in forms
  api-reference/10 UI Components/dxButton/1 Configuration/useSubmitBehavior.md
Labels: 21_2

#3298 Button: extend description of the behavior in forms (#3281)
  api-reference/10 UI Components/dxButton/1 Configuration/useSubmitBehavior.md
Labels: cherry-pick, 22_1

#3297 Button: extend description of the behavior in forms (#3281)
  api-reference/10 UI Components/dxButton/1 Configuration/useSubmitBehavior.md
Labels: 21_1, cherry-pick
