Repository DevExpress/devextreme-documentation, pull requests merged in 2021-05, with the labels that each got.

#2304 Grids state(state): fix
  api-reference/10 UI Components/GridBase/3 Methods/state(state).md
Labels: 20_2

#2307 Grids state(state): fix (#2304)
  api-reference/10 UI Components/GridBase/3 Methods/state(state).md
Labels: 21_1, cherry-pick

#2308 Grids state(state): fix (#2304)
  api-reference/10 UI Components/GridBase/3 Methods/state(state).md
Labels: 21_2, cherry-pick

#2313 TreeList T1000206 stateStoring: add note for columns.visible and fix columns[] properties order
  api-reference/10 UI Components/dxTreeList/1 Configuration/stateStoring/stateStoring.md
Labels: 20_2

#2315 TreeList T1000206 stateStoring: add note for columns.visible
  api-reference/10 UI Components/dxTreeList/1 Configuration/stateStoring/stateStoring.md
Labels: 21_2, cherry-pick

#2314 TreeList T1000206 stateStoring: add note for columns.visible
  api-reference/10 UI Components/dxTreeList/1 Configuration/stateStoring/stateStoring.md
Labels: 21_1, cherry-pick

#2325 Switch Between Themes at Runtime: Mention initialized(callback)
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/5 With Page Reload.md
  includes/switch-themes-initialized-note.md
Labels: 20_2

#2326 GridBase selection.allowSelectAll: reference selectAllMode
  api-reference/10 UI Components/GridBase/1 Configuration/selection/allowSelectAll.md
Labels: 20_2

#2334 GridBase selection.allowSelectAll: reference selectAllMode (#2326)
  api-reference/10 UI Components/GridBase/1 Configuration/selection/allowSelectAll.md
Labels: 21_2, cherry-pick

#2333 GridBase selection.allowSelectAll: reference selectAllMode (#2326)
  api-reference/10 UI Components/GridBase/1 Configuration/selection/allowSelectAll.md
Labels: 21_1, cherry-pick

#2332 Fix DataGrid.filterBuilder docissues (T855505, T861528)
  api-reference/10 UI Components/GridBase/1 Configuration/filterBuilder.md
Labels: 20_2

#2324 DataGrid: W1017 and W1018
  api-reference/10 UI Components/Errors and Warnings/W1017.md
  api-reference/10 UI Components/Errors and Warnings/W1018.md
Labels: 21_1

#2340 DataGrid: W1017 and W1018 (#2324)
  api-reference/10 UI Components/Errors and Warnings/W1017.md
  api-reference/10 UI Components/Errors and Warnings/W1018.md
Labels: 21_2, cherry-pick

#2335 Update calculateFilterExpression and fix T875683, T884232, T892205
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
  api-reference/_hidden/GridBaseColumn/headerFilter/dataSource.md
  api-reference/_hidden/dxFilterBuilderField/calculateFilterExpression.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/10 Specify a Custom Data Source.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/30 Change the Generated Data Source.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/40 Customize Item Appearance.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/Customize Header Filter Data Source.md
Labels: 20_2

#2344 Update calculateFilterExpression and fix T875683, T884232, T892205 (#2335)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
  api-reference/_hidden/GridBaseColumn/headerFilter/dataSource.md
  api-reference/_hidden/dxFilterBuilderField/calculateFilterExpression.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/10 Specify a Custom Data Source.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/30 Change the Generated Data Source.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/40 Customize Item Appearance.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/Customize Header Filter Data Source.md
Labels: 21_1, cherry-pick

#2345 Update calculateFilterExpression and fix T875683, T884232, T892205 (#2335)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
  api-reference/_hidden/GridBaseColumn/headerFilter/dataSource.md
  api-reference/_hidden/dxFilterBuilderField/calculateFilterExpression.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/10 Specify a Custom Data Source.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/30 Change the Generated Data Source.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/40 Customize Item Appearance.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/Customize Header Filter Data Source.md
Labels: 21_2, cherry-pick

#2347 Update external links to the Angular, Vue, and React websites
  api-reference/10 UI Components/DOMComponent/3 Methods/dispose().md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/55 Vue Components/20 Component Configuration Syntax/17 Collections.md
  concepts/55 Vue Components/20 Component Configuration Syntax/32 One-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/33 Two-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/37 Templates.md
  concepts/55 Vue Components/20 Component Configuration Syntax/42 Call Methods.md
  concepts/55 Vue Components/20 Component Configuration Syntax/75 Vue Form Input Bindings Support.md
  concepts/55 Vue Components/70 TypeScript Support.md
Labels: 20_2

#2356 Scheduler Assign Appointments to Resources: link and list formatting
  concepts/05 UI Components/Scheduler/040 Resources/020 Assign Appointments to Resources/Assign Appointments to Resources.md
Labels: 20_2

#2357 Scheduler Assign Appointments to Resources: list formatting
  concepts/05 UI Components/Scheduler/040 Resources/020 Assign Appointments to Resources/Assign Appointments to Resources.md
Labels: 21_2, cherry-pick

#2348 Update external links to the Angular, Vue, and React websites (#2347)
  api-reference/10 UI Components/DOMComponent/3 Methods/dispose().md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/55 Vue Components/20 Component Configuration Syntax/17 Collections.md
  concepts/55 Vue Components/20 Component Configuration Syntax/32 One-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/33 Two-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/37 Templates.md
  concepts/55 Vue Components/20 Component Configuration Syntax/42 Call Methods.md
  concepts/55 Vue Components/20 Component Configuration Syntax/75 Vue Form Input Bindings Support.md
  concepts/55 Vue Components/70 TypeScript Support.md
Labels: 21_1, cherry-pick

#2349 Update external links to the Angular, Vue, and React websites (#2347)
  api-reference/10 UI Components/DOMComponent/3 Methods/dispose().md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/55 Vue Components/20 Component Configuration Syntax/17 Collections.md
  concepts/55 Vue Components/20 Component Configuration Syntax/32 One-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/33 Two-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/37 Templates.md
  concepts/55 Vue Components/20 Component Configuration Syntax/42 Call Methods.md
  concepts/55 Vue Components/20 Component Configuration Syntax/75 Vue Form Input Bindings Support.md
  concepts/55 Vue Components/70 TypeScript Support.md
Labels: 21_2, cherry-pick
