Repository DevExpress/devextreme-documentation, pull requests merged in 2021-11, with the labels that each got.

#3066 DataGrid/TreeList: Add Customize the Toolbar to tutorials
  applications/GettingStartedWith/DataGrid/index.js
  applications/GettingStartedWith/TreeList/index.js
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/50 Select Records.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/65 Customize the Toolbar.md
  concepts/05 UI Components/TreeList/00 Getting Started with TreeList/50 Select Records.md
  concepts/05 UI Components/TreeList/00 Getting Started with TreeList/55 Customize the Toolbar.md
  concepts/05 UI Components/TreeList/00 Getting Started with TreeList/60 Enable Row Drag & Drop.md
  includes/grids-tutorial-customize-the-toolbar.md
Labels: 21_2

#3073 Grids: Fix code in Customize the Toolbar
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/65 Customize the Toolbar.md
  concepts/05 UI Components/TreeList/00 Getting Started with TreeList/55 Customize the Toolbar.md
Labels: 21_2

#3075 Fix T1041754 - One of the selectedRowKeys' demo buttons points to a TreeList demo but it says DataGrid demo (#3074)
  api-reference/10 UI Components/GridBase/1 Configuration/selectedRowKeys.md
Labels: 21_1, cherry-pick

#3076 Fix T1041754 - One of the selectedRowKeys' demo buttons points to a TreeList demo but it says DataGrid demo (#3074)
  api-reference/10 UI Components/GridBase/1 Configuration/selectedRowKeys.md
Labels: 20_2, cherry-pick

#3078 DateBox, SelectBox, TagBox: Create 'Add a Label' topic in Getting Started
  applications/GettingStartedWith/DateBox/index.css
  applications/GettingStartedWith/DateBox/index.js
  applications/GettingStartedWith/SelectBox/index.css
  applications/GettingStartedWith/SelectBox/index.js
  applications/GettingStartedWith/TagBox/index.css
  applications/GettingStartedWith/TagBox/index.js
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/20 Handle the Value Change Event.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/23 Add a Label.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/20 Handle the Value Change Event.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/23 Add a Label.md
  concepts/05 UI Components/TagBox/00 Getting Started with TagBox/45 Add a Label.md
  includes/texteditor-labelMode.md
  includes/tutorials-editors-add-label.md
Labels: 21_2

#3080 Fix minor things in Getting Started with Form
  applications/GettingStartedWith/Form/index.css
  applications/GettingStartedWith/Form/index.js
  concepts/05 UI Components/Form/01 Getting Started with Form/40 Organize the Form Items/20 In Groups.md
  concepts/05 UI Components/Form/01 Getting Started with Form/40 Organize the Form Items/30 In Tabs.md
Labels: 21_2

#3081 Fix minor things in Getting Started with Form (#3080)
  applications/GettingStartedWith/Form/index.css
  applications/GettingStartedWith/Form/index.js
  concepts/05 UI Components/Form/01 Getting Started with Form/40 Organize the Form Items/20 In Groups.md
  concepts/05 UI Components/Form/01 Getting Started with Form/40 Organize the Form Items/30 In Tabs.md
Labels: 21_1, cherry-pick

#3082 Fix minor things in Getting Started with Form (#3080)
  applications/GettingStartedWith/Form/index.css
  applications/GettingStartedWith/Form/index.js
  concepts/05 UI Components/Form/01 Getting Started with Form/40 Organize the Form Items/20 In Groups.md
  concepts/05 UI Components/Form/01 Getting Started with Form/40 Organize the Form Items/30 In Tabs.md
Labels: 20_2, cherry-pick

#3086 Actualize "Create a Custom Bundle" topic
  concepts/Common/Modularity/015 Create a Custom Bundle/Create a Custom Bundle.md
Labels: 21_2

#3085 Update E4011
  api-reference/30 Data Layer/zz Errors and Warnings/E4011.md
Labels: 21_2

#3088 Update E4011 (#3085)
  api-reference/30 Data Layer/zz Errors and Warnings/E4011.md
Labels: 20_2, cherry-pick

#3089 Update E4011 (#3085)
  api-reference/30 Data Layer/zz Errors and Warnings/E4011.md
Labels: 21_1, cherry-pick

#3100 Fix T1043062 - TreeList - Command Columns - Remove code snippet
  concepts/05 UI Components/TreeList/10 Columns/10 Column Types/4 Command Columns/05 Configure a Command Column.md
Labels: 21_2

#3101 Fix T1043062 - TreeList - Command Columns - Remove code snippet (#3100)
  concepts/05 UI Components/TreeList/10 Columns/10 Column Types/4 Command Columns/05 Configure a Command Column.md
Labels: cherry-pick, 22_1

#3102 Fix T1043062 - TreeList - Command Columns - Remove code snippet (#3100)
  concepts/05 UI Components/TreeList/10 Columns/10 Column Types/4 Command Columns/05 Configure a Command Column.md
Labels: 21_1, cherry-pick

#3103 Fix T1043731 - DataGrid - The renderAsync option behavior is different
  api-reference/10 UI Components/GridBase/1 Configuration/scrolling/renderAsync.md
Labels: 21_2

#3104 Fix T1043731 - DataGrid - The renderAsync option behavior is differe…
  api-reference/10 UI Components/GridBase/1 Configuration/scrolling/renderAsync.md
Labels: cherry-pick, 22_1

#3107 Update icon application
  applications/Icons/script.js
Labels: 21_2

#3108 Update icon application
  applications/Icons/script.js
Labels: cherry-pick, 22_1

#3093 Add Troubleshooting - Date values are parsed or serialized incorrectly
  api-reference/10 UI Components/GridBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateSerializationFormat.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/dataType.md
  api-reference/_hidden/GridBaseColumn/dataType.md
  concepts/70 Data Binding/90 Troubleshooting/0 Troubleshooting.md
  concepts/70 Data Binding/90 Troubleshooting/Date values are parsed or serialized incorrectly.md
Labels: 21_2

#3125 Add Troubleshooting - Date values are parsed or serialized incorrectl…
  api-reference/10 UI Components/GridBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateSerializationFormat.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/dataType.md
  api-reference/_hidden/GridBaseColumn/dataType.md
  concepts/70 Data Binding/90 Troubleshooting/0 Troubleshooting.md
  concepts/70 Data Binding/90 Troubleshooting/Date values are parsed or serialized incorrectly.md
Labels: 21_1, cherry-pick

#3126 Add Troubleshooting - Date values are parsed or serialized incorrectl…
  api-reference/10 UI Components/GridBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateSerializationFormat.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/dataType.md
  api-reference/_hidden/GridBaseColumn/dataType.md
  concepts/70 Data Binding/90 Troubleshooting/0 Troubleshooting.md
  concepts/70 Data Binding/90 Troubleshooting/Date values are parsed or serialized incorrectly.md
Labels: cherry-pick, 22_1

#3127 Drop-down editors: Add a link to showDataBeforeSearch into minSearchLength
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/minSearchLength.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/minSearchLength.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/minSearchLength.md
Labels: 21_2

#3129 Drop-down editors: Add a link to showDataBeforeSearch into minSearchLength
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/minSearchLength.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/minSearchLength.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/minSearchLength.md
Labels: 21_1, cherry-pick

#3128 Drop-down editors: Add a link to showDataBeforeSearch into minSearchLength (#3127)
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/minSearchLength.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/minSearchLength.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/minSearchLength.md
Labels: cherry-pick, 22_1

#3133 Fix T920662 - Switch between themes without page reload does not cover scenario with svg-based widgets
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: 21_2

#3111 Fix T1045480 - async/await examples in onRowInserting and similar handlers
  api-reference/10 UI Components/GridBase/1 Configuration/onRowRemoving.md
  includes/datagrid-ref-confirm-action-and-validate-data.md
Labels: 21_2

#3137 Fix T1045480 - async/await examples in onRowInserting and similar handlers (#3111)
  api-reference/10 UI Components/GridBase/1 Configuration/onRowRemoving.md
  includes/datagrid-ref-confirm-action-and-validate-data.md
Labels: cherry-pick, 22_1

#3138 Fix T1045480 - async/await examples in onRowInserting and similar han…
  api-reference/10 UI Components/GridBase/1 Configuration/onRowRemoving.md
  includes/datagrid-ref-confirm-action-and-validate-data.md
Labels: 21_1, cherry-pick

#3134 Fix T920662 - Switch between themes without page reload does not cover scenario with svg-based widgets
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: 21_1, cherry-pick

#3135 Fix T920662 - Switch between themes without page reload does not cover scenario with svg-based widgets
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: cherry-pick, 22_1

#2862 State storing: Fix customLoad and customSave DocIssues
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customLoad.md
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/stateStoring/customLoad.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/stateStoring/stateStoring.md
Labels: 20_2

#3142 State storing: Fix customLoad and customSave DocIssues (#2862)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customLoad.md
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/stateStoring/customLoad.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/stateStoring/stateStoring.md
Labels: 21_1, cherry-pick

#3143 State storing: Fix customLoad and customSave DocIssues (#2862)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customLoad.md
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/stateStoring/customLoad.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/stateStoring/stateStoring.md
Labels: cherry-pick, 21_2

#3144 State storing: Fix customLoad and customSave DocIssues (#2862)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customLoad.md
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/stateStoring/customLoad.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/stateStoring/stateStoring.md
Labels: cherry-pick, 22_1

#3136 Editors: add valueExpr usage
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/valueExpr.md
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: 21_2

#3148 Fix T1046844 - The `between` filter operator is not supported by our Data layer
  api-reference/10 UI Components/GridBase/1 Configuration/filterValue.md
Labels: 21_2

#3153 Fix T1046844 - The `between` filter operator is not supported by our Data layer (#3148)
  api-reference/10 UI Components/GridBase/1 Configuration/filterValue.md
Labels: cherry-pick, 22_1

#3154 Fix T1046844 - The `between` filter operator is not supported by our Data layer (#3148)
  api-reference/10 UI Components/GridBase/1 Configuration/filterValue.md
Labels: cherry-pick, 21_2

#3156 Editors: Add valueExpr usage
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: 21_2

#3158 Editors: Add valueExpr usage
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/valueExpr.md
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: 21_1, cherry-pick

#3159 Editors: Add valueExpr usage
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/valueExpr.md
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: cherry-pick, 22_1

#3162 Overlays: deprecate closeOnOutsideClick and publish hideOnOutsideClick
  api-reference/10 UI Components/dxContextMenu/1 Configuration/closeOnOutsideClick.md
  api-reference/10 UI Components/dxContextMenu/1 Configuration/hideOnOutsideClick.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/closeOnOutsideClick.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/hideOnOutsideClick.md
  api-reference/10 UI Components/dxPopover/1 Configuration/closeOnOutsideClick.md
  api-reference/10 UI Components/dxPopover/1 Configuration/hideOnOutsideClick.md
  api-reference/10 UI Components/dxToast/1 Configuration/closeOnOutsideClick.md
  api-reference/10 UI Components/dxToast/1 Configuration/hideOnOutsideClick.md
  applications/GettingStartedWith/Popup/index.js
  concepts/05 UI Components/ContextMenu/10 Open and Close the Context Menu/05 User Interaction.md
  concepts/05 UI Components/LoadPanel/00 Overview.md
  concepts/05 UI Components/LoadPanel/05 Show and Hide Using the API.md
  concepts/05 UI Components/LoadPanel/10 Customize the Appearance/10 Customize the Loading Indicator.md
  concepts/05 UI Components/LoadPanel/10 Customize the Appearance/20 Change the Text.md
  concepts/05 UI Components/LoadPanel/10 Customize the Appearance/30 Hide the Pane.md
  concepts/05 UI Components/LoadPanel/10 Customize the Appearance/40 Color the Shading of the Background.md
  concepts/05 UI Components/LoadPanel/15 Resize and Relocate.md
  concepts/05 UI Components/Popover/10 Show and Hide the Popover/01 User Interaction.md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/05 User Interaction.md
  concepts/05 UI Components/Toast/05 Show and Hide the Toast/05 User Interaction.md
  concepts/05 UI Components/Tooltip/05 Show and Hide the Tooltip/01 User Interaction.md
Labels: 22_1

#3157 Form - update description for the floating labels feature
  api-reference/10 UI Components/dxForm/1 Configuration/alignItemLabels.md
  api-reference/10 UI Components/dxForm/1 Configuration/alignItemLabelsInAllGroups.md
  api-reference/10 UI Components/dxForm/1 Configuration/labelLocation.md
  api-reference/10 UI Components/dxForm/1 Configuration/labelMode.md
  api-reference/10 UI Components/dxForm/1 Configuration/optionalMark.md
  api-reference/10 UI Components/dxForm/1 Configuration/showColonAfterLabel.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/helpText.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/alignment.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/location.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/showColon.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/visible.md
Labels: 21_2

#3165 Form - update description for the floating labels feature (#3157)
  api-reference/10 UI Components/dxForm/1 Configuration/alignItemLabels.md
  api-reference/10 UI Components/dxForm/1 Configuration/alignItemLabelsInAllGroups.md
  api-reference/10 UI Components/dxForm/1 Configuration/labelLocation.md
  api-reference/10 UI Components/dxForm/1 Configuration/labelMode.md
  api-reference/10 UI Components/dxForm/1 Configuration/optionalMark.md
  api-reference/10 UI Components/dxForm/1 Configuration/showColonAfterLabel.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/helpText.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/alignment.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/location.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/showColon.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/visible.md
Labels: cherry-pick, 22_1
