Repository DevExpress/devextreme-documentation, pull requests merged in 2021-06, with the labels that each got.

#2346 Fix headerFilter docissues T884624, T896965, T942522, T855042
  api-reference/_hidden/GridBaseColumn/headerFilter/groupInterval.md
Labels: 20_2

#2365 Fix T855409: Data types of the lookup's ValueExpr and the column's dataField must be the same
  api-reference/_hidden/GridBaseColumn/lookup/valueExpr.md
  api-reference/_hidden/dxFilterBuilderField/lookup/valueExpr.md
Labels: 20_2

#2366 Grids: Fix filterRow and filter(filterExpr) docissues
  api-reference/10 UI Components/BaseLegend/title/font/font.md
  api-reference/10 UI Components/BaseLegend/title/subtitle/font/font.md
  api-reference/10 UI Components/BaseWidget/1 Configuration/title/font/font.md
  api-reference/10 UI Components/GridBase/1 Configuration/filterRow/operationDescriptions/operationDescriptions.md
  api-reference/10 UI Components/GridBase/1 Configuration/filterRow/showOperationChooser.md
  api-reference/10 UI Components/GridBase/3 Methods/filter(filterExpr).md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/filterOperationDescriptions/filterOperationDescriptions.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/groupOperationDescriptions/groupOperationDescriptions.md
  api-reference/30 Data Layer/CustomStore/LoadOptions/filter.md
  api-reference/30 Data Layer/DataSource/1 Configuration/filter.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/filter.md
  api-reference/_hidden/GridBaseColumn/filterOperations.md
  api-reference/_hidden/GridBaseColumn/selectedFilterOperation.md
  api-reference/_hidden/dxFilterBuilderField/filterOperations.md
  includes/datalayer-ref-filter-acceptedvalues.md
Labels: 20_2

#2373 DataGrid: Fix filtering docissues
  api-reference/10 UI Components/BaseLegend/title/font/font.md
  api-reference/10 UI Components/BaseLegend/title/subtitle/font/font.md
  api-reference/10 UI Components/BaseWidget/1 Configuration/title/font/font.md
  api-reference/10 UI Components/GridBase/1 Configuration/filterRow/operationDescriptions/operationDescriptions.md
  api-reference/10 UI Components/GridBase/1 Configuration/filterRow/showOperationChooser.md
  api-reference/10 UI Components/GridBase/3 Methods/filter(filterExpr).md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/filterOperationDescriptions/filterOperationDescriptions.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/groupOperationDescriptions/groupOperationDescriptions.md
  api-reference/30 Data Layer/CustomStore/LoadOptions/filter.md
  api-reference/30 Data Layer/DataSource/1 Configuration/filter.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/filter.md
  api-reference/_hidden/GridBaseColumn/filterOperations.md
  api-reference/_hidden/GridBaseColumn/headerFilter/groupInterval.md
  api-reference/_hidden/GridBaseColumn/lookup/valueExpr.md
  api-reference/_hidden/GridBaseColumn/selectedFilterOperation.md
  api-reference/_hidden/dxFilterBuilderField/filterOperations.md
  api-reference/_hidden/dxFilterBuilderField/lookup/valueExpr.md
  includes/datalayer-ref-filter-acceptedvalues.md
Labels: 21_1, cherry-pick

#2380 DataGrid: Fix filtering docissues (#2373)
  api-reference/10 UI Components/BaseLegend/title/font/font.md
  api-reference/10 UI Components/BaseLegend/title/subtitle/font/font.md
  api-reference/10 UI Components/BaseWidget/1 Configuration/title/font/font.md
  api-reference/10 UI Components/GridBase/1 Configuration/filterRow/operationDescriptions/operationDescriptions.md
  api-reference/10 UI Components/GridBase/1 Configuration/filterRow/showOperationChooser.md
  api-reference/10 UI Components/GridBase/3 Methods/filter(filterExpr).md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/filterOperationDescriptions/filterOperationDescriptions.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/groupOperationDescriptions/groupOperationDescriptions.md
  api-reference/30 Data Layer/CustomStore/LoadOptions/filter.md
  api-reference/30 Data Layer/DataSource/1 Configuration/filter.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/filter.md
  api-reference/_hidden/GridBaseColumn/filterOperations.md
  api-reference/_hidden/GridBaseColumn/headerFilter/groupInterval.md
  api-reference/_hidden/GridBaseColumn/lookup/valueExpr.md
  api-reference/_hidden/GridBaseColumn/selectedFilterOperation.md
  api-reference/_hidden/dxFilterBuilderField/filterOperations.md
  api-reference/_hidden/dxFilterBuilderField/lookup/valueExpr.md
  includes/datalayer-ref-filter-acceptedvalues.md
Labels: 21_2, cherry-pick

#2362 fix imports in baseZIndex article
  api-reference/50 Common/utils/ui/dxOverlay/baseZIndex(zIndex).md
Labels: 21_1

#2384 fix imports after t1003441 fix (cp)
  api-reference/50 Common/utils/ui/dxOverlay/baseZIndex(zIndex).md
Labels: 21_2, cherry-pick

#2382 Form: Add missing Vue/React examples
  api-reference/10 UI Components/dxForm/1 Configuration/colCount.md
  api-reference/10 UI Components/dxForm/1 Configuration/colCountByScreen/colCountByScreen.md
  api-reference/10 UI Components/dxForm/1 Configuration/screenByWidth.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/colCount.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/colCount.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/colCountByScreen/colCountByScreen.md
Labels: 21_1

#2383 DataViz: Add missing Vue/React examples
  concepts/05 UI Components/PieChart/10 Series/55 Group Smaller Points.md
  concepts/05 UI Components/PolarChart/20 Series Types/Bar/05 Specify the Bar Width/01 Relative Bar Width.md
  concepts/05 UI Components/PolarChart/20 Series Types/Bar/05 Specify the Bar Width/02 Fixed Bar Width.md
Labels: 21_1

#2387 Form/DataViz: Add missing Vue/React examples
  api-reference/10 UI Components/dxForm/1 Configuration/colCount.md
  api-reference/10 UI Components/dxForm/1 Configuration/colCountByScreen/colCountByScreen.md
  api-reference/10 UI Components/dxForm/1 Configuration/screenByWidth.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/colCount.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/colCount.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/colCountByScreen/colCountByScreen.md
  concepts/05 UI Components/PieChart/10 Series/55 Group Smaller Points.md
  concepts/05 UI Components/PolarChart/20 Series Types/Bar/05 Specify the Bar Width/01 Relative Bar Width.md
  concepts/05 UI Components/PolarChart/20 Series Types/Bar/05 Specify the Bar Width/02 Fixed Bar Width.md
Labels: 20_2, cherry-pick

#2388 Form/DataViz: Add missing Vue/React examples
  api-reference/10 UI Components/dxForm/1 Configuration/colCount.md
  api-reference/10 UI Components/dxForm/1 Configuration/colCountByScreen/colCountByScreen.md
  api-reference/10 UI Components/dxForm/1 Configuration/screenByWidth.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/colCount.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/colCount.md
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/tabs/colCountByScreen/colCountByScreen.md
  concepts/05 UI Components/PieChart/10 Series/55 Group Smaller Points.md
  concepts/05 UI Components/PolarChart/20 Series Types/Bar/05 Specify the Bar Width/01 Relative Bar Width.md
  concepts/05 UI Components/PolarChart/20 Series Types/Bar/05 Specify the Bar Width/02 Fixed Bar Width.md
Labels: 21_2, cherry-pick

#2389 Grids closeEditCell also works in the 'cell' edit mode
  api-reference/10 UI Components/GridBase/3 Methods/closeEditCell().md
Labels: 20_2

#2390 Grids closeEditCell also works in the 'cell' edit mode
  api-reference/10 UI Components/GridBase/3 Methods/closeEditCell().md
Labels: 21_1, cherry-pick

#2391 Grids closeEditCell also works in the 'cell' edit mode
  api-reference/10 UI Components/GridBase/3 Methods/closeEditCell().md
Labels: 21_2, cherry-pick

#2393 Gantt: Fix exportToPdf() code example
  api-reference/10 UI Components/dxGantt/3 Methods/exportToPdf(options).md
Labels: 21_1

#2395 Gantt: Fix exportToPdf() code example (#2393)
  api-reference/10 UI Components/dxGantt/3 Methods/exportToPdf(options).md
Labels: 21_2, cherry-pick

#2316 PivotGrid.CustomStore - Samples for Angular/Vue/React
  concepts/05 UI Components/PivotGrid/035 Use CustomStore/20 Remote Operations.md
Labels: 21_1

#2394 Add a list of deprecated properties and methods
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/0 Learn Breaking Changes and Deprecated API.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/1 Deprecated Properties and Methods.md
Labels: 21_1

#2415 Add a list of deprecated properties and methods (#2394)
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/0 Learn Breaking Changes and Deprecated API.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/1 Deprecated Properties and Methods.md
Labels: 21_2, cherry-pick

#2417 Remove a forgotten mention of dx.viz-web.js
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
Labels: 20_2

#2418 Remove a forgotten mention of dx.viz-web.js (#2417)
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
Labels: 21_1, cherry-pick

#2419 Remove a forgotten mention of dx.viz-web.js (#2417)
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
Labels: 21_2, cherry-pick

#2416 Grids.columnAutoWidth: Fix awkward wording
  api-reference/10 UI Components/GridBase/1 Configuration/columnAutoWidth.md
Labels: 20_2

#2423 Grids.columnAutoWidth: Fix awkward wording (#2416)
  api-reference/10 UI Components/GridBase/1 Configuration/columnAutoWidth.md
Labels: 21_2, cherry-pick

#2424 Grids.columnAutoWidth: Fix awkward wording (#2416)
  api-reference/10 UI Components/GridBase/1 Configuration/columnAutoWidth.md
Labels: 21_1, cherry-pick

#2426 Fix weird characters (#2425)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/rowTemplate.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/customShapes/template.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/chart/commonSeriesSettings.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/chart/series/series.md
Labels: 21_2, cherry-pick

#2427 Fix weird characters (#2425)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/rowTemplate.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/customShapes/template.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/chart/commonSeriesSettings.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/chart/series/series.md
Labels: 21_1, cherry-pick

#2465 Update dx-tools
  package.json
Labels: 21_1

#2467 Update dx-tools
  package.json
Labels: 21_2

#2468 Support generate extra topics
  package.json
Labels: 21_1

#2469 Support generate extra topics
  package.json
Labels: 21_2

#2480 TreeView item: describe the `id` field
  api-reference/_hidden/dxTreeViewItem/id.md
Labels: 20_2

#2484 Add table deprecated property
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/1 Deprecated Properties and Methods.md
Labels: 21_2, cherry-pick

#2483 Add table deprecated property
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/1 Deprecated Properties and Methods.md
Labels: 21_1

#2414 Update Data - Local Array: Put content in an accordion
  concepts/70 Data Binding/03 Update Data/20 Local Array/02 Angular.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/05 Vue.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/08 React.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/15 jQuery.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
Labels: 20_2

#2491 Scheduler: update recurrent appointment picture
  images/UiWidgets/Scheduler_RecurrentAppointment_Details.png
Labels: 21_2, cherry-pick

#2490 Scheduler: update recurrent appointment picture
  images/UiWidgets/Scheduler_RecurrentAppointment_Details.png
Labels: 21_1, cherry-pick

#2489 Scheduler: update recurrent appointment picture
  images/UiWidgets/Scheduler_RecurrentAppointment_Details.png
Labels: 20_2

#2492 Update Data - Local Array: Put content in an accordion (#2414)
  concepts/70 Data Binding/03 Update Data/20 Local Array/02 Angular.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/05 Vue.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/08 React.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/15 jQuery.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
Labels: 21_1, cherry-pick

#2493 Update Data - Local Array: Put content in an accordion (#2414)
  concepts/70 Data Binding/03 Update Data/20 Local Array/02 Angular.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/05 Vue.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/08 React.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/15 jQuery.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
Labels: 21_2, cherry-pick

#2494 GridBaseColumn groupInterval: remove extra para
  api-reference/_hidden/GridBaseColumn/headerFilter/groupInterval.md
Labels: 21_1

#2487 Fix T1009709: DataGrid - allowSearch MUST be false if a mapped dataSource is used for a column header filter
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
Labels: 20_2

#2495 Fix T1009709: DataGrid - allowSearch MUST be false if a mapped dataSource is used for a column header filter (#2487)
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
Labels: 21_1, cherry-pick

#2496 Fix T1009709: DataGrid - allowSearch MUST be false if a mapped dataSource is used for a column header filter (#2487)
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
Labels: 21_2, cherry-pick
