Repository DevExpress/devextreme-documentation, pull requests merged in 2022-09, with the labels that each got.

#4140 HtmlEditor: remove 'iframe' from supported tags
  concepts/05 UI Components/HtmlEditor/05 Tags and Attributes.md
Labels: 22_1

#4141 HtmlEditor: remove 'iframe' from supported tags (#4140)
  concepts/05 UI Components/HtmlEditor/05 Tags and Attributes.md
Labels: cherry-pick, 21_2

#4142 HtmlEditor: remove 'iframe' from supported tags (#4140)
  concepts/05 UI Components/HtmlEditor/05 Tags and Attributes.md
Labels: cherry-pick, 22_2

#4145 Fix typo in documentation (#4144)
  concepts/50 React Components/60 Components Testing/00 Components Testing.md
Labels: cherry-pick, 22_2

#4146 Grids: fix allowedPageSizes T1112315
  api-reference/10 UI Components/GridBase/1 Configuration/pager/allowedPageSizes.md
Labels: 22_1

#4147 Grids: fix allowedPageSizes T1112315 (#4146)
  api-reference/10 UI Components/GridBase/1 Configuration/pager/allowedPageSizes.md
Labels: cherry-pick, 21_2

#4149 HtmlEditor: add "mention" format T1105541
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
Labels: 22_1

#4151 HtmlEditor: add "mention" format T1105541 (#4149)
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
Labels: cherry-pick, 22_2

#4152 HtmlEditor: add "mention" format T1105541 (#4149)
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
Labels: cherry-pick, 21_2

#4158 DataGrid: virtual scrolling description T1092891
  api-reference/10 UI Components/GridBase/1 Configuration/scrolling/rowRenderingMode.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
Labels: 22_1

#4161 DataGrid: virtual scrolling description T1092891 (#4158)
  api-reference/10 UI Components/GridBase/1 Configuration/scrolling/rowRenderingMode.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
Labels: cherry-pick, 22_2

#4160 DataGrid: virtual scrolling description T1092891 (#4158)
  api-reference/10 UI Components/GridBase/1 Configuration/scrolling/rowRenderingMode.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
Labels: cherry-pick, 21_2

#4159 DropDownBox: add a Getting Started tutorial
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/contentTemplate.md
  api-reference/10 UI Components/dxDropDownBox/dxDropDownBox.md
  applications/GettingStartedWith/DropDownBox/index.css
  applications/GettingStartedWith/DropDownBox/index.html
  applications/GettingStartedWith/DropDownBox/index.js
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/00 Getting Started with DropDownBox.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/05 Create DropDownBox.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/10 Add an Embedded Element.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/15 Configure Selection.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/20 Handle Events.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/25 Customize Appearance.md
  concepts/05 UI Components/DropDownBox/10 Overview.md
  concepts/Common/Editors Concepts/How to Choose a Drop-Down Editor.md
Labels: 22_1

#4167 DropDownBox: add a Getting Started tutorial (#4159)
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/contentTemplate.md
  api-reference/10 UI Components/dxDropDownBox/dxDropDownBox.md
  applications/GettingStartedWith/DropDownBox/index.css
  applications/GettingStartedWith/DropDownBox/index.html
  applications/GettingStartedWith/DropDownBox/index.js
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/00 Getting Started with DropDownBox.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/05 Create DropDownBox.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/10 Add an Embedded Element.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/15 Configure Selection.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/20 Handle Events.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/25 Customize Appearance.md
  concepts/05 UI Components/DropDownBox/10 Overview.md
  concepts/Common/Editors Concepts/How to Choose a Drop-Down Editor.md
Labels: cherry-pick, 22_2

#4168 DropDownBox: add a Getting Started tutorial (#4159)
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/contentTemplate.md
  api-reference/10 UI Components/dxDropDownBox/dxDropDownBox.md
  applications/GettingStartedWith/DropDownBox/index.css
  applications/GettingStartedWith/DropDownBox/index.html
  applications/GettingStartedWith/DropDownBox/index.js
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/00 Getting Started with DropDownBox.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/05 Create DropDownBox.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/10 Add an Embedded Element.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/15 Configure Selection.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/20 Handle Events.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/25 Customize Appearance.md
  concepts/05 UI Components/DropDownBox/10 Overview.md
  concepts/05 UI Components/SelectBox/How to Choose a Drop-Down Editor.md
Labels: cherry-pick, 21_2

#4163 DateBox: pickerType: 'rollers' behaviour T1108174
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: 22_1

#4169 DateBox: pickerType: 'rollers' behaviour T1108174 (#4163)
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: cherry-pick, 22_2

#4170 DateBox: pickerType: 'rollers' behaviour T1108174 (#4163)
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: cherry-pick, 21_2

#4171 Accordion: add code snippets to items.titleTemplate option
  api-reference/_hidden/dxAccordionItem/titleTemplate.md
Labels: 22_2

#4172 DataGrid: Form Mode unclear description T1103451
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
Labels: 22_1

#4174 DataGrid: Form Mode unclear description T1103451 (#4172)
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
Labels: cherry-pick, 22_2

#4173 DataGrid: Form Mode unclear description T1103451 (#4172)
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
Labels: cherry-pick, 21_2

#4178 DataGrid: Master-Detail JQuery code snippet typos
  concepts/05 UI Components/DataGrid/60 Master-Detail Interface/10 User Interaction.md
Labels: 22_1

#4180 DataGrid: Master-Detail JQuery code snippet typos (#4178)
  concepts/05 UI Components/DataGrid/60 Master-Detail Interface/10 User Interaction.md
Labels: cherry-pick, 22_2

#4179 DataGrid: Master-Detail JQuery code snippet typos (#4178)
  concepts/05 UI Components/DataGrid/60 Master-Detail Interface/10 User Interaction.md
Labels: cherry-pick, 21_2

#4084 Add a Troubleshooting section
  concepts/80 Troubleshooting/00 Basics/00 Basics.md
  concepts/80 Troubleshooting/00 Basics/05 Check Console for Warnings or Errors.md
  concepts/80 Troubleshooting/00 Basics/10 Check Requests in the Network Tab.md
  concepts/80 Troubleshooting/00 Basics/15 Examine CSS.md
  images/Troubleshooting/troubleshooting-inspect-css-1.png
  images/Troubleshooting/troubleshooting-inspect-css-2.png
  images/Troubleshooting/troubleshooting-inspect-css-3.png
Labels: 22_1

#4181 Add a Troubleshooting section (#4084)
  concepts/80 Troubleshooting/00 Basics/00 Basics.md
  concepts/80 Troubleshooting/00 Basics/05 Check Console for Warnings or Errors.md
  concepts/80 Troubleshooting/00 Basics/10 Check Requests in the Network Tab.md
  concepts/80 Troubleshooting/00 Basics/15 Examine CSS.md
  images/Troubleshooting/troubleshooting-inspect-css-1.png
  images/Troubleshooting/troubleshooting-inspect-css-2.png
  images/Troubleshooting/troubleshooting-inspect-css-3.png
Labels: cherry-pick, 21_2

#4182 Add a Troubleshooting section (#4084)
  concepts/80 Troubleshooting/00 Basics/00 Basics.md
  concepts/80 Troubleshooting/00 Basics/05 Check Console for Warnings or Errors.md
  concepts/80 Troubleshooting/00 Basics/10 Check Requests in the Network Tab.md
  concepts/80 Troubleshooting/00 Basics/15 Examine CSS.md
  images/Troubleshooting/troubleshooting-inspect-css-1.png
  images/Troubleshooting/troubleshooting-inspect-css-2.png
  images/Troubleshooting/troubleshooting-inspect-css-3.png
Labels: cherry-pick, 22_2

#4183 DropDownBox: dataSource does not support a hierarchical data source T…
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/dataSource.md
Labels: 22_1

#4185 DropDownBox: dataSource does not support a hierarchical data source T…
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/dataSource.md
Labels: cherry-pick, 22_2

#4184 DropDownBox: dataSource does not support a hierarchical data source T…
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/dataSource.md
Labels: cherry-pick, 21_2

#4189 Troubleshooting Basics: fix links
  concepts/80 Troubleshooting/00 Basics/05 Check Console for Warnings or Errors.md
Labels: 22_1

#4190 Troubleshooting Basics: fix links (#4189)
  concepts/80 Troubleshooting/00 Basics/05 Check Console for Warnings or Errors.md
Labels: cherry-pick, 21_2

#4191 Troubleshooting Basics: fix links (#4189)
  concepts/80 Troubleshooting/00 Basics/05 Check Console for Warnings or Errors.md
Labels: cherry-pick, 22_2

#4192 PieChart: Missing arguments for customizeTooltip config T1113230
  api-reference/10 UI Components/dxPieChart/1 Configuration/tooltip/customizeTooltip.md
Labels: 22_1

#4195 PieChart: Missing arguments for customizeTooltip config T1113230 (#4192)
  api-reference/10 UI Components/dxPieChart/1 Configuration/tooltip/customizeTooltip.md
Labels: cherry-pick, 22_2

#4193 PieChart: Missing arguments for customizeTooltip config T1113230 (#4192)
  api-reference/10 UI Components/dxPieChart/1 Configuration/tooltip/customizeTooltip.md
Labels: cherry-pick, 21_2

#4194 Grids: describe pager.label property
  api-reference/10 UI Components/GridBase/1 Configuration/pager/label.md
Labels: 22_1

#4201 Grids: describe pager.label property (#4194)
  api-reference/10 UI Components/GridBase/1 Configuration/pager/label.md
Labels: cherry-pick, 21_2

#4202 Grids: describe pager.label property (#4194)
  api-reference/10 UI Components/GridBase/1 Configuration/pager/label.md
Labels: cherry-pick, 22_2

#4197 FAB: Incorrect information about SpeedDialAction limits T1112375
  api-reference/10 UI Components/dxSpeedDialAction/dxSpeedDialAction.md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/20 Multiple Actions (Speed Dial).md
Labels: 22_1

#4203 FAB: Incorrect information about SpeedDialAction limits T1112375 (#4197)
  api-reference/10 UI Components/dxSpeedDialAction/dxSpeedDialAction.md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/20 Multiple Actions (Speed Dial).md
Labels: cherry-pick, 21_2

#4206 DropDownButton: Using the stylingMode T1112377
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/stylingMode.md
Labels: 22_1

#4208 DropDownButton: Using the stylingMode T1112377 (#4206)
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/stylingMode.md
Labels: cherry-pick, 22_2

#4207 DropDownButton: Using the stylingMode T1112377 (#4206)
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/stylingMode.md
Labels: cherry-pick, 21_2

#4209 NumberBox: Format. Limitet number of digits. T1114679
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
Labels: 22_1

#4211 NumberBox: Format. Limited number of digits. T1114679 (#4209)
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
Labels: cherry-pick, 22_2

#4210 NumberBox: Format. Limited number of digits. T1114679 (#4209)
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
Labels: cherry-pick, 21_2

#4223 DataGrid: The 'calculateCellValue' property extra info T1094373
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
Labels: 22_1

#4219 Checkbox: add enableThreeStateBehavior description
  api-reference/10 UI Components/dxCheckBox/1 Configuration/allowIndeterminateStateByClick.md
  api-reference/10 UI Components/dxCheckBox/1 Configuration/enableThreeStateBehavior.md
  api-reference/10 UI Components/dxCheckBox/1 Configuration/value.md
Labels: 22_2

#4228 CheckBox: fix enableThreeStateBehavior description
  api-reference/10 UI Components/dxCheckBox/1 Configuration/enableThreeStateBehavior.md
  api-reference/10 UI Components/dxCheckBox/1 Configuration/value.md
Labels: 22_2

#4227 DataGrid: The 'calculateCellValue' property extra info T1094373 (#4223)
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
Labels: cherry-pick, 22_2

#4226 DataGrid: The 'calculateCellValue' property extra info T1094373 (#4223)
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
Labels: cherry-pick, 21_2

#4230 React: Add extra info about creating React App with TypeScript T1097151
  concepts/50 React Components/02 Create a DevExtreme Application.md
Labels: 22_1

#4231 React: Add extra info about creating React App with TypeScript T10971…
  concepts/50 React Components/02 Create a DevExtreme Application.md
Labels: cherry-pick, 21_2

#4232 React: Add extra info about creating React App with TypeScript T10971…
  concepts/50 React Components/02 Create a DevExtreme Application.md
Labels: cherry-pick, 22_2

#4236 PivotGrid: Fix the Totals and Grand Totals typos
  concepts/05 UI Components/PivotGrid/010 Visual Elements/05 Totals/02 Total Rows or Columns.md
  concepts/05 UI Components/PivotGrid/010 Visual Elements/05 Totals/03 Grand Total Row and Column.md
Labels: 22_1

#4238 PivotGrid: Fix the Totals and Grand Totals typos (#4236)
  concepts/05 UI Components/PivotGrid/010 Visual Elements/05 Totals/02 Total Rows or Columns.md
  concepts/05 UI Components/PivotGrid/010 Visual Elements/05 Totals/03 Grand Total Row and Column.md
Labels: cherry-pick, 22_2

#4237 PivotGrid: Fix the Totals and Grand Totals typos (#4236)
  concepts/05 UI Components/PivotGrid/010 Visual Elements/05 Totals/02 Total Rows or Columns.md
  concepts/05 UI Components/PivotGrid/010 Visual Elements/05 Totals/03 Grand Total Row and Column.md
Labels: cherry-pick, 21_2

#4224 Add bell icon
  applications/Icons/script.js
  applications/Icons/styles.css
Labels: 22_1

#4239 Add bell icon
  applications/Icons/script.js
  applications/Icons/styles.css
Labels: cherry-pick, 22_2
