Repository DevExpress/devextreme-documentation, pull requests merged in 2022-10, with the labels that each got.

#4240 DataGrid: Update the setCellValue description T1118390
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: 22_1

#4242 DataGrid: Update the setCellValue description T1118390 (#4240)
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: cherry-pick, 22_2

#4241 DataGrid: Update the setCellValue description T1118390 (#4240)
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: cherry-pick, 21_2

#4245 Diagram: Update the onContentReady property T1118215
  api-reference/10 UI Components/Widget/1 Configuration/onContentReady.md
Labels: 22_1

#4246 Diagram: Update the onContentReady property T1118215 (#4245)
  api-reference/10 UI Components/Widget/1 Configuration/onContentReady.md
Labels: cherry-pick, 21_2

#4251 Troubleshooting: update description T1118739 (#4250)
  concepts/80 Troubleshooting/00 Basics/15 Examine CSS.md
Labels: cherry-pick, 21_2

#4252 Troubleshooting: update description T1118739 (#4250)
  concepts/80 Troubleshooting/00 Basics/15 Examine CSS.md
Labels: cherry-pick, 22_2

#4255 DataGrid: Update the dataSource property description T1118622 (#4253)
  api-reference/_hidden/GridBaseColumn/headerFilter/dataSource.md
Labels: cherry-pick, 21_2

#4262 CustomStore: add loadOptions.startDate and endDate descriptions
  api-reference/30 Data Layer/CustomStore/LoadOptions/1 Configuration/Configuration.md
  api-reference/30 Data Layer/CustomStore/LoadOptions/1 Configuration/endDate.md
  api-reference/30 Data Layer/CustomStore/LoadOptions/1 Configuration/startDate.md
  api-reference/30 Data Layer/CustomStore/LoadOptions/endDate.md
  api-reference/30 Data Layer/CustomStore/LoadOptions/startDate.md
Labels: 22_2

#4261 Create codeql-analysis.yml (#4254)
  .github/workflows/codeql-analysis.yml
Labels: 21_2

#4263 Validator: update Validation Result React snippet
  api-reference/10 UI Components/dxValidationGroup/9 Validation Result/complete.md
Labels: 22_1

#4264 Validator: update Validation Result React snippet (#4263)
  api-reference/10 UI Components/dxValidationGroup/9 Validation Result/complete.md
Labels: cherry-pick, 21_2

#4265 Validator: update Validation Result React snippet (#4263)
  api-reference/10 UI Components/dxValidationGroup/9 Validation Result/complete.md
Labels: cherry-pick, 22_2

#4260 Create codeql-analysis.yml (#4254)
  .github/workflows/codeql-analysis.yml
Labels: 22_2

#4266 Simplify CodeQL config
  .github/workflows/codeql-analysis.yml
Labels: cherry-pick, 22_1

#4267 Simplify CodeQL config
  .github/workflows/codeql-analysis.yml
Labels: cherry-pick, 21_2

#4270 DataGrid: Fix typo related to Filter Row React demo
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/1 Filter Row.md
Labels: 22_1

#4272 DataGrid: Fix typo related to Filter Row React demo (#4270)
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/1 Filter Row.md
Labels: cherry-pick, 22_2

#4271 DataGrid: Fix typo related to Filter Row React demo (#4270)
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/1 Filter Row.md
Labels: cherry-pick, 21_2

#4273 Corrected typo (#4268)
  api-reference/30 Data Layer/ODataContext/ODataContext.md
Labels: cherry-pick, 21_2

#4274 Corrected typo (#4268)
  api-reference/30 Data Layer/ODataContext/ODataContext.md
Labels: cherry-pick, 22_2

#4278 DataGrid: Add extra information about using the selectRows() method T…
  api-reference/10 UI Components/GridBase/3 Methods/selectRows(keys_preserve).md
Labels: cherry-pick, 21_2

#4279 DataGrid: Add extra information about using the selectRows() method T…
  api-reference/10 UI Components/GridBase/3 Methods/selectRows(keys_preserve).md
Labels: cherry-pick, 22_2

#4284 Custom Format String: fix insufficient info T1119741
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: 22_1

#4286 Custom Format String: fix insufficient info T1119741 (#4284)
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: cherry-pick, 22_2

#4285 Custom Format String: fix insufficient info T1119741 (#4284)
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: cherry-pick, 21_2

#4287 Calendar: update cellTemplate property
  api-reference/10 UI Components/dxCalendar/1 Configuration/cellTemplate.md
Labels: 22_2

#4280 Calendar: describe weekNumberRule option
  api-reference/10 UI Components/dxCalendar/1 Configuration/weekNumberRule.md
Labels: 22_2

#4288 Calendar: add the showWeekNumbers property description
  api-reference/10 UI Components/dxCalendar/1 Configuration/showWeekNumbers.md
Labels: 22_2

#4293 CheckBox: add a Getting Started tutorial
  api-reference/10 UI Components/dxCheckBox/dxCheckBox.md
  applications/GettingStartedWith/CheckBox/index.css
  applications/GettingStartedWith/CheckBox/index.html
  applications/GettingStartedWith/CheckBox/index.js
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/00 Getting Started with CheckBox.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/05 Create a CheckBox.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/10 Specify the Initial Value.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/15 Configure the CheckBox.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/20 Handle the Value Change.md
  concepts/05 UI Components/CheckBox/00 Overview.md
  concepts/Getting Started/Widget Basics - AngularJS/05 Change Options.md
Labels: 22_1

#4305 CheckBox: add a Getting Started tutorial (#4293)
  api-reference/10 UI Components/dxCheckBox/dxCheckBox.md
  applications/GettingStartedWith/CheckBox/index.css
  applications/GettingStartedWith/CheckBox/index.html
  applications/GettingStartedWith/CheckBox/index.js
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/00 Getting Started with CheckBox.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/05 Create a CheckBox.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/10 Specify the Initial Value.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/15 Configure the CheckBox.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/20 Handle the Value Change.md
  concepts/05 UI Components/CheckBox/00 Overview.md
  concepts/Getting Started/Widget Basics - AngularJS/05 Change Options.md
Labels: cherry-pick, 21_2

#4306 CheckBox: add a Getting Started tutorial (#4293)
  api-reference/10 UI Components/dxCheckBox/dxCheckBox.md
  applications/GettingStartedWith/CheckBox/index.css
  applications/GettingStartedWith/CheckBox/index.html
  applications/GettingStartedWith/CheckBox/index.js
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/00 Getting Started with CheckBox.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/05 Create a CheckBox.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/10 Specify the Initial Value.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/15 Configure the CheckBox.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/20 Handle the Value Change.md
  concepts/05 UI Components/CheckBox/00 Overview.md
  concepts/Getting Started/Widget Basics - AngularJS/05 Change Options.md
Labels: cherry-pick, 22_2

#4310 DataGrid: update information related to the remoteOperations property
  api-reference/10 UI Components/dxDataGrid/1 Configuration/remoteOperations/remoteOperations.md
Labels: 22_1

#4311 DataGrid: update information related to the remoteOperations property…
  api-reference/10 UI Components/dxDataGrid/1 Configuration/remoteOperations/remoteOperations.md
Labels: cherry-pick, 22_2

#4313 Update redrawOnResize option description
  api-reference/10 UI Components/BaseWidget/1 Configuration/redrawOnResize.md
Labels: 22_2

#4315 SelectBox and TagBox: update customItemCreateEvent
  api-reference/10 UI Components/dxSelectBox/1 Configuration/customItemCreateEvent.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/onCustomItemCreating.md
Labels: 22_2

#4312 Form: add label.template description
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/template.md
Labels: 22_2

#4320 DateBox: add todayButtonText description
  api-reference/10 UI Components/dxDateBox/1 Configuration/todayButtonText.md
Labels: 22_2

#4321 VectorMap: describe panVisible and zoomVisible
  api-reference/10 UI Components/dxVectorMap/1 Configuration/controlBar/panVisible.md
  api-reference/10 UI Components/dxVectorMap/1 Configuration/controlBar/zoomVisible.md
Labels: 22_2

#4319 Overlays: add W1021 warning description
  api-reference/10 UI Components/Errors and Warnings/W1021.md
Labels: 22_1

#4323 Overlays: add W1021 warning description (#4319)
  api-reference/10 UI Components/Errors and Warnings/W1021.md
Labels: cherry-pick, 22_2
