Repository DevExpress/devextreme-documentation, pull requests merged in 2022-07, with the labels that each got.

#3936 Drop-down Editors: add a note to Getting Started tutorials
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/00 Getting Started with Lookup.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/00 Getting Started with SelectBox.md
  concepts/05 UI Components/TagBox/00 Getting Started with TagBox/00 Getting Started with TagBox.md
  includes/uiwidgets-editors-choose-a-dropdown-editor.md
Labels: 22_1

#3945 Drop-down Editors: add a note to Getting Started tutorials (#3936)
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/00 Getting Started with Lookup.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/00 Getting Started with SelectBox.md
  concepts/05 UI Components/TagBox/00 Getting Started with TagBox/00 Getting Started with TagBox.md
  includes/uiwidgets-editors-choose-a-dropdown-editor.md
Labels: cherry-pick, 21_2

#3946 Drop-down Editors: add a note to Getting Started tutorials (#3936)
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/00 Getting Started with Lookup.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/00 Getting Started with SelectBox.md
  concepts/05 UI Components/TagBox/00 Getting Started with TagBox/00 Getting Started with TagBox.md
  includes/uiwidgets-editors-choose-a-dropdown-editor.md
Labels: cherry-pick, 22_2

#3940 Grids: update the 'setCellValue' description
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: 22_1

#3947 Grids: update the 'setCellValue' description (#3940)
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: cherry-pick, 21_2

#3948 Grids: update the 'setCellValue' description (#3940)
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: cherry-pick, 22_2

#3941 DataGrid: update the 'scrolling.mode' description
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
Labels: 22_1

#3955 DataGrid: update the 'scrolling.mode' description (#3941)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
Labels: cherry-pick, 21_2

#3956 DataGrid: update the 'scrolling.mode' description (#3941)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
Labels: cherry-pick, 22_2

#3963 Drop-down editors: delete misleading links
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/00 Getting Started with Lookup.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/00 Getting Started with SelectBox.md
  concepts/05 UI Components/TagBox/00 Getting Started with TagBox/00 Getting Started with TagBox.md
  includes/uiwidgets-editors-choose-a-dropdown-editor.md
Labels: 21_2

#3968 PivotGridFieldChooser: describe the 'encodeHtml' option
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/encodeHtml.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/encodeHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/encodeHtml.md
Labels: 22_1

#3972 PivotGridFieldChooser: describe the 'encodeHtml' option (#3968)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/encodeHtml.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/encodeHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/encodeHtml.md
Labels: cherry-pick, 21_2

#3973 PivotGridFieldChooser: describe the 'encodeHtml' option (#3968)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/encodeHtml.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/encodeHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/encodeHtml.md
Labels: cherry-pick, 22_2

#3981 Autocomplete: add a Getting Started tutorial
  applications/GettingStartedWith/Autocomplete/index.css
  applications/GettingStartedWith/Autocomplete/index.html
  applications/GettingStartedWith/Autocomplete/index.js
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/00 Getting Started with Accordion.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/00 Getting Started with Autocomplete.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/05 Create Autocomplete and Bind It to Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/10 Group Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/15 Configure Search Settings.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/20 Customize Field Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/25 Customize Item Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/30 Handle Value Change.md
  concepts/05 UI Components/Autocomplete/00 Overview.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/00 Getting Started with Calendar.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/00 Getting Started with PieChart.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/00 Getting Started with TextBox.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/00 Getting Started with Toast.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/00 Getting Started with Toolbar.md
Labels: 22_1

#3989 Autocomplete: add a Getting Started tutorial (#3981)
  applications/GettingStartedWith/Autocomplete/index.css
  applications/GettingStartedWith/Autocomplete/index.html
  applications/GettingStartedWith/Autocomplete/index.js
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/00 Getting Started with Autocomplete.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/05 Create Autocomplete and Bind It to Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/10 Group Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/15 Configure Search Settings.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/20 Customize Field Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/25 Customize Item Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/30 Handle Value Change.md
  concepts/05 UI Components/Autocomplete/00 Overview.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/00 Getting Started with Calendar.md
Labels: 21_2

#3990 Autocomplete: add a Getting Started tutorial (#3981)
  applications/GettingStartedWith/Autocomplete/index.css
  applications/GettingStartedWith/Autocomplete/index.html
  applications/GettingStartedWith/Autocomplete/index.js
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/00 Getting Started with Accordion.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/00 Getting Started with Autocomplete.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/05 Create Autocomplete and Bind It to Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/10 Group Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/15 Configure Search Settings.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/20 Customize Field Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/25 Customize Item Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/30 Handle Value Change.md
  concepts/05 UI Components/Autocomplete/00 Overview.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/00 Getting Started with Calendar.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/00 Getting Started with PieChart.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/00 Getting Started with TextBox.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/00 Getting Started with Toast.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/00 Getting Started with Toolbar.md
Labels: cherry-pick, 22_2

#3992 Toolbar.items.options: fix code snippet (#3991)
  api-reference/_hidden/dxToolbarItem/options.md
Labels: cherry-pick, 22_2

#3993 Grids: add the 'syncLookupFilterValues' description
  api-reference/10 UI Components/GridBase/1 Configuration/syncLookupFilterValues.md
  images/DataGrid/sync-lookup-filter-values/filter-row-false.png
  images/DataGrid/sync-lookup-filter-values/filter-row-true.png
  images/DataGrid/sync-lookup-filter-values/header-filter-false.png
  images/DataGrid/sync-lookup-filter-values/header-filter-true.png
Labels: 22_1

#4000 Grids: add the 'syncLookupFilterValues' description (#3993)
  api-reference/10 UI Components/GridBase/1 Configuration/syncLookupFilterValues.md
  images/DataGrid/sync-lookup-filter-values/filter-row-false.png
  images/DataGrid/sync-lookup-filter-values/filter-row-true.png
  images/DataGrid/sync-lookup-filter-values/header-filter-false.png
  images/DataGrid/sync-lookup-filter-values/header-filter-true.png
Labels: cherry-pick, 22_2

#4001 Update dxGantt.scaleType description
  api-reference/10 UI Components/dxGantt/1 Configuration/scaleType.md
Labels: 22_2

#4002 Update dxGantt.scaleType description (#4001)
  api-reference/10 UI Components/dxGantt/1 Configuration/scaleType.md
Labels: cherry-pick, 22_1

#4003 minor fixes
  api-reference/10 UI Components/Widget/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxButton/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/accept.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/allowedFileExtensions.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onProgress.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onUploadStarted.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onUploaded.md
  api-reference/10 UI Components/dxMenuBase/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/onContextMenuPreparing.md
  api-reference/10 UI Components/dxSlideOut/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxTileView/1 Configuration/activeStateEnabled.md
Labels: 22_2

#3967 Widgets: update 'target' code snippet
  includes/uiwidgets-ref-target.md
Labels: 22_1

#4009 Widgets: update 'target' code snippet (#3967)
  includes/uiwidgets-ref-target.md
Labels: cherry-pick, 21_2

#4005 Drawer: rework section in the Getting Started tutorial
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: 22_1

#4010 Drawer: rework section in the Getting Started tutorial (#4005)
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: cherry-pick, 22_2

#4011 Toolbar: add the 'multiline' property description
  api-reference/10 UI Components/dxToolbar/1 Configuration/multiline.md
Labels: 22_2

#4017 Fix link in Drawer: Getting Started
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: 22_1

#4018 Fix link in Drawer: Getting Started (#4017)
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: cherry-pick, 22_2

#4019 Accordion: describe titleTemplate option
  api-reference/_hidden/dxAccordionItem/titleTemplate.md
Labels: 22_2

#4023 Fix broken link
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: 22_1

#4024 Fix broken link (#4023)
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: cherry-pick, 22_2

#4025 Overlays: add code snippets to 'container' option
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/container.md
  api-reference/10 UI Components/dxPopover/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
  includes/uiwidgets-ref-container.md
Labels: 22_1

#4027 Overlays: add code snippets to 'container' option (#4025)
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/container.md
  api-reference/10 UI Components/dxPopover/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
  includes/uiwidgets-ref-container.md
Labels: cherry-pick, 22_2

#4026 Overlays: add code snippets to 'container' option (#4025)
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/container.md
  api-reference/10 UI Components/dxPopover/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
  includes/uiwidgets-ref-container.md
Labels: cherry-pick, 21_2
