Repository DevExpress/devextreme-documentation, pull requests merged in 2022-01, with the labels that each got.

#3319 T1056120: Update DataChange.key
  api-reference/_hidden/DataChange/key.md
Labels: 22_1

#3270 Popup Getting Started: fix resizeEnabled link (#3269)
  concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Resize the Popup.md
Labels: 21_1, cherry-pick

#3331 Change the title of the article
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/10 Bind the SelectBox to Data.md
Labels: 21_2

#3333 Change the title of the article
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/10 Bind the SelectBox to Data.md
Labels: 21_1, cherry-pick

#3332 Change the title of the article (#3331)
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/10 Bind the SelectBox to Data.md
Labels: cherry-pick, 22_1

#3336 T1046450: FileManager - update example in uploadFileChunk
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Custom/1 Configuration/uploadFileChunk.md
Labels: 22_1

#3337 T1046450: FileManager - update example in uploadFileChunk (#3336)
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Custom/1 Configuration/uploadFileChunk.md
Labels: 21_1, cherry-pick

#3338 T1046450: FileManager - update example in uploadFileChunk (#3336)
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Custom/1 Configuration/uploadFileChunk.md
Labels: cherry-pick, 21_2

#3289 Lookup: Add a Getting Started tutorial
  api-reference/10 UI Components/dxLookup/dxLookup.md
  applications/GettingStartedWith/Lookup/index.css
  applications/GettingStartedWith/Lookup/index.html
  applications/GettingStartedWith/Lookup/index.js
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/00 Getting Started with Lookup.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/10 Bind Lookup to Data.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/15 Configure Search.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/20 Handle the Value Change Event.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/25 Group Data.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/30 Enable Pagination.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/35 Customize Item Appearance.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/40 Customize the Drop-Down Menu.md
  concepts/05 UI Components/Lookup/00 Overview.md
Labels: 21_2

#3339 Lookup: Add a Getting Started tutorial
  api-reference/10 UI Components/dxLookup/dxLookup.md
  applications/GettingStartedWith/Lookup/index.css
  applications/GettingStartedWith/Lookup/index.html
  applications/GettingStartedWith/Lookup/index.js
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/00 Getting Started with Lookup.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/10 Bind Lookup to Data.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/15 Configure Search.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/20 Handle the Value Change Event.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/25 Group Data.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/30 Enable Pagination.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/35 Customize Item Appearance.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/40 Customize the Drop-Down Menu.md
  concepts/05 UI Components/Lookup/00 Overview.md
Labels: 21_1, cherry-pick

#3340 Lookup: Add a Getting Started tutorial (#3289)
  api-reference/10 UI Components/dxLookup/dxLookup.md
  applications/GettingStartedWith/Lookup/index.css
  applications/GettingStartedWith/Lookup/index.html
  applications/GettingStartedWith/Lookup/index.js
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/00 Getting Started with Lookup.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/10 Bind Lookup to Data.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/15 Configure Search.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/20 Handle the Value Change Event.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/25 Group Data.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/30 Enable Pagination.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/35 Customize Item Appearance.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/40 Customize the Drop-Down Menu.md
  concepts/05 UI Components/Lookup/00 Overview.md
Labels: cherry-pick, 22_1

#3342 Getting Started Lookup: fix version
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/00 Getting Started with Lookup.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
Labels: 22_1

#3341 Getting Started Lookup: fix version
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/00 Getting Started with Lookup.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
Labels: 21_1

#3130 Editors: add an example to validationStatus
  api-reference/10 UI Components/Editor/1 Configuration/validationStatus.md
Labels: 21_2

#3345 Editors: add an example to validationStatus
  api-reference/10 UI Components/Editor/1 Configuration/validationStatus.md
Labels: 21_1, cherry-pick

#3346 Editors: add an example to validationStatus (#3130)
  api-reference/10 UI Components/Editor/1 Configuration/validationStatus.md
Labels: cherry-pick, 22_1

#3352 Drop-down Editors: fix a content link
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/dropDownOptions.md
Labels: 21_1

#3354 Drop-down Editors: fix a content link (#3352)
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/dropDownOptions.md
Labels: cherry-pick, 22_1

#3323 Gantt: describe export fonts
  api-reference/50 Common/Object Structures/PdfExportGanttProps/dateRange.md
  api-reference/50 Common/Object Structures/PdfExportGanttProps/fileName.md
  api-reference/50 Common/Object Structures/PdfExportGanttProps/font.md
  api-reference/50 Common/Object Structures/PdfExportGanttProps/format.md
  api-reference/50 Common/utils/pdfExporter/exportGantt(options).md
  api-reference/NewTopics/PdfExportGanttFont/PdfExportGanttFont.md
  api-reference/NewTopics/PdfExportGanttFont/fontObject.md
  api-reference/_hidden/PdfExportGanttFont/PdfExportGanttFont.md
  api-reference/_hidden/PdfExportGanttFont/fontObject.md
  api-reference/_hidden/PdfExportGanttFont/name.md
  api-reference/_hidden/PdfExportGanttFont/style.md
  api-reference/_hidden/PdfExportGanttFont/weight.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/pdf_exporter.md
  images/Gantt/font-object-converter.png
Labels: 22_1

#3356 T1060160: Add note related to Text Editor Buttons
  api-reference/_hidden/dxTextEditorButton/location.md
  api-reference/_hidden/dxTextEditorButton/options.md
Labels: 21_2

#3359 T1060160: Add note related to Text Editor Buttons
  api-reference/_hidden/dxTextEditorButton/location.md
  api-reference/_hidden/dxTextEditorButton/options.md
Labels: 21_1, cherry-pick

#3360 T1060160: Add note related to Text Editor Buttons (#3356)
  api-reference/_hidden/dxTextEditorButton/location.md
  api-reference/_hidden/dxTextEditorButton/options.md
Labels: cherry-pick, 22_1

#3347 Update isExpanded property in loadOptions
  api-reference/30 Data Layer/CustomStore/LoadOptions/group.md
Labels: 22_1

#3368 Update isExpanded property in loadOptions (#3347)
  api-reference/30 Data Layer/CustomStore/LoadOptions/group.md
Labels: cherry-pick, 21_2

#3369 Update isExpanded property in loadOptions (#3347)
  api-reference/30 Data Layer/CustomStore/LoadOptions/group.md
Labels: 21_1, cherry-pick

#3370 Update wrapperAttr property (#3363)
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/wrapperAttr.md
  api-reference/10 UI Components/dxPopover/1 Configuration/wrapperAttr.md
  api-reference/10 UI Components/dxPopup/1 Configuration/wrapperAttr.md
  api-reference/10 UI Components/dxToast/1 Configuration/wrapperAttr.md
  api-reference/10 UI Components/dxTooltip/1 Configuration/wrapperAttr.md
  includes/overlays-specify-attributes.md
Labels: cherry-pick, 21_2

#3374 T899642: Change the autoResizeEnabled description
  api-reference/10 UI Components/dxTextArea/1 Configuration/autoResizeEnabled.md
Labels: 21_2

#3376 T899642: Change the autoResizeEnabled description (#3374)
  api-reference/10 UI Components/dxTextArea/1 Configuration/autoResizeEnabled.md
Labels: cherry-pick, 22_1

#3375 T899642: Change the autoResizeEnabled description (#3374)
  api-reference/10 UI Components/dxTextArea/1 Configuration/autoResizeEnabled.md
Labels: 21_1, cherry-pick

#3380 Incorrect options setting
  concepts/05 UI Components/Scheduler/060 Views/010 View Types/View Types.md
Labels: 21_2

#3377 T860753: Change the TextArea height description
  api-reference/10 UI Components/dxTextArea/1 Configuration/height.md
Labels: 21_2

#3385 T860753: Change the TextArea height description (#3377)
  api-reference/10 UI Components/dxTextArea/1 Configuration/height.md
Labels: cherry-pick, 22_1

#3384 T860753: Change the TextArea height description (#3377)
  api-reference/10 UI Components/dxTextArea/1 Configuration/height.md
Labels: 21_1, cherry-pick

#3390 Update the description of Popup drag properties
  api-reference/10 UI Components/dxPopup/1 Configuration/dragAndResizeArea.md
  api-reference/10 UI Components/dxPopup/1 Configuration/dragOutsideBoundary.md
Labels: 22_1

#3391 Fix the link in dragOutsideBoundary
  api-reference/10 UI Components/dxOverlay/1 Configuration/dragOutsideBoundary.md
Labels: 21_2

#3392 ODataStore: describe the createQuery method's parameters
  api-reference/30 Data Layer/ODataStore/3 Methods/createQuery(loadOptions).md
Labels: 22_1

#3386 Getting Started with Calendar: Add a tutorial
  api-reference/10 UI Components/dxCalendar/dxCalendar.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPrepared.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPreparing.md
  applications/GettingStartedWith/Calendar/index.css
  applications/GettingStartedWith/Calendar/index.html
  applications/GettingStartedWith/Calendar/index.js
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/00 Getting Started with Calendar.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/05 Create a Calendar.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/10 Specify Available Dates.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/15 Specify Available Views.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/20 Add the Today Button.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/25 Customize Cell Appearance.md
  concepts/05 UI Components/Calendar/00 Overview.md
  concepts/05 UI Components/DateBox/03 Platform-Specific Value Pickers.md
  concepts/05 UI Components/Form/15 Configure Item Labels/05 Location and Alignment/05 Align Labels Relatively to Editors.md
Labels: 21_2

#3396 Getting Started with Calendar: Add a tutorial (#3386)
  api-reference/10 UI Components/dxCalendar/dxCalendar.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPrepared.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPreparing.md
  applications/GettingStartedWith/Calendar/index.css
  applications/GettingStartedWith/Calendar/index.html
  applications/GettingStartedWith/Calendar/index.js
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/00 Getting Started with Calendar.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/05 Create a Calendar.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/10 Specify Available Dates.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/15 Specify Available Views.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/20 Add the Today Button.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/25 Customize Cell Appearance.md
  concepts/05 UI Components/Calendar/00 Overview.md
  concepts/05 UI Components/DateBox/03 Platform-Specific Value Pickers.md
  concepts/05 UI Components/Form/15 Configure Item Labels/05 Location and Alignment/05 Align Labels Relatively to Editors.md
Labels: 21_1, cherry-pick

#3397 Getting Started with Calendar: Add a tutorial (#3386)
  api-reference/10 UI Components/dxCalendar/dxCalendar.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPrepared.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPreparing.md
  applications/GettingStartedWith/Calendar/index.css
  applications/GettingStartedWith/Calendar/index.html
  applications/GettingStartedWith/Calendar/index.js
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/00 Getting Started with Calendar.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/05 Create a Calendar.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/10 Specify Available Dates.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/15 Specify Available Views.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/20 Add the Today Button.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/25 Customize Cell Appearance.md
  concepts/05 UI Components/Calendar/00 Overview.md
  concepts/05 UI Components/DateBox/03 Platform-Specific Value Pickers.md
  concepts/05 UI Components/Form/15 Configure Item Labels/05 Location and Alignment/05 Align Labels Relatively to Editors.md
Labels: cherry-pick, 22_1

#3398 T1011771: add example for custom button type
  api-reference/10 UI Components/dxButton/1 Configuration/type.md
Labels: 21_2
