Repository DevExpress/devextreme-documentation, pull requests merged in 2022-08, with the labels that each got.

#4054 Fix false empty descriptions
  api-reference/50 Common/utils/TransitionExecutor/enter(elements_animation).md
  api-reference/50 Common/utils/TransitionExecutor/leave(elements_animation).md
  api-reference/50 Common/utils/registerComponent(name_componentClass).md
  api-reference/50 Common/utils/registerComponent(name_namespace_componentClass).md
Labels: 22_1

#4055 Gantt: fix example in taskTooltipContentTemplate
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTooltipContentTemplate.md
Labels: 22_1

#4056 Gantt: fix example in taskTooltipContentTemplate (#4055)
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTooltipContentTemplate.md
Labels: cherry-pick, 22_2

#4057 Gantt: fix example in taskTooltipContentTemplate (#4055)
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTooltipContentTemplate.md
Labels: cherry-pick, 21_2

#4058 Custom Store: update example for Angular in the Load Data guide
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/2 Client-Side Data Processing.md
Labels: 22_1

#4059 Custom Store: update example for Angular in the Load Data guide (#4058)
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/2 Client-Side Data Processing.md
Labels: cherry-pick, 21_2

#4060 Custom Store: update example for Angular in the Load Data guide (#4058)
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/2 Client-Side Data Processing.md
Labels: cherry-pick, 22_2

#4061 Widgets: change Angular code in defaultOptions
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: 22_1

#4063 Widgets: change Angular code in defaultOptions (#4061)
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: cherry-pick, 22_2

#4064 DataGrid: update Column and Row Indexes guide
  concepts/05 UI Components/DataGrid/15 Columns/12 Column and Row Indexes.md
Labels: 22_1

#4068 DataGrid: update Column and Row Indexes guide (#4064)
  concepts/05 UI Components/DataGrid/15 Columns/12 Column and Row Indexes.md
Labels: cherry-pick, 21_2

#4069 DataGrid: update Column and Row Indexes guide (#4064)
  concepts/05 UI Components/DataGrid/15 Columns/12 Column and Row Indexes.md
Labels: cherry-pick, 22_2

#4065 Scheduler: update deleteRecurrence code example
  api-reference/10 UI Components/dxScheduler/3 Methods/deleteRecurrence(appointment_date_recurrenceEditMode).md
Labels: 22_1

#4070 Scheduler: update deleteRecurrence code example (#4065)
  api-reference/10 UI Components/dxScheduler/3 Methods/deleteRecurrence(appointment_date_recurrenceEditMode).md
Labels: cherry-pick, 22_2

#4073 Popup: change the toolbarItems
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/component.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/disabled.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/html.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/location.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/options.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/render.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/template.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/text.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/toolbarItems.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/visible.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/widget.md
  api-reference/NewTopics/dxPopupToolbarItem/dxPopupToolbarItem.md
  api-reference/NewTopics/dxPopupToolbarItem/toolbar.md
Labels: 22_2

#4078 Fix dxPopup toolbarItems
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/toolbarItems.md
  api-reference/_hidden/dxPopupToolbarItem/dxPopupToolbarItem.md
  api-reference/_hidden/dxPopupToolbarItem/toolbar.md
Labels: 22_2

#4079 FileUploader: fix code snippets in Overview
  concepts/05 UI Components/FileUploader/00 Overview.md
Labels: 22_1

#4080 FileUploader: fix code snippets in Overview (#4079)
  concepts/05 UI Components/FileUploader/00 Overview.md
Labels: cherry-pick, 21_2

#4081 FileUploader: fix code snippets in Overview
  concepts/05 UI Components/FileUploader/00 Overview.md
Labels: cherry-pick, 22_2

#4082 Popup: fix toolbarItems structure
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/toolbar.md
  api-reference/10 UI Components/dxPopup/1 Configuration/toolbarItems/toolbarItems.md
  api-reference/_hidden/dxPopupToolbarItem/options.md
  api-reference/_hidden/dxPopupToolbarItem/template.md
  api-reference/_hidden/dxPopupToolbarItem/toolbar.md
Labels: 22_2

#4088 Popup.toolbarItems.template: fix React code snippet
  api-reference/_hidden/dxPopupToolbarItem/template.md
Labels: 22_2

#4091 HtmlEditor: fix tableContextMenuItem.template code snippet
  api-reference/_hidden/dxHtmlEditorTableContextMenuItem/template.md
Labels: 22_1

#4092 HtmlEditor: fix tableContextMenuItem.template code snippet (#4091)
  api-reference/_hidden/dxHtmlEditorTableContextMenuItem/template.md
Labels: cherry-pick, 21_2

#4093 HtmlEditor: fix tableContextMenuItem.template code snippet (#4091)
  api-reference/_hidden/dxHtmlEditorTableContextMenuItem/template.md
Labels: cherry-pick, 22_2

#4101 Map: fix 'type' description T1109746
  api-reference/10 UI Components/dxMap/1 Configuration/type.md
Labels: 22_1

#4102 Map: fix 'type' description T1109746 (#4101)
  api-reference/10 UI Components/dxMap/1 Configuration/type.md
Labels: cherry-pick, 21_2

#4103 Map: fix 'type' description T1109746 (#4101)
  api-reference/10 UI Components/dxMap/1 Configuration/type.md
Labels: cherry-pick, 22_2

#4104 Drawer: fix size-related descriptions
  api-reference/10 UI Components/dxDrawer/1 Configuration/height.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/openedStateMode.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/template.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/width.md
Labels: 22_1

#4105 Drawer: fix size-related descriptions (#4104)
  api-reference/10 UI Components/dxDrawer/1 Configuration/height.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/openedStateMode.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/template.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/width.md
Labels: cherry-pick, 21_2

#4106 Drawer: fix size-related descriptions (#4104)
  api-reference/10 UI Components/dxDrawer/1 Configuration/height.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/openedStateMode.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/template.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/width.md
Labels: cherry-pick, 22_2

#4113 Getting Started with Drawer: fix React code
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/10 Open and Close the Drawer.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/15 Implement Navigation.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/20 Configure the Reveal Behavior.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/30 Configure Interaction with the View.md
Labels: 22_1

#4115 Getting Started with Drawer: fix React code (#4113)
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/10 Open and Close the Drawer.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/15 Implement Navigation.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/20 Configure the Reveal Behavior.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/30 Configure Interaction with the View.md
Labels: cherry-pick, 22_2

#4117 DataGrid: fix bug in sorting.mode T1110572
  api-reference/10 UI Components/GridBase/1 Configuration/sorting/mode.md
Labels: 22_1

#4118 DataGrid: fix bug in sorting.mode T1110572 (#4117)
  api-reference/10 UI Components/GridBase/1 Configuration/sorting/mode.md
Labels: cherry-pick, 21_2

#4119 DataGrid: fix bug in sorting.mode T1110572 (#4117)
  api-reference/10 UI Components/GridBase/1 Configuration/sorting/mode.md
Labels: cherry-pick, 22_2

#3969 React: Add an Optimize Performance guide
  concepts/50 React Components/45 Optimize Performance/00 Optimize Performance.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/00 Do not pass inline functions and objects as component props.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/10 Functions.md
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
Labels: 22_1

#4123 React: Add an Optimize Performance guide (#3969)
  concepts/50 React Components/45 Optimize Performance/00 Optimize Performance.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/00 Do not pass inline functions and objects as component props.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/10 Functions.md
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
Labels: cherry-pick, 21_2

#4124 React: Add an Optimize Performance guide (#3969)
  concepts/50 React Components/45 Optimize Performance/00 Optimize Performance.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/00 Do not pass inline functions and objects as component props.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/10 Functions.md
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
Labels: cherry-pick, 22_2

#4125 Widgets: fix defaultOptions React code sample
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: 22_1

#4126 Widgets: fix defaultOptions React code sample (#4125)
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: cherry-pick, 21_2

#4127 Widgets: fix defaultOptions React code sample (#4125)
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: cherry-pick, 22_2

#4128 Pivot Grid: add new 'export headers' option descriptions
  api-reference/50 Common/Object Structures/ExcelExportPivotGridProps/exportColumnFieldHeaders.md
  api-reference/50 Common/Object Structures/ExcelExportPivotGridProps/exportDataFieldHeaders.md
  api-reference/50 Common/Object Structures/ExcelExportPivotGridProps/exportFilterFieldHeaders.md
  api-reference/50 Common/Object Structures/ExcelExportPivotGridProps/exportRowFieldHeaders.md
  api-reference/50 Common/Object Structures/ExcelPivotGridCell/headerType.md
Labels: 22_2

#4132 React Optimize Performance guide: fix link
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
Labels: 22_1

#4133 React Optimize Performance guide: fix link (#4132)
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
Labels: cherry-pick, 21_2

#4134 React Optimize Performance guide: fix link (#4132)
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
Labels: cherry-pick, 22_2

#4135 Sliders: describe callValueChange option
  api-reference/10 UI Components/dxSliderBase/1 Configuration/callValueChange.md
Labels: 22_2
