Repository DevExpress/devextreme-documentation, pull requests merged in 2022-02, with the labels that each got.

#3399 T1011771: add example for custom button type (#3398)
  api-reference/10 UI Components/dxButton/1 Configuration/type.md
Labels: 21_1, cherry-pick

#3400 T1011771: add example for custom button type (#3398)
  api-reference/10 UI Components/dxButton/1 Configuration/type.md
Labels: cherry-pick, 22_1

#3401 Getting Started with Lookup: fix an example
  applications/GettingStartedWith/Lookup/index.js
Labels: 21_2

#3407 Getting Started with Lookup: fix an example
  applications/GettingStartedWith/Lookup/index.js
Labels: 21_1

#3408 Getting Started with Lookup: fix an example (#3401)
  applications/GettingStartedWith/Lookup/index.js
Labels: cherry-pick, 22_1

#3418 Gantt: update export api descriptions
  api-reference/_hidden/PdfExportGanttFont/style.md
  api-reference/_hidden/PdfExportGanttFont/weight.md
Labels: 22_1

#3424 Gantt: fix links
  api-reference/10 UI Components/dxGantt/1 Configuration/columns/filterValue.md
Labels: 22_1

#3425 Gantt: fix links (#3424)
  api-reference/10 UI Components/dxGantt/1 Configuration/columns/filterValue.md
Labels: cherry-pick, 21_2

#3420 Gantt: update info about columns
  api-reference/10 UI Components/dxGantt/1 Configuration/columns/columns.md
  api-reference/_hidden/dxGanttColumn/dxGanttColumn.md
Labels: 22_1

#3426 ODataStore: describe the createQuery method's parameters (#3392)
  api-reference/30 Data Layer/ODataStore/3 Methods/createQuery(loadOptions).md
Labels: cherry-pick, 21_2

#3430 FileManager: update the onItemDownloading property
  api-reference/10 UI Components/dxFileManager/1 Configuration/onItemDownloading.md
Labels: 22_1

#3421 ValidationSummary: Describe refreshValidationGroup method
  api-reference/10 UI Components/dxValidationSummary/3 Methods/refreshValidationGroup().md
Labels: 22_1

#3429 Minor fix for ODataStore.insert(values)
  api-reference/30 Data Layer/ODataStore/3 Methods/insert(values).md
Labels: 22_1

#3434 Minor fix for ODataStore.insert(values) (#3429)
  api-reference/30 Data Layer/ODataStore/3 Methods/insert(values).md
Labels: cherry-pick, 21_2

#3431 FileManager: update onItemDownloading
  api-reference/10 UI Components/dxFileManager/1 Configuration/onItemDownloading.md
Labels: cherry-pick, 21_2

#3439 dxSortable: remove unuseful link to demo (#3437)
  api-reference/10 UI Components/dxSortable/1 Configuration/group.md
Labels: 21_1, cherry-pick

#3445 CustomStore: add example to LoadOptions.userData (#3423)
  api-reference/30 Data Layer/CustomStore/LoadOptions/userData.md
Labels: cherry-pick, 21_2

#3449 Scheduler: minor fix (#3447)
  api-reference/10 UI Components/dxScheduler/1 Configuration/resourceCellTemplate.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/resourceCellTemplate.md
Labels: 21_1, cherry-pick

#3450 GridColumn.customizeText - fix note
  api-reference/10 UI Components/dxGantt/1 Configuration/columns/customizeText.md
Labels: 22_1

#3451 GridColumn.customizeText - fix note (#3450)
  api-reference/10 UI Components/dxGantt/1 Configuration/columns/customizeText.md
Labels: cherry-pick, 21_2

#3458 Add information about bundle size in Angular (#3436)
  concepts/40 Angular Components/40 Common Features/10 Tree Shaking.md
Labels: 21_1, cherry-pick

#3459 Add information about bundle size in Angular (#3436)
  concepts/40 Angular Components/40 Common Features/10 Tree Shaking.md
Labels: 22_1

#3463 Update recurrenceRule.md (#3442)
  api-reference/50 Common/Object Structures/dxSchedulerAppointment/recurrenceRule.md
Labels: cherry-pick, 22_1

#3464 Update recurrenceRule.md (#3442)
  api-reference/50 Common/Object Structures/dxSchedulerAppointment/recurrenceRule.md
Labels: 21_1, cherry-pick

#3465 Gantt: update validation info
  api-reference/10 UI Components/dxGantt/1 Configuration/validation/validateDependencies.md
  api-reference/10 UI Components/dxGantt/1 Configuration/validation/validation.md
Labels: 22_1

#3466 Gantt: update validation info
  api-reference/10 UI Components/dxGantt/1 Configuration/validation/validateDependencies.md
  api-reference/10 UI Components/dxGantt/1 Configuration/validation/validation.md
Labels: cherry-pick, 21_2

#3467 Gantt: update validation info
  api-reference/10 UI Components/dxGantt/1 Configuration/validation/validateDependencies.md
  api-reference/10 UI Components/dxGantt/1 Configuration/validation/validation.md
Labels: 21_1, cherry-pick

#3468 DataGrid: fix bug in code
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/015 Deferred Selection.md
Labels: 22_1

#3470 DataGrid: fix code (#3468)
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/015 Deferred Selection.md
Labels: 21_1, cherry-pick

#3472 minor fix
  includes/overlays-specify-attributes.md
Labels: 22_1

#3473 minor fix (#3472)
  includes/overlays-specify-attributes.md
Labels: cherry-pick, 21_2
