Repository DevExpress/devextreme-documentation, pull requests merged in 2022-06, with the labels that each got.

#3759 PieChart: add a Getting Started tutorial
  applications/DataVisualization/Guides/PieChartOverview/pieChartExample.html
  applications/DataVisualization/Guides/PieChartOverview/pieChartExample.js
  applications/GettingStartedWith/PieChart/index.css
  applications/GettingStartedWith/PieChart/index.html
  applications/GettingStartedWith/PieChart/index.js
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/10 Bind Accordion to Data.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/00 Getting Started with PieChart.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/05 Create a PieChart.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/10 Bind PieChart to Data and Configure Series.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/15 Set PieChart Title.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/20 Configure Point Labels.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/25 Enable Tooltips.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/30 Handle Selection.md
  concepts/05 UI Components/PieChart/00 Overview.md
  concepts/60 Themes and Styles/00 HTML- and SVG-Based UI Components.md
Labels: 21_2

#3768 PieChart: add a Getting Started tutorial #3759
  applications/DataVisualization/Guides/PieChartOverview/pieChartExample.html
  applications/DataVisualization/Guides/PieChartOverview/pieChartExample.js
  applications/GettingStartedWith/PieChart/index.css
  applications/GettingStartedWith/PieChart/index.html
  applications/GettingStartedWith/PieChart/index.js
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/10 Bind Accordion to Data.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/00 Getting Started with PieChart.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/05 Create a PieChart.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/10 Bind PieChart to Data and Configure Series.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/15 Set PieChart Title.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/20 Configure Point Labels.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/25 Enable Tooltips.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/30 Handle Selection.md
  concepts/05 UI Components/PieChart/00 Overview.md
  concepts/60 Themes and Styles/00 HTML- and SVG-Based UI Components.md
Labels: cherry-pick, 22_1

#3769 TagBox: fix code snippet T1082589 (#3763)
  concepts/05 UI Components/TagBox/15 Create a User-Defined Item.md
Labels: 21_1, cherry-pick

#3770 TagBox: fix code snippet T1082589 (#3763)
  concepts/05 UI Components/TagBox/15 Create a User-Defined Item.md
Labels: cherry-pick, 22_1

#3771 DataGrid: fix the code snippet T1047806 (#3764)
  concepts/05 UI Components/DataGrid/99 How To/Dynamically Change Form Item Properties in the Editing State.md
Labels: 21_1, cherry-pick

#3777 Scheduler: Get CellData of multiple selected cells after user actions T956636
  api-reference/10 UI Components/dxScheduler/1 Configuration/selectedCellData.md
Labels: 21_2

#3781 Scheduler: Get CellData of multiple selected cells after user actions T956636 (#3777)
  api-reference/10 UI Components/dxScheduler/1 Configuration/selectedCellData.md
Labels: 21_1, cherry-pick

#3782 Scheduler: Get CellData of multiple selected cells after user actions T956636 (#3777)
  api-reference/10 UI Components/dxScheduler/1 Configuration/selectedCellData.md
Labels: cherry-pick, 22_1

#3783 CLI: minor fix
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/10 Create a New Application.md
Labels: 22_1

#3785 Minor updates in docs
  api-reference/10 UI Components/BaseChart/1 Configuration/onPointHoverChanged.md
  api-reference/10 UI Components/BaseChart/1 Configuration/onPointSelectionChanged.md
  api-reference/10 UI Components/DOMComponent/1 Configuration/onOptionChanged.md
  api-reference/10 UI Components/dxChart/1 Configuration/onLegendClick.md
  api-reference/10 UI Components/dxGantt/1 Configuration/onResourceManagerDialogShowing.md
  api-reference/10 UI Components/dxPieChart/5 Series Types/CommonPieChartSeries/label/displayFormat.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/onLegendClick.md
  api-reference/10 UI Components/dxPolarChart/5 Series Types/CommonPolarChartSeries/label/displayFormat.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/discreteAxisDivisionMode.md
  api-reference/10 UI Components/dxRangeSlider/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/onAppointmentTooltipShowing.md
  api-reference/10 UI Components/dxSpeedDialAction/1 Configuration/onClick.md
Labels: 22_1

#3786 HtmlEditor: update list of features
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
Labels: 22_1

#3787 Charts: update point labels customization
  concepts/05 UI Components/Chart/15 Point Labels/05 Customize Point Labels.md
Labels: 22_1

#3784 HtmlEditor: describe image upload
  api-reference/_hidden/dxHtmlEditorImageUpload/fileUploaderOptions.md
  api-reference/_hidden/dxHtmlEditorImageUpload/tabs.md
  api-reference/_hidden/dxHtmlEditorImageUploadTabItem/dxHtmlEditorImageUploadTabItem.md
  api-reference/_hidden/dxHtmlEditorImageUploadTabItem/name.md
Labels: 22_1

#3788 Gantt: update export api
  api-reference/50 Common/Object Structures/PdfExportGanttProps/component.md
  api-reference/50 Common/Object Structures/PdfExportGanttProps/createDocumentMethod.md
  api-reference/50 Common/Object Structures/PdfExportGanttProps/dateRange.md
  api-reference/50 Common/Object Structures/PdfExportGanttProps/exportMode.md
  api-reference/50 Common/Object Structures/PdfExportGanttProps/format.md
  api-reference/50 Common/Object Structures/PdfExportGanttProps/landscape.md
Labels: 22_1

#3792 Getting Started Tutorials: fix version
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/05 Create an Accordion.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/05 Create a Calendar.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/05 Create a PieChart.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/05 Use the 'notify' Method.md
Labels: 21_1

#3793 Getting Started Tutorials: fix version
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/05 Create an Accordion.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/05 Create a Calendar.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/05 Create a PieChart.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/05 Create a TextBox.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/05 Use the 'notify' Method.md
Labels: 22_1

#3796 Scheduler: update appointmentTooltipTemplate
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentTooltipTemplate.md
Labels: 22_1

#3798 Accordion: Getting started tutorial minor fix
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/05 Create an Accordion.md
Labels: 21_1

#3794 dxScheduler: describe the deleteRecurrence method
  api-reference/10 UI Components/dxScheduler/3 Methods/deleteRecurrence(appointment_date_recurrenceEditMode).md
Labels: 22_1

#3773 Chart: update the 'size' object description T1082603
  api-reference/10 UI Components/dxChart/1 Configuration/size/size.md
Labels: 21_2

#3802 Chart: update the 'size' object description T1082603 (#3773)
  api-reference/10 UI Components/dxChart/1 Configuration/size/size.md
Labels: cherry-pick, 22_1

#3801 Chart: update the 'size' object description T1082603 (#3773)
  api-reference/10 UI Components/dxChart/1 Configuration/size/size.md
Labels: 21_1, cherry-pick

#3804 VectorMap: update guide links T970432
  concepts/05 UI Components/VectorMap/20 Providing Data/10 Data for Areas/30 Using a JSON object.md
Labels: 21_2

#3806 VectorMap: update guide links T970432 (#3804)
  concepts/05 UI Components/VectorMap/20 Providing Data/10 Data for Areas/30 Using a JSON object.md
Labels: 21_1, cherry-pick

#3807 VectorMap: update guide links T970432 (#3804)
  concepts/05 UI Components/VectorMap/20 Providing Data/10 Data for Areas/30 Using a JSON object.md
Labels: cherry-pick, 22_1

#3809 Fix code in 'Use Webpack' guide T961074 (#3808)
  concepts/Common/Modularity/01 Link Modules/10 Use Webpack.md
Labels: 21_1, cherry-pick

#3810 Fix code in 'Use Webpack' guide T961074 (#3808)
  concepts/Common/Modularity/01 Link Modules/10 Use Webpack.md
Labels: cherry-pick, 22_1

#3811 HtmlEditor: change Validation Status description T893560
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/validationStatus.md
Labels: 21_2

#3812 HtmlEditor: change Validation Status description T893560 (#3811)
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/validationStatus.md
Labels: 21_1, cherry-pick

#3800 Scheduler: describe the appointmentTooltipShowing event
  api-reference/10 UI Components/dxScheduler/1 Configuration/onAppointmentTooltipShowing.md
  api-reference/10 UI Components/dxScheduler/4 Events/appointmentTooltipShowing.md
Labels: 22_1

#3818 Angular: Update the Visual Studio version T1010310
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/20 Add DevExtreme to an ASP.NET Core Angular Application.md
Labels: 21_2

#3819 Angular: Update the Visual Studio version T1010310
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/20 Add DevExtreme to an ASP.NET Core Angular Application.md
Labels: 21_1

#3820 Angular: Update the Visual Studio version T1010310
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/20 Add DevExtreme to an ASP.NET Core Angular Application.md
Labels: 22_1

#3821 TreeList: update 'allowSelectAll' description + fix markup
  api-reference/10 UI Components/dxGantt/1 Configuration/columns/filterValue.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/selection/allowSelectAll.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/05 Create an Accordion.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/05 Create a Calendar.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/05 Create a PieChart.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/05 Create a TextBox.md
Labels: 21_2

#3822 TreeList: update 'allowSelectAll' description + fix markup (#3821)
  api-reference/10 UI Components/dxTreeList/1 Configuration/selection/allowSelectAll.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/05 Create an Accordion.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/05 Create a Calendar.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/05 Create a PieChart.md
Labels: 21_1, cherry-pick

#3823 TreeList: update 'allowSelectAll' description + fix markup (#3821)
  api-reference/10 UI Components/dxGantt/1 Configuration/columns/filterValue.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/selection/allowSelectAll.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/05 Create an Accordion.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/05 Create a Calendar.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/05 Create a PieChart.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/05 Create a TextBox.md
Labels: cherry-pick, 22_1

#3814 Scheduler: add the 'allDayPanelMode' property description
  api-reference/10 UI Components/dxScheduler/1 Configuration/allDayPanelMode.md
  images/Scheduler/scheduler-all-day-panel-mode.png
Labels: 22_1

#3795 Toolbar: Add a Getting Started tutorial
  api-reference/10 UI Components/dxToolbar/dxToolbar.md
  applications/GettingStartedWith/Toolbar/index.css
  applications/GettingStartedWith/Toolbar/index.html
  applications/GettingStartedWith/Toolbar/index.js
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/00 Getting Started with Toolbar.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/05 Create a Toolbar and its Items.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/10 Specify Item Location.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/15 Customize Items.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/20 Create an Overflow Menu.md
  concepts/05 UI Components/Toolbar/00 Overview.md
Labels: 21_2

#3824 Toolbar: Add a Getting Started tutorial
  api-reference/10 UI Components/dxToolbar/dxToolbar.md
  applications/GettingStartedWith/Toolbar/index.css
  applications/GettingStartedWith/Toolbar/index.html
  applications/GettingStartedWith/Toolbar/index.js
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/00 Getting Started with Toolbar.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/05 Create a Toolbar and its Items.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/10 Specify Item Location.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/15 Customize Items.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/20 Create an Overflow Menu.md
  concepts/05 UI Components/Toolbar/00 Overview.md
Labels: 21_1, cherry-pick

#3825 Toolbar: Add a Getting Started tutorial
  api-reference/10 UI Components/dxToolbar/dxToolbar.md
  applications/GettingStartedWith/Toolbar/index.css
  applications/GettingStartedWith/Toolbar/index.html
  applications/GettingStartedWith/Toolbar/index.js
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/00 Getting Started with Toolbar.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/05 Create a Toolbar and its Items.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/10 Specify Item Location.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/15 Customize Items.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/20 Create an Overflow Menu.md
  concepts/05 UI Components/Toolbar/00 Overview.md
Labels: cherry-pick, 22_1

#3826 Angular: change config file in Globalize section T1021938
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/08 Register 3rd-Party Dependencies/02 Globalize Registration.md
Labels: 21_2

#3827 Angular: change config file in Globalize section T1021938 (#3826)
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/08 Register 3rd-Party Dependencies/02 Globalize Registration.md
Labels: 21_1, cherry-pick

#3828 Angular: change config file in Globalize section T1021938 (#3826)
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/08 Register 3rd-Party Dependencies/02 Globalize Registration.md
Labels: cherry-pick, 22_1

#3829 DataGrid: update allowFiltering T1067029
  api-reference/_hidden/dxDataGridColumn/allowFiltering.md
Labels: 21_2

#3830 DataGrid: update allowFiltering T1067029 (#3829)
  api-reference/_hidden/dxDataGridColumn/allowFiltering.md
Labels: 21_1, cherry-pick

#3831 DataGrid: update allowFiltering T1067029 (#3829)
  api-reference/_hidden/dxDataGridColumn/allowFiltering.md
Labels: cherry-pick, 22_1

#3832 DataGrid: update columns.customizeText description T939443
  api-reference/_hidden/GridBaseColumn/customizeText.md
Labels: 21_2

#3833 DataGrid: update columns.customizeText description T939443 (#3832)
  api-reference/_hidden/GridBaseColumn/customizeText.md
Labels: 21_1, cherry-pick

#3834 DataGrid: update columns.customizeText description T939443 (#3832)
  api-reference/_hidden/GridBaseColumn/customizeText.md
Labels: cherry-pick, 22_1

#3837 FileManager: update rootFolderName description T1092188 (#3835)
  api-reference/10 UI Components/dxFileManager/1 Configuration/rootFolderName.md
Labels: cherry-pick, 22_1

#3841 ThemeBuilder: update the Import/Export dialog T898648
  concepts/60 Themes and Styles/05 Predefined Themes/70 Color Swatches.md
  concepts/60 Themes and Styles/08 ThemeBuilder/20 Postpone Customization.md
  concepts/60 Themes and Styles/08 ThemeBuilder/40 Export the Resulting Theme.md
  concepts/Common/Migrate to the New Version/20 Upgrade Themes Created in ThemeBuilder.md
  images/Common/ThemeBuilder/themebuilder-themeexport-format.png
  images/Common/ThemeBuilder/themebuilder-themeexport-name.png
  images/Common/ThemeBuilder/themebuilder-themeexport-widgets.png
  images/Common/ThemeBuilder/themebuilder-themeexport.png
  images/Common/ThemeBuilder/themebuilder-themeimport-view.png
  images/Common/ThemeBuilder/themebuilder-themeimport.png
Labels: 21_2

#3842 ThemeBuilder: update the Import/Export dialog T898648 (#3841)
  concepts/60 Themes and Styles/05 Predefined Themes/70 Color Swatches.md
  concepts/60 Themes and Styles/08 ThemeBuilder/20 Postpone Customization.md
  concepts/60 Themes and Styles/08 ThemeBuilder/40 Export the Resulting Theme.md
  concepts/Common/Migrate to the New Version/20 Upgrade Themes Created in ThemeBuilder.md
  images/Common/ThemeBuilder/themebuilder-themeexport-format.png
  images/Common/ThemeBuilder/themebuilder-themeexport-name.png
  images/Common/ThemeBuilder/themebuilder-themeexport-widgets.png
  images/Common/ThemeBuilder/themebuilder-themeexport.png
  images/Common/ThemeBuilder/themebuilder-themeimport-view.png
  images/Common/ThemeBuilder/themebuilder-themeimport.png
Labels: 21_1, cherry-pick

#3843 ThemeBuilder: update the Import/Export dialog T898648 (#3841)
  concepts/60 Themes and Styles/05 Predefined Themes/70 Color Swatches.md
  concepts/60 Themes and Styles/08 ThemeBuilder/20 Postpone Customization.md
  concepts/60 Themes and Styles/08 ThemeBuilder/40 Export the Resulting Theme.md
  concepts/Common/Migrate to the New Version/20 Upgrade Themes Created in ThemeBuilder.md
  images/Common/ThemeBuilder/themebuilder-themeexport-format.png
  images/Common/ThemeBuilder/themebuilder-themeexport-name.png
  images/Common/ThemeBuilder/themebuilder-themeexport-widgets.png
  images/Common/ThemeBuilder/themebuilder-themeexport.png
  images/Common/ThemeBuilder/themebuilder-themeimport-view.png
  images/Common/ThemeBuilder/themebuilder-themeimport.png
Labels: cherry-pick, 22_1

#3844 Charts: delete Data Binding topics
  concepts/05 UI Components/Chart/03 Data Binding/05 Simple Array/05 Array Only.md
  concepts/05 UI Components/Chart/03 Data Binding/05 Simple Array/10 ArrayStore.md
  concepts/05 UI Components/Chart/03 Data Binding/10 JSON Data.md
  concepts/05 UI Components/Chart/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/01 DevExtreme DataSource.md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/05 JavaScript Array/07 Angular.md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/05 JavaScript Array/10 AngularJS.md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/05 JavaScript Array/20 Knockout.md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/05 JavaScript Array/JavaScript Array.md
  concepts/05 UI Components/Chart/03 Data Binding/26 Update Data/Update Data.md
Labels: 22_1

#3849 Chart: 'size' description minor fix
  api-reference/10 UI Components/dxChart/1 Configuration/size/size.md
Labels: 21_2

#3850 Chart: 'size' description minor fix (#3849)
  api-reference/10 UI Components/dxChart/1 Configuration/size/size.md
Labels: 21_1, cherry-pick

#3851 Chart: 'size' description minor fix (#3849)
  api-reference/10 UI Components/dxChart/1 Configuration/size/size.md
Labels: cherry-pick, 22_1

#3853 Chart: fix code snippet in 'Provide Data' section
  concepts/05 UI Components/Chart/91 Drill-Down Chart/01 Provide Data.md
Labels: 21_2

#3854 Chart: fix code snippet in 'Provide Data' section (#3853)
  concepts/05 UI Components/Chart/91 Drill-Down Chart/01 Provide Data.md
Labels: 21_1, cherry-pick

#3855 Chart: fix code snippet in 'Provide Data' section (#3853)
  concepts/05 UI Components/Chart/91 Drill-Down Chart/01 Provide Data.md
Labels: cherry-pick, 22_1

#3857 Items.template: add a code snippet (#3856)
  api-reference/_hidden/CollectionWidgetItem/template.md
Labels: 21_1, cherry-pick

#3858 Items.template: add a code snippet (#3856)
  api-reference/_hidden/CollectionWidgetItem/template.md
Labels: cherry-pick, 22_1

#3862 Grid changes.key: minor code fix
  api-reference/_hidden/DataChange/key.md
Labels: 21_2

#3861 Update localization.formatMessage
  api-reference/50 Common/utils/localization/formatMessage(key_value).md
Labels: 22_1

#3863 Grid changes.key: minor code fix (#3862)
  api-reference/_hidden/DataChange/key.md
Labels: 21_1, cherry-pick

#3864 Grid changes.key: minor code fix (#3862)
  api-reference/_hidden/DataChange/key.md
Labels: cherry-pick, 22_1

#3866 Update localization.formatMessage (#3861)
  api-reference/50 Common/utils/localization/formatMessage(key_value).md
Labels: cherry-pick, 21_2

#3865 minor fix
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
Labels: 22_1

#3873 fix formatting (#3865)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
Labels: cherry-pick, 21_2

#3872 fix formatting (#3865)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
Labels: 21_1, cherry-pick

#3875 Diagram.defaultProperties: fix code (#3874)
  api-reference/10 UI Components/dxDiagram/1 Configuration/defaultItemProperties/defaultItemProperties.md
Labels: 21_1, cherry-pick

#3876 Diagram.defaultProperties: fix code (#3874)
  api-reference/10 UI Components/dxDiagram/1 Configuration/defaultItemProperties/defaultItemProperties.md
Labels: cherry-pick, 22_1

#3878 Menu: update the 'adaptivityEnabled' description
  api-reference/10 UI Components/dxMenu/1 Configuration/adaptivityEnabled.md
Labels: 21_2

#3880 Menu: update the 'adaptivityEnabled' description (#3878)
  api-reference/10 UI Components/dxMenu/1 Configuration/adaptivityEnabled.md
Labels: 21_1, cherry-pick

#3881 Menu: update the 'adaptivityEnabled' description (#3878)
  api-reference/10 UI Components/dxMenu/1 Configuration/adaptivityEnabled.md
Labels: cherry-pick, 22_1

#3877 Menu: add a Getting Started tutorial
  api-reference/10 UI Components/dxMenu/dxMenu.md
  applications/GettingStartedWith/Menu/index.css
  applications/GettingStartedWith/Menu/index.html
  applications/GettingStartedWith/Menu/index.js
  concepts/05 UI Components/Menu/00 Getting Started with Menu/00 Getting Started with Menu.md
  concepts/05 UI Components/Menu/00 Getting Started with Menu/05 Create Base Menu Level.md
  concepts/05 UI Components/Menu/00 Getting Started with Menu/10 Create Submenus.md
  concepts/05 UI Components/Menu/00 Getting Started with Menu/15 Handle Clicks on Items.md
  concepts/05 UI Components/Menu/00 Getting Started with Menu/20 Enable Menu Adaptivity.md
  concepts/05 UI Components/Menu/00 Overview.md
Labels: 21_2

#3846 Tabs: add a Getting Started tutorial
  api-reference/10 UI Components/dxTabPanel/dxTabPanel.md
  api-reference/10 UI Components/dxTabs/dxTabs.md
  applications/GettingStartedWith/Tabs/index.css
  applications/GettingStartedWith/Tabs/index.html
  applications/GettingStartedWith/Tabs/index.js
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/00 Getting Started with Tabs.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/05 Create Predefined Tabs.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/10 Create Custom Tabs.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/15 Specify Selection Mode.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/20 Handle Tab Click.md
  concepts/05 UI Components/Tabs/00 Overview.md
Labels: 21_2

#3886 Tabs: add a Getting Started tutorial
  api-reference/10 UI Components/dxTabPanel/dxTabPanel.md
  api-reference/10 UI Components/dxTabs/dxTabs.md
  applications/GettingStartedWith/Tabs/index.css
  applications/GettingStartedWith/Tabs/index.html
  applications/GettingStartedWith/Tabs/index.js
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/00 Getting Started with Tabs.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/05 Create Predefined Tabs.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/10 Create Custom Tabs.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/15 Specify Selection Mode.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/20 Handle Tab Click.md
  concepts/05 UI Components/Tabs/00 Overview.md
Labels: cherry-pick, 22_1

#3887 TagBox: fix link in the itemTemplate option T1096591
  api-reference/10 UI Components/dxSelectBox/1 Configuration/itemTemplate.md
Labels: 21_2

#3888 TagBox: fix link in the itemTemplate option T1096591 (#3887)
  api-reference/10 UI Components/dxSelectBox/1 Configuration/itemTemplate.md
Labels: 21_1, cherry-pick

#3889 TagBox: fix link in the itemTemplate option T1096591 (#3887)
  api-reference/10 UI Components/dxSelectBox/1 Configuration/itemTemplate.md
Labels: cherry-pick, 22_1

#3891 Menu: fix application of Getting Started tutorial
  applications/GettingStartedWith/Menu/index.css
  applications/GettingStartedWith/Menu/index.html
Labels: 21_2

#3895 Drawer: fix code snippet in Getting Started tutorial T1096867
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: 21_2

#3896 Drawer: fix code snippet in Getting Started tutorial T1096867 (#3895)
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: 21_1, cherry-pick

#3897 Drawer: fix code snippet in Getting Started tutorial T1096867 (#3895)
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: cherry-pick, 22_1

#3898 Pdf Export: add jsPDF version
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/PdfExportDataGridProps.md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportGantt(options).md
Labels: 22_1

#3901 Lookup: closeOnOutsideClick -> hideOnOutsideClick
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/40 Customize the Drop-Down Menu.md
Labels: 22_1

#3904 Angular: add Components Testing article
  concepts/40 Angular Components/50 Components Testing/00 Components Testing.md
  concepts/40 Angular Components/50 Components Testing/10 Unit Testing.md
  concepts/40 Angular Components/50 Components Testing/20 Integration Testing.md
  concepts/40 Angular Components/50 Components Testing/30 End-to-End Testing.md
Labels: 22_1

#3665 React testing
  concepts/50 React Components/60 Components Testing/00 Components Testing.md
  concepts/50 React Components/60 Components Testing/10 Unit Testing.md
  concepts/50 React Components/60 Components Testing/20 Integration Testing.md
  concepts/50 React Components/60 Components Testing/30 End-to-End Testing.md
Labels: 22_1

#3907 Drawer: update Getting Started tutorial
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/10 Open and Close the Drawer.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/15 Implement Navigation.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/20 Configure the Reveal Behavior.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/30 Configure Interaction with the View.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/40 Change the Position.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/Getting Started with Navigation Drawer.md
Labels: 22_1

#3912 SelectBox: update the 'fieldTemplate' property
  api-reference/10 UI Components/dxSelectBox/1 Configuration/fieldTemplate.md
Labels: 22_1

#3916 SelectBox: update the 'fieldTemplate' property (#3912)
  api-reference/10 UI Components/dxSelectBox/1 Configuration/fieldTemplate.md
Labels: cherry-pick, 21_2

#3917 SelectBox: update the 'fieldTemplate' property (#3912)
  api-reference/10 UI Components/dxSelectBox/1 Configuration/fieldTemplate.md
Labels: cherry-pick, 22_2

#3915 Grids: update the 'onToolbarPreparing' description
  api-reference/10 UI Components/GridBase/1 Configuration/onToolbarPreparing.md
  includes/datagrid-ontoolbarpreparing-jquery.md
Labels: 22_1

#3921 Grids: update the 'onToolbarPreparing' description (#3915)
  api-reference/10 UI Components/GridBase/1 Configuration/onToolbarPreparing.md
  includes/datagrid-ontoolbarpreparing-jquery.md
Labels: cherry-pick, 21_2

#3923 Grids: update the 'onEditorPreparing' description
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onEditorPreparing.md
Labels: 22_1

#3931 Grids: update the 'onEditorPreparing' description (#3923)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onEditorPreparing.md
Labels: cherry-pick, 21_2

#3932 Grids: update the 'onEditorPreparing' description (#3923)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onEditorPreparing.md
Labels: cherry-pick, 22_2

#3934 Editors: update the 'valueExpr' property description T879516 (#3933)
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: cherry-pick, 21_2
