Repository DevExpress/devextreme-documentation, pull requests merged in 2022-05, with the labels that each got.

#3666 Grids: the customizeColumns function limitation in React
  api-reference/10 UI Components/dxDataGrid/1 Configuration/customizeColumns.md
  includes/grids-customize-columns-react-note.md
Labels: 22_1

#3668 Grids: the customizeColumns function limitation in React (#3666)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/customizeColumns.md
  includes/grids-customize-columns-react-note.md
Labels: cherry-pick, 21_2

#3669 Grids: the customizeColumns function limitation in React (#3666)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/customizeColumns.md
  includes/grids-customize-columns-react-note.md
Labels: 21_1, cherry-pick

#3674 Export to PDF: fix links and examples
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/PdfExportDataGridProps.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/margin.md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
Labels: 22_1

#3670 DataGrid 'export': add information about PDF
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/allowExportSelectedData.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/enabled.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/texts/exportAll.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/texts/exportSelectedRows.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onExporting.md
  images/DataGrid/Export_SelectedRows.png
  images/DataGrid/export_texts/export_all_and_selected_data.png
  images/DataGrid/export_texts/export_all_default.png
  images/DataGrid/export_texts/export_all_on_small_screen.png
  images/DataGrid/export_texts/export_to.png
Labels: 22_1

#3672 Accordion: add a Getting Started tutorial
  api-reference/10 UI Components/dxAccordion/dxAccordion.md
  applications/GettingStartedWith/Accordion/index.css
  applications/GettingStartedWith/Accordion/index.html
  applications/GettingStartedWith/Accordion/index.js
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/00 Getting Started with Accordion.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/05 Create an Accordion.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/10 Bind Accordion to Data.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/15 Control the Accordion Behavior.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/20 Customize Item Appearance.md
  concepts/05 UI Components/Accordion/00 Overview.md
Labels: 21_2

#3689 Accordion: add a Getting Started tutorial (#3672)
  api-reference/10 UI Components/dxAccordion/dxAccordion.md
  applications/GettingStartedWith/Accordion/index.css
  applications/GettingStartedWith/Accordion/index.html
  applications/GettingStartedWith/Accordion/index.js
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/00 Getting Started with Accordion.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/05 Create an Accordion.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/10 Bind Accordion to Data.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/15 Control the Accordion Behavior.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/20 Customize Item Appearance.md
  concepts/05 UI Components/Accordion/00 Overview.md
Labels: 21_1, cherry-pick

#3690 Accordion: add a Getting Started tutorial (#3672)
  api-reference/10 UI Components/dxAccordion/dxAccordion.md
  applications/GettingStartedWith/Accordion/index.css
  applications/GettingStartedWith/Accordion/index.html
  applications/GettingStartedWith/Accordion/index.js
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/00 Getting Started with Accordion.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/05 Create an Accordion.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/10 Bind Accordion to Data.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/15 Control the Accordion Behavior.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/20 Customize Item Appearance.md
  concepts/05 UI Components/Accordion/00 Overview.md
Labels: cherry-pick, 22_1

#3677 DataGrid Getting Started tutorial: change 'Export Data' section
  applications/GettingStartedWith/DataGrid/index.js
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/10 Customize Columns/3 Reorder Columns.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/10 Customize Columns/8 Hide Columns.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/20 Sort Data.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/30 Filter and Search Data.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/35 Group Data.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data to Excel.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  includes/grids-tutorial-customize-the-toolbar.md
  includes/uiwidgets-grids-export-csv.md
Labels: 22_1

#3687 NumberBox: add description to the 'format' property
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
Labels: 21_2

#3703 NumberBox: add description to the 'format' property (#3687)
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
Labels: 21_1, cherry-pick

#3704 NumberBox: add description to the 'format' property (#3687)
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
Labels: cherry-pick, 22_1

#3705 Custom Format String: rework documentation
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: 21_2

#3709 Custom Format String: rework documentation (#3705)
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: 21_1, cherry-pick

#3710 Custom Format String: rework documentation (#3705)
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
  concepts/Common/Value Formatting/10 Format UI Component Values/20 Custom Format String.md
Labels: cherry-pick, 22_1

#3716 Add type for dxLoadPanel.contentTemplate (T1089001)
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/contentTemplate.md
Labels: cherry-pick, 21_2

#3715 Add type for dxLoadPanel.contentTemplate (T1089001)
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/contentTemplate.md
Labels: 22_1

#3717 Add type for dxLoadPanel.contentTemplate (T1089001)
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/contentTemplate.md
Labels: 21_1, cherry-pick

#3711 Toast: add a Getting Started tutorial
  applications/GettingStartedWith/Toast/index.css
  applications/GettingStartedWith/Toast/index.html
  applications/GettingStartedWith/Toast/index.js
  concepts/05 UI Components/Toast/00 Getting Started with Toast/00 Getting Started with Toast.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/00 Display a Toast notification.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/05 Use the 'notify' Method.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/10 Show and Hide the Toast.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/10 Customize Toast Content.md
  concepts/05 UI Components/Toast/00 Overview.md
Labels: 21_2

#3729 Toast: add a Getting Started tutorial (#3711)
  applications/GettingStartedWith/Toast/index.css
  applications/GettingStartedWith/Toast/index.html
  applications/GettingStartedWith/Toast/index.js
  concepts/05 UI Components/Toast/00 Getting Started with Toast/00 Getting Started with Toast.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/00 Display a Toast notification.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/05 Use the 'notify' Method.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/10 Show and Hide the Toast.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/10 Customize Toast Content.md
  concepts/05 UI Components/Toast/00 Overview.md
Labels: 21_1, cherry-pick

#3730 Toast: add a Getting Started tutorial (#3711)
  applications/GettingStartedWith/Toast/index.css
  applications/GettingStartedWith/Toast/index.html
  applications/GettingStartedWith/Toast/index.js
  concepts/05 UI Components/Toast/00 Getting Started with Toast/00 Getting Started with Toast.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/00 Display a Toast notification.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/05 Use the 'notify' Method.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/10 Show and Hide the Toast.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/10 Customize Toast Content.md
  concepts/05 UI Components/Toast/00 Overview.md
Labels: cherry-pick, 22_1

#3732 DataGrid: Fix example in Getting Started tutorial
  applications/GettingStartedWith/DataGrid/index.js
Labels: 22_1

#3736 DataGrid: Fix jQuery examples in the Getting Started tutorial
  applications/GettingStartedWith/DataGrid/index.js
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
Labels: 22_1

#3741 minor fix
  api-reference/50 Common/Object Structures/FileSystemError/FileSystemError.md
Labels: 22_1

#3739 dxRangeSelector: describe discreteAxisDivisionMode
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/discreteAxisDivisionMode.md
  images/ChartJS/range-selector-discreteAxisDivisionMode.png
Labels: 21_2

#3742 minor fix
  api-reference/50 Common/Object Structures/FileSystemError/FileSystemError.md
Labels: cherry-pick, 21_2

#3738 Format: describe useCurrencyAccountingStyle
  api-reference/50 Common/Object Structures/format/useCurrencyAccountingStyle.md
  api-reference/50 Common/Object Structures/globalConfig/defaultUseCurrencyAccountingStyle.md
  images/types/use-currency-accounting-style.png
Labels: 22_1

#3749 Charts: fix 'overlappingBehavior' description T1091675
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/overlappingBehavior.md
Labels: 21_2

#3751 Export to PDF: delete files
  api-reference/50 Common/Object Structures/PdfDataGridCell/column.md
  api-reference/50 Common/Object Structures/PdfDataGridCell/data.md
  api-reference/50 Common/Object Structures/PdfDataGridCell/groupIndex.md
  api-reference/50 Common/Object Structures/PdfDataGridCell/groupSummaryItems/groupSummaryItems.md
  api-reference/50 Common/Object Structures/PdfDataGridCell/groupSummaryItems/name.md
  api-reference/50 Common/Object Structures/PdfDataGridCell/groupSummaryItems/value.md
  api-reference/50 Common/Object Structures/PdfDataGridCell/rowType.md
  api-reference/50 Common/Object Structures/PdfDataGridCell/totalSummaryItemName.md
  api-reference/50 Common/Object Structures/PdfDataGridCell/value.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderColor.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderWidth.md
Labels: 22_1

#3758 Remove russian localization from the installer
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/05 Using Intl.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: 22_1

#3762 dxRangeSelector: describe discreteAxisDivisionMode (#3739)
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/discreteAxisDivisionMode.md
  images/ChartJS/range-selector-discreteAxisDivisionMode.png
Labels: 21_1, cherry-pick
