Repository DevExpress/devextreme-documentation, pull requests merged in 2022-03, with the labels that each got.

#3378 T925716, T1053765: Update showEditorAlways
  api-reference/_hidden/GridBaseColumn/showEditorAlways.md
Labels: 22_1

#3475 T925716, T1053765: Update showEditorAlways (#3378)
  api-reference/_hidden/GridBaseColumn/showEditorAlways.md
Labels: cherry-pick, 21_2

#3476 T925716, T1053765: Update showEditorAlways (#3378)
  api-reference/_hidden/GridBaseColumn/showEditorAlways.md
Labels: 21_1, cherry-pick

#3479 GridBaseColumn.showEditorAlways: add example (#3478)
  api-reference/_hidden/GridBaseColumn/showEditorAlways.md
  images/DataGrid/showEditorAlways.png
Labels: cherry-pick, 21_2

#3480 GridBaseColumn.showEditorAlways: add example (#3478)
  api-reference/_hidden/GridBaseColumn/showEditorAlways.md
  images/DataGrid/showEditorAlways.png
Labels: 21_1, cherry-pick

#3474 Pager: update images for compact mode
  api-reference/10 UI Components/GridBase/1 Configuration/pager/displayMode.md
  images/DataGrid/pager-display-mode-compact.png
  images/DataGrid/pager-display-mode-full.png
Labels: 22_1

#3477 TreeView: add description to getScrollable method
  api-reference/10 UI Components/GridBase/3 Methods/getScrollable().md
  api-reference/10 UI Components/dxTreeView/3 Methods/getScrollable().md
Labels: 21_2

#3484 TreeView: add description to getScrollable method (#3477)
  api-reference/10 UI Components/GridBase/3 Methods/getScrollable().md
  api-reference/10 UI Components/dxTreeView/3 Methods/getScrollable().md
Labels: cherry-pick, 22_1

#3485 Toolbar: delete obsolete submenuType
  api-reference/10 UI Components/dxToolbar/1 Configuration/submenuType.md
Labels: 22_1

#3486 Toolbar: delete obsolete submenuType (#3485)
  api-reference/10 UI Components/dxToolbar/1 Configuration/submenuType.md
Labels: cherry-pick, 21_2

#3490 Toolbar: change height description
  api-reference/10 UI Components/dxToolbar/1 Configuration/height.md
Labels: 21_2

#3494 T864994 Menu: add description to beginGroup
  api-reference/_hidden/dxMenuBaseItem/beginGroup.md
Labels: 21_2

#3495 T864994 Menu: add description to beginGroup (#3494)
  api-reference/_hidden/dxMenuBaseItem/beginGroup.md
Labels: 21_1, cherry-pick

#3526 Overlays: describe container and position options in more details
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/container.md
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/height.md
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/position.md
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/width.md
  api-reference/10 UI Components/dxPopover/1 Configuration/container.md
  api-reference/10 UI Components/dxPopover/1 Configuration/height.md
  api-reference/10 UI Components/dxPopover/1 Configuration/shading.md
  api-reference/10 UI Components/dxPopover/1 Configuration/width.md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/height.md
  api-reference/10 UI Components/dxPopup/1 Configuration/position.md
  api-reference/10 UI Components/dxPopup/1 Configuration/width.md
  api-reference/10 UI Components/dxToast/1 Configuration/height.md
  api-reference/10 UI Components/dxToast/1 Configuration/position.md
  api-reference/10 UI Components/dxToast/1 Configuration/width.md
Labels: 21_2

#3536 Overlays: describe container and position options in more details (#3526)
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/container.md
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/height.md
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/position.md
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/width.md
  api-reference/10 UI Components/dxPopover/1 Configuration/container.md
  api-reference/10 UI Components/dxPopover/1 Configuration/height.md
  api-reference/10 UI Components/dxPopover/1 Configuration/shading.md
  api-reference/10 UI Components/dxPopover/1 Configuration/width.md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/height.md
  api-reference/10 UI Components/dxPopup/1 Configuration/position.md
  api-reference/10 UI Components/dxPopup/1 Configuration/width.md
  api-reference/10 UI Components/dxToast/1 Configuration/height.md
  api-reference/10 UI Components/dxToast/1 Configuration/position.md
  api-reference/10 UI Components/dxToast/1 Configuration/width.md
Labels: 21_1, cherry-pick

#3537 Overlays: describe container and position options in more details
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/container.md
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/height.md
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/position.md
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/width.md
  api-reference/10 UI Components/dxPopover/1 Configuration/container.md
  api-reference/10 UI Components/dxPopover/1 Configuration/height.md
  api-reference/10 UI Components/dxPopover/1 Configuration/shading.md
  api-reference/10 UI Components/dxPopover/1 Configuration/width.md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/height.md
  api-reference/10 UI Components/dxPopup/1 Configuration/position.md
  api-reference/10 UI Components/dxPopup/1 Configuration/width.md
  api-reference/10 UI Components/dxToast/1 Configuration/height.md
  api-reference/10 UI Components/dxToast/1 Configuration/position.md
  api-reference/10 UI Components/dxToast/1 Configuration/width.md
Labels: cherry-pick, 22_1

#3441 TextBox: Add a Getting Started tutorial
  api-reference/10 UI Components/dxCalendar/dxCalendar.md
  api-reference/10 UI Components/dxColorBox/1 Configuration/fieldTemplate.md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/fieldTemplate.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPrepared.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPreparing.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/fieldTemplate.md
  api-reference/10 UI Components/dxTextBox/dxTextBox.md
  applications/GettingStartedWith/TextBox/index.css
  applications/GettingStartedWith/TextBox/index.html
  applications/GettingStartedWith/TextBox/index.js
  concepts/05 UI Components/TextArea/00 Overview.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/00 Getting Started with TextBox.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/05 Create a TextBox.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/10 Configure the Input Mode.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/15 Specify a Label or Placeholder.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/20 Limit the Text Length.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/25 Place Buttons Inside a TextBox.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/30 Handle the Keyboard Events.md
  concepts/05 UI Components/TextBox/00 Overview.md
  concepts/40 Angular Components/40 Common Features/10 Tree Shaking.md
Labels: 21_2

#3538 TextBox: Add a Getting Started tutorial (#3441)
  api-reference/10 UI Components/dxCalendar/dxCalendar.md
  api-reference/10 UI Components/dxColorBox/1 Configuration/fieldTemplate.md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/fieldTemplate.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPrepared.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPreparing.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/fieldTemplate.md
  api-reference/10 UI Components/dxTextBox/dxTextBox.md
  applications/GettingStartedWith/TextBox/index.css
  applications/GettingStartedWith/TextBox/index.html
  applications/GettingStartedWith/TextBox/index.js
  concepts/05 UI Components/TextArea/00 Overview.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/00 Getting Started with TextBox.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/05 Create a TextBox.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/10 Configure the Input Mode.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/15 Specify a Label or Placeholder.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/20 Limit the Text Length.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/25 Place Buttons Inside a TextBox.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/30 Handle the Keyboard Events.md
  concepts/05 UI Components/TextBox/00 Overview.md
  concepts/40 Angular Components/40 Common Features/10 Tree Shaking.md
Labels: cherry-pick, 22_1

#3491 Change the activeStateEnabled description
  api-reference/10 UI Components/Widget/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxButton/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxMenuBase/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxSlideOut/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxTileView/1 Configuration/activeStateEnabled.md
Labels: 21_2

#3545 Change the activeStateEnabled description (#3491)
  api-reference/10 UI Components/Widget/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxButton/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxMenuBase/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxSlideOut/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxTileView/1 Configuration/activeStateEnabled.md
Labels: 21_1, cherry-pick

#3546 Change the activeStateEnabled description (#3491)
  api-reference/10 UI Components/Widget/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxButton/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxMenuBase/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxSlideOut/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxTileView/1 Configuration/activeStateEnabled.md
Labels: cherry-pick, 22_1

#3565 Toast: move to ui/toast folder
  concepts/Common/Modularity/02 DevExtreme Modules Structure/ui/toast/toast.md
Labels: 22_1

#3553 Resizable: add keepAspectRatio description
  api-reference/10 UI Components/dxResizable/1 Configuration/keepAspectRatio.md
Labels: 22_1
