Repository DevExpress/devextreme-documentation, pull requests merged in 2022-04, with the labels that each got.

#3497 PDF - documentation draft
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/autoTableOptions.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderColor.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderWidth.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/customizeCell.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/indent.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/keepColumnWidths.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/loadPanel.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/bottom.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/left.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/margin.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/right.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/top.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/onRowExporting.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/repeatHeaders.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/topLeft.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/x.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/y.md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/_hidden/PdfCell/backgroundColor.md
  api-reference/_hidden/PdfCell/font/font.md
  api-reference/_hidden/PdfCell/font/name.md
  api-reference/_hidden/PdfCell/font/size.md
  api-reference/_hidden/PdfCell/font/style.md
  api-reference/_hidden/PdfCell/horizontalAlign.md
  api-reference/_hidden/PdfCell/padding/bottom.md
  api-reference/_hidden/PdfCell/padding/left.md
  api-reference/_hidden/PdfCell/padding/padding.md
  api-reference/_hidden/PdfCell/padding/right.md
  api-reference/_hidden/PdfCell/padding/top.md
  api-reference/_hidden/PdfCell/text.md
  api-reference/_hidden/PdfCell/textColor.md
  api-reference/_hidden/PdfCell/verticalAlign.md
  api-reference/_hidden/PdfCell/wordWrapEnabled.md
Labels: 22_1

#3579 ExportToPDF: change 'indent' property description
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/indent.md
  images/PDFExport/indent.png
Labels: 22_1

#3577 Resizable: change keepAspectRatio description
  api-reference/10 UI Components/dxResizable/1 Configuration/keepAspectRatio.md
  images/Editors/resizable-keep-aspect-ratio-true.gif
Labels: 22_1

#3498 Change name for zip-file with artifacts
  .github/workflows/docgen.yml
  .github/workflows/nodejs.yml
Labels: 22_1

#3568 Resizable: add area description
  api-reference/10 UI Components/dxResizable/1 Configuration/area.md
  images/Editors/resizable-area.png
Labels: 22_1

#3582 Add hideToasts method description
  api-reference/50 Common/utils/ui/3 Methods/hideToasts().md
  api-reference/50 Common/utils/ui/3 Methods/hideToasts(container).md
Labels: 22_1

#3555 Sortable and Draggable: update Drag functions and templates
  api-reference/10 UI Components/dxDraggable/1 Configuration/dragTemplate.md
  api-reference/10 UI Components/dxDraggable/1 Configuration/onDragEnd.md
  api-reference/10 UI Components/dxDraggable/1 Configuration/onDragMove.md
  api-reference/10 UI Components/dxDraggable/1 Configuration/onDragStart.md
  api-reference/10 UI Components/dxSortable/1 Configuration/dragTemplate.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragChange.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragEnd.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragMove.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragStart.md
Labels: 22_1

#3586 Update dxGantt scaleCellPrepared event
  api-reference/10 UI Components/dxGantt/1 Configuration/onScaleCellPrepared.md
Labels: 22_1

#3588 DataGrid: update saveRowChanges and cancelRowChanges properties
  api-reference/10 UI Components/GridBase/1 Configuration/editing/texts/cancelRowChanges.md
  api-reference/10 UI Components/GridBase/1 Configuration/editing/texts/saveRowChanges.md
Labels: 21_2

#3589 DataGrid: update saveRowChanges and cancelRowChanges properties
  api-reference/10 UI Components/GridBase/1 Configuration/editing/texts/cancelRowChanges.md
  api-reference/10 UI Components/GridBase/1 Configuration/editing/texts/saveRowChanges.md
Labels: 21_1, cherry-pick

#3594 DataGrid: remove ctp for PDF Export
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
Labels: 22_1

#3596 Chart: describe label.displayFormat
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/displayFormat.md
  images/ChartJS/label-display-format.png
Labels: 22_1

#3598 Chart: describe commonAxisSettings.aggregatedPointsPosition
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/aggregatedPointsPosition.md
  images/ChartJS/aggregated-points-position.png
Labels: 22_1

#3603 Chart, Polar - Deprecate event.cancel field(T1061174)
  api-reference/10 UI Components/BaseChart/1 Configuration/onPointClick.md
  api-reference/10 UI Components/dxChart/1 Configuration/onLegendClick.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/onLegendClick.md
Labels: 22_1

#3605 T1078819: update webpack configuration
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/04 Using Webpack/03 Configure Webpack Loaders.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/65 Additional Configuration for Webpack.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/65 Additional Configuration for Webpack.md
Labels: 22_1

#3607 T1078819: update webpack configuration
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/04 Using Webpack/03 Configure Webpack Loaders.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/65 Additional Configuration for Webpack.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/65 Additional Configuration for Webpack.md
Labels: cherry-pick, 21_2

#3608 T1078819: update webpack configuration
  concepts/40 Angular Components/10 Getting Started/30 Other Approaches/04 Using Webpack/03 Configure Webpack Loaders.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/65 Additional Configuration for Webpack.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/65 Additional Configuration for Webpack.md
Labels: 21_1, cherry-pick

#3609 T1079397 - Add a note about date strings convertation to filter-related topics
  api-reference/10 UI Components/GridBase/1 Configuration/filterValue.md
  api-reference/_hidden/GridBaseColumn/filterValues.md
Labels: 22_1

#3611 T1079397 - Add a note about date strings convertation to filter-related topics
  api-reference/10 UI Components/GridBase/1 Configuration/filterValue.md
  api-reference/_hidden/GridBaseColumn/filterValues.md
Labels: 21_1, cherry-pick

#3610 T1079397 - Add a note about date strings convertation to filter-related topics
  api-reference/10 UI Components/GridBase/1 Configuration/filterValue.md
  api-reference/_hidden/GridBaseColumn/filterValues.md
Labels: cherry-pick, 21_2

#3612 dxGantt: add note about data binding
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/tasks.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/20 Bind the Gantt to Data.md
Labels: 22_1

#3613 dxGantt: add note about data binding
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/tasks.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/20 Bind the Gantt to Data.md
Labels: cherry-pick, 21_2

#3614 dxGantt: add note about data binding
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/tasks.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/20 Bind the Gantt to Data.md
Labels: 21_1, cherry-pick

#3616 DataGrid: update dxDataGridColumn.allowExporting
  api-reference/_hidden/dxDataGridColumn/allowExporting.md
Labels: 22_1

#3615 T1082724: FileUploader fix description of the function
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onFilesUploaded.md
  api-reference/10 UI Components/dxFileUploader/4 Events/filesUploaded.md
Labels: 22_1

#3621 T1082724: FileUploader fix description of the function (#3615)
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onFilesUploaded.md
  api-reference/10 UI Components/dxFileUploader/4 Events/filesUploaded.md
Labels: cherry-pick, 21_2

#3622 DataGrid: update dxDataGridColumn.allowExporting (#3616)
  api-reference/_hidden/dxDataGridColumn/allowExporting.md
Labels: cherry-pick, 21_2

#3623 T1082724: FileUploader fix description of the function (#3615)
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onFilesUploaded.md
  api-reference/10 UI Components/dxFileUploader/4 Events/filesUploaded.md
Labels: 21_1, cherry-pick

#3624 DataGrid: update dxDataGridColumn.allowExporting (#3616)
  api-reference/_hidden/dxDataGridColumn/allowExporting.md
Labels: 21_1, cherry-pick

#3625 fix link
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/container.md
  api-reference/10 UI Components/dxPopover/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
Labels: 22_1

#3626 fix link
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/container.md
  api-reference/10 UI Components/dxPopover/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
Labels: cherry-pick, 21_2

#3627 fix link
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/container.md
  api-reference/10 UI Components/dxPopover/1 Configuration/container.md
  api-reference/10 UI Components/dxPopup/1 Configuration/container.md
Labels: 21_1, cherry-pick

#3628 HtmlEditor: imageUpload folder structure
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/imageUpload/imageUpload.md
Labels: 22_1

#3592 dxGantt: improve scale documentation
  api-reference/10 UI Components/dxGantt/1 Configuration/onScaleCellPrepared.md
  images/Gantt/customize-scale-seasons.png
  images/Gantt/customize-scale.png
Labels: 22_1

#3632 Change exportDataGrid(options) description
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
Labels: 22_1

#3633 Export to PDF: change 'customizeCell' description
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/customizeCell.md
Labels: 22_1

#3634 Export to PDF: change 'customDrawCell' description
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/customDrawCell.md
Labels: 22_1

#3635 Export to PDF: change 'onRowExporting' description
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/onRowExporting.md
Labels: 22_1

#3637 Chart: describe commonAxisSettings.aggregatedPointsPosition (#3598)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/aggregatedPointsPosition.md
  images/ChartJS/aggregated-points-position.png
Labels: cherry-pick, 21_2

#3638 Chart: describe commonAxisSettings.aggregatedPointsPosition (#3598)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/aggregatedPointsPosition.md
  images/ChartJS/aggregated-points-position.png
Labels: 21_1, cherry-pick

#3643 Export to PDF: change 'indent' description
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/indent.md
Labels: 22_1

#3642 Export to PDF: change 'loadPanel' description + minor fix
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/PdfExportDataGridProps.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/loadPanel.md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
Labels: 22_1

#3646 DevExtreme CLI: update arguments
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/10 Create a New Application.md
Labels: 22_1

#3645 Export to PDF: add examples to new API members
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderColor.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/borderWidth.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/columnWidths.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/margin/margin.md
  api-reference/50 Common/Object Structures/PdfExportDataGridProps/topLeft/topLeft.md
Labels: 22_1

#3618 jQuery: unit testing
  concepts/58 jQuery Components/30 Components Testing/00 Components Testing.md
  concepts/58 jQuery Components/30 Components Testing/10 Unit Testing.md
Labels: 22_1

#3653 Pager: update images for compact mode (#3474)
  api-reference/10 UI Components/GridBase/1 Configuration/pager/displayMode.md
  images/DataGrid/pager-display-mode-compact.png
  images/DataGrid/pager-display-mode-full.png
Labels: 21_1, cherry-pick

#3652 Pager: update images for compact mode (#3474)
  api-reference/10 UI Components/GridBase/1 Configuration/pager/displayMode.md
  images/DataGrid/pager-display-mode-compact.png
  images/DataGrid/pager-display-mode-full.png
Labels: cherry-pick, 21_2

#3651 Grid and TreeList: add notes
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/mode.md
Labels: 22_1

#3656 Grid and TreeList: add notes (#3651)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/mode.md
Labels: 21_1, cherry-pick

#3655 Grid and TreeList: add notes (#3651)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/mode.md
Labels: cherry-pick, 21_2

#3619 jQuery: integration tests
  concepts/58 jQuery Components/30 Components Testing/20 Integration Testing.md
Labels: 22_1

#3649 Notify: add description
  api-reference/50 Common/utils/ui/3 Methods/notify(message_stack).md
  api-reference/50 Common/utils/ui/3 Methods/notify(options_stack).md
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
  images/Utilities/notify-stack-up-push.png
  images/Utilities/notify-stack-up-stack.png
Labels: 22_1

#3664 Lookup: add 'searchStartEvent' description
  api-reference/10 UI Components/dxLookup/1 Configuration/searchStartEvent.md
Labels: 22_1

#3663 Export to PDF: make 'PdfCell' public and update descriptions
  api-reference/50 Common/Object Structures/PdfCell/PdfCell.md
  api-reference/50 Common/Object Structures/PdfCell/backgroundColor.md
  api-reference/50 Common/Object Structures/PdfCell/borderColor.md
  api-reference/50 Common/Object Structures/PdfCell/borderWidth.md
  api-reference/50 Common/Object Structures/PdfCell/drawBottomBorder.md
  api-reference/50 Common/Object Structures/PdfCell/drawLeftBorder.md
  api-reference/50 Common/Object Structures/PdfCell/drawRightBorder.md
  api-reference/50 Common/Object Structures/PdfCell/drawTopBorder.md
  api-reference/50 Common/Object Structures/PdfCell/font/font.md
  api-reference/50 Common/Object Structures/PdfCell/font/name.md
  api-reference/50 Common/Object Structures/PdfCell/font/size.md
  api-reference/50 Common/Object Structures/PdfCell/font/style.md
  api-reference/50 Common/Object Structures/PdfCell/horizontalAlign.md
  api-reference/50 Common/Object Structures/PdfCell/padding/bottom.md
  api-reference/50 Common/Object Structures/PdfCell/padding/left.md
  api-reference/50 Common/Object Structures/PdfCell/padding/padding.md
  api-reference/50 Common/Object Structures/PdfCell/padding/right.md
  api-reference/50 Common/Object Structures/PdfCell/padding/top.md
  api-reference/50 Common/Object Structures/PdfCell/text.md
  api-reference/50 Common/Object Structures/PdfCell/textColor.md
  api-reference/50 Common/Object Structures/PdfCell/verticalAlign.md
  api-reference/50 Common/Object Structures/PdfCell/wordWrapEnabled.md
  api-reference/_hidden/PdfCell/PdfCell.md
  api-reference/_hidden/PdfCell/borderWidth.md
  api-reference/_hidden/PdfCell/drawBottomBorder.md
  api-reference/_hidden/PdfCell/drawLeftBorder.md
  api-reference/_hidden/PdfCell/drawRightBorder.md
  api-reference/_hidden/PdfCell/drawTopBorder.md
Labels: 22_1

#3657 jQuery: End-to-End Testing
  concepts/58 jQuery Components/30 Components Testing/30 End-to-End Testing.md
Labels: 22_1
