Repository DevExpress/devextreme-documentation, pull requests merged in 2022-12, with the labels that each got.

#4416 dxToast: update the width and height properties description
  api-reference/10 UI Components/dxToast/1 Configuration/height.md
  api-reference/10 UI Components/dxToast/1 Configuration/maxHeight.md
  api-reference/10 UI Components/dxToast/1 Configuration/maxWidth.md
  api-reference/10 UI Components/dxToast/1 Configuration/minHeight.md
  api-reference/10 UI Components/dxToast/1 Configuration/minWidth.md
  api-reference/10 UI Components/dxToast/1 Configuration/width.md
Labels: 22_1

#4417 dxToast: update the width and height properties description (#4416)
  api-reference/10 UI Components/dxToast/1 Configuration/height.md
  api-reference/10 UI Components/dxToast/1 Configuration/maxHeight.md
  api-reference/10 UI Components/dxToast/1 Configuration/maxWidth.md
  api-reference/10 UI Components/dxToast/1 Configuration/minHeight.md
  api-reference/10 UI Components/dxToast/1 Configuration/minWidth.md
  api-reference/10 UI Components/dxToast/1 Configuration/width.md
Labels: cherry-pick, 21_2

#4418 dxToast: update the width and height properties description (#4416)
  api-reference/10 UI Components/dxToast/1 Configuration/height.md
  api-reference/10 UI Components/dxToast/1 Configuration/maxHeight.md
  api-reference/10 UI Components/dxToast/1 Configuration/maxWidth.md
  api-reference/10 UI Components/dxToast/1 Configuration/minHeight.md
  api-reference/10 UI Components/dxToast/1 Configuration/minWidth.md
  api-reference/10 UI Components/dxToast/1 Configuration/width.md
Labels: cherry-pick, 22_2

#4419 FileManager: update Getting Started description (See Also list typo)
  concepts/05 UI Components/FileManager/00 Getting Started with File Manager/20 Bind the File Manager Component to a File System.md
Labels: 22_1

#4422 FileManager: update Getting Started description (See Also list typo)
  concepts/05 UI Components/FileManager/00 Getting Started with File Manager/20 Bind the File Manager Component to a File System.md
Labels: cherry-pick, 21_2

#4427 CheckBox: update the value property typo
  api-reference/10 UI Components/dxCheckBox/1 Configuration/value.md
Labels: 22_2

#4425 TextArea: add a Getting Started tutorial
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPreparing.md
  api-reference/10 UI Components/dxTextArea/dxTextArea.md
  applications/GettingStartedWith/TextArea/index.css
  applications/GettingStartedWith/TextArea/index.html
  applications/GettingStartedWith/TextArea/index.js
  concepts/05 UI Components/Form/15 Configure Item Labels/05 Location and Alignment/05 Align Labels Relatively to Editors.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/00 Getting Started with TextArea.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/05 Create a TextArea.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/10 Specify Value and Label.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/15 Resize TextArea.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/20 Handle Value Change.md
  concepts/05 UI Components/TextArea/00 Overview.md
Labels: 22_1

#4430 TextArea: add a Getting Started tutorial
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPreparing.md
  api-reference/10 UI Components/dxTextArea/dxTextArea.md
  applications/GettingStartedWith/TextArea/index.css
  applications/GettingStartedWith/TextArea/index.html
  applications/GettingStartedWith/TextArea/index.js
  concepts/05 UI Components/Form/15 Configure Item Labels/05 Location and Alignment/05 Align Labels Relatively to Editors.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/00 Getting Started with TextArea.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/05 Create a TextArea.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/10 Specify Value and Label.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/15 Resize TextArea.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/20 Handle Value Change.md
  concepts/05 UI Components/TextArea/00 Overview.md
Labels: cherry-pick, 21_2

#4431 TextArea: add a Getting Started tutorial
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPreparing.md
  api-reference/10 UI Components/dxTextArea/dxTextArea.md
  applications/GettingStartedWith/TextArea/index.css
  applications/GettingStartedWith/TextArea/index.html
  applications/GettingStartedWith/TextArea/index.js
  concepts/05 UI Components/Form/15 Configure Item Labels/05 Location and Alignment/05 Align Labels Relatively to Editors.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/00 Getting Started with TextArea.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/05 Create a TextArea.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/10 Specify Value and Label.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/15 Resize TextArea.md
  concepts/05 UI Components/TextArea/00 Getting Started with TextArea/20 Handle Value Change.md
  concepts/05 UI Components/TextArea/00 Overview.md
Labels: cherry-pick, 22_2

#4433 ZIP Archive: add a note related to the latest version (#4428)
  concepts/Common/Distribution Channels/15 ZIP Archive.md
Labels: cherry-pick, 22_2

#4432 ZIP Archive: add a note related to the latest version (#4428)
  concepts/Common/Distribution Channels/15 ZIP Archive.md
Labels: cherry-pick, 21_2

#4436 CheckBox: update the Getting Started tutorial
  applications/GettingStartedWith/CheckBox/index.js
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/10 Specify the Initial Value.md
Labels: 22_2

#4438 Calendar: update Getting Started tutorial
  applications/GettingStartedWith/Calendar/index.js
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/23 Show Week Numbers.md
  concepts/05 UI Components/Calendar/00 Getting Started with Calendar/25 Customize Cell Appearance.md
Labels: 22_2

#4441 NumberBox: update GS code snippets typos
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/10 Limit and Format the Value.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/15 Configure Spin Buttons.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/20 Specify the Label.md
Labels: 22_1

#4442 NumberBox: update GS code snippets typos
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/10 Limit and Format the Value.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/15 Configure Spin Buttons.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/20 Specify the Label.md
Labels: cherry-pick, 21_2

#4443 NumberBox: update GS code snippets typos
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/10 Limit and Format the Value.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/15 Configure Spin Buttons.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/20 Specify the Label.md
Labels: cherry-pick, 22_2

#4439 TabPanel: update Getting Started tutorial
  applications/GettingStartedWith/TabPanel/index.js
  concepts/05 UI Components/TabPanel/01 Getting Started with TabPanel/20 Create Tabs.md
  concepts/05 UI Components/TabPanel/01 Getting Started with TabPanel/30 Specify View Content.md
Labels: 22_2

#4447 Funnel: update algorithm property typo
  api-reference/10 UI Components/dxFunnel/1 Configuration/algorithm.md
Labels: 22_1

#4450 Funnel: update algorithm property typo
  api-reference/10 UI Components/dxFunnel/1 Configuration/algorithm.md
Labels: cherry-pick, 22_2

#4449 Funnel: update algorithm property typo
  api-reference/10 UI Components/dxFunnel/1 Configuration/algorithm.md
Labels: cherry-pick, 21_2

#4452 CustomStore: update load and load(options)
  api-reference/30 Data Layer/CustomStore/3 Methods/load().md
  api-reference/30 Data Layer/CustomStore/3 Methods/load(options).md
Labels: 22_2

#4454 CustomStore: update load and load(options) (#4452)
  api-reference/30 Data Layer/CustomStore/3 Methods/load().md
  api-reference/30 Data Layer/CustomStore/3 Methods/load(options).md
Labels: cherry-pick, 22_1

#4456 Fix display of topics with "include" and [tags]
  includes/custom-templates.md
  includes/datagrid-ontoolbarpreparing-jquery.md
  includes/grids-customize-columns-react-note.md
  includes/named-templates-note.md
Labels: 22_2

#4458 Fix display of topics with "include" and [tags] (#4456)
  includes/custom-templates.md
  includes/datagrid-ontoolbarpreparing-jquery.md
  includes/grids-customize-columns-react-note.md
  includes/named-templates-note.md
Labels: cherry-pick, 22_1

#4459 Fix display of topics with "include" and [tags] (#4456)
  includes/custom-templates.md
  includes/datagrid-ontoolbarpreparing-jquery.md
  includes/grids-customize-columns-react-note.md
  includes/named-templates-note.md
Labels: cherry-pick, 21_2

#4446 Switch: add getting started tutorial
  api-reference/10 UI Components/dxSwitch/dxSwitch.md
  applications/GettingStartedWith/Switch/index.css
  applications/GettingStartedWith/Switch/index.html
  applications/GettingStartedWith/Switch/index.js
  concepts/05 UI Components/DataGrid/20 Editing/40 Customize Editors.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/00 Getting Started with Switch.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/05 Create a Switch.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/10 Specify the Initial State.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/15 Configure Size.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/20 Define a Hint.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/25 Handle Value Change.md
  concepts/05 UI Components/Switch/00 Overview.md
  concepts/05 UI Components/Tooltip/10 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/TreeList/20 Editing/40 Customize Editors.md
Labels: 22_1

#4460 Switch: add getting started tutorial
  api-reference/10 UI Components/dxSwitch/dxSwitch.md
  applications/GettingStartedWith/Switch/index.css
  applications/GettingStartedWith/Switch/index.html
  applications/GettingStartedWith/Switch/index.js
  concepts/05 UI Components/DataGrid/20 Editing/40 Customize Editors.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/00 Getting Started with Switch.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/05 Create a Switch.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/10 Specify the Initial State.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/15 Configure Size.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/20 Define a Hint.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/25 Handle Value Change.md
  concepts/05 UI Components/Switch/00 Overview.md
  concepts/05 UI Components/Tooltip/10 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/TreeList/20 Editing/40 Customize Editors.md
Labels: cherry-pick, 22_2

#4462 Switch: add getting started tutorial
  api-reference/10 UI Components/dxSwitch/dxSwitch.md
  applications/GettingStartedWith/Switch/index.css
  applications/GettingStartedWith/Switch/index.html
  applications/GettingStartedWith/Switch/index.js
  concepts/05 UI Components/DataGrid/20 Editing/40 Customize Editors.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/00 Getting Started with Switch.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/05 Create a Switch.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/10 Specify the Initial State.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/15 Configure Size.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/20 Define a Hint.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/25 Handle Value Change.md
  concepts/05 UI Components/Switch/00 Overview.md
  concepts/05 UI Components/Tooltip/10 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/TreeList/20 Editing/40 Customize Editors.md
Labels: cherry-pick, 23_1

#4468 Switch: update variables in code snippets
  applications/GettingStartedWith/Switch/index.js
  concepts/05 UI Components/Switch/00 Getting Started with Switch/20 Define a Hint.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/25 Handle Value Change.md
Labels: cherry-pick, 23_1

#4469 Switch: update variables in code snippets
  applications/GettingStartedWith/Switch/index.js
  concepts/05 UI Components/Switch/00 Getting Started with Switch/20 Define a Hint.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/25 Handle Value Change.md
Labels: cherry-pick, 22_1

#4471 Gantt: fix broken code snippets
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskProgressTooltipContentTemplate.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTimeTooltipContentTemplate.md
Labels: 22_2

#4472 Gantt: fix broken code snippets
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskProgressTooltipContentTemplate.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTimeTooltipContentTemplate.md
Labels: cherry-pick, 22_1

#4473 Gantt: fix broken code snippets (#4471)
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskProgressTooltipContentTemplate.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTimeTooltipContentTemplate.md
Labels: cherry-pick, 23_1

#4476 Update frameworks supported versions
  concepts/40 Angular Components/80 Supported Versions.md
  concepts/50 React Components/80 Supported Versions.md
  concepts/55 Vue Components/80 Supported Versions.md
  concepts/58 jQuery Components/80 Supported Versions.md
Labels: 22_2

#4474 Toolbar: add menuItemTemplate code snippets
  api-reference/10 UI Components/dxToolbar/1 Configuration/menuItemTemplate.md
  api-reference/_hidden/dxToolbarItem/menuItemTemplate.md
Labels: 22_2

#4477 Update frameworks supported versions (#4476)
  concepts/40 Angular Components/80 Supported Versions.md
  concepts/50 React Components/80 Supported Versions.md
  concepts/55 Vue Components/80 Supported Versions.md
  concepts/58 jQuery Components/80 Supported Versions.md
Labels: 23_1

#4478 Toolbar: add menuItemTemplate code snippets (#4474)
  api-reference/10 UI Components/dxToolbar/1 Configuration/menuItemTemplate.md
  api-reference/_hidden/dxToolbarItem/menuItemTemplate.md
Labels: cherry-pick, 22_1

#4479 Toolbar: add menuItemTemplate code snippets (#4474)
  api-reference/10 UI Components/dxToolbar/1 Configuration/menuItemTemplate.md
  api-reference/_hidden/dxToolbarItem/menuItemTemplate.md
Labels: cherry-pick, 23_1

#4470 SelectBox/TagBox: update custom item creating topics
  concepts/05 UI Components/SelectBox/15 Create a User-Defined Item.md
  concepts/05 UI Components/TagBox/15 Create a User-Defined Item.md
Labels: 22_2

#4482 SelectBox/TagBox: update custom item creating topics (#4470)
  concepts/05 UI Components/SelectBox/15 Create a User-Defined Item.md
  concepts/05 UI Components/TagBox/15 Create a User-Defined Item.md
Labels: cherry-pick, 23_1
