Repository DevExpress/devextreme-documentation, pull requests merged in 2022-11, with the labels that each got.

#4326 Overlay: update baseZIndex(zIndex) description
  api-reference/50 Common/utils/ui/dxOverlay/baseZIndex(zIndex).md
Labels: 22_1

#4327 Overlay: update baseZIndex(zIndex) description (#4326)
  api-reference/50 Common/utils/ui/dxOverlay/baseZIndex(zIndex).md
Labels: cherry-pick, 21_2

#4329 Overlay: update baseZIndex(zIndex) description (#4326)
  api-reference/50 Common/utils/ui/dxOverlay/baseZIndex(zIndex).md
Labels: cherry-pick, 22_2

#4332 Sliders: add ValueChangeMode description
  api-reference/10 UI Components/dxSliderBase/1 Configuration/callValueChange.md
  api-reference/10 UI Components/dxSliderBase/1 Configuration/valueChangeMode.md
Labels: 22_2

#4333 Scheduler: update appointmentTooltipTemplate description
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentTooltipTemplate.md
Labels: 22_1

#4334 Scheduler: update appointmentTooltipTemplate description (#4333)
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentTooltipTemplate.md
Labels: cherry-pick, 22_2

#4336 HtmlEditor: update toolbar.options code snippet (jquery)
  includes/uiwidgets-nestedtoolbar-widgetoptions-fulldesc.md
Labels: 22_1

#4339 HtmlEditor: update toolbar.options code snippet (jquery) (#4336)
  includes/uiwidgets-nestedtoolbar-widgetoptions-fulldesc.md
Labels: cherry-pick, 22_2

#4338 HtmlEditor: update toolbar.options code snippet (jquery)
  includes/uiwidgets-nestedtoolbar-widgetoptions-fulldesc.md
Labels: cherry-pick, 21_2

#4343 Remove the use of dx.common.css
  api-reference/10 UI Components/GridBase/3 Methods/cellValue(rowIndex_dataField_value).md
  api-reference/10 UI Components/GridBase/3 Methods/cellValue(rowIndex_visibleColumnIndex_value).md
  api-reference/10 UI Components/dxDataGrid/3 Methods/totalCount().md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/fieldTemplate.md
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/onEditorPreparing.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskProgressTooltipContentTemplate.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTimeTooltipContentTemplate.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTooltipContentTemplate.md
  api-reference/_hidden/dxFilterBuilderField/editorOptions.md
  api-reference/_hidden/dxGanttContextMenu/enabled.md
  api-reference/_hidden/dxGanttContextMenuItem/name.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/05 Create Autocomplete and Bind It to Data.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/05 UI Components/DataGrid/45 Grouping/10 User Interaction/20 Expand and Collapse Groups.md
  concepts/05 UI Components/DataGrid/45 Grouping/20 API/10 Initial and Runtime Grouping.md
  concepts/05 UI Components/DataGrid/45 Grouping/20 API/20 Expand and Collapse Groups.md
  concepts/05 UI Components/DataGrid/45 Grouping/20 API/30 Clear Grouping.md
  concepts/05 UI Components/DataGrid/45 Grouping/30 Events.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/10 Specify a Custom Data Source.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/30 Change the Generated Data Source.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/40 Customize Item Appearance.md
  concepts/05 UI Components/DateBox/15 Specify Value Range.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/15 Implement Navigation.md
  concepts/05 UI Components/Form/01 Getting Started with Form/10 Create a Form.md
  concepts/05 UI Components/List/00 Getting Started with List/02 Create a List.md
  concepts/05 UI Components/List/00 Getting Started with List/03 Bind the List to Data.md
  concepts/05 UI Components/List/00 Getting Started with List/04 Select Items.md
  concepts/05 UI Components/List/00 Getting Started with List/05 Group Items.md
  concepts/05 UI Components/List/00 Getting Started with List/06 Search Items.md
  concepts/05 UI Components/List/00 Getting Started with List/08 Delete Items.md
  concepts/05 UI Components/PivotGrid/00 Getting Started with PivotGrid/02 Create a PivotGrid.md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/02 Create a Popup.md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
  concepts/05 UI Components/TreeList/50 Selection/10 User Interaction.md
  concepts/05 UI Components/TreeList/50 Selection/20 API/1 Initial and Runtime Selection.md
  concepts/05 UI Components/TreeList/50 Selection/20 API/8 Clear Selection Settings.md
  concepts/05 UI Components/TreeList/50 Selection/30 Events.md
  concepts/Common/Distribution Channels/05 CDN/10 Subresource Integrity Hashes.md
  includes/tutorials-export-data-to-excel.md
Labels: 22_2

#4349 Overlays: describe default values for the animation object
  api-reference/10 UI Components/dxOverlay/1 Configuration/animation/animation.md
  api-reference/10 UI Components/dxPopover/1 Configuration/animation/animation.md
  api-reference/10 UI Components/dxPopup/1 Configuration/animation/animation.md
  api-reference/10 UI Components/dxToast/1 Configuration/animation/animation.md
Labels: 22_1

#4350 Overlays: describe default values for the animation object (#4349)
  api-reference/10 UI Components/dxOverlay/1 Configuration/animation/animation.md
  api-reference/10 UI Components/dxPopover/1 Configuration/animation/animation.md
  api-reference/10 UI Components/dxPopup/1 Configuration/animation/animation.md
  api-reference/10 UI Components/dxToast/1 Configuration/animation/animation.md
Labels: cherry-pick, 21_2

#4351 Overlays: describe default values for the animation object (#4349)
  api-reference/10 UI Components/dxOverlay/1 Configuration/animation/animation.md
  api-reference/10 UI Components/dxPopover/1 Configuration/animation/animation.md
  api-reference/10 UI Components/dxPopup/1 Configuration/animation/animation.md
  api-reference/10 UI Components/dxToast/1 Configuration/animation/animation.md
Labels: cherry-pick, 22_2

#4356 Button: add a note about deprecated type
  api-reference/10 UI Components/dxButton/1 Configuration/type.md
Labels: 22_2

#4348 ColorBox: add a Getting Started tutorial
  api-reference/10 UI Components/dxColorBox/dxColorBox.md
  applications/GettingStartedWith/ColorBox/index.css
  applications/GettingStartedWith/ColorBox/index.html
  applications/GettingStartedWith/ColorBox/index.js
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/00 Getting Started with ColorBox.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/05 Create a ColorBox.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/10 Configure Values.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/15 Customize Buttons and Labels.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/20 Handle Value Change.md
  concepts/05 UI Components/ColorBox/00 Overview.md
Labels: 22_1

#4360 Angular: delete Visual Studio Integration guides
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/20 Add DevExtreme to an ASP.NET Core Angular Application.md
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/30 Troubleshooting.md
  concepts/40 Angular Components/70 Visual Studio Integration/50 Scaffold an Angular Component.md
Labels: 22_2

#4361 ColorBox: add a Getting Started tutorial (#4348)
  api-reference/10 UI Components/dxColorBox/dxColorBox.md
  applications/GettingStartedWith/ColorBox/index.css
  applications/GettingStartedWith/ColorBox/index.html
  applications/GettingStartedWith/ColorBox/index.js
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/00 Getting Started with ColorBox.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/05 Create a ColorBox.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/10 Configure Values.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/15 Customize Buttons and Labels.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/20 Handle Value Change.md
  concepts/05 UI Components/ColorBox/00 Overview.md
Labels: cherry-pick, 22_2

#4362 ColorBox: add a Getting Started tutorial (#4348)
  api-reference/10 UI Components/dxColorBox/dxColorBox.md
  applications/GettingStartedWith/ColorBox/index.css
  applications/GettingStartedWith/ColorBox/index.html
  applications/GettingStartedWith/ColorBox/index.js
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/00 Getting Started with ColorBox.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/05 Create a ColorBox.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/10 Configure Values.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/15 Customize Buttons and Labels.md
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/20 Handle Value Change.md
  concepts/05 UI Components/ColorBox/00 Overview.md
Labels: cherry-pick, 21_2

#4363 Calendar: fix weekNumberRule description
  api-reference/10 UI Components/dxCalendar/1 Configuration/weekNumberRule.md
Labels: 22_2

#4380 Angular: return VS Integration topics
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/20 Add DevExtreme to an ASP.NET Core Angular Application.md
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/30 Troubleshooting.md
  concepts/40 Angular Components/70 Visual Studio Integration/50 Scaffold an Angular Component.md
Labels: 22_2

#4379 activeStateEnabled: update description (remove MUI link)
  api-reference/10 UI Components/Widget/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxButton/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxMenuBase/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxSlideOut/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxTileView/1 Configuration/activeStateEnabled.md
Labels: 22_1

#4382 activeStateEnabled: update description (remove MUI link) (#4379)
  api-reference/10 UI Components/Widget/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxButton/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxMenuBase/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxTileView/1 Configuration/activeStateEnabled.md
Labels: cherry-pick, 22_2

#4381 activeStateEnabled: update description (remove MUI link)
  api-reference/10 UI Components/Widget/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxButton/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxMenuBase/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxSlideOut/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxTileView/1 Configuration/activeStateEnabled.md
Labels: cherry-pick, 21_2

#4383 Remove VS Integration topics
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/20 Add DevExtreme to an ASP.NET Core Angular Application.md
  concepts/40 Angular Components/70 Visual Studio Integration/20 Add DevExtreme to an ASP.NET Core Angular Application/30 Troubleshooting.md
  concepts/40 Angular Components/70 Visual Studio Integration/50 Scaffold an Angular Component.md
Labels: 22_2

#4377 NumberBox: add getting started description
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/00 Getting Started with NumberBox.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/05 Create a NumberBox.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/10 Limit and Format the Value.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/15 Configure Spin Buttons.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/20 Specify the Label.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/25 Handle Value Change.md
  concepts/05 UI Components/NumberBox/00 Overview.md
Labels: 22_1

#4388 NumberBox: add example
  applications/GettingStartedWith/NumberBox/index.css
  applications/GettingStartedWith/NumberBox/index.html
  applications/GettingStartedWith/NumberBox/index.js
Labels: 22_1

#4386 NumberBox: add getting started tutorial
  applications/GettingStartedWith/NumberBox/index.css
  applications/GettingStartedWith/NumberBox/index.html
  applications/GettingStartedWith/NumberBox/index.js
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/00 Getting Started with NumberBox.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/05 Create a NumberBox.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/10 Limit and Format the Value.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/15 Configure Spin Buttons.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/20 Specify the Label.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/25 Handle Value Change.md
  concepts/05 UI Components/NumberBox/00 Overview.md
Labels: cherry-pick, 21_2

#4387 NumberBox: add getting started tutorial
  applications/GettingStartedWith/NumberBox/index.css
  applications/GettingStartedWith/NumberBox/index.html
  applications/GettingStartedWith/NumberBox/index.js
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/00 Getting Started with NumberBox.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/05 Create a NumberBox.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/10 Limit and Format the Value.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/15 Configure Spin Buttons.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/20 Specify the Label.md
  concepts/05 UI Components/NumberBox/00 Getting Started with NumberBox/25 Handle Value Change.md
  concepts/05 UI Components/NumberBox/00 Overview.md
Labels: cherry-pick, 22_2

#4392 Update number of components in the framework pages
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
Labels: 22_1

#4393 Update number of components in the framework pages (#4392)
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
Labels: cherry-pick, 21_2

#4397 Scheduler: add an example to 'views'
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/views.md
Labels: 22_1

#4398 Scheduler: add an example to 'views' (#4397)
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/views.md
Labels: cherry-pick, 22_2

#4399 Scheduler: add an example to 'views' (#4397)
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/views.md
Labels: cherry-pick, 21_2

#4403 DataGrid: add a context reference
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
  api-reference/_hidden/GridBaseColumn/calculateDisplayValue.md
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
  api-reference/_hidden/GridBaseColumn/customizeText.md
  api-reference/_hidden/GridBaseColumn/setCellValue.md
  api-reference/_hidden/GridBaseColumn/sortingMethod.md
  api-reference/_hidden/dxDataGridColumn/calculateGroupValue.md
Labels: 22_1

#4404 DataGrid: add a context reference (#4403)
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
  api-reference/_hidden/GridBaseColumn/calculateDisplayValue.md
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
  api-reference/_hidden/GridBaseColumn/customizeText.md
  api-reference/_hidden/GridBaseColumn/setCellValue.md
  api-reference/_hidden/GridBaseColumn/sortingMethod.md
  api-reference/_hidden/dxDataGridColumn/calculateGroupValue.md
Labels: cherry-pick, 22_2

#4405 Popup: fix toolbarItems links
  api-reference/_hidden/dxPopupToolbarItem/showText.md
  api-reference/_hidden/dxPopupToolbarItem/widget.md
Labels: 22_2

#4406 DataGrid: update cell render code snippets
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/2 Customize the Appearance.md
Labels: 22_1

#4407 DataGrid: update cell render code snippets
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/2 Customize the Appearance.md
Labels: cherry-pick, 21_2

#4408 DataGrid: update cell render code snippets
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/2 Customize the Appearance.md
Labels: cherry-pick, 22_2

#4409 Accordion: update code snippets in gs (Angular, Vue)
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/15 Control the Accordion Behavior.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/20 Customize Item Appearance.md
Labels: 22_1

#4411 Accordion: update code snippets in gs (Angular, Vue) (#4409)
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/15 Control the Accordion Behavior.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/20 Customize Item Appearance.md
Labels: cherry-pick, 22_2

#4410 Accordion: update code snippets in gs (Angular, Vue)
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/15 Control the Accordion Behavior.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/20 Customize Item Appearance.md
Labels: cherry-pick, 21_2

#4413 Data Validation: update code snippet (add react hook)
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/60 Validate a Custom Value.md
Labels: 22_1

#4414 Data Validation: update code snippet (add react hook) (#4413)
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/60 Validate a Custom Value.md
Labels: cherry-pick, 21_2

#4415 Data Validation: update code snippet (add react hook)
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/60 Validate a Custom Value.md
Labels: cherry-pick, 22_2
