Repository DevExpress/devextreme-documentation, pull requests merged in 2023-08, with the labels that each got.

#5428 Change versions from 22.2 to 23.1
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/0 Learn Breaking Changes and Deprecated API.md
  concepts/Common/Modularity/01 Link Modules/10 Use Webpack.md
  concepts/Common/Modularity/01 Link Modules/20 Use jspm.md
  concepts/Common/Modularity/01 Link Modules/30 Use RequireJS.md
Labels: 23_1

#5429 Change versions in 23.2
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
  concepts/Common/Migrate to the New Version/40 Learn What's New.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/0 Learn Breaking Changes and Deprecated API.md
  concepts/Common/Modularity/01 Link Modules/10 Use Webpack.md
  concepts/Common/Modularity/01 Link Modules/20 Use jspm.md
  concepts/Common/Modularity/01 Link Modules/30 Use RequireJS.md
  includes/ng-install-devextreme.md
Labels: 23_2

#5430 Localization: update topic
  concepts/Common/Localization/01 Dictionaries/05 Add Strings to a Dictionary.md
  concepts/Common/Localization/01 Dictionaries/07 Override Strings in a Dictionary.md
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
Labels: 23_1

#5432 Localization: update topic (#5430)
  concepts/Common/Localization/01 Dictionaries/05 Add Strings to a Dictionary.md
  concepts/Common/Localization/01 Dictionaries/07 Override Strings in a Dictionary.md
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
Labels: cherry-pick, 22_2

#5431 W1024: add description
  api-reference/10 UI Components/Errors and Warnings/W1024.md
Labels: 23_1

#5433 Localization: update topic (#5430)
  concepts/Common/Localization/01 Dictionaries/05 Add Strings to a Dictionary.md
  concepts/Common/Localization/01 Dictionaries/07 Override Strings in a Dictionary.md
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
Labels: cherry-pick, 23_2

#5435 W1024: add description (#5431)
  api-reference/10 UI Components/Errors and Warnings/W1024.md
Labels: cherry-pick, 23_2

#5439 Custom templates: update info
  includes/custom-templates.md
Labels: 23_1

#5440 Custom templates: update info
  includes/custom-templates.md
Labels: cherry-pick, 22_2

#5441 Custom templates: update info (#5439)
  includes/custom-templates.md
Labels: cherry-pick, 23_2

#5443 E1046: add Gantt
  api-reference/10 UI Components/Errors and Warnings/E1046.md
Labels: 23_1

#5444 E1046: add Gantt (#5443)
  api-reference/10 UI Components/Errors and Warnings/E1046.md
Labels: cherry-pick, 22_2

#5451 TreeList: delete KB link (#5450)
  api-reference/10 UI Components/dxTreeList/1 Configuration/dataStructure.md
Labels: cherry-pick, 23_2

#5395 Button: update type description
  api-reference/10 UI Components/dxButton/1 Configuration/type.md
  images/UiWidgets/Button_Types.png
Labels: 23_2

#5456 Accessibility Overview: update Standard Compliance
  concepts/Common/Accessibility/00 Overview/35 Standard Compliance.md
  concepts/Common/Accessibility/05 Documentation for Components.md
Labels: 23_1

#5457 Accessibility Overview: update Standard Compliance (#5456)
  concepts/Common/Accessibility/00 Overview/35 Standard Compliance.md
  concepts/Common/Accessibility/05 Documentation for Components.md
Labels: cherry-pick, 23_2

#5442 Troubleshooting: Component Content is not Scrollable
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/00 Component Content is not Scrollable.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/05 Component Displays Only a Part of the Content.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/10 The Page is Scrollable, the Component is Not.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/15 Component Height is 100% But It Does Not Fit Into the Page.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/20 Scrolling Methods Do Not Work.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/25 Scrollbar is Displayed but Component is Overlapped.md
  images/Troubleshooting/scrolling-grid-in-popup-native-scrolling.gif
  images/Troubleshooting/scrolling-grid-in-popup-no-scrollbar.png
  images/Troubleshooting/scrolling-whole-page.gif
Labels: 23_1

#5458 Troubleshooting: Component Content is not Scrollable (#5442)
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/00 Component Content is not Scrollable.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/05 Component Displays Only a Part of the Content.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/10 The Page is Scrollable, the Component is Not.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/15 Component Height is 100% But It Does Not Fit Into the Page.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/20 Scrolling Methods Do Not Work.md
  concepts/80 Troubleshooting/45 Component Content is not Scrollable/25 Scrollbar is Displayed but Component is Overlapped.md
  images/Troubleshooting/scrolling-grid-in-popup-native-scrolling.gif
  images/Troubleshooting/scrolling-grid-in-popup-no-scrollbar.png
  images/Troubleshooting/scrolling-whole-page.gif
Labels: cherry-pick, 23_2

#5459 RangeSelector: add example to min/maxRange
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/maxRange/maxRange.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/minRange/minRange.md
Labels: 23_1

#5460 RangeSelector: add example to min/maxRange (#5459)
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/maxRange/maxRange.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/minRange/minRange.md
Labels: cherry-pick, 22_2

#5461 RangeSelector: add example to min/maxRange (#5459)
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/maxRange/maxRange.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/minRange/minRange.md
Labels: cherry-pick, 23_2

#5462 Button: Change Icon Position
  concepts/05 UI Components/Button/13 Change Icon Position.md
Labels: 23_1

#5467 Button: Change Icon Position (#5462)
  concepts/05 UI Components/Button/13 Change Icon Position.md
Labels: cherry-pick, 22_2

#5468 Button: Change Icon Position (#5462)
  concepts/05 UI Components/Button/13 Change Icon Position.md
Labels: cherry-pick, 23_2

#5472 jQuery: limit code snippets
  api-reference/10 UI Components/CollectionWidget/1 Configuration/onItemDeleting.md
  api-reference/10 UI Components/GridBase/3 Methods/byKey(key).md
  api-reference/30 Data Layer/DataSource/1 Configuration/requireTotalCount.md
  api-reference/30 Data Layer/DataSource/3 Methods/cancel(operationId).md
  api-reference/30 Data Layer/zz Errors and Warnings/E4021.md
  api-reference/30 Data Layer/zz Errors and Warnings/E4022.md
  concepts/70 Data Binding/5 Data Layer/55 Handling Errors.md
Labels: 23_1

#5473 jQuery: limit code snippets (#5472)
  api-reference/10 UI Components/CollectionWidget/1 Configuration/onItemDeleting.md
  api-reference/10 UI Components/GridBase/3 Methods/byKey(key).md
  api-reference/30 Data Layer/DataSource/1 Configuration/requireTotalCount.md
  api-reference/30 Data Layer/DataSource/3 Methods/cancel(operationId).md
  api-reference/30 Data Layer/zz Errors and Warnings/E4021.md
  api-reference/30 Data Layer/zz Errors and Warnings/E4022.md
  concepts/70 Data Binding/5 Data Layer/55 Handling Errors.md
Labels: cherry-pick, 22_2

#5474 jQuery: limit code snippets (#5472)
  api-reference/10 UI Components/CollectionWidget/1 Configuration/onItemDeleting.md
  api-reference/10 UI Components/GridBase/3 Methods/byKey(key).md
  api-reference/30 Data Layer/DataSource/1 Configuration/requireTotalCount.md
  api-reference/30 Data Layer/DataSource/3 Methods/cancel(operationId).md
  api-reference/30 Data Layer/zz Errors and Warnings/E4021.md
  api-reference/30 Data Layer/zz Errors and Warnings/E4022.md
  concepts/70 Data Binding/5 Data Layer/55 Handling Errors.md
Labels: cherry-pick, 23_2

#5475 CustomStore: update `loadOptions.group`
  api-reference/30 Data Layer/CustomStore/LoadOptions/group.md
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/5 Server-Side Data Processing.md
Labels: 23_1

#5476 CustomStore: update `loadOptions.group` (#5475)
  api-reference/30 Data Layer/CustomStore/LoadOptions/group.md
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/5 Server-Side Data Processing.md
Labels: cherry-pick, 22_2

#5477 CustomStore: update `loadOptions.group` (#5475)
  api-reference/30 Data Layer/CustomStore/LoadOptions/group.md
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/5 Server-Side Data Processing.md
Labels: cherry-pick, 23_2

#5481 Form: update Submit the Form topic
  concepts/05 UI Components/Form/01 Getting Started with Form/80 Submit the Form.md
Labels: 23_1

#5483 Form: update Submit the Form topic (#5481)
  concepts/05 UI Components/Form/01 Getting Started with Form/80 Submit the Form.md
Labels: cherry-pick, 22_2

#5484 Form: update Submit the Form topic (#5481)
  concepts/05 UI Components/Form/01 Getting Started with Form/80 Submit the Form.md
Labels: cherry-pick, 23_2

#5485 Grids: update `syncLookupFilterValues`
  api-reference/10 UI Components/GridBase/1 Configuration/syncLookupFilterValues.md
Labels: 23_1

#5490 Grids: update `syncLookupFilterValues` (#5485)
  api-reference/10 UI Components/GridBase/1 Configuration/syncLookupFilterValues.md
Labels: cherry-pick, 22_2

#5496 Drop-down editors: update `valueExpr`
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: 23_1

#5497 Drop-down editors: update `valueExpr` (#5496)
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: cherry-pick, 22_2

#5498 Drop-down editors: update `valueExpr` (#5496)
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: cherry-pick, 23_2

#5501 Change emails to Support Center link
  includes/common-ctp-note-wo-devextreme.md
  includes/common-ctp-note.md
Labels: 23_1

#5502 Change emails to Support Center link (#5501)
  includes/common-ctp-note-wo-devextreme.md
  includes/common-ctp-note.md
Labels: cherry-pick, 22_2

#5504 HtmlEditor: add info about CSP
  concepts/05 UI Components/HtmlEditor/05 Overview.md
Labels: 23_1

#5505 HtmlEditor: add info about CSP (#5504)
  concepts/05 UI Components/HtmlEditor/05 Overview.md
Labels: cherry-pick, 23_2

#5507 Grids: add 'none' to sorting.mode
  api-reference/10 UI Components/GridBase/1 Configuration/sorting/mode.md
Labels: 23_1

#5508 Grids: add 'none' to sorting.mode (#5507)
  api-reference/10 UI Components/GridBase/1 Configuration/sorting/mode.md
Labels: cherry-pick, 22_2

#5509 Grids: add 'none' to sorting.mode (#5507)
  api-reference/10 UI Components/GridBase/1 Configuration/sorting/mode.md
Labels: cherry-pick, 23_2

#5492 Calendar: describe selection properties
  api-reference/10 UI Components/DateBoxBase/1 Configuration/calendarOptions.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/disabledDates.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/selectWeekOnClick.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/selectionMode.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/value.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/values.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/calendarOptions.md
Labels: 23_2

#5512 Map: update onReady description
  api-reference/10 UI Components/dxMap/1 Configuration/onReady.md
Labels: 23_1

#5513 Map: update onReady description (#5512)
  api-reference/10 UI Components/dxMap/1 Configuration/onReady.md
Labels: cherry-pick, 23_2

#5514 Form: update item.label.template
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/template.md
Labels: 23_1

#5515 Form: update item.label.template (#5514)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/template.md
Labels: cherry-pick, 22_2

#5516 Form: update item.label.template (#5514)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/label/template.md
Labels: cherry-pick, 23_2

#5517 Chart: update `exportFromMarkup`
  api-reference/50 Common/utils/viz/exportFromMarkup(markup_options).md
Labels: 23_1

#5518 Chart: update `exportFromMarkup` (#5517)
  api-reference/50 Common/utils/viz/exportFromMarkup(markup_options).md
Labels: cherry-pick, 22_2

#5519 Chart: update `exportFromMarkup` (#5517)
  api-reference/50 Common/utils/viz/exportFromMarkup(markup_options).md
Labels: cherry-pick, 23_2

#5522 Chart: update discreteAxisDivisionMode
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/discreteAxisDivisionMode.md
  images/ChartJS/discreteAxisDivisionMode/between.png
  images/ChartJS/discreteAxisDivisionMode/cross.png
Labels: 23_1

#5524 Chart: update discreteAxisDivisionMode (#5522)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/discreteAxisDivisionMode.md
  images/ChartJS/discreteAxisDivisionMode/between.png
  images/ChartJS/discreteAxisDivisionMode/cross.png
Labels: cherry-pick, 22_2

#5526 Chart: update discreteAxisDivisionMode (#5522)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/discreteAxisDivisionMode.md
  images/ChartJS/discreteAxisDivisionMode/between.png
  images/ChartJS/discreteAxisDivisionMode/cross.png
Labels: cherry-pick, 23_2

#5527 Drawer: fix bug in code
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: 23_1

#5528 Drawer: fix bug in code (#5527)
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: cherry-pick, 22_2

#5529 Drawer: fix bug in code (#5527)
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/00 Create the Drawer.md
Labels: cherry-pick, 23_2

#5533 Revert "Revert "CDN: rename devextreme to devextreme-dist""
  concepts/Common/Distribution Channels/05 CDN/05 CDN.md
Labels: 23_1

#5534 Recover closing } after (#5518)
  api-reference/50 Common/utils/viz/exportFromMarkup(markup_options).md
Labels: 22_2

#5535 valuExpr: fix link
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: 23_1

#5536 valuExpr: fix link (#5535)
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
Labels: cherry-pick, 23_2

#5537 Grids: update `searchPanel.width`
  api-reference/10 UI Components/GridBase/1 Configuration/searchPanel/width.md
Labels: 23_1

#5538 Grids: update `searchPanel.width` (#5537)
  api-reference/10 UI Components/GridBase/1 Configuration/searchPanel/width.md
Labels: cherry-pick, 22_2

#5539 Grids: update `searchPanel.width` (#5537)
  api-reference/10 UI Components/GridBase/1 Configuration/searchPanel/width.md
Labels: cherry-pick, 23_2

#5541 Calendar: describe `CalendarSelectionMode`
  api-reference/10 UI Components/dxCalendar/9 Types/CalendarSelectionMode.md
Labels: 23_2

#5525 React: TypeScript support section update
  concepts/50 React Components/70 TypeScript Support/00 TypeScript Support.md
  concepts/50 React Components/70 TypeScript Support/05 Component-Specific Types.md
  concepts/50 React Components/70 TypeScript Support/10 Generics Usage.md
Labels: 23_2

#5540 Vue: update TypeScript Support topic
  concepts/50 React Components/70 TypeScript Support/10 Generics Usage.md
  concepts/55 Vue Components/70 TypeScript Support/00 TypeScript Support.md
  concepts/55 Vue Components/70 TypeScript Support/05 Component Specific Types.md
  concepts/55 Vue Components/70 TypeScript Support/10 Generics Usage.md
Labels: 23_2

#5546 Vue: remove additional configuration for Vite
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/70 Additional Configuration for Vite/00 Additional Configuration for Vite.md
Labels: 23_2
