Repository DevExpress/devextreme-documentation, pull requests merged in 2023-04, with the labels that each got.

#4820 Chart: remove aggregateByCategory mentions
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/aggregationGroupWidth.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/aggregation/aggregation.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/aggregation/method.md
  concepts/05 UI Components/Chart/88 Data Aggregation/05 Specify the Aggregation Interval.md
Labels: 23_1

#4824 DataGrid: add a note to 'height'/'width' descriptions
  api-reference/10 UI Components/dxDataGrid/1 Configuration/height.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/width.md
Labels: 22_2

#4825 DataGrid: add a note to 'height'/'width' descriptions (#4824)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/height.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/width.md
Labels: cherry-pick, 22_1

#4826 DataGrid: add a note to 'height'/'width' descriptions (#4824)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/height.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/width.md
Labels: cherry-pick, 23_1

#4812 Charts: describe 'shift' method
  api-reference/10 UI Components/BaseChart/7 Chart Elements/Label/3 Methods/shift(x_y).md
Labels: 23_1

#4832 CLI: quick code fix
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
Labels: 22_2

#4833 CLI: quick code fix (#4832)
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
Labels: cherry-pick, 22_1

#4834 CLI: quick code fix (#4832)
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
Labels: cherry-pick, 23_1

#4830 DataGrid: update Popup mode advanced customization
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/50 Popup Mode.md
Labels: 22_2

#4835 DataGrid: update Popup mode advanced customization (#4830)
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/50 Popup Mode.md
Labels: cherry-pick, 22_1

#4836 DataGrid: update Popup mode advanced customization (#4830)
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/50 Popup Mode.md
Labels: cherry-pick, 23_1

#4802 Scheduler: add code snippet related to appointmentTooltipTemplate
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentTooltipTemplate.md
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
Labels: 22_2

#4838 Scheduler: add code snippet related to appointmentTooltipTemplate
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentTooltipTemplate.md
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
Labels: cherry-pick, 23_1

#4842 Vue: update One-Way and Two-Way Property Binding (Composition API)
  concepts/55 Vue Components/20 Component Configuration Syntax/32 One-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/33 Two-Way Property Binding.md
Labels: 22_2

#4843 Vue: update One-Way and Two-Way Property Binding (Composition API)
  concepts/55 Vue Components/20 Component Configuration Syntax/32 One-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/33 Two-Way Property Binding.md
Labels: cherry-pick, 22_1

#4844 Vue: update One-Way and Two-Way Property Binding (Composition API)
  concepts/55 Vue Components/20 Component Configuration Syntax/32 One-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/33 Two-Way Property Binding.md
Labels: cherry-pick, 23_1

#4845 ODataStore: add note about Web API Service
  api-reference/30 Data Layer/ODataContext/ODataContext.md
  api-reference/30 Data Layer/ODataStore/ODataStore.md
  concepts/05 UI Components/Funnel/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Lookup/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PieChart/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Provide Data/20 Using the Client-Side Processing/30 Using an ODataStore.md
  concepts/05 UI Components/Sankey/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/TagBox/02 Data Binding/15 OData Service.md
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
  concepts/70 Data Binding/51 Data Source Examples/2 OData/5 Invoking Service Operations.md
Labels: 22_2

#4846 ODataStore: add note about Web API Service (#4845)
  api-reference/30 Data Layer/ODataContext/ODataContext.md
  api-reference/30 Data Layer/ODataStore/ODataStore.md
  concepts/05 UI Components/Funnel/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Lookup/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PieChart/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Provide Data/20 Using the Client-Side Processing/30 Using an ODataStore.md
  concepts/05 UI Components/Sankey/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/TagBox/02 Data Binding/15 OData Service.md
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
  concepts/70 Data Binding/51 Data Source Examples/2 OData/5 Invoking Service Operations.md
Labels: cherry-pick, 22_1

#4847 ODataStore: add note about Web API Service (#4845)
  api-reference/30 Data Layer/ODataContext/ODataContext.md
  api-reference/30 Data Layer/ODataStore/ODataStore.md
  concepts/05 UI Components/Funnel/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Lookup/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PieChart/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Provide Data/20 Using the Client-Side Processing/30 Using an ODataStore.md
  concepts/05 UI Components/Sankey/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/TagBox/02 Data Binding/15 OData Service.md
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
  concepts/70 Data Binding/51 Data Source Examples/2 OData/5 Invoking Service Operations.md
Labels: cherry-pick, 23_1

#4853 End-to-End Testing: update code snippet (T1158370)
  concepts/50 React Components/60 Components Testing/30 End-to-End Testing.md
Labels: 22_2

#4854 End-to-End Testing: update code snippet (T1158370) (#4853)
  concepts/50 React Components/60 Components Testing/30 End-to-End Testing.md
Labels: cherry-pick, 22_1

#4855 End-to-End Testing: update code snippet (T1158370) (#4853)
  concepts/50 React Components/60 Components Testing/30 End-to-End Testing.md
Labels: cherry-pick, 23_1

#4856 Localization: update info about currency and dates formatting (T1026482)
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/05 Using Intl.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: 22_2

#4862 Localization: update info about currency and dates formatting (T1026482)
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/05 Using Intl.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: cherry-pick, 22_1

#4863 Localization: update info about currency and dates formatting (T10264…
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/05 Using Intl.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: cherry-pick, 23_1

#4864 Move "See Also" sections
  concepts/05 UI Components/Chart/95 Zooming and Panning/15 Set the Initial Zoom.md
  concepts/05 UI Components/ContextMenu/10 Open and Close the Context Menu/10 API.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
Labels: 22_2

#4878 Add empty shortDescription
  api-reference/10 UI Components/dxBarGauge/9 Types/dxBarGaugeLegend/visible.md
  api-reference/10 UI Components/dxChart/9 Types/dxChartArgumentAxis/endOnTick.md
  api-reference/10 UI Components/dxChart/9 Types/dxChartTooltip/dxChartTooltip.md
  api-reference/10 UI Components/dxChart/9 Types/dxChartValueAxis/endOnTick.md
  api-reference/10 UI Components/dxDataGrid/9 Types/Editing/texts.md
  api-reference/10 UI Components/dxFunnel/9 Types/dxFunnelLegend/visible.md
  api-reference/10 UI Components/dxFunnel/9 Types/dxFunnelTooltip/dxFunnelTooltip.md
  api-reference/10 UI Components/dxLinearGauge/9 Types/dxLinearGaugeScale/scaleDivisionFactor.md
  api-reference/10 UI Components/dxLoadPanel/9 Types/dxLoadPanelAnimation/hide.md
  api-reference/10 UI Components/dxLoadPanel/9 Types/dxLoadPanelAnimation/show.md
  api-reference/10 UI Components/dxPieChart/9 Types/dxPieChartAdaptiveLayout/keepLabels.md
  api-reference/10 UI Components/dxPieChart/9 Types/dxPieChartLegend/customizeItems.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartAdaptiveLayout/height.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartAdaptiveLayout/width.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxis/minorTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxis/tick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxisMinorTick/dxPolarChartArgumentAxisMinorTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxisTick/dxPolarChartArgumentAxisTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartTooltip/dxPolarChartTooltip.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartTooltip/shared.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxis/endOnTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxis/tick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxisTick/dxPolarChartValueAxisTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxisTick/visible.md
  api-reference/10 UI Components/dxPopup/9 Types/dxPopupAnimation/dxPopupAnimation.md
  api-reference/10 UI Components/dxPopup/9 Types/dxPopupAnimation/hide.md
  api-reference/10 UI Components/dxPopup/9 Types/dxPopupAnimation/show.md
  api-reference/10 UI Components/dxSankey/9 Types/dxSankeyTooltip/dxSankeyTooltip.md
  api-reference/10 UI Components/dxSankey/9 Types/dxSankeyTooltip/enabled.md
  api-reference/10 UI Components/dxSparkline/9 Types/BaseSparklineTooltip/enabled.md
  api-reference/10 UI Components/dxToast/9 Types/dxToastAnimation/dxToastAnimation.md
  api-reference/10 UI Components/dxTreeList/9 Types/Editing/texts.md
  api-reference/10 UI Components/dxTreeList/9 Types/EditingTexts/EditingTexts.md
  api-reference/10 UI Components/dxTreeList/9 Types/Paging/Paging.md
  api-reference/10 UI Components/dxTreeList/9 Types/Paging/enabled.md
  api-reference/10 UI Components/dxTreeMap/9 Types/dxTreeMapTooltip/dxTreeMapTooltip.md
  api-reference/10 UI Components/dxVectorMap/9 Types/dxVectorMapLegends/markerSize.md
  api-reference/10 UI Components/dxVectorMap/9 Types/dxVectorMapTooltip/format.md
Labels: 23_1

#4879 Fix empty shortDescription
  api-reference/10 UI Components/dxBarGauge/9 Types/dxBarGaugeLegend/visible.md
  api-reference/10 UI Components/dxChart/9 Types/dxChartArgumentAxis/endOnTick.md
  api-reference/10 UI Components/dxChart/9 Types/dxChartTooltip/dxChartTooltip.md
  api-reference/10 UI Components/dxChart/9 Types/dxChartValueAxis/endOnTick.md
  api-reference/10 UI Components/dxDataGrid/9 Types/Editing/texts.md
  api-reference/10 UI Components/dxFunnel/9 Types/dxFunnelLegend/visible.md
  api-reference/10 UI Components/dxFunnel/9 Types/dxFunnelTooltip/dxFunnelTooltip.md
  api-reference/10 UI Components/dxLinearGauge/9 Types/dxLinearGaugeScale/scaleDivisionFactor.md
  api-reference/10 UI Components/dxLoadPanel/9 Types/dxLoadPanelAnimation/hide.md
  api-reference/10 UI Components/dxLoadPanel/9 Types/dxLoadPanelAnimation/show.md
  api-reference/10 UI Components/dxPieChart/9 Types/dxPieChartAdaptiveLayout/keepLabels.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartAdaptiveLayout/height.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartAdaptiveLayout/width.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxis/minorTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxis/tick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxisMinorTick/dxPolarChartArgumentAxisMinorTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxisTick/dxPolarChartArgumentAxisTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartTooltip/dxPolarChartTooltip.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartTooltip/shared.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxis/endOnTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxis/tick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxisTick/dxPolarChartValueAxisTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxisTick/visible.md
  api-reference/10 UI Components/dxPopup/9 Types/dxPopupAnimation/hide.md
  api-reference/10 UI Components/dxPopup/9 Types/dxPopupAnimation/show.md
  api-reference/10 UI Components/dxSankey/9 Types/dxSankeyTooltip/dxSankeyTooltip.md
  api-reference/10 UI Components/dxSankey/9 Types/dxSankeyTooltip/enabled.md
  api-reference/10 UI Components/dxSparkline/9 Types/BaseSparklineTooltip/enabled.md
  api-reference/10 UI Components/dxTreeList/9 Types/Editing/texts.md
  api-reference/10 UI Components/dxTreeList/9 Types/EditingTexts/EditingTexts.md
  api-reference/10 UI Components/dxTreeList/9 Types/Paging/Paging.md
  api-reference/10 UI Components/dxTreeList/9 Types/Paging/enabled.md
  api-reference/10 UI Components/dxTreeMap/9 Types/dxTreeMapTooltip/dxTreeMapTooltip.md
  api-reference/10 UI Components/dxVectorMap/9 Types/dxVectorMapLegends/markerSize.md
  api-reference/10 UI Components/dxVectorMap/9 Types/dxVectorMapTooltip/format.md
Labels: 23_1

#4881 Charts: Fix a note in the minorTickInterval option description T948281
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/minorTickInterval/minorTickInterval.md
Labels: 22_2

#4882 Charts: Fix a note in the minorTickInterval option description T94828…
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/minorTickInterval/minorTickInterval.md
Labels: cherry-pick, 22_1

#4883 Charts: Fix a note in the minorTickInterval option description T94828…
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/minorTickInterval/minorTickInterval.md
Labels: cherry-pick, 23_1

#4886 CI: truncate PR description
  .github/workflows/docgen.yml
Labels: 23_1

#4889 CustomStore: add a note
  api-reference/30 Data Layer/CustomStore/1 Configuration/loadMode.md
  api-reference/30 Data Layer/CustomStore/CustomStore.md
Labels: 22_2

#4890 CustomStore: add a note (#4889)
  api-reference/30 Data Layer/CustomStore/1 Configuration/loadMode.md
  api-reference/30 Data Layer/CustomStore/CustomStore.md
Labels: cherry-pick, 22_1

#4891 CustomStore: add a note (#4889)
  api-reference/30 Data Layer/CustomStore/1 Configuration/loadMode.md
  api-reference/30 Data Layer/CustomStore/CustomStore.md
Labels: cherry-pick, 23_1

#4893 Form: add note to itemOption
  includes/form-item-options.md
Labels: 22_2

#4894 Form: add note to itemOption (#4893)
  includes/form-item-options.md
Labels: cherry-pick, 22_1

#4895 Form: add note to itemOption (#4893)
  includes/form-item-options.md
Labels: cherry-pick, 23_1

#4898 DataGrid: update calculateFilterExpression code snippet (T1158674)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: 22_2

#4899 DataGrid: update calculateFilterExpression code snippet (T1158674)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: cherry-pick, 22_1

#4900 DataGrid: update calculateFilterExpression code snippet (T1158674)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: cherry-pick, 23_1

#4901 Bullet/Spakline: update size and render
  api-reference/10 UI Components/BaseSparkline/1 Configuration/size/size.md
  api-reference/10 UI Components/BaseSparkline/3 Methods/render().md
  api-reference/10 UI Components/dxBullet/1 Configuration/size/size.md
Labels: 22_2

#4902 Bullet/Spakline: update size and render (#4901)
  api-reference/10 UI Components/BaseSparkline/1 Configuration/size/size.md
  api-reference/10 UI Components/BaseSparkline/3 Methods/render().md
  api-reference/10 UI Components/dxBullet/1 Configuration/size/size.md
Labels: cherry-pick, 22_1

#4903 Bullet/Spakline: update size and render (#4901)
  api-reference/10 UI Components/BaseSparkline/1 Configuration/size/size.md
  api-reference/10 UI Components/BaseSparkline/3 Methods/render().md
  api-reference/10 UI Components/dxBullet/1 Configuration/size/size.md
Labels: cherry-pick, 23_1

#4904 Drawer: update revealMode description
  api-reference/10 UI Components/dxDrawer/1 Configuration/revealMode.md
Labels: 22_2

#4905 Drawer: update revealMode description (#4904)
  api-reference/10 UI Components/dxDrawer/1 Configuration/revealMode.md
Labels: cherry-pick, 22_1

#4913 PivotGrid: update incorrect link (T1069312)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
Labels: 22_2

#4914 PivotGrid: update incorrect link (T1069312) (#4913)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
Labels: cherry-pick, 22_1

#4915 PivotGrid: update incorrect link (T1069312)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
Labels: cherry-pick, 23_1

#4911 List: update Selection guide
  api-reference/10 UI Components/dxList/1 Configuration/selectByClick.md
  concepts/05 UI Components/List/25 Selection/01 User Interaction.md
  concepts/05 UI Components/List/25 Selection/05 API.md
Labels: 23_1

#4919 Scheduler: add the maxAppointmentsPerCell property description (T1131…
  api-reference/10 UI Components/dxScheduler/1 Configuration/maxAppointmentsPerCell.md
Labels: cherry-pick, 22_1

#4920 Scheduler: add the maxAppointmentsPerCell property description (T1131267)
  api-reference/10 UI Components/dxScheduler/1 Configuration/maxAppointmentsPerCell.md
Labels: cherry-pick, 23_1

#4921 DataSource: update reload description (#4916)
  api-reference/30 Data Layer/DataSource/3 Methods/reload().md
Labels: cherry-pick, 22_1

#4922 DataSource: update reload description (#4916)
  api-reference/30 Data Layer/DataSource/3 Methods/reload().md
Labels: cherry-pick, 23_1

#4923 CustomRule: update reevaluate description (#4912)
  api-reference/10 UI Components/dxValidator/8 Validation Rules/CustomRule/reevaluate.md
Labels: cherry-pick, 22_1

#4924 CustomRule: update reevaluate description (#4912)
  api-reference/10 UI Components/dxValidator/8 Validation Rules/CustomRule/reevaluate.md
Labels: cherry-pick, 23_1

#4925 Form: add a note in Validation guide (#4917)
  concepts/05 UI Components/Form/40 Validate and Submit the Form.md
Labels: cherry-pick, 22_1

#4918 VectorMap: update projection description
  api-reference/10 UI Components/dxVectorMap/1 Configuration/projection/projection.md
Labels: 22_2

#4926 VectorMap: update projection description (#4918)
  api-reference/10 UI Components/dxVectorMap/1 Configuration/projection/projection.md
Labels: cherry-pick, 22_1

#4927 VectorMap: update projection description (#4918)
  api-reference/10 UI Components/dxVectorMap/1 Configuration/projection/projection.md
Labels: cherry-pick, 23_1

#4928 TreeView: update highlighting in code snippets
  includes/treeview-custom-icons.md
Labels: 23_1

#4935 Box: update 'ratio' description (#4934)
  api-reference/_hidden/dxBoxItem/ratio.md
Labels: cherry-pick, 22_1

#4936 Box: update 'ratio' description (#4934)
  api-reference/_hidden/dxBoxItem/ratio.md
Labels: cherry-pick, 23_1

#4885 Add rename topics tools
  package.json
  tools/updateFolder.ts
Labels: 23_1

#4938 SelectBox: update 'value' description (#4937)
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/value.md
Labels: cherry-pick, 22_1

#4939 SelectBox: update 'value' description (#4937)
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/value.md
Labels: cherry-pick, 23_1

#4943 Diagram: change indents in getItems code (#4941)
  api-reference/10 UI Components/dxDiagram/3 Methods/getItems().md
Labels: cherry-pick, 23_1

#4944 Chart: add a note to 'templates'
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/template.md
  api-reference/_hidden/dxChartCommonAnnotationConfig/template.md
  api-reference/_hidden/dxPolarChartCommonAnnotationConfig/template.md
  includes/dataviz-template-note-svg.md
Labels: 22_2

#4945 Chart: add a note to 'templates' (#4944)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/template.md
  api-reference/_hidden/dxChartCommonAnnotationConfig/template.md
  api-reference/_hidden/dxPolarChartCommonAnnotationConfig/template.md
  includes/dataviz-template-note-svg.md
Labels: cherry-pick, 22_1

#4946 Chart: add a note to 'templates' (#4944)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/template.md
  api-reference/_hidden/dxChartCommonAnnotationConfig/template.md
  api-reference/_hidden/dxPolarChartCommonAnnotationConfig/template.md
  includes/dataviz-template-note-svg.md
Labels: cherry-pick, 23_1

#4940 Chart: update 'containerBackgroundColor' description
  api-reference/10 UI Components/dxChart/1 Configuration/containerBackgroundColor.md
Labels: 22_2

#4948 Chart: update 'containerBackgroundColor' description (#4940)
  api-reference/10 UI Components/dxChart/1 Configuration/containerBackgroundColor.md
Labels: cherry-pick, 23_1

#4871 Menu: describe 'url' and 'linkAttr'
  api-reference/_hidden/dxMenuItem/linkAttr.md
  api-reference/_hidden/dxMenuItem/url.md
Labels: 23_1

#4949 Update '3rd-Party Template Engines' article
  concepts/05 UI Components/zz Common/30 Templates/30 3rd-Party Template Engines.md
Labels: 23_1

#4954 HtmlEditor: add note to Getting Started tutorial
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
Labels: 22_2

#4957 HtmlEditor: add note to Getting Started tutorial (#4954)
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
Labels: cherry-pick, 22_1

#4958 HtmlEditor: add note to Getting Started tutorial (#4954)
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
Labels: cherry-pick, 23_1

#4962 OData Service: add a title to the note
  api-reference/30 Data Layer/ODataContext/ODataContext.md
  api-reference/30 Data Layer/ODataStore/ODataStore.md
  concepts/05 UI Components/Funnel/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Lookup/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PieChart/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Provide Data/20 Using the Client-Side Processing/30 Using an ODataStore.md
  concepts/05 UI Components/Sankey/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/TagBox/02 Data Binding/15 OData Service.md
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
  concepts/70 Data Binding/51 Data Source Examples/2 OData/5 Invoking Service Operations.md
Labels: 22_2

#4964 OData Service: add a title to the note (#4962)
  api-reference/30 Data Layer/ODataContext/ODataContext.md
  api-reference/30 Data Layer/ODataStore/ODataStore.md
  concepts/05 UI Components/Funnel/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Lookup/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PieChart/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Provide Data/20 Using the Client-Side Processing/30 Using an ODataStore.md
  concepts/05 UI Components/Sankey/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/TagBox/02 Data Binding/15 OData Service.md
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
  concepts/70 Data Binding/51 Data Source Examples/2 OData/5 Invoking Service Operations.md
Labels: cherry-pick, 23_1

#4963 OData Service: add a title to the note (#4962)
  api-reference/30 Data Layer/ODataContext/ODataContext.md
  api-reference/30 Data Layer/ODataStore/ODataStore.md
  concepts/05 UI Components/Funnel/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Lookup/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PieChart/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Provide Data/20 Using the Client-Side Processing/30 Using an ODataStore.md
  concepts/05 UI Components/Sankey/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/TagBox/02 Data Binding/15 OData Service.md
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
  concepts/70 Data Binding/51 Data Source Examples/2 OData/5 Invoking Service Operations.md
Labels: cherry-pick, 22_1

#4965 Editors: update inputAttr description
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxColorBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxTagBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxTextArea/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxTextBox/1 Configuration/inputAttr.md
  includes/texteditor-aria-label.md
Labels: 22_2

#4966 Editors: update inputAttr description (#4965)
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxColorBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxTagBox/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxTextArea/1 Configuration/inputAttr.md
  api-reference/10 UI Components/dxTextBox/1 Configuration/inputAttr.md
  includes/texteditor-aria-label.md
Labels: cherry-pick, 22_1
