Repository DevExpress/devextreme-documentation, pull requests merged in 2023-09, with the labels that each got.

#5551 Add new icons
  applications/Icons/script.js
Labels: 23_2

#5557 Add code snippet to `defaultOptions`
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: 23_1

#5558 Add code snippet to `defaultOptions` (#5557)
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: cherry-pick, 22_2

#5559 Add code snippet to `defaultOptions` (#5557)
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: cherry-pick, 23_2

#5547 Tabs/TabPanel: describe `tabsPosition` and `orientation`
  api-reference/10 UI Components/dxTabPanel/1 Configuration/tabsPosition.md
  api-reference/10 UI Components/dxTabs/1 Configuration/orientation.md
Labels: 23_2

#5560 Remove 'Synchronize Two DateBoxes' article
  concepts/05 UI Components/DateBox/16 Synchronize Two DateBoxes.md
Labels: 23_1

#5561 Remove 'Synchronize Two DateBoxes' article (#5560)
  concepts/05 UI Components/DateBox/16 Synchronize Two DateBoxes.md
Labels: cherry-pick, 23_2

#5565 Calendar: remove `values`
  api-reference/10 UI Components/DateBoxBase/1 Configuration/calendarOptions.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/disabledDates.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/selectionMode.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/value.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/values.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/calendarOptions.md
Labels: 23_2

#5570 React: update TypeScript support article
  concepts/50 React Components/70 TypeScript Support/00 TypeScript Support.md
  concepts/50 React Components/70 TypeScript Support/05 Component-Specific Types.md
Labels: 23_2

#5569 Grids: describe W1025
  api-reference/10 UI Components/Errors and Warnings/W1025.md
Labels: 23_1

#5572 Grids: describe W1025 (#5569)
  api-reference/10 UI Components/Errors and Warnings/W1025.md
Labels: cherry-pick, 23_2

#5563 Delete unnecessary files 23.1
  api-reference/10 UI Components/dxDateBox/3 Methods/close().md
  api-reference/10 UI Components/dxDateBox/3 Methods/open().md
  api-reference/50 Common/utils/setTemplateEngine(name).md
  api-reference/50 Common/utils/zz Errors and Warnings/E0020.md
  api-reference/_hidden/Enums/DateRangePickerType.md
  api-reference/_hidden/setTemplateEngine(name).md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/core/set_template_engine.md
Labels: 23_1

#5562 Delete unnecessary files 23.2
  api-reference/10 UI Components/dxDateBox/3 Methods/close().md
  api-reference/10 UI Components/dxDateBox/3 Methods/open().md
  api-reference/50 Common/utils/setTemplateEngine(name).md
  api-reference/50 Common/utils/zz Errors and Warnings/E0020.md
  api-reference/_hidden/Enums/DateRangePickerType.md
  api-reference/_hidden/Enums/IconPosition.md
  api-reference/_hidden/setTemplateEngine(name).md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/core/set_template_engine.md
Labels: 23_2

#5574 Vue: update Typescript Support topic
  concepts/55 Vue Components/70 TypeScript Support/05 Component Specific Types.md
Labels: 23_2

#5573 DataGrid: add Custom keyboard navigation topic
  concepts/05 UI Components/DataGrid/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/00 Custom Keyboard Navigation.md
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/05 Change the Default Focused Cell.md
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/10 Focus Cells Programatically.md
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/15 Override and Create Keys.md
Labels: 23_1

#5580 DataGrid: add Custom keyboard navigation topic (#5573)
  concepts/05 UI Components/DataGrid/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/00 Custom Keyboard Navigation.md
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/05 Change the Default Focused Cell.md
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/10 Focus Cells Programatically.md
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/15 Override and Create Keys.md
Labels: cherry-pick, 23_2

#5584 List: fix code error
  concepts/05 UI Components/List/40 Item Context Menu.md
Labels: 23_1

#5583 Drop-down editors: update value description
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/value.md
Labels: 23_1

#5585 List: fix code error
  concepts/05 UI Components/List/40 Item Context Menu.md
Labels: cherry-pick, 22_2

#5586 List: fix code error (#5584)
  concepts/05 UI Components/List/40 Item Context Menu.md
Labels: cherry-pick, 23_2

#5587 Drop-down editors: update value description (#5583)
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/value.md
Labels: cherry-pick, 22_2

#5588 Drop-down editors: update value description (#5583)
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/value.md
Labels: cherry-pick, 23_2

#5506 Add topics for ColumnButtonClickEvent Type/Members
  api-reference/10 UI Components/dxDataGrid/9 Types/ColumnButtonClickEvent/ColumnButtonClickEvent.md
  api-reference/10 UI Components/dxDataGrid/9 Types/ColumnButtonClickEvent/column.md
  api-reference/10 UI Components/dxDataGrid/9 Types/ColumnButtonClickEvent/row.md
  api-reference/_hidden/dxDataGridColumnButton/onClick.md
  metadata/syntax-data.json
Labels: 23_2

#5598 Add topics for ColumnButtonClickEvent Type/Members
  api-reference/10 UI Components/dxDataGrid/9 Types/ColumnButtonClickEvent/ColumnButtonClickEvent.md
  api-reference/10 UI Components/dxDataGrid/9 Types/ColumnButtonClickEvent/column.md
  api-reference/10 UI Components/dxDataGrid/9 Types/ColumnButtonClickEvent/row.md
  api-reference/_hidden/dxDataGridColumnButton/onClick.md
  metadata/syntax-data.json
Labels: cherry-pick, 23_1

#5564 Tabs/TabPanel: describe iconPosition and stylingMode
  api-reference/10 UI Components/dxTabPanel/1 Configuration/iconPosition.md
  api-reference/10 UI Components/dxTabPanel/1 Configuration/stylingMode.md
  api-reference/10 UI Components/dxTabs/1 Configuration/iconPosition.md
  api-reference/10 UI Components/dxTabs/1 Configuration/stylingMode.md
  api-reference/40 Common Types/TabsIconPosition.md
  api-reference/40 Common Types/TabsStyle.md
  images/UiWidgets/Tabs/primarytabs.png
  images/UiWidgets/Tabs/secondarytabs.png
Labels: 23_2

#5579 Form/Editors: describe `isDirty`, `clear` and `reset`
  api-reference/10 UI Components/Editor/1 Configuration/isDirty.md
  api-reference/10 UI Components/Editor/3 Methods/clear().md
  api-reference/10 UI Components/Editor/3 Methods/reset().md
  api-reference/10 UI Components/Editor/3 Methods/reset(value).md
  api-reference/10 UI Components/dxForm/1 Configuration/isDirty.md
  api-reference/10 UI Components/dxForm/3 Methods/clear().md
  api-reference/10 UI Components/dxForm/3 Methods/reset(editorsData).md
Labels: 23_2

#5602 DataSource: update Configuration topic
  api-reference/30 Data Layer/DataSource/1 Configuration/Configuration.md
Labels: 23_1

#5603 DataSource: update Configuration topic (#5602)
  api-reference/30 Data Layer/DataSource/1 Configuration/Configuration.md
Labels: cherry-pick, 22_2

#5604 DataSource: update Configuration topic (#5602)
  api-reference/30 Data Layer/DataSource/1 Configuration/Configuration.md
Labels: cherry-pick, 23_2

#5607 Add mentions of Customize Edit Form topic
  api-reference/10 UI Components/GridBase/1 Configuration/editing/form.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
Labels: 23_1

#5608 Add mentions of Customize Edit Form topic (#5607)
  api-reference/10 UI Components/GridBase/1 Configuration/editing/form.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
Labels: cherry-pick, 22_2

#5609 Add mentions of Customize Edit Form topic
  api-reference/10 UI Components/GridBase/1 Configuration/editing/form.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
Labels: cherry-pick, 23_2

#5615 Drop-down editors: update `grouped` description
  api-reference/10 UI Components/dxDropDownList/1 Configuration/grouped.md
  api-reference/10 UI Components/dxLookup/1 Configuration/grouped.md
Labels: 23_1

#5617 Drop-down editors: update `grouped` description (#5615)
  api-reference/10 UI Components/dxDropDownList/1 Configuration/grouped.md
  api-reference/10 UI Components/dxLookup/1 Configuration/grouped.md
Labels: cherry-pick, 22_2

#5618 Drop-down editors: update `grouped` description (#5615)
  api-reference/10 UI Components/dxDropDownList/1 Configuration/grouped.md
  api-reference/10 UI Components/dxLookup/1 Configuration/grouped.md
Labels: cherry-pick, 23_2
