Repository DevExpress/devextreme-documentation, pull requests merged in 2023-05, with the labels that each got.

#4978 CustomStore: fix link
  api-reference/30 Data Layer/CustomStore/CustomStore.md
Labels: 22_2

#4979 CustomStore: fix link (#4978)
  api-reference/30 Data Layer/CustomStore/CustomStore.md
Labels: cherry-pick, 22_1

#4980 CustomStore: fix link (#4978)
  api-reference/30 Data Layer/CustomStore/CustomStore.md
Labels: cherry-pick, 23_1

#4977 Chart: update sortingMethod description
  api-reference/10 UI Components/dxChart/1 Configuration/dataPrepareSettings/sortingMethod.md
Labels: 22_2

#4984 Chart: update sortingMethod description (#4977)
  api-reference/10 UI Components/dxChart/1 Configuration/dataPrepareSettings/sortingMethod.md
Labels: cherry-pick, 22_1

#4986 jQuery: change devextreme package
  api-reference/10 UI Components/dxVectorMap/1 Configuration/layers/palette.md
  concepts/60 Themes and Styles/20 SVG-Based Components Customization/10 Palettes/10 Apply a Palette.md
  concepts/60 Themes and Styles/20 SVG-Based Components Customization/10 Palettes/15 Override a Palette Color.md
  concepts/Common/Distribution Channels/01 npm.md
  concepts/Common/Migrate to the New Version/10 Upgrade DevExtreme Sources/7 npm Packages.md
Labels: 23_1

#4976 Content Security Policy: add a section related to CSP
  concepts/Common/Security Considerations/30 Export Vulnerabilities/20 ExcelJS CSP Threats.md
  concepts/Common/Security Considerations/40 Content Security Policy/00 Content Security Policy.md
  concepts/Common/Security Considerations/40 Content Security Policy/05 Common CSP Directives.md
  concepts/Common/Security Considerations/40 Content Security Policy/15 CSP Source List.md
Labels: 23_1

#4992 Bump "devextreme-internal-tools" to "10.0.0-beta.7"
  package.json
Labels: 23_1

#4995 DataGrid: update the cellTemplate property (T1163601)
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
Labels: 22_2

#4997 DataGrid: update the cellTemplate property (T1163601)
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
Labels: cherry-pick, 22_1

#4998 DataGrid: update the cellTemplate property (T1163601)
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
Labels: cherry-pick, 23_1

#4996 DataGrid/PivotGrid: add NOTE about ExcelJS potential vulnerabilities
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/excelExporter/exportPivotGrid(options).md
Labels: 23_1

#4888 Autocomplete: add Accessibility topic
  concepts/05 UI Components/Autocomplete/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/Autocomplete/15 Keyboard Support.md
Labels: 23_1

#5002 Chart Custom Styles: add info about supported series
  api-reference/10 UI Components/dxChart/1 Configuration/commonPaneSettings/backgroundColor.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/hoverStyle/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/point/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/point/hoverStyle/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/point/selectionStyle/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/selectionStyle/color.md
  includes/dataviz-chart-series-for-custom-styles.md
Labels: 23_1

#5004 DataGrid: add info about Column Chooser default position
  api-reference/10 UI Components/GridBase/1 Configuration/columnChooser/position.md
Labels: 23_1

#5006 Lookup: add Accessibility topic
  concepts/05 UI Components/Lookup/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Lookup/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Lookup/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Lookup/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Lookup/05 Accessibility/20 Screen Reader Support.md
  includes/common-code-register-key-handler.md
Labels: 23_1

#5007 ColumnHeaderFilter - Merge inherited types members ref 4896
  api-reference/_hidden/GridBaseColumn/headerFilter/search/search.md
Labels: 23_1

#5010 DataGrid: add note to the editCellTemplate property
  api-reference/_hidden/dxDataGridColumn/editCellTemplate.md
Labels: 22_2

#5011 DataGrid: update the calculateFilterExpression property
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: 22_2

#5013 DataGrid: update the calculateFilterExpression property (#5011)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: cherry-pick, 23_1

#5015 DataGrid: add note to the editCellTemplate property (#5010)
  api-reference/_hidden/dxDataGridColumn/editCellTemplate.md
Labels: cherry-pick, 23_1

#5014 DataGrid: add note to the editCellTemplate property (#5010)
  api-reference/_hidden/dxDataGridColumn/editCellTemplate.md
Labels: cherry-pick, 22_1

#5005 Docs for DataSource Types
  api-reference/30 Data Layer/DataSource/1 Configuration/langParams.md
  api-reference/40 Common Types/10 data/DataSource/DataSource.md
  api-reference/40 Common Types/10 data/DataSource/FilterDescriptor.md
  api-reference/40 Common Types/10 data/DataSource/GroupDescriptor.md
  api-reference/40 Common Types/10 data/DataSource/LangParams/LangParams.md
  api-reference/40 Common Types/10 data/DataSource/LangParams/collatorOptions.md
  api-reference/40 Common Types/10 data/DataSource/LangParams/locale.md
  api-reference/40 Common Types/10 data/DataSource/SelectDescriptor.md
  api-reference/40 Common Types/10 data/DataSource/SortDescriptor.md
  api-reference/40 Common Types/10 data/DataSource/SummaryDescriptor.md
Labels: 23_1

#5009 DataGrid: add a code snippet to the searchExpr property
  api-reference/_hidden/GridBaseColumn/headerFilter/search/searchExpr.md
  includes/column-header-filter-searchexpr-code.md
Labels: 23_1

#5016 Chart Custom Styles: add PieChart guide
  api-reference/50 Common/utils/viz/registerPattern(options).md
  concepts/05 UI Components/PieChart/10 Series/30 Customize Appearance.md
Labels: 23_1

#5022 Add "sun", "photooutline", "panelright", "panelleft", "moon", "login", "eyeopen", "eyeclose", "expandform", "description", "belloutline", "to" icons
  applications/Icons/script.js
Labels: 23_1

#5023 Drop-down editors: add Accessibility topics
  concepts/05 UI Components/DropDownBox/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/DropDownBox/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/DropDownBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DropDownBox/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/DropDownBox/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/DropDownBox/26 Keyboard Support.md
  concepts/05 UI Components/Lookup/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/SelectBox/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/SelectBox/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/SelectBox/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/SelectBox/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/SelectBox/03 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/SelectBox/25 Keyboard Support.md
  concepts/05 UI Components/TagBox/01 Accessibility/00 Accessibility.md
  concepts/05 UI Components/TagBox/01 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/TagBox/01 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TagBox/01 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/TagBox/01 Accessibility/20 Screen Reader Support.md
Labels: 23_1

#5021 DataSource: describe langParams
  api-reference/30 Data Layer/DataSource/1 Configuration/langParams.md
  api-reference/40 Common Types/10 data/DataSource/DataSource.md
  api-reference/40 Common Types/10 data/DataSource/LangParams/collatorOptions.md
  api-reference/40 Common Types/10 data/DataSource/LangParams/locale.md
  api-reference/40 Common Types/10 data/index/FilterDescriptor.md
  api-reference/40 Common Types/10 data/index/GroupDescriptor.md
  api-reference/40 Common Types/10 data/index/LangParams/LangParams.md
  api-reference/40 Common Types/10 data/index/LangParams/collatorOptions.md
  api-reference/40 Common Types/10 data/index/LangParams/locale.md
  api-reference/40 Common Types/10 data/index/SelectDescriptor.md
  api-reference/40 Common Types/10 data/index/SortDescriptor.md
  api-reference/40 Common Types/10 data/index/SummaryDescriptor.md
Labels: 23_1

#5029 TreeList: update the scrolling.mode property (T1166221)
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/mode.md
Labels: 22_2

#5030 TreeList: update the scrolling.mode property (#5029)
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/mode.md
Labels: cherry-pick, 22_1

#5031 TreeList: update the scrolling.mode property (#5029)
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/mode.md
Labels: cherry-pick, 23_1

#5033 PieChart/Gauges: update centerTemplate fieds description
  api-reference/10 UI Components/dxBarGauge/1 Configuration/centerTemplate.md
  api-reference/10 UI Components/dxCircularGauge/1 Configuration/centerTemplate.md
  api-reference/10 UI Components/dxPieChart/1 Configuration/centerTemplate.md
Labels: 23_1

#5034 DataGrid: update pager.visible property help topic (T1165507)
  api-reference/10 UI Components/GridBase/1 Configuration/pager/visible.md
Labels: 22_2

#5036 DataGrid: update pager.visible property help topic (T1165507) (#5034)
  api-reference/10 UI Components/GridBase/1 Configuration/pager/visible.md
Labels: cherry-pick, 23_1

#5024 DataGrid/TreeList: add Accessibility topic
  api-reference/10 UI Components/dxDataGrid/1 Configuration/selection/showCheckBoxesMode.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/DataGrid/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/DataGrid/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DataGrid/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/DataGrid/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/DataGrid/50 Selection/10 User Interaction.md
  concepts/05 UI Components/Lookup/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/TreeList/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/TreeList/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TreeList/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/TreeList/05 Accessibility/20 Screen Reader Support.md
Labels: 23_1

#5040 Accordion, Tabs, Popup: add Accessibility topics
  concepts/05 UI Components/Accordion/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Accordion/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Accordion/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Accordion/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Accordion/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/DropDownBox/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Popup/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Popup/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Popup/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Popup/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Popup/03 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/SelectBox/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Tabs/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Tabs/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Tabs/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Tabs/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Tabs/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/TagBox/01 Accessibility/15 Keyboard Navigation.md
Labels: 23_1

#5047 Chart: deprecate 'shift' mode for visualRangeUpdateMode
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/visualRangeUpdateMode.md
Labels: 23_1

#5048 React: add a command for TS template
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
Labels: 22_2

#5050 React: add a command for TS template (#5048)
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
Labels: cherry-pick, 23_1

#5054 PivotGridDataSource: add calculateSummaryValue extended description (T1125306)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/calculateSummaryValue.md
Labels: 22_2

#5053 Themes: update info about 'data-theme'
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: 23_1

#5051 FileSystemItem: update path/pathKeys description
  api-reference/50 Common/Object Structures/FileSystemItem/2 Fields/path.md
  api-reference/50 Common/Object Structures/FileSystemItem/2 Fields/pathKeys.md
Labels: 22_2

#5055 Themes: update info about 'data-theme' (#5053)
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: cherry-pick, 22_2

#5056 Themes: update info about 'data-theme' (#5053)
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: cherry-pick, 22_1

#5057 FileSystemItem: update path/pathKeys description (#5051)
  api-reference/50 Common/Object Structures/FileSystemItem/2 Fields/path.md
  api-reference/50 Common/Object Structures/FileSystemItem/2 Fields/pathKeys.md
Labels: cherry-pick, 23_1

#5058 PivotGridDataSource: add calculateSummaryValue extended description (…
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/calculateSummaryValue.md
Labels: cherry-pick, 22_1

#5059 FileSystemItem: update path/pathKeys description (#5051)
  api-reference/50 Common/Object Structures/FileSystemItem/2 Fields/path.md
  api-reference/50 Common/Object Structures/FileSystemItem/2 Fields/pathKeys.md
Labels: cherry-pick, 22_1

#5060 PivotGridDataSource: add calculateSummaryValue extended description (…
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/calculateSummaryValue.md
Labels: cherry-pick, 23_1

#5061 DataSource: update collatorOptions link
  api-reference/40 Common Types/10 data/index/LangParams/collatorOptions.md
Labels: 23_1

#5041 DateRangeBox: Add Getting Started with DateRangeBox guide
  applications/GettingStartedWith/DateRangeBox/index.css
  applications/GettingStartedWith/DateRangeBox/index.html
  applications/GettingStartedWith/DateRangeBox/index.js
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/00 Getting Started with DateRangeBox.md
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/05 Create the DateRangeBox.md
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/10 Set the Accepted Date Range.md
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/15 Set the Initial Date Range Values.md
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/20 Add  Labels.md
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/25 Handle the Value Change Event.md
  concepts/05 UI Components/DateRangeBox/05 Control the Behavior.md
  concepts/05 UI Components/DateRangeBox/10 Value Formatting and Masked Input.md
Labels: 23_1

#5063 DateRangeBox: update version for live example
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/00 Getting Started with DateRangeBox.md
Labels: 23_1

#5062 Vue/React: update TS Support topics
  concepts/50 React Components/70 TypeScript Support.md
  concepts/55 Vue Components/70 TypeScript Support.md
Labels: 23_1

#5064 Themes: add info about `dx-theme-marker`
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: 23_1

#5069 Themes: add info about `dx-theme-marker` (#5064)
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: cherry-pick, 22_2

#5070 Themes: add info about `dx-theme-marker` (#5064)
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: cherry-pick, 22_1

#5072 DataGrid: add button template code snippet (T1140896)
  api-reference/_hidden/dxDataGridColumnButton/template.md
Labels: 22_2

#5073 DataGrid: add button template code snippet (T1140896)
  api-reference/_hidden/dxDataGridColumnButton/template.md
Labels: cherry-pick, 22_1

#5074 DataGrid: add button template code snippet (T1140896) (#5072)
  api-reference/_hidden/dxDataGridColumnButton/template.md
Labels: cherry-pick, 23_1

#5082 Angular CLI: update information about version
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/Add DevExtreme to an Angular CLI Application.md
Labels: 22_2

#5083 Angular CLI: update information about version (#5082)
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/Add DevExtreme to an Angular CLI Application.md
Labels: cherry-pick, 22_1

#5084 Angular CLI: update information about version (#5082)
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/Add DevExtreme to an Angular CLI Application.md
Labels: cherry-pick, 23_1

#5071 Themes: update Application Template articles
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/55 Vue Components/50 Application Template/40 Configure Themes/10 Switch the Theme.md
Labels: 22_2

#5075 Themebuilder docIssues fix
  concepts/60 Themes and Styles/08 ThemeBuilder/01 Get Started/7 Import an Existing Theme.md
  concepts/60 Themes and Styles/08 ThemeBuilder/10 Customize the Theme.md
  concepts/60 Themes and Styles/08 ThemeBuilder/40 Export the Resulting Theme.md
  concepts/60 Themes and Styles/10 HTML-Based Components Customization/40 Individual CSS Classes.md
Labels: 22_2

#5086 Themes: update Application Template articles (#5071)
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/55 Vue Components/50 Application Template/40 Configure Themes/10 Switch the Theme.md
Labels: cherry-pick, 22_1

#5087 Themes: update Application Template articles (#5071)
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/55 Vue Components/50 Application Template/40 Configure Themes/10 Switch the Theme.md
Labels: cherry-pick, 23_1

#5076 DataGrid: add note about using string dates (T871898)
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/value.md
  api-reference/_hidden/GridBaseColumn/filterValue.md
Labels: 22_2

#5088 Themebuilder docIssues fix (#5075)
  concepts/60 Themes and Styles/08 ThemeBuilder/01 Get Started/7 Import an Existing Theme.md
  concepts/60 Themes and Styles/08 ThemeBuilder/10 Customize the Theme.md
  concepts/60 Themes and Styles/08 ThemeBuilder/40 Export the Resulting Theme.md
  concepts/60 Themes and Styles/10 HTML-Based Components Customization/40 Individual CSS Classes.md
Labels: cherry-pick, 22_1

#5089 Themebuilder docIssues fix (#5075)
  concepts/60 Themes and Styles/08 ThemeBuilder/01 Get Started/7 Import an Existing Theme.md
  concepts/60 Themes and Styles/08 ThemeBuilder/10 Customize the Theme.md
  concepts/60 Themes and Styles/08 ThemeBuilder/40 Export the Resulting Theme.md
  concepts/60 Themes and Styles/10 HTML-Based Components Customization/40 Individual CSS Classes.md
Labels: cherry-pick, 23_1

#5090 DataGrid: add note about using string dates (T871898) (#5076)
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/value.md
  api-reference/_hidden/GridBaseColumn/filterValue.md
Labels: cherry-pick, 22_1

#5091 DataGrid: add note about using string dates (T871898) (#5076)
  api-reference/10 UI Components/dxFilterBuilder/1 Configuration/value.md
  api-reference/_hidden/GridBaseColumn/filterValue.md
Labels: cherry-pick, 23_1

#5077 Icons: fix docIssues
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
  concepts/60 Themes and Styles/30 Icons/10 Built-In Icon Library.md
  concepts/60 Themes and Styles/30 Icons/60 SVG Icons.md
Labels: 22_2

#5092 Icons: fix docIssues (#5077)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
  concepts/60 Themes and Styles/30 Icons/10 Built-In Icon Library.md
  concepts/60 Themes and Styles/30 Icons/60 SVG Icons.md
Labels: cherry-pick, 22_1

#5093 Icons: fix docIssues (#5077)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
  concepts/60 Themes and Styles/30 Icons/10 Built-In Icon Library.md
  concepts/60 Themes and Styles/30 Icons/60 SVG Icons.md
Labels: cherry-pick, 23_1

#5080 DataGrid: add note about remote operations
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
  api-reference/_hidden/dxDataGridColumn/calculateGroupValue.md
Labels: 22_2

#5079 React: add a note about Optimize Performance topic
  concepts/50 React Components/00 DevExtreme React Components.md
Labels: 22_2

#5094 DataGrid: add note about remote operations (#5080)
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
  api-reference/_hidden/dxDataGridColumn/calculateGroupValue.md
Labels: cherry-pick, 22_1

#5095 DataGrid: add note about remote operations (#5080)
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
  api-reference/_hidden/dxDataGridColumn/calculateGroupValue.md
Labels: cherry-pick, 23_1

#5078 Scheduler: fix docIssues
  api-reference/10 UI Components/dxScheduler/3 Methods/repaint().md
  concepts/05 UI Components/Scheduler/060 Views/010 View Types/030 Month View.md
Labels: 22_2

#5096 React: add a note about Optimize Performance topic (#5079)
  concepts/50 React Components/00 DevExtreme React Components.md
Labels: cherry-pick, 22_1

#5097 React: add a note about Optimize Performance topic (#5079)
  concepts/50 React Components/00 DevExtreme React Components.md
Labels: cherry-pick, 23_1

#5098 Scheduler: fix docIssues (#5078)
  api-reference/10 UI Components/dxScheduler/3 Methods/repaint().md
  concepts/05 UI Components/Scheduler/060 Views/010 View Types/030 Month View.md
Labels: cherry-pick, 22_1

#5081 DataGrid: update dataSource information (T1167689)
  api-reference/10 UI Components/GridBase/1 Configuration/dataSource.md
Labels: 22_2

#5099 Scheduler: fix docIssues (#5078)
  api-reference/10 UI Components/dxScheduler/3 Methods/repaint().md
  concepts/05 UI Components/Scheduler/060 Views/010 View Types/030 Month View.md
Labels: cherry-pick, 23_1

#5100 DataGrid: update dataSource information (T1167689) (#5081)
  api-reference/10 UI Components/GridBase/1 Configuration/dataSource.md
Labels: cherry-pick, 22_1

#5101 DataGrid: update dataSource information (T1167689) (#5081)
  api-reference/10 UI Components/GridBase/1 Configuration/dataSource.md
Labels: cherry-pick, 23_1

#5085 Popup: update `focus()` description
  api-reference/10 UI Components/dxPopup/3 Methods/focus().md
Labels: 22_2

#5102 Popup: update `focus()` description (#5085)
  api-reference/10 UI Components/dxPopup/3 Methods/focus().md
Labels: cherry-pick, 22_1

#5103 Popup: update `focus()` description (#5085)
  api-reference/10 UI Components/dxPopup/3 Methods/focus().md
Labels: cherry-pick, 23_1

#5104 Drawer: add openedStateMode extended description (T1145566)
  api-reference/10 UI Components/dxDrawer/1 Configuration/openedStateMode.md
Labels: 22_2

#5105 Drawer: add openedStateMode extended description (T1145566) (#5104)
  api-reference/10 UI Components/dxDrawer/1 Configuration/openedStateMode.md
Labels: cherry-pick, 22_1

#5108 Scheduler: update cell templates description
  api-reference/10 UI Components/dxScheduler/1 Configuration/dataCellTemplate.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateCellTemplate.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/timeCellTemplate.md
  images/Scheduler/scheduler-cells.png
Labels: 22_2

#5110 Scheduler: update cell templates description (#5108)
  api-reference/10 UI Components/dxScheduler/1 Configuration/dataCellTemplate.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateCellTemplate.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/timeCellTemplate.md
  images/Scheduler/scheduler-cells.png
Labels: cherry-pick, 23_1

#5065 Charts: update valueErrorBar and customizeTooltip
  api-reference/10 UI Components/BaseChart/1 Configuration/tooltip/customizeTooltip.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/valueErrorBar/valueErrorBar.md
Labels: 22_2

#5042 Accessibility: add Overview topic
  concepts/Common/Accessibility/00 Overview/00 Overview.md
  concepts/Common/Accessibility/00 Overview/05 Right-to-Left Support.md
  concepts/Common/Accessibility/00 Overview/10 Keyboard Navigation Support.md
  concepts/Common/Accessibility/00 Overview/15 Screen Reader Support.md
  concepts/Common/Accessibility/00 Overview/20 Contrast Color Theme.md
  concepts/Common/Accessibility/00 Overview/25 Mobile Device Support.md
  concepts/Common/Accessibility/00 Overview/30 Validation Tools.md
  concepts/Common/Accessibility/00 Overview/35 Standard Compliance.md
  concepts/Common/Accessibility/05 Documentation for Components.md
  concepts/Common/Accessibility/Section 508/Section 508.md
Labels: 23_1

#5116 Charts: update valueErrorBar and customizeTooltip (#5065)
  api-reference/10 UI Components/BaseChart/1 Configuration/tooltip/customizeTooltip.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/valueErrorBar/valueErrorBar.md
Labels: cherry-pick, 22_1

#5117 Charts: update valueErrorBar and customizeTooltip (#5065)
  api-reference/10 UI Components/BaseChart/1 Configuration/tooltip/customizeTooltip.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/valueErrorBar/valueErrorBar.md
Labels: cherry-pick, 23_1

#5112 DataGrid: update comparison information (T890180)
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowEnabled.md
  api-reference/10 UI Components/GridBase/3 Methods/navigateToRow(key).md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
Labels: 22_2

#5118 DataGrid: update comparison information (T890180) (#5112)
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowEnabled.md
  api-reference/10 UI Components/GridBase/3 Methods/navigateToRow(key).md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
Labels: cherry-pick, 22_1

#5119 DataGrid: update comparison information (T890180) (#5112)
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowEnabled.md
  api-reference/10 UI Components/GridBase/3 Methods/navigateToRow(key).md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
Labels: cherry-pick, 23_1

#5107 Troubleshooting: add 'Editors Values are not Saved' article
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/00 DataGrid and TreeList Issues.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/00 Editors Values are not Saved.md
Labels: 22_2

#5120 Troubleshooting: add 'Editors Values are not Saved' article (#5107)
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/00 DataGrid and TreeList Issues.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/00 Editors Values are not Saved.md
Labels: cherry-pick, 22_1

#5123 Fix link for What's New 23.1
  concepts/Common/Migrate to the New Version/40 Learn What's New.md
Labels: 23_1
