Repository DevExpress/devextreme-documentation, pull requests merged in 2023-07, with the labels that each got.

#5291 Gantt: update calculateFilterExpression and calculateSortValue (T1175973)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
Labels: 23_1

#5292 Gantt: update calculateFilterExpression and calculateSortValue (T1175973)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
Labels: cherry-pick, 23_2

#5293 Gantt: update calculateFilterExpression and calculateSortValue (T1175973)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
Labels: cherry-pick, 22_2

#5294 Components: update the beginUpdate and endUpdate (T1175998)
  api-reference/10 UI Components/Component/3 Methods/beginUpdate().md
  api-reference/10 UI Components/Component/3 Methods/endUpdate().md
Labels: 23_1

#5300 Components: update the beginUpdate and endUpdate (T1175998) (#5294)
  api-reference/10 UI Components/Component/3 Methods/beginUpdate().md
  api-reference/10 UI Components/Component/3 Methods/endUpdate().md
Labels: cherry-pick, 22_2

#5301 Components: update the beginUpdate and endUpdate (T1175998) (#5294)
  api-reference/10 UI Components/Component/3 Methods/beginUpdate().md
  api-reference/10 UI Components/Component/3 Methods/endUpdate().md
Labels: cherry-pick, 23_2

#5287 DataGrid: add the Appearance and Editing section
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/10 Form Layout Customization.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/20 Editor Customization.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/Appearance and Editing.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/Customize Edit Form.md
Labels: 22_2

#5302 Add kb dg customize edit form 23 1
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/10 Form Layout Customization.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/20 Editor Customization.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/Appearance and Editing.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/Customize Edit Form.md
Labels: cherry-pick, 23_1

#5303 Add kb dg customize edit form 23 1 (#5302)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/10 Form Layout Customization.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/20 Editor Customization.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/Appearance and Editing.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/Customize Edit Form.md
Labels: cherry-pick, 23_2

#5286 Themes: add 'Using SCSS' guide
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme/00 Apply a Theme.md
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme/05 Using SCSS.md
Labels: 23_1

#5323 Themes: add 'Using SCSS' guide (#5286)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme/00 Apply a Theme.md
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme/05 Using SCSS.md
Labels: cherry-pick, 22_2

#5324 Themes: add 'Using SCSS' guide (#5286)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme/00 Apply a Theme.md
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme/05 Using SCSS.md
Labels: cherry-pick, 23_2

#5325 VectorMap Tooltip - Update Uid
  api-reference/10 UI Components/dxVectorMap/9 Types/Tooltip/format.md
Labels: 23_1

#5314 Update Uids for renamed grids types
  api-reference/10 UI Components/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
  api-reference/10 UI Components/dxDataGrid/9 Types/Editing/Editing.md
  api-reference/10 UI Components/dxDataGrid/9 Types/Scrolling/Scrolling.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SortByGroupSummaryInfoItem/SortByGroupSummaryInfoItem.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SortByGroupSummaryInfoItem/groupColumn.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SortByGroupSummaryInfoItem/sortOrder.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SortByGroupSummaryInfoItem/summaryItem.md
  api-reference/10 UI Components/dxTreeList/9 Types/Editing/Editing.md
  api-reference/10 UI Components/dxTreeList/9 Types/Scrolling/Scrolling.md
  api-reference/40 Common Types/15 grids/EditingBase/EditingBase.md
  api-reference/40 Common Types/15 grids/EditingTextsBase/EditingTextsBase.md
  api-reference/40 Common Types/15 grids/PagingBase/PagingBase.md
  api-reference/40 Common Types/15 grids/ScrollingBase/ScrollingBase.md
  api-reference/40 Common Types/15 grids/SelectionBase/SelectionBase.md
  api-reference/40 Common Types/SortOrder.md
  api-reference/_hidden/GridBaseColumn/GridBaseColumn.md
  api-reference/_hidden/GridBaseColumn/buttons/buttons.md
Labels: 23_1

#5326 VectorMap Tooltip - Update Uid
  api-reference/10 UI Components/dxVectorMap/9 Types/Tooltip/format.md
Labels: cherry-pick, 23_2

#5327 Update Uids for renamed grids types
  api-reference/10 UI Components/dxDataGrid/1 Configuration/sortByGroupSummaryInfo/sortByGroupSummaryInfo.md
  api-reference/10 UI Components/dxDataGrid/9 Types/Editing/Editing.md
  api-reference/10 UI Components/dxDataGrid/9 Types/Scrolling/Scrolling.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SortByGroupSummaryInfoItem/SortByGroupSummaryInfoItem.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SortByGroupSummaryInfoItem/groupColumn.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SortByGroupSummaryInfoItem/sortOrder.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SortByGroupSummaryInfoItem/summaryItem.md
  api-reference/10 UI Components/dxTreeList/9 Types/Editing/Editing.md
  api-reference/10 UI Components/dxTreeList/9 Types/Scrolling/Scrolling.md
  api-reference/40 Common Types/15 grids/EditingBase/EditingBase.md
  api-reference/40 Common Types/15 grids/EditingTextsBase/EditingTextsBase.md
  api-reference/40 Common Types/15 grids/PagingBase/PagingBase.md
  api-reference/40 Common Types/15 grids/ScrollingBase/ScrollingBase.md
  api-reference/40 Common Types/15 grids/SelectionBase/SelectionBase.md
  api-reference/40 Common Types/SortOrder.md
  api-reference/_hidden/GridBaseColumn/GridBaseColumn.md
  api-reference/_hidden/GridBaseColumn/buttons/buttons.md
Labels: cherry-pick, 23_2

#5295 Troubleshooting: add Fluent UI topic
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/10 Fluent UI/00 Fluent UI.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/10 Fluent UI/05 Panels, Modals, Dialogs.md
Labels: 23_1

#5332 Troubleshooting: add Fluent UI topic (#5295)
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/10 Fluent UI/00 Fluent UI.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/10 Fluent UI/05 Panels, Modals, Dialogs.md
Labels: cherry-pick, 22_2

#5334 CSP: add new information related to security (#5313)
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
  concepts/Common/Security Considerations/40 Content Security Policy/00 Content Security Policy.md
  concepts/Common/Security Considerations/40 Content Security Policy/20 CSP Directives for Map Integrations.md
Labels: cherry-pick, 23_2

#5335 Remove VPAT link
  concepts/Common/Accessibility/00 Overview/35 Standard Compliance.md
Labels: 23_1

#5336 Remove VPAT link (#5335)
  concepts/Common/Accessibility/00 Overview/35 Standard Compliance.md
Labels: cherry-pick, 23_2

#5321 Components: update dragging events
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onDragChange.md
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onDragEnd.md
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onDragMove.md
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onDragStart.md
  api-reference/10 UI Components/dxDraggable/1 Configuration/onDragEnd.md
  api-reference/10 UI Components/dxDraggable/1 Configuration/onDragMove.md
  api-reference/10 UI Components/dxDraggable/1 Configuration/onDragStart.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentDragging/onDragEnd.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentDragging/onDragMove.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentDragging/onDragStart.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragChange.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragEnd.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragMove.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragStart.md
Labels: 22_2

#5338 Components: update dragging events (#5321) (#5337)
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onDragChange.md
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onDragEnd.md
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onDragMove.md
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onDragStart.md
  api-reference/10 UI Components/dxDraggable/1 Configuration/onDragEnd.md
  api-reference/10 UI Components/dxDraggable/1 Configuration/onDragMove.md
  api-reference/10 UI Components/dxDraggable/1 Configuration/onDragStart.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentDragging/onDragEnd.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentDragging/onDragMove.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentDragging/onDragStart.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragChange.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragEnd.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragMove.md
  api-reference/10 UI Components/dxSortable/1 Configuration/onDragStart.md
Labels: cherry-pick, 23_2

#5331 Scheduler: add the W1023 warning description
  api-reference/10 UI Components/Errors and Warnings/W1023.md
Labels: 22_2

#5340 Scheduler: add the W1023 warning description (#5331)
  api-reference/10 UI Components/Errors and Warnings/W1023.md
Labels: cherry-pick, 23_1

#5341 Scheduler: add the W1023 warning description (#5331)
  api-reference/10 UI Components/Errors and Warnings/W1023.md
Labels: cherry-pick, 23_2

#5346 Rename LoadedSummary type and typeguard (move to CustomStore sub folder)
  api-reference/30 Data Layer/CustomStore/9 Types/9 Types.md
  api-reference/30 Data Layer/CustomStore/9 Types/ResolvedData.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/GroupItem.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResult/LoadResult.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/LoadResultObject.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/custom-store.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/isGroupItemsArray.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/isItemsArray.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/isLoadResultObject.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/GroupItem.md
Labels: cherry-pick, 22_2

#5347 CustomStore: Data Types Guards
  api-reference/30 Data Layer/CustomStore/1 Configuration/load.md
  api-reference/30 Data Layer/CustomStore/3 Methods/load(options).md
  api-reference/40 Common Types/10 data/ResolvedData.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/GroupItem.md
  api-reference/40 Common Types/10 data/custom-store/LoadResult/LoadResult.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/LoadResultObject.md
  api-reference/40 Common Types/10 data/custom-store/custom-store.md
  api-reference/40 Common Types/10 data/custom-store/isGroupItemsArray.md
  api-reference/40 Common Types/10 data/custom-store/isItemsArray.md
  api-reference/40 Common Types/10 data/custom-store/isLoadResultObject.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/common/data/custom-store.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/data/data.md
Labels: cherry-pick, 23_2

#5349 Delete VPAT link
  concepts/Common/Accessibility/Section 508/Section 508.md
Labels: 22_2

#5350 Delete VPAT link (#5349)
  concepts/Common/Accessibility/Section 508/Section 508.md
Labels: cherry-pick, 22_1

#5351 Delete VPAT link (#5349)
  concepts/Common/Accessibility/Section 508/Section 508.md
Labels: cherry-pick, 21_2

#5353 Delete VPAT link (#5352)
  concepts/Common/Accessibility/Section 508/Section 508.md
Labels: 20_2

#5354 Delete VPAT link (#5352) (#5353)
  concepts/Common/Accessibility/Section 508/Section 508.md
Labels: 20_1

#5348 DataGrid: update calculateFilterExpression
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: 23_1

#5356 DataGrid: update calculateFilterExpression (#5348)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: cherry-pick, 22_2

#5357 DataGrid: update calculateFilterExpression (#5348)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: cherry-pick, 23_2

#5362 React: clarify a difference between the itemRender and itemComponent props (T1170160)
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/0 Markup Customization.md
Labels: 22_2

#5364 React: clarify a difference between the itemRender and itemComponent props (T1170160)
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/0 Markup Customization.md
Labels: cherry-pick, 23_1

#5365 React: clarify a difference between the itemRender and itemComponent props (T1170160)
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/0 Markup Customization.md
Labels: cherry-pick, 23_2

#5366 CustomStore: describe LoadResult types (#5363)
  api-reference/40 Common Types/10 data/ResolvedData.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/GroupItem.md
  api-reference/40 Common Types/10 data/custom-store/LoadResult/LoadResult.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/LoadResultObject.md
  api-reference/40 Common Types/10 data/custom-store/isGroupItemsArray.md
  api-reference/40 Common Types/10 data/custom-store/isItemsArray.md
  api-reference/40 Common Types/10 data/custom-store/isLoadResultObject.md
Labels: cherry-pick, 23_2

#5370 CustomStore: move types
  api-reference/40 Common Types/10 data/ResolvedData.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/GroupItem.md
  api-reference/40 Common Types/10 data/custom-store/LoadResult.md
  api-reference/40 Common Types/10 data/custom-store/LoadResult/LoadResult.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/LoadResultObject.md
  api-reference/40 Common Types/10 data/custom-store/isGroupItemsArray.md
  api-reference/40 Common Types/10 data/custom-store/isItemsArray.md
  api-reference/40 Common Types/10 data/custom-store/isLoadResultObject.md
Labels: 23_1

#5371 CustomStore: move types
  api-reference/30 Data Layer/CustomStore/9 Types/ResolvedData.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/GroupItem.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResult.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResult/LoadResult.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/LoadResultObject.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/isGroupItemsArray.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/isItemsArray.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/isLoadResultObject.md
Labels: 22_2

#5373 CustomStore: add topics for result types
  api-reference/40 Common Types/10 data/ResolvedData.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/GroupItem.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/count.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/items.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/key.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/summary.md
  api-reference/40 Common Types/10 data/custom-store/LoadResult.md
  api-reference/40 Common Types/10 data/custom-store/LoadResult/LoadResult.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/LoadResultObject.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/data.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/groupCount.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/summary.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/totalCount.md
  api-reference/40 Common Types/10 data/custom-store/isGroupItemsArray.md
  api-reference/40 Common Types/10 data/custom-store/isItemsArray.md
  api-reference/40 Common Types/10 data/custom-store/isLoadResultObject.md
Labels: 23_1

#5374 CustomStore: add topics for result types
  api-reference/30 Data Layer/CustomStore/9 Types/ResolvedData.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/GroupItem.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/count.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/items.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/key.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/summary.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResult.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResult/LoadResult.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/LoadResultObject.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/data.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/groupCount.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/summary.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/totalCount.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/isGroupItemsArray.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/isItemsArray.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/isLoadResultObject.md
Labels: cherry-pick, 22_2

#5376 Calendar: remove notes from `height` and `width`
  api-reference/10 UI Components/dxCalendar/1 Configuration/height.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/width.md
Labels: 23_1

#5377 Calendar: remove notes from `height` and `width` (#5376)
  api-reference/10 UI Components/dxCalendar/1 Configuration/height.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/width.md
Labels: cherry-pick, 23_2

#5378 CDN: rename devextreme to devextreme-dist
  concepts/Common/Distribution Channels/05 CDN/05 CDN.md
Labels: 23_1

#5379 CDN: rename devextreme to devextreme-dist
  concepts/Common/Distribution Channels/05 CDN/05 CDN.md
Labels: 23_2

#5381 DataGrid: add Custom Edit Form/Validation topic (#5380)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/20 Validation.md
Labels: cherry-pick, 22_2

#5382 DataGrid: add Custom Edit Form/Validation topic (#5380)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/20 Validation.md
Labels: cherry-pick, 23_2

#5386 DateBox: add note for pickerType="rollers"
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: 23_1

#5387 DateBox: add note for pickerType="rollers" (#5386)
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: cherry-pick, 22_2

#5388 DateBox: add note for pickerType="rollers" (#5386)
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: cherry-pick, 23_2

#5385 DataGrid: add Customize Edit Form/Save, Cancel, and Custom Buttons guide
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/30 Save, Cancel, and Custom Buttons.md
Labels: 23_1

#5389 DataGrid: add Customize Edit Form/Save, Cancel, and Custom Buttons guide (#5385)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/30 Save, Cancel, and Custom Buttons.md
Labels: cherry-pick, 23_2

#5392 Revert "CDN: rename devextreme to devextreme-dist"
  concepts/Common/Distribution Channels/05 CDN/05 CDN.md
Labels: 23_1

#5391 CustomStore: describe fields in GroupItem and LoadResultObject
  api-reference/40 Common Types/10 data/custom-store/GroupItem/count.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/items.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/key.md
  api-reference/40 Common Types/10 data/custom-store/GroupItem/summary.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/data.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/groupCount.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/summary.md
  api-reference/40 Common Types/10 data/custom-store/LoadResultObject/totalCount.md
Labels: 23_1

#5393 CustomStore: describe fields in GroupItem and LoadResultObject
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/count.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/items.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/key.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/GroupItem/summary.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/data.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/groupCount.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/summary.md
  api-reference/30 Data Layer/CustomStore/9 Types/custom-store/LoadResultObject/totalCount.md
Labels: 22_2

#5394 DataGrid: add Other topics to Customize Edit Form guide
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/40 Dynamically Change Editor or Form Item Properties.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/50 Advanced Customization.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/60 Edit Form Limitations.md
Labels: 23_1

#5397 DataGrid: add Other topics to Customize Edit Form guide (#5394)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/40 Dynamically Change Editor or Form Item Properties.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/50 Advanced Customization.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/60 Edit Form Limitations.md
Labels: cherry-pick, 23_2

#5396 DataGrid: add Other topics to Customize Edit Form guide (#5394)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/40 Dynamically Change Editor or Form Item Properties.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/50 Advanced Customization.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/60 Edit Form Limitations.md
Labels: cherry-pick, 22_2

#5402 FileManager: add server object structure
  concepts/05 UI Components/FileManager/10 Bind to File Systems/20 Remote File System.md
Labels: 23_1

#5403 FileManager: add server object structure (#5402)
  concepts/05 UI Components/FileManager/10 Bind to File Systems/20 Remote File System.md
Labels: cherry-pick, 22_2

#5404 FileManager: add server object structure (#5402)
  concepts/05 UI Components/FileManager/10 Bind to File Systems/20 Remote File System.md
Labels: cherry-pick, 23_2

#5409 HtmlEditor: add info about extend/modify operations
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/Customize Built-In Formats and Modules.md
Labels: 23_1

#5410 HtmlEditor: add info about extend/modify operations (#5409)
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/Customize Built-In Formats and Modules.md
Labels: cherry-pick, 22_2

#5411 HtmlEditor: add info about extend/modify operations (#5409)
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/Customize Built-In Formats and Modules.md
Labels: cherry-pick, 23_2

#5424 Charts: remove repeating part from `color`
  api-reference/10 UI Components/dxChart/5 Series Types/AreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/BarSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/BubbleSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/FullStackedAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/FullStackedBarSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/FullStackedSplineAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/RangeAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/RangeBarSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/SplineAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/StackedAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/StackedBarSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/StackedSplineAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/StepAreaSeries/color.md
Labels: 23_1

#5425 Charts: remove repeating part from `color` (#5424)
  api-reference/10 UI Components/dxChart/5 Series Types/AreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/BarSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/BubbleSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/FullStackedAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/FullStackedBarSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/FullStackedSplineAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/RangeAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/RangeBarSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/SplineAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/StackedAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/StackedBarSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/StackedSplineAreaSeries/color.md
  api-reference/10 UI Components/dxChart/5 Series Types/StepAreaSeries/color.md
Labels: cherry-pick, 23_2
