Repository DevExpress/devextreme-documentation, pull requests merged in 2023-06, with the labels that each got.

#5125 Describe missed types + move index folder
  api-reference/10 UI Components/dxBarGauge/9 Types/dxBarGaugeLegend/visible.md
  api-reference/10 UI Components/dxCalendar/9 Types/DisabledDate.md
  api-reference/10 UI Components/dxChart/9 Types/dxChartArgumentAxis/endOnTick.md
  api-reference/10 UI Components/dxChart/9 Types/dxChartValueAxis/endOnTick.md
  api-reference/10 UI Components/dxDataGrid/9 Types/Editing/texts.md
  api-reference/10 UI Components/dxDataGrid/9 Types/GroupData.md
  api-reference/10 UI Components/dxFunnel/9 Types/dxFunnelLegend/visible.md
  api-reference/10 UI Components/dxLinearGauge/9 Types/dxLinearGaugeScale/scaleDivisionFactor.md
  api-reference/10 UI Components/dxLoadPanel/9 Types/dxLoadPanelAnimation/hide.md
  api-reference/10 UI Components/dxLoadPanel/9 Types/dxLoadPanelAnimation/show.md
  api-reference/10 UI Components/dxPieChart/9 Types/dxPieChartAdaptiveLayout/keepLabels.md
  api-reference/10 UI Components/dxPieChart/9 Types/dxPieChartLegend/customizeItems.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartAdaptiveLayout/height.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartAdaptiveLayout/width.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxis/minorTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartArgumentAxis/tick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartTooltip/shared.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxis/endOnTick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxis/tick.md
  api-reference/10 UI Components/dxPolarChart/9 Types/dxPolarChartValueAxisTick/visible.md
  api-reference/10 UI Components/dxPopup/9 Types/dxPopupAnimation/hide.md
  api-reference/10 UI Components/dxPopup/9 Types/dxPopupAnimation/show.md
  api-reference/10 UI Components/dxSankey/9 Types/dxSankeyTooltip/enabled.md
  api-reference/10 UI Components/dxScheduler/9 Types/AppointmentTooltipShowingAppointmentInfo.md
  api-reference/10 UI Components/dxSparkline/9 Types/BaseSparklineTooltip/enabled.md
  api-reference/10 UI Components/dxTreeList/9 Types/Editing/texts.md
  api-reference/10 UI Components/dxTreeList/9 Types/EditingTexts/EditingTexts.md
  api-reference/10 UI Components/dxTreeList/9 Types/Paging/Paging.md
  api-reference/10 UI Components/dxTreeList/9 Types/Paging/enabled.md
  api-reference/10 UI Components/dxVectorMap/9 Types/dxVectorMapLegends/markerSize.md
  api-reference/40 Common Types/10 data/FilterDescriptor.md
  api-reference/40 Common Types/10 data/GroupDescriptor.md
  api-reference/40 Common Types/10 data/GroupItem.md
  api-reference/40 Common Types/10 data/LangParams/LangParams.md
  api-reference/40 Common Types/10 data/LangParams/collatorOptions.md
  api-reference/40 Common Types/10 data/LangParams/locale.md
  api-reference/40 Common Types/10 data/ResolvedData.md
  api-reference/40 Common Types/10 data/SearchOperation.md
  api-reference/40 Common Types/10 data/SelectDescriptor.md
  api-reference/40 Common Types/10 data/SortDescriptor.md
  api-reference/40 Common Types/10 data/SummaryDescriptor.md
  api-reference/40 Common Types/10 data/index.md
  api-reference/40 Common Types/13 events/Cancelable.md
  api-reference/40 Common Types/13 events/ChangedOptionInfo.md
  api-reference/40 Common Types/13 events/EventInfo.md
  api-reference/40 Common Types/13 events/InitializedEventInfo.md
  api-reference/40 Common Types/13 events/NativeEventInfo.md
  api-reference/40 Common Types/DefaultOptionsRule.md
  api-reference/40 Common Types/ValidationRule.md
Labels: 23_1

#5126 Update the "end-user" expression
  api-reference/10 UI Components/dxCalendar/1 Configuration/value.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/masterDetail/enabled.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/applyValueMode.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/value.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/acceptCustomValue.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/applyValueMode.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/extendSelection.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/labelText.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/multiple.md
  api-reference/10 UI Components/dxList/1 Configuration/collapsibleGroups.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowExpandAll.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowSorting.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowSortingBySummary.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/fieldChooser/fieldChooser.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/scrolling/mode.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/scrolling/scrolling.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/crossScrollingEnabled.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowAdding.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowDeleting.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowResizing.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowUpdating.md
  api-reference/10 UI Components/dxScrollable/1 Configuration/scrollByContent.md
  api-reference/10 UI Components/dxTabs/1 Configuration/scrollByContent.md
  api-reference/10 UI Components/dxTabs/1 Configuration/scrollingEnabled.md
  api-reference/10 UI Components/dxTabs/1 Configuration/selectionMode.md
  api-reference/10 UI Components/dxVectorMap/1 Configuration/maxZoomFactor.md
Labels: 22_2

#5127 Update the "end-user" expression (#5126)
  api-reference/10 UI Components/dxCalendar/1 Configuration/value.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/masterDetail/enabled.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/applyValueMode.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/value.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/acceptCustomValue.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/applyValueMode.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/extendSelection.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/labelText.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/multiple.md
  api-reference/10 UI Components/dxList/1 Configuration/collapsibleGroups.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowExpandAll.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowSorting.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowSortingBySummary.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/fieldChooser/fieldChooser.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/scrolling/mode.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/scrolling/scrolling.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/crossScrollingEnabled.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowAdding.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowDeleting.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowResizing.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowUpdating.md
  api-reference/10 UI Components/dxScrollable/1 Configuration/scrollByContent.md
  api-reference/10 UI Components/dxTabs/1 Configuration/scrollByContent.md
  api-reference/10 UI Components/dxTabs/1 Configuration/scrollingEnabled.md
  api-reference/10 UI Components/dxTabs/1 Configuration/selectionMode.md
  api-reference/10 UI Components/dxVectorMap/1 Configuration/maxZoomFactor.md
Labels: cherry-pick, 22_1

#5128 Update the "end-user" expression (#5126)
  api-reference/10 UI Components/dxCalendar/1 Configuration/value.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/masterDetail/enabled.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/applyValueMode.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/value.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/acceptCustomValue.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/applyValueMode.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/extendSelection.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/labelText.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/multiple.md
  api-reference/10 UI Components/dxList/1 Configuration/collapsibleGroups.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowExpandAll.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowSorting.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/allowSortingBySummary.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/fieldChooser/fieldChooser.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/scrolling/mode.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/scrolling/scrolling.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/crossScrollingEnabled.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowAdding.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowDeleting.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowResizing.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowUpdating.md
  api-reference/10 UI Components/dxScrollable/1 Configuration/scrollByContent.md
  api-reference/10 UI Components/dxTabs/1 Configuration/scrollByContent.md
  api-reference/10 UI Components/dxTabs/1 Configuration/scrollingEnabled.md
  api-reference/10 UI Components/dxTabs/1 Configuration/selectionMode.md
  api-reference/10 UI Components/dxVectorMap/1 Configuration/maxZoomFactor.md
Labels: cherry-pick, 23_1

#5129 Troubleshooting: add article about container state change (#5122)
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/05 Bootstrap/00 Bootstrap.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/05 Bootstrap/05 Modals.md
  concepts/80 Troubleshooting/40 Components are Rendered Incorrectly if a Container State is Changed/00 Components are Rendered Incorrectly if a Container State is Changed.md
  concepts/80 Troubleshooting/40 Components are Rendered Incorrectly if a Container State is Changed/05 ResizeObserver.md
Labels: cherry-pick, 23_1

#5130 Troubleshooting: add article about container state change (#5122)
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/05 Bootstrap/00 Bootstrap.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/05 Bootstrap/05 Modals.md
  concepts/80 Troubleshooting/40 Components are Rendered Incorrectly if a Container State is Changed/00 Components are Rendered Incorrectly if a Container State is Changed.md
  concepts/80 Troubleshooting/40 Components are Rendered Incorrectly if a Container State is Changed/05 ResizeObserver.md
Labels: cherry-pick, 22_1

#5124 Scheduler: add note about grouping resouces in agenda view (T1169012)
  api-reference/10 UI Components/dxScheduler/1 Configuration/resources/resources.md
  concepts/05 UI Components/Scheduler/040 Resources/030 Group Appointments by Resources.md
  concepts/05 UI Components/Scheduler/060 Views/010 View Types/050 Agenda View.md
Labels: 22_2

#5137 Scheduler: add note about grouping resouces in agenda view (T1169012)…
  api-reference/10 UI Components/dxScheduler/1 Configuration/resources/resources.md
  concepts/05 UI Components/Scheduler/040 Resources/030 Group Appointments by Resources.md
  concepts/05 UI Components/Scheduler/060 Views/010 View Types/050 Agenda View.md
Labels: cherry-pick, 22_1

#5138 Scheduler: add note about grouping resouces in agenda view (T1169012)…
  api-reference/10 UI Components/dxScheduler/1 Configuration/resources/resources.md
  concepts/05 UI Components/Scheduler/040 Resources/030 Group Appointments by Resources.md
  concepts/05 UI Components/Scheduler/060 Views/010 View Types/050 Agenda View.md
Labels: cherry-pick, 23_1

#5139 Scheduler: add info about grouping in Agenda view
  api-reference/10 UI Components/dxScheduler/1 Configuration/groups.md
Labels: 22_2

#5141 Scheduler: add info about grouping in Agenda view (#5139)
  api-reference/10 UI Components/dxScheduler/1 Configuration/groups.md
Labels: cherry-pick, 22_1

#5142 Scheduler: add info about grouping in Agenda view (#5139)
  api-reference/10 UI Components/dxScheduler/1 Configuration/groups.md
Labels: cherry-pick, 23_1

#5143 DateRangeBox: update code snippets
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/10 Set the Accepted Date Range.md
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/15 Set the Initial Date Range Values.md
Labels: 23_1

#5145 DateRangeBox: add Accessibility topic
  concepts/05 UI Components/DateRangeBox/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/DateRangeBox/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/DateRangeBox/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DateRangeBox/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/DateRangeBox/03 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/DateRangeBox/10 Value Formatting and Masked Input.md
Labels: 23_1

#5144 Update GitHub and CodeSandBox button includes
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
  api-reference/40 Common Types/10 data/LangParams/locale.md
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
  api-reference/_hidden/dxDataGridColumn/calculateGroupValue.md
  concepts/05 UI Components/Accordion/00 Getting Started with Accordion/00 Getting Started with Accordion.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/00 Getting Started with Autocomplete.md
  concepts/05 UI Components/Button/00 Getting Started with Button/00 Getting Started with Button.md
  concepts/05 UI Components/ButtonGroup/00 Getting Started with ButtonGroup/0 Getting Started with ButtonGroup.md
  concepts/05 UI Components/CheckBox/00 Getting Started with CheckBox/00 Getting Started with CheckBox.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/00 Getting Started with DataGrid.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/50 Popup Mode.md
  concepts/05 UI Components/DataGrid/99 How To/Dynamically Change Editor Properties in the Editing State.md
  concepts/05 UI Components/DataGrid/99 How To/Dynamically Change Form Item Properties in the Editing State.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/00 Getting Started with DateBox.md
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/00 Getting Started with DateRangeBox.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/Getting Started with Navigation Drawer.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/00 Getting Started with DropDownBox.md
  concepts/05 UI Components/DropDownButton/00 Getting Started with DropDownButton/00 Getting Started with DropDownButton.md
  concepts/05 UI Components/FileUploader/99 How To/20 Specify a file's GUID.md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/10 Single Action.md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/20 Multiple Actions (Speed Dial).md
  concepts/05 UI Components/Form/01 Getting Started with Form/00 Getting Started with Form.md
  concepts/05 UI Components/Form/05 Configure Simple Items/05 Customize a Simple Item.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
  concepts/05 UI Components/List/00 Getting Started with List/00 Getting Started with List.md
  concepts/05 UI Components/Menu/00 Getting Started with Menu/00 Getting Started with Menu.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/00 Getting Started with PieChart.md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/00 Getting Started with Popup.md
  concepts/05 UI Components/SelectBox/00 Getting Started with SelectBox/00 Getting Started with SelectBox.md
  concepts/05 UI Components/TabPanel/01 Getting Started with TabPanel/00 Getting Started with TabPanel.md
  concepts/05 UI Components/TagBox/00 Getting Started with TagBox/00 Getting Started with TagBox.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/00 Getting Started with TextBox.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/00 Getting Started with Toolbar.md
  concepts/05 UI Components/TreeView/00 Getting Started with TreeView/00 Getting Started with TreeView.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/10 Functions.md
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
  concepts/80 Troubleshooting/40 Components are Rendered Incorrectly if a Container State is Changed/05 ResizeObserver.md
Labels: 23_1

#5147 Change 'DevExtreme CLI' visibility (#5146)
  concepts/Common/DevExtreme CLI/00 DevExtreme CLI.md
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
Labels: cherry-pick, 22_1

#5148 Change 'DevExtreme CLI' visibility (#5146)
  concepts/Common/DevExtreme CLI/00 DevExtreme CLI.md
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
Labels: cherry-pick, 23_1

#5149 TreeList: update the autoExpandAll property (T1170086)
  api-reference/10 UI Components/dxTreeList/1 Configuration/autoExpandAll.md
Labels: 22_2

#5151 DataSource: fix link in `locale`
  api-reference/40 Common Types/10 data/LangParams/locale.md
Labels: 23_1

#5152 TreeList: update the autoExpandAll property (T1170086) (#5149)
  api-reference/10 UI Components/dxTreeList/1 Configuration/autoExpandAll.md
Labels: cherry-pick, 22_1

#5153 TreeList: update the autoExpandAll property (T1170086)
  api-reference/10 UI Components/dxTreeList/1 Configuration/autoExpandAll.md
Labels: cherry-pick, 23_1

#5155 Get rid of allow + -ing (#5045)
  api-reference/10 UI Components/Errors and Warnings/E1049.md
  api-reference/10 UI Components/GridBase/1 Configuration/filterSyncEnabled.md
  api-reference/10 UI Components/GridBase/1 Configuration/searchPanel/searchPanel.md
  api-reference/10 UI Components/dxButtonGroup/1 Configuration/selectedItemKeys.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/groupPanel/groupPanel.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/grouping/contextMenuEnabled.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/masterDetail/template.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/searchEnabled.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/fieldChooser/allowSearch.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/allowSearch.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onNodesInitialized.md
  api-reference/30 Data Layer/DataSource/1 Configuration/Configuration.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/Configuration.md
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
  api-reference/_hidden/dxTreeListColumn/cellTemplate.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/3 Search Panel.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/5 Standalone Filter Builder.md
  concepts/05 UI Components/DataGrid/40 Scrolling/Scrolling.md
  concepts/05 UI Components/FileUploader/00 Overview.md
  concepts/05 UI Components/FilterBuilder/020 Integrate with a DevExtreme UI Component.md
  concepts/05 UI Components/FilterBuilder/030 Filter Hierarchical Fields.md
  concepts/05 UI Components/PivotGrid/060 Sorting/20 Sorting in the UI/20 Sorting by Field Values.md
  concepts/05 UI Components/PivotGrid/060 Sorting/20 Sorting in the UI/30 Sorting by Summary Values.md
  concepts/05 UI Components/Scheduler/030 Appointments/030 Update Appointments/010 User Interaction.md
  concepts/05 UI Components/Scheduler/030 Appointments/040 Delete Appointments/010 User Interaction.md
  concepts/05 UI Components/TreeList/40 Filtering and Searching/3 Search Panel.md
  concepts/05 UI Components/TreeList/40 Filtering and Searching/5 Standalone Filter Builder.md
  concepts/60 Themes and Styles/30 Icons/60 SVG Icons.md
Labels: cherry-pick, 22_1

#5156 Get rid of allow + -ing (#5045)
  api-reference/10 UI Components/Errors and Warnings/E1049.md
  api-reference/10 UI Components/GridBase/1 Configuration/filterSyncEnabled.md
  api-reference/10 UI Components/GridBase/1 Configuration/searchPanel/searchPanel.md
  api-reference/10 UI Components/dxButtonGroup/1 Configuration/selectedItemKeys.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/groupPanel/groupPanel.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/grouping/contextMenuEnabled.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/masterDetail/template.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/searchEnabled.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/fieldChooser/allowSearch.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/allowSearch.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onNodesInitialized.md
  api-reference/30 Data Layer/DataSource/1 Configuration/Configuration.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/Configuration.md
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
  api-reference/_hidden/dxTreeListColumn/cellTemplate.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/3 Search Panel.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/5 Standalone Filter Builder.md
  concepts/05 UI Components/DataGrid/40 Scrolling/Scrolling.md
  concepts/05 UI Components/FileUploader/00 Overview.md
  concepts/05 UI Components/FilterBuilder/020 Integrate with a DevExtreme UI Component.md
  concepts/05 UI Components/FilterBuilder/030 Filter Hierarchical Fields.md
  concepts/05 UI Components/PivotGrid/060 Sorting/20 Sorting in the UI/20 Sorting by Field Values.md
  concepts/05 UI Components/PivotGrid/060 Sorting/20 Sorting in the UI/30 Sorting by Summary Values.md
  concepts/05 UI Components/Scheduler/030 Appointments/030 Update Appointments/010 User Interaction.md
  concepts/05 UI Components/Scheduler/030 Appointments/040 Delete Appointments/010 User Interaction.md
  concepts/05 UI Components/TreeList/40 Filtering and Searching/3 Search Panel.md
  concepts/05 UI Components/TreeList/40 Filtering and Searching/5 Standalone Filter Builder.md
  concepts/60 Themes and Styles/30 Icons/60 SVG Icons.md
Labels: cherry-pick, 23_1

#5154 DateBox: update missing properties description
  api-reference/10 UI Components/dxDateBox/1 Configuration/label.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/maxLength.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/name.md
Labels: 23_1

#5157 Charts: update column/rowCount descriptions
  api-reference/10 UI Components/BaseLegend/columnCount.md
  api-reference/10 UI Components/BaseLegend/rowCount.md
Labels: 22_2

#5158 Charts: update column/rowCount descriptions (#5157)
  api-reference/10 UI Components/BaseLegend/columnCount.md
  api-reference/10 UI Components/BaseLegend/rowCount.md
Labels: cherry-pick, 22_1

#5164 Add new demos in doc 23 1
  api-reference/10 UI Components/DateBoxBase/1 Configuration/displayFormat.md
  api-reference/10 UI Components/DateBoxBase/1 Configuration/max.md
  api-reference/10 UI Components/DateBoxBase/1 Configuration/min.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnChooser/mode.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnChooser/position.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnChooser/selection.md
  api-reference/10 UI Components/GridBase/1 Configuration/headerFilter/search/search.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/endDate.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/endDateLabel.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/endDatePlaceholder.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/multiView.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/startDate.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/startDateLabel.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/startDatePlaceholder.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/value.md
  api-reference/10 UI Components/dxPieChart/5 Series Types/CommonPieChartSeries/color.md
  api-reference/40 Common Types/15 grids/ColumnChooserSearchConfig/enabled.md
  api-reference/40 Common Types/15 grids/ColumnChooserSelectionConfig/recursive.md
  api-reference/40 Common Types/15 grids/ColumnHeaderFilterSearchConfig/searchExpr.md
  api-reference/40 Common Types/15 grids/HeaderFilterSearchConfig/mode.md
  api-reference/50 Common/utils/viz/registerGradient(type_options).md
  api-reference/50 Common/utils/viz/registerPattern(options).md
  concepts/05 UI Components/PieChart/10 Series/30 Customize Appearance.md
Labels: 23_1

#5165 Troubleshooting: add an article about gray boxes in grids (#5131)
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/05 Editors Values are not Saved.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/00 Gray Boxes Appear After Data Loading.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/05 Use the Latest Version.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/10 Use Another Machine for Testing.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/15 Ensure Component Size Matches Container Size.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/20 Ensure Component is Correctly Bound to Data Source.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/25 Eliminate Side Effects.md
  images/DataGrid/datagrid-gray-boxes.png
Labels: cherry-pick, 22_1

#5166 Troubleshooting: add an article about gray boxes in grids (#5131)
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/05 Editors Values are not Saved.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/00 Gray Boxes Appear After Data Loading.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/05 Use the Latest Version.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/10 Use Another Machine for Testing.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/15 Ensure Component Size Matches Container Size.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/20 Ensure Component is Correctly Bound to Data Source.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/25 Eliminate Side Effects.md
  images/DataGrid/datagrid-gray-boxes.png
Labels: cherry-pick, 23_1

#5167 TreeList: add description for rowRenderingMode (T1170183)
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/rowRenderingMode.md
Labels: 22_2

#5169 TreeList: add description for rowRenderingMode (T1170183) (#5167)
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/rowRenderingMode.md
Labels: cherry-pick, 22_1

#5175 Add GitHub example references (buttons) into documentation
  api-reference/10 UI Components/GridBase/1 Configuration/onRowUpdating.md
  api-reference/10 UI Components/GridBase/1 Configuration/onToolbarPreparing.md
  api-reference/10 UI Components/GridBase/1 Configuration/selection/allowSelectAll.md
  api-reference/10 UI Components/GridBase/1 Configuration/selection/mode.md
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/stateStoring.md
  api-reference/10 UI Components/Widget/1 Configuration/onContentReady.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onCellClick.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onCellPrepared.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onContextMenuPreparing.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onEditorPrepared.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/selection/selectAllMode.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/selection/showCheckBoxesMode.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorOptions.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/onAppointmentFormOpening.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxTooltip/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxValidator/1 Configuration/Configuration.md
  api-reference/30 Data Layer/PivotGridDataSource/3 Methods/createDrillDownDataSource(options).md
  api-reference/50 Common/Object Structures/ExcelExportDataGridProps/customizeCell.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/_hidden/CollectionWidgetItem/template.md
  api-reference/_hidden/GridBaseColumn/formItem.md
  api-reference/_hidden/GridBaseColumn/setCellValue.md
  api-reference/_hidden/dxDataGridColumn/groupCellTemplate.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/30 Batch Mode.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/50 Popup Mode.md
  concepts/05 UI Components/DropDownBox/15 Synchronize with the Embedded Element.md
  concepts/05 UI Components/FileUploader/20 Upload Files/05 Client-Side Settings/05 Upload Mode.md
Labels: 23_1

#5180 Add GitHub example references (buttons) into documentation
  api-reference/10 UI Components/BaseChart/1 Configuration/customizePoint.md
  api-reference/10 UI Components/BaseWidget/3 Methods/render().md
  api-reference/10 UI Components/Component/1 Configuration/onOptionChanged.md
  api-reference/10 UI Components/DataHelperMixin/3 Methods/getDataSource().md
  api-reference/10 UI Components/GridBase/1 Configuration/editing/mode.md
  api-reference/10 UI Components/GridBase/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/GridBase/1 Configuration/searchPanel/searchPanel.md
  api-reference/10 UI Components/GridBase/1 Configuration/selection/mode.md
  api-reference/10 UI Components/GridBase/3 Methods/getCombinedFilter(returnDataField).md
  api-reference/10 UI Components/GridBase/3 Methods/updateDimensions().md
  api-reference/10 UI Components/Widget/3 Methods/repaint().md
  api-reference/10 UI Components/dxChart/1 Configuration/commonPaneSettings/backgroundColor.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/editing/mode.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/masterDetail/template.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onCellHoverChanged.md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Remote/Remote.md
  api-reference/10 UI Components/dxForm/1 Configuration/onFieldDataChanged.md
  api-reference/10 UI Components/dxForm/1 Configuration/validationGroup.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorType.md
  api-reference/10 UI Components/dxList/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxMap/1 Configuration/markers/markers.md
  api-reference/10 UI Components/dxMap/1 Configuration/onReady.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/views.md
  api-reference/10 UI Components/dxSortable/dxSortable.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/onInput.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/onKeyDown.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/dataStructure.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/selection/recursive.md
  api-reference/10 UI Components/dxValidator/1 Configuration/validationGroup.md
  api-reference/10 UI Components/zz CSS Classes/CSS Classes.md
  api-reference/30 Data Layer/DataSource/3 Methods/loadOptions().md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/calculateCustomSummary.md
  api-reference/30 Data Layer/Store/3 Methods/push(changes).md
  api-reference/50 Common/utils/validationEngine/validateGroup(group).md
  api-reference/_hidden/GridBaseColumn/lookup/lookup.md
  concepts/05 UI Components/DataGrid/15 Columns/10 Column Types/4 Command Columns/05 Configure a Command Column.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/50 Popup Mode.md
  concepts/05 UI Components/Map/00 Overview.md
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/40 Angular Components/50 Components Testing/00 Components Testing.md
  concepts/50 React Components/60 Components Testing/00 Components Testing.md
  concepts/58 jQuery Components/30 Components Testing/00 Components Testing.md
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
  concepts/70 Data Binding/5 Data Layer/6 Query Concept.md
  concepts/70 Data Binding/51 Data Source Examples/2 OData/0 Using ODataContext.md
Labels: 23_1

#5181 Format: add note about different tools
  api-reference/50 Common/Object Structures/format/format.md
Labels: 22_2

#5183 Format: add note about different tools (#5181)
  api-reference/50 Common/Object Structures/format/format.md
Labels: cherry-pick, 22_1

#5184 Format: add note about different tools (#5181)
  api-reference/50 Common/Object Structures/format/format.md
Labels: cherry-pick, 23_1

#5188 Toolbar: fix `menuItemTemplate` code snippets
  api-reference/_hidden/dxToolbarItem/menuItemTemplate.md
Labels: 22_2

#5189 Toolbar: fix `menuItemTemplate` code snippets (#5188)
  api-reference/_hidden/dxToolbarItem/menuItemTemplate.md
Labels: cherry-pick, 22_1

#5190 Toolbar: fix `menuItemTemplate` code snippets (#5188)
  api-reference/_hidden/dxToolbarItem/menuItemTemplate.md
Labels: cherry-pick, 23_1

#5191 TreeList: update comparison information (T890180)
  api-reference/10 UI Components/GridBase/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxTreeList/3 Methods/navigateToRow(key).md
Labels: 22_2

#5193 TreeList: update comparison information (T890180) (#5191)
  api-reference/10 UI Components/GridBase/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxTreeList/3 Methods/navigateToRow(key).md
Labels: cherry-pick, 23_1

#5192 Update treelist odata comparison 22 1
  api-reference/10 UI Components/GridBase/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxTreeList/3 Methods/navigateToRow(key).md
Labels: cherry-pick, 22_1

#5199 Security Considerations: update article
  concepts/Common/Security Considerations/20 HTML Encoding/00 HTML Encoding.md
  concepts/Common/Security Considerations/20 HTML Encoding/10 Encode User Input.md
  concepts/Common/Security Considerations/20 HTML Encoding/20 Encode Template Data.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/0 Potentially Vulnerable API.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/customizeTooltip.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/encodeHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/html.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/markers[].tooltip.text.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/noDataText.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/05 CSV Injection.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/20 ExcelJS CSP Threats.md
  concepts/Common/Security Considerations/40 Content Security Policy/00 Content Security Policy.md
  concepts/Common/Security Considerations/40 Content Security Policy/05 Common CSP Directives.md
  concepts/Common/Security Considerations/40 Content Security Policy/15 CSP Source List.md
  concepts/Common/Security Considerations/Security Considerations.md
Labels: 23_1

#5200 DateRangeBox: fix buttons
  api-reference/10 UI Components/dxDateRangeBox/dxDateRangeBox.md
Labels: 23_1

#5201 DateRangeBox: update links
  api-reference/10 UI Components/dxDateRangeBox/dxDateRangeBox.md
Labels: 23_1

#5198 Popup: update Getting Started tutorial
  applications/GettingStartedWith/Popup/index.js
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/7 Add Scrolling.md
Labels: 23_1

#5168 HtmlEditor: add Overview topic + small fixes
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/value.md
  applications/GettingStartedWith/HtmlEditor/index.html
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/30 Work with Tables.md
  concepts/05 UI Components/HtmlEditor/05 Overview.md
Labels: 23_1

#5204 Fix links in troubleshooting
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/25 Eliminate Side Effects.md
Labels: 22_2

#5205 Fix links in troubleshooting (#5204)
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/10 Gray Boxes Appear After Data Loading/25 Eliminate Side Effects.md
Labels: cherry-pick, 23_1

#5171 Update 2 Client-Side Data Processing.md
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/2 Client-Side Data Processing.md
Labels: 22_2

#5207 Fix TextEditorButton renaming
  api-reference/10 UI Components/Errors and Warnings/E1054.md
  api-reference/10 UI Components/Errors and Warnings/E1055.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/buttons/buttons.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/buttons/buttons.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/buttons/buttons.md
  api-reference/10 UI Components/dxTextEditor/3 Methods/getButton(name).md
  api-reference/_hidden/TextEditorButton/TextEditorButton.md
Labels: 22_2

#5209 Add examples into documentation
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/70 Additional Configuration for Vite/00 Additional Configuration for Vite.md
  concepts/70 Data Binding/00 Specify a Data Source/30 Web API, PHP, MongoDB.md
  concepts/Common/Modularity/01 Link Modules/10 Use Webpack.md
  concepts/Common/Modularity/01 Link Modules/20 Use jspm.md
  concepts/Common/Modularity/01 Link Modules/30 Use RequireJS.md
Labels: 23_1

#5210 PivotGrid: update the onCellPrepared property (T1171567)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/onCellPrepared.md
Labels: 22_2

#5215 PivotGrid: update the onCellPrepared property (T1171567) (#5210)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/onCellPrepared.md
Labels: cherry-pick, 22_1

#5216 PivotGrid: update the onCellPrepared property (T1171567) (#5210)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/onCellPrepared.md
Labels: cherry-pick, 23_1

#5208 HtmlEditor: add image formats + note
  api-reference/_hidden/dxHtmlEditorImageUpload/fileUploadMode.md
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
Labels: 23_1

#5217 HtmlEditor: add a note to `marker`
  api-reference/_hidden/dxHtmlEditorMention/marker.md
Labels: 23_1

#5185 Chart: describe `label.alignment`
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/alignment.md
Labels: 22_2

#5221 Event types: add descriptions
  api-reference/40 Common Types/13 events/Cancelable/cancel.md
  api-reference/40 Common Types/13 events/ChangedOptionInfo/fullName.md
  api-reference/40 Common Types/13 events/ChangedOptionInfo/name.md
  api-reference/40 Common Types/13 events/ChangedOptionInfo/previousValue.md
  api-reference/40 Common Types/13 events/ChangedOptionInfo/value.md
  api-reference/40 Common Types/13 events/ItemInfo/ItemInfo.md
  api-reference/40 Common Types/13 events/ItemInfo/itemData.md
  api-reference/40 Common Types/13 events/ItemInfo/itemElement.md
  api-reference/40 Common Types/13 events/ItemInfo/itemIndex.md
  api-reference/40 Common Types/13 events/NativeEventInfo/event.md
Labels: 23_1

#5220 Angular: update Angular Change Detection Specifics section
  concepts/40 Angular Components/20 Component Configuration Syntax/85 Angular Change Detection Specifics.md
Labels: 22_2

#5231 Angular: update Angular Change Detection Specifics section (#5220)
  concepts/40 Angular Components/20 Component Configuration Syntax/85 Angular Change Detection Specifics.md
Labels: cherry-pick, 23_1

#5236 Theme: remove unnecassary info (T1173601)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
Labels: 23_1

#5237 Theme: remove unnecessary info (T1173601)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
Labels: cherry-pick, 22_2

#5238 Theme: remove unnecessary info (T1173601)
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme.md
Labels: cherry-pick, 23_2

#5229 Data Shaping: add a note about `getDataSource()`
  concepts/70 Data Binding/03 Update Data/05 DevExtreme DataSource/02 Data Shaping.md
Labels: 23_1

#5240 Data Shaping: add a note about `getDataSource()` (#5229)
  concepts/70 Data Binding/03 Update Data/05 DevExtreme DataSource/02 Data Shaping.md
Labels: cherry-pick, 22_2

#5241 Data Shaping: add a note about `getDataSource()` (#5229)
  concepts/70 Data Binding/03 Update Data/05 DevExtreme DataSource/02 Data Shaping.md
Labels: cherry-pick, 23_2

#5239 DateBox: update Sync 2 DateBoxes section (T1173084)
  concepts/05 UI Components/DateBox/16 Synchronize Two DateBoxes.md
Labels: 23_1

#5246 DateBox: update Sync 2 DateBoxes section (T1173084)
  concepts/05 UI Components/DateBox/16 Synchronize Two DateBoxes.md
Labels: cherry-pick, 23_2

#5242 Errors and Warnings: describe the W1022 warning
  api-reference/10 UI Components/Errors and Warnings/W1022.md
Labels: 22_2

#5247 Errors and Warnings: describe the W1022 warning (#5242)
  api-reference/10 UI Components/Errors and Warnings/W1022.md
Labels: cherry-pick, 23_1

#5248 Errors and Warnings: describe the W1022 warning (#5242)
  api-reference/10 UI Components/Errors and Warnings/W1022.md
Labels: cherry-pick, 23_2

#5230 DataGrid: add note to `filterRow`
  api-reference/10 UI Components/GridBase/1 Configuration/filterRow/filterRow.md
Labels: 23_1

#5249 DataGrid: add note to `filterRow` (#5230)
  api-reference/10 UI Components/GridBase/1 Configuration/filterRow/filterRow.md
Labels: cherry-pick, 22_2

#5250 DataGrid: add note to `filterRow` (#5230)
  api-reference/10 UI Components/GridBase/1 Configuration/filterRow/filterRow.md
Labels: cherry-pick, 23_2

#5251 Update `dateSerializationFormat`
  api-reference/10 UI Components/dxCalendar/1 Configuration/dateSerializationFormat.md
  includes/uiwidgets-ref-dateSerializationFormat.md
Labels: 23_1

#5252 Update `dateSerializationFormat` (#5251)
  api-reference/10 UI Components/dxCalendar/1 Configuration/dateSerializationFormat.md
  includes/uiwidgets-ref-dateSerializationFormat.md
Labels: cherry-pick, 22_2

#5253 Update `dateSerializationFormat` (#5251)
  api-reference/10 UI Components/dxCalendar/1 Configuration/dateSerializationFormat.md
  includes/uiwidgets-ref-dateSerializationFormat.md
Labels: cherry-pick, 23_2

#5254 DataGrid: update Column Fixing topic (T1173798)
  concepts/05 UI Components/DataGrid/15 Columns/30 Column Fixing.md
Labels: 22_2

#5258 DataGrid: update Column Fixing topic (T1173798) (#5254)
  concepts/05 UI Components/DataGrid/15 Columns/30 Column Fixing.md
Labels: cherry-pick, 23_1

#5259 DataGrid: update Column Fixing topic (T1173798)
  concepts/05 UI Components/DataGrid/15 Columns/30 Column Fixing.md
Labels: cherry-pick, 23_2

#5264 Update 'Switch Between Themes at Runtime' guide
  concepts/60 Themes and Styles/05 Predefined Themes/55 Color Swatches.md
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/7 Switch Between Color Swatches.md
Labels: 23_1

#5270 Update 'Switch Between Themes at Runtime' guide (#5264)
  concepts/60 Themes and Styles/05 Predefined Themes/55 Color Swatches.md
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/7 Switch Between Color Swatches.md
Labels: cherry-pick, 23_2

#5260 DataGrid: add Filtering Columns Bound to Collection section
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/10 Client-Side Filtering.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/20 Server-Side Filtering.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/Filtering Columns Bound to Collection.md
Labels: 22_2

#5271 DataGrid: add Filtering Columns Bound to Collection section (#5260)
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/10 Client-Side Filtering.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/20 Server-Side Filtering.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/Filtering Columns Bound to Collection.md
Labels: cherry-pick, 23_1

#5272 DataGrid: add Filtering Columns Bound to Collection section (#5260)
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/10 Client-Side Filtering.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/20 Server-Side Filtering.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/Filtering Columns Bound to Collection.md
Labels: cherry-pick, 23_2

#5273 Chart: update `wholeRange`
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/wholeRange/wholeRange.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/wholeRange/wholeRange.md
Labels: 23_1

#5274 Chart: update `wholeRange` (#5273)
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/wholeRange/wholeRange.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/wholeRange/wholeRange.md
Labels: cherry-pick, 22_2

#5275 Chart: update `wholeRange` (#5273)
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/wholeRange/wholeRange.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/wholeRange/wholeRange.md
Labels: cherry-pick, 23_2

#5280 DataGrid: update the topLeftCell property (T1175367)
  api-reference/50 Common/Object Structures/ExcelExportDataGridProps/topLeftCell.md
Labels: 23_1

#5281 DataGrid: update the topLeftCell property (T1175367) (#5280)
  api-reference/50 Common/Object Structures/ExcelExportDataGridProps/topLeftCell.md
Labels: cherry-pick, 23_2

#5282 DataGrid: update the topLeftCell property (T1175367) (#5280)
  api-reference/50 Common/Object Structures/ExcelExportDataGridProps/topLeftCell.md
Labels: cherry-pick, 22_2

#5283 Form: add a note to `validationGroup`
  api-reference/10 UI Components/dxForm/1 Configuration/validationGroup.md
Labels: 23_1

#5284 Form: add a note to `validationGroup` (#5283)
  api-reference/10 UI Components/dxForm/1 Configuration/validationGroup.md
Labels: cherry-pick, 22_2

#5285 Form: add a note to `validationGroup` (#5283)
  api-reference/10 UI Components/dxForm/1 Configuration/validationGroup.md
Labels: cherry-pick, 23_2
