Repository DevExpress/devextreme-documentation, pull requests merged in 2023-01, with the labels that each got.

#4488 Form: remove unnecessary View Demo button (template)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
Labels: 22_2

#4490 Form: remove unnecessary View Demo button (template)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
Labels: cherry-pick, 23_1

#4489 Form: remove unnecessary View Demo button (template)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
Labels: cherry-pick, 22_1

#4475 Scheduler: update code snippets
  concepts/05 UI Components/Scheduler/040 Resources/040 Customize Resource Headers.md
Labels: 22_2

#4495 Scheduler: change snippets structure
  concepts/05 UI Components/Scheduler/040 Resources/040 Customize Resource Headers.md
Labels: 22_2

#4493 Scheduler: update code snippets (#4475)
  concepts/05 UI Components/Scheduler/040 Resources/040 Customize Resource Headers.md
Labels: cherry-pick, 23_1

#4485 DataGrid: replace the deprecated toPromise method
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
Labels: 22_2

#4496 DataGrid: replace the deprecated toPromise method (#4485)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
Labels: cherry-pick, 22_1

#4497 DataGrid: replace the deprecated toPromise method (#4485)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/customSave.md
Labels: cherry-pick, 23_1

#4491 DataGrid/TreeList: add Note to the autoNavigateToFocusedRow property
  api-reference/10 UI Components/GridBase/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
Labels: 22_2

#4502 DataGrid/TreeList: add Note to the autoNavigateToFocusedRow property …
  api-reference/10 UI Components/GridBase/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
Labels: cherry-pick, 22_1

#4503 DataGrid/TreeList: add Note to the autoNavigateToFocusedRow property …
  api-reference/10 UI Components/GridBase/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
Labels: cherry-pick, 23_1

#4500 HtmlEditor: add Quill note
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
Labels: 22_2

#4509 HtmlEditor: add Quill note (#4500)
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
Labels: cherry-pick, 23_1

#4508 HtmlEditor: add Quill note
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
Labels: cherry-pick, 22_1

#4455 DataGrid: add Disable Editing section
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/10 Disable Editing.md
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/20 Column.md
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/30 Row.md
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/40 Cell.md
Labels: 22_1

#4511 DataGrid: add Disable Editing section (#4455)
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/10 Disable Editing.md
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/20 Column.md
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/30 Row.md
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/40 Cell.md
Labels: cherry-pick, 23_1

#4510 DataGrid: add Disable Editing section (#4455)
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/10 Disable Editing.md
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/20 Column.md
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/30 Row.md
  concepts/05 UI Components/DataGrid/20 Editing/45 Disable Editing/40 Cell.md
Labels: cherry-pick, 22_2

#4504 Toolbar: add Note to repaint method
  api-reference/10 UI Components/Widget/3 Methods/repaint().md
Labels: 22_2

#4512 Toolbar: add Note to repaint method (#4504)
  api-reference/10 UI Components/Widget/3 Methods/repaint().md
Labels: cherry-pick, 22_1

#4513 Toolbar: add Note to repaint method (#4504)
  api-reference/10 UI Components/Widget/3 Methods/repaint().md
Labels: cherry-pick, 23_1

#4481 Troubleshooting: A drop-down editor does not show data
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/00 A Drop-Down Editor Does Not Show Data.md
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/05 Key and ValueExpr Should Match.md
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/10 DataField and ValueExpr Should Store The Same Keys.md
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/15 AspNet.Data.createStore() Method Specifics.md
  images/Troubleshooting/datagrid-lookup-network-request-parameters.png
Labels: 22_1

#4514 Troubleshooting: A drop-down editor does not show data (#4481)
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/00 A Drop-Down Editor Does Not Show Data.md
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/05 Key and ValueExpr Should Match.md
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/10 DataField and ValueExpr Should Store The Same Keys.md
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/15 AspNet.Data.createStore() Method Specifics.md
  images/Troubleshooting/datagrid-lookup-network-request-parameters.png
Labels: cherry-pick, 22_2

#4515 Troubleshooting: A drop-down editor does not show data (#4481)
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/00 A Drop-Down Editor Does Not Show Data.md
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/05 Key and ValueExpr Should Match.md
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/10 DataField and ValueExpr Should Store The Same Keys.md
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/15 AspNet.Data.createStore() Method Specifics.md
  images/Troubleshooting/datagrid-lookup-network-request-parameters.png
Labels: cherry-pick, 23_1

#4486 Troubleshooting: Bootstrap modals issues
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 3rd-Party Frameworks Issues.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 Bootstrap/00 Bootstrap.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 Bootstrap/05 Modals.md
Labels: 22_2

#4519 Troubleshooting: Bootstrap modals issues (#4486)
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 3rd-Party Frameworks Issues.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 Bootstrap/00 Bootstrap.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 Bootstrap/05 Modals.md
Labels: cherry-pick, 22_1

#4520 Troubleshooting: Bootstrap modals issues (#4486)
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 3rd-Party Frameworks Issues.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 Bootstrap/00 Bootstrap.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 Bootstrap/05 Modals.md
Labels: cherry-pick, 23_1

#4521 Rename GlobalConfig options
  api-reference/10 UI Components/Errors and Warnings/W1014.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/position.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/stylingMode.md
  api-reference/10 UI Components/dxSpeedDialAction/dxSpeedDialAction.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/stylingMode.md
  api-reference/30 Data Layer/ODataContext/1 Configuration/filterToLower.md
  api-reference/30 Data Layer/ODataStore/1 Configuration/filterToLower.md
  api-reference/50 Common/Object Structures/format/currency.md
  api-reference/50 Common/Object Structures/format/type.md
  api-reference/50 Common/Object Structures/format/useCurrencyAccountingStyle.md
  api-reference/50 Common/Object Structures/globalConfig/decimalSeparator.md
  api-reference/50 Common/Object Structures/globalConfig/defaultCurrency.md
  api-reference/50 Common/Object Structures/globalConfig/defaultUseCurrencyAccountingStyle.md
  api-reference/50 Common/Object Structures/globalConfig/editorStylingMode.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/closeIcon.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/direction.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/floatingActionButtonConfig.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/icon.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/label.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/maxSpeedDialActionCount.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/position.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/shading.md
  api-reference/50 Common/Object Structures/globalConfig/forceIsoDateParsing.md
  api-reference/50 Common/Object Structures/globalConfig/globalConfig.md
  api-reference/50 Common/Object Structures/globalConfig/oDataFilterToLower.md
  api-reference/50 Common/Object Structures/globalConfig/rtlEnabled.md
  api-reference/50 Common/Object Structures/globalConfig/serverDecimalSeparator.md
  api-reference/50 Common/Object Structures/globalConfig/thousandsSeparator.md
  api-reference/50 Common/Object Structures/globalConfig/useJQuery.md
  api-reference/50 Common/utils/config().md
  api-reference/50 Common/utils/ui/repaintFloatingActionButton().md
  api-reference/NewTopics/GlobalConfig/GlobalConfig.md
  api-reference/NewTopics/GlobalConfig/decimalSeparator.md
  api-reference/NewTopics/GlobalConfig/defaultCurrency.md
  api-reference/NewTopics/GlobalConfig/defaultUseCurrencyAccountingStyle.md
  api-reference/NewTopics/GlobalConfig/editorStylingMode.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/closeIcon.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/direction.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/floatingActionButtonConfig.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/icon.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/label.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/maxSpeedDialActionCount.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/position.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/shading.md
  api-reference/NewTopics/GlobalConfig/forceIsoDateParsing.md
  api-reference/NewTopics/GlobalConfig/oDataFilterToLower.md
  api-reference/NewTopics/GlobalConfig/rtlEnabled.md
  api-reference/NewTopics/GlobalConfig/serverDecimalSeparator.md
  api-reference/NewTopics/GlobalConfig/thousandsSeparator.md
  api-reference/NewTopics/GlobalConfig/useJQuery.md
  api-reference/NewTopics/GlobalConfig/useLegacyStoreResult.md
  api-reference/NewTopics/GlobalConfig/useLegacyVisibleIndex.md
  api-reference/_hidden/useLegacyStoreResult.md
  api-reference/_hidden/useLegacyVisibleIndex.md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/10 Single Action.md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/20 Multiple Actions (Speed Dial).md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/30 Handle Screen Transitions.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/05 Using Intl.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/1 Deprecated Properties and Methods.md
  metadata/modules-meta.json
Labels: 22_2

#4522 Rename GlobalConfig options (#4521)
  api-reference/10 UI Components/Errors and Warnings/W1014.md
  api-reference/10 UI Components/dxDrawer/1 Configuration/position.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/stylingMode.md
  api-reference/10 UI Components/dxSpeedDialAction/dxSpeedDialAction.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/stylingMode.md
  api-reference/30 Data Layer/ODataContext/1 Configuration/filterToLower.md
  api-reference/30 Data Layer/ODataStore/1 Configuration/filterToLower.md
  api-reference/50 Common/Object Structures/format/currency.md
  api-reference/50 Common/Object Structures/format/type.md
  api-reference/50 Common/Object Structures/format/useCurrencyAccountingStyle.md
  api-reference/50 Common/Object Structures/globalConfig/decimalSeparator.md
  api-reference/50 Common/Object Structures/globalConfig/defaultCurrency.md
  api-reference/50 Common/Object Structures/globalConfig/defaultUseCurrencyAccountingStyle.md
  api-reference/50 Common/Object Structures/globalConfig/editorStylingMode.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/closeIcon.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/direction.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/floatingActionButtonConfig.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/icon.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/label.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/maxSpeedDialActionCount.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/position.md
  api-reference/50 Common/Object Structures/globalConfig/floatingActionButtonConfig/shading.md
  api-reference/50 Common/Object Structures/globalConfig/forceIsoDateParsing.md
  api-reference/50 Common/Object Structures/globalConfig/globalConfig.md
  api-reference/50 Common/Object Structures/globalConfig/oDataFilterToLower.md
  api-reference/50 Common/Object Structures/globalConfig/rtlEnabled.md
  api-reference/50 Common/Object Structures/globalConfig/serverDecimalSeparator.md
  api-reference/50 Common/Object Structures/globalConfig/thousandsSeparator.md
  api-reference/50 Common/Object Structures/globalConfig/useJQuery.md
  api-reference/50 Common/utils/config().md
  api-reference/50 Common/utils/ui/repaintFloatingActionButton().md
  api-reference/NewTopics/GlobalConfig/GlobalConfig.md
  api-reference/NewTopics/GlobalConfig/decimalSeparator.md
  api-reference/NewTopics/GlobalConfig/defaultCurrency.md
  api-reference/NewTopics/GlobalConfig/defaultUseCurrencyAccountingStyle.md
  api-reference/NewTopics/GlobalConfig/editorStylingMode.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/closeIcon.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/direction.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/floatingActionButtonConfig.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/icon.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/label.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/maxSpeedDialActionCount.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/position.md
  api-reference/NewTopics/GlobalConfig/floatingActionButtonConfig/shading.md
  api-reference/NewTopics/GlobalConfig/forceIsoDateParsing.md
  api-reference/NewTopics/GlobalConfig/oDataFilterToLower.md
  api-reference/NewTopics/GlobalConfig/rtlEnabled.md
  api-reference/NewTopics/GlobalConfig/serverDecimalSeparator.md
  api-reference/NewTopics/GlobalConfig/thousandsSeparator.md
  api-reference/NewTopics/GlobalConfig/useJQuery.md
  api-reference/NewTopics/GlobalConfig/useLegacyStoreResult.md
  api-reference/NewTopics/GlobalConfig/useLegacyVisibleIndex.md
  api-reference/_hidden/useLegacyStoreResult.md
  api-reference/_hidden/useLegacyVisibleIndex.md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/10 Single Action.md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/20 Multiple Actions (Speed Dial).md
  concepts/05 UI Components/Floating Action Button/00 Getting Started with Floating Action Button/30 Handle Screen Transitions.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/05 Using Intl.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/1 Deprecated Properties and Methods.md
  metadata/modules-meta.json
Labels: cherry-pick, 23_1

#4523 Fix Docgen
  .github/workflows/docgen.yml
Labels: 21_2

#4525 Fix DocGen
  .github/workflows/docgen.yml
Labels: 21_1, cherry-pick

#4531 Enable DocGen
  .github/workflows/docgen.yml
  .github/workflows/nodejs.yml
Labels: 20_2

#4536 Fix GlobalConfig
  api-reference/50 Common/Object Structures/GlobalConfig/GlobalConfig.md
  api-reference/50 Common/Object Structures/GlobalConfig/decimalSeparator.md
  api-reference/50 Common/Object Structures/GlobalConfig/defaultCurrency.md
  api-reference/50 Common/Object Structures/GlobalConfig/defaultUseCurrencyAccountingStyle.md
  api-reference/50 Common/Object Structures/GlobalConfig/editorStylingMode.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/closeIcon.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/direction.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/floatingActionButtonConfig.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/icon.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/label.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/maxSpeedDialActionCount.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/position.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/shading.md
  api-reference/50 Common/Object Structures/GlobalConfig/forceIsoDateParsing.md
  api-reference/50 Common/Object Structures/GlobalConfig/oDataFilterToLower.md
  api-reference/50 Common/Object Structures/GlobalConfig/rtlEnabled.md
  api-reference/50 Common/Object Structures/GlobalConfig/serverDecimalSeparator.md
  api-reference/50 Common/Object Structures/GlobalConfig/thousandsSeparator.md
  api-reference/50 Common/Object Structures/GlobalConfig/useJQuery.md
Labels: 23_1

#4537 TreeList: update the Customize Edit Column code snippets
  concepts/05 UI Components/TreeList/10 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/1 Customize Buttons.md
Labels: 22_2

#4545 TreeList: update the Customize Edit Column code snippets (#4537)
  concepts/05 UI Components/TreeList/10 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/1 Customize Buttons.md
Labels: cherry-pick, 22_1

#4546 TreeList: update the Customize Edit Column code snippets (#4537)
  concepts/05 UI Components/TreeList/10 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/1 Customize Buttons.md
Labels: cherry-pick, 23_1

#4538 Notify: update code snippet
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: 22_2

#4548 Notify: update code snippet (#4538)
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: cherry-pick, 23_1

#4547 Notify: update code snippet (#4538)
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: cherry-pick, 22_1

#4551 Add encodeExecutableContent.md
  api-reference/_hidden/ExcelExportBaseProps/encodeExecutableContent.md
Labels: 20_2

#4552 Add encodeExecutableContent.md
  .github/workflows/nodejs.yml
  api-reference/50 Common/Object Structures/ExportDataGridProps/encodeExecutableContent.md
Labels: cherry-pick, 20_1

#4556 List: update Sortable code snippet (T1140263)
  api-reference/10 UI Components/dxSortable/1 Configuration/dragTemplate.md
Labels: 22_2

#4558 List: update Sortable code snippet (T1140263)
  api-reference/10 UI Components/dxSortable/1 Configuration/dragTemplate.md
Labels: cherry-pick, 23_1

#4557 List: update Sortable code snippet (T1140263) (#4556)
  api-reference/10 UI Components/dxSortable/1 Configuration/dragTemplate.md
Labels: cherry-pick, 22_1

#4550 DataGrid/PivotGrid: add encodeExecutableContent description
  api-reference/_hidden/ExcelExportBaseProps/encodeExecutableContent.md
Labels: 22_2

#4560 DataGrid/PivotGrid: add encodeExecutableContent description (#4550)
  api-reference/_hidden/ExcelExportBaseProps/encodeExecutableContent.md
Labels: cherry-pick, 22_1

#4561 DataGrid/PivotGrid: add encodeExecutableContent description (#4550)
  api-reference/_hidden/ExcelExportBaseProps/encodeExecutableContent.md
Labels: cherry-pick, 21_2

#4563 DataGrid/PivotGrid: add encodeExecutableContent description (#4550)
  api-reference/_hidden/ExcelExportBaseProps/encodeExecutableContent.md
Labels: 20_2, cherry-pick

#4564 DataGrid/PivotGrid: add encodeExecutableContent description (#4550)
  api-reference/50 Common/Object Structures/ExportDataGridProps/encodeExecutableContent.md
Labels: cherry-pick, 20_1

#4565 DataGrid: update the LoadPanel.shading property (T1140557)
  api-reference/10 UI Components/GridBase/1 Configuration/loadPanel/shading.md
Labels: 22_2

#4567 DataGrid: update the LoadPanel.shading property (T1140557) (#4565)
  api-reference/10 UI Components/GridBase/1 Configuration/loadPanel/shading.md
Labels: cherry-pick, 23_1

#4566 DataGrid: update the LoadPanel.shading property (T1140557) (#4565)
  api-reference/10 UI Components/GridBase/1 Configuration/loadPanel/shading.md
Labels: cherry-pick, 22_1

#4569 RangeSelector: add valueChangeMode description
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/behavior/callValueChanged.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/behavior/valueChangeMode.md
Labels: 23_1

#4572 DataGrid: update "Dynamically Change Form Item Properties in the Editing State" code snippet (T1141266)
  concepts/05 UI Components/DataGrid/99 How To/Dynamically Change Form Item Properties in the Editing State.md
Labels: 22_2

#4574 DataGrid: update "Dynamically Change Form Item Properties in the Editing State" code snippet (T1141266)
  concepts/05 UI Components/DataGrid/99 How To/Dynamically Change Form Item Properties in the Editing State.md
Labels: cherry-pick, 23_1

#4573 DataGrid: update "Dynamically Change Form Item Properties in the Editing State" code snippet (T1141266)
  concepts/05 UI Components/DataGrid/99 How To/Dynamically Change Form Item Properties in the Editing State.md
Labels: cherry-pick, 22_1

#4575 DataGrid/PivotGrid: update onExporting deprecated options
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onExporting.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/onExporting.md
  api-reference/50 Common/Object Structures/ExcelExportDataGridProps/customizeCell.md
  api-reference/50 Common/Object Structures/ExcelExportPivotGridProps/customizeCell.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/excelExporter/exportPivotGrid(options).md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
Labels: 23_1

#4570 Security Consideration: add Export Vulnerabilities section
  concepts/Common/Security Considerations/30 Export Vulnerabilities/00 Export Vulnerabilities.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/05 CSV Injection.md
Labels: 22_2

#4582 DataGrid/PivotGrid: remove deprecated e.cancel option
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/00 Export Vulnerabilities.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/05 CSV Injection.md
  includes/tutorials-export-data-to-excel.md
Labels: cherry-pick, 23_1

#4577 Security Consideration: add Export Vulnerabilities section (#4570)
  concepts/Common/Security Considerations/30 Export Vulnerabilities/00 Export Vulnerabilities.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/05 CSV Injection.md
Labels: cherry-pick, 21_2

#4578 Security Consideration: add Export Vulnerabilities section (#4570)
  concepts/Common/Security Considerations/30 Export Vulnerabilities/00 Export Vulnerabilities.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/05 CSV Injection.md
Labels: 21_1, cherry-pick

#4579 Security Consideration: add Export Vulnerabilities section (#4570)
  concepts/Common/Security Considerations/30 Export Vulnerabilities/00 Export Vulnerabilities.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/05 CSV Injection.md
Labels: 20_2, cherry-pick

#4581 Security Consideration: add Export Vulnerabilities section (#4570)
  concepts/Common/Security Considerations/30 Export Vulnerabilities/00 Export Vulnerabilities.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/05 CSV Injection.md
Labels: cherry-pick, 20_1

#4590 DataGrid/PivotGrid Export: add CSV vulnerabilities note
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
  includes/uiwidgets-grids-export-csv.md
Labels: 22_2

#4600 DataGrid/PivotGrid Export: add CSV vulnerabilities note (#4590)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
  includes/uiwidgets-grids-export-csv.md
Labels: cherry-pick, 23_1

#4596 DataGrid/PivotGrid Export: add CSV vulnerabilities note (#4590)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
  includes/uiwidgets-grids-export-csv.md
Labels: cherry-pick, 22_1

#4597 DataGrid/PivotGrid Export: add CSV vulnerabilities note (#4590)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  includes/uiwidgets-grids-export-csv.md
Labels: cherry-pick, 21_2

#4598 DataGrid/PivotGrid Export: add CSV vulnerabilities note (#4590)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  includes/uiwidgets-grids-export-csv.md
Labels: 21_1, cherry-pick

#4599 DataGrid/PivotGrid Export: add CSV vulnerabilities note
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  includes/uiwidgets-grids-export-csv.md
Labels: 20_2, cherry-pick

#4501 DataGrid: customize cell/row appearance
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onCellPrepared.md
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/2 Customize Cell Appearance.md
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/2 Customize the Appearance.md
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/3 Customize Row Apperance.md
  images/DataGrid/customize-appearance/column-cellTemplate.png
  images/DataGrid/customize-appearance/onCellPrepared.png
  images/DataGrid/customize-appearance/onRowPrepared.png
Labels: 22_2

#4616 DataGrid: customize cell/row appearance (#4501)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onCellPrepared.md
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/2 Customize Cell Appearance.md
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/2 Customize the Appearance.md
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/3 Customize Row Apperance.md
  images/DataGrid/customize-appearance/column-cellTemplate.png
  images/DataGrid/customize-appearance/onCellPrepared.png
  images/DataGrid/customize-appearance/onRowPrepared.png
Labels: cherry-pick, 22_1

#4617 DataGrid: customize cell/row appearance (#4501)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onCellPrepared.md
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/2 Customize Cell Appearance.md
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/2 Customize the Appearance.md
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/3 Customize Row Apperance.md
  images/DataGrid/customize-appearance/column-cellTemplate.png
  images/DataGrid/customize-appearance/onCellPrepared.png
  images/DataGrid/customize-appearance/onRowPrepared.png
Labels: cherry-pick, 23_1
