Repository DevExpress/devextreme-documentation, pull requests merged in 2023-10, with the labels that each got.

#5625 DataSource: update langParams
  api-reference/30 Data Layer/DataSource/1 Configuration/langParams.md
Labels: 23_1

#5627 Form: update simpleItem.editorType
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorType.md
Labels: 23_1

#5629 Form: update simpleItem.editorType (#5627)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorType.md
Labels: cherry-pick, 23_2

#5628 Form: update simpleItem.editorType (#5627)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorType.md
Labels: cherry-pick, 22_2

#5630 TreeList: add a note to scrolling.mode
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/mode.md
Labels: 23_1

#5631 TreeList: add a note to scrolling.mode (#5630)
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/mode.md
Labels: cherry-pick, 22_2

#5632 TreeList: add a note to scrolling.mode (#5630)
  api-reference/10 UI Components/dxTreeList/1 Configuration/scrolling/mode.md
Labels: cherry-pick, 23_2

#5637 Text editors: add a note about masking
  api-reference/10 UI Components/DateBoxBase/1 Configuration/useMaskBehavior.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/useMaskBehavior.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/mask.md
Labels: 23_1

#5638 Text editors: add a note about masking (#5637)
  api-reference/10 UI Components/dxDateBox/1 Configuration/useMaskBehavior.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/mask.md
Labels: cherry-pick, 22_2

#5639 Text editors: add a note about masking (#5637)
  api-reference/10 UI Components/DateBoxBase/1 Configuration/useMaskBehavior.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/useMaskBehavior.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/mask.md
Labels: cherry-pick, 23_2

#5640 Themes: wrap code
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/5 With Page Reload.md
Labels: 23_1

#5641 Themes: wrap code (#5640)
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/5 With Page Reload.md
Labels: cherry-pick, 23_2

#5643 Editors/Form: add restrictions to isDirty
  api-reference/10 UI Components/dxDateBox/1 Configuration/isDirty.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/isDirty.md
  api-reference/10 UI Components/dxForm/1 Configuration/isDirty.md
Labels: 23_2

#5644 HtmlEditor: add info to Overview
  concepts/05 UI Components/HtmlEditor/05 Overview.md
Labels: 23_1

#5645 HtmlEditor: add info to Overview (#5644)
  concepts/05 UI Components/HtmlEditor/05 Overview.md
Labels: cherry-pick, 23_2

#5646 PivotGridDataSource: fix code snippets
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/headerFilter/search/editorOptions.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/headerFilter/search/search.md
Labels: 23_1

#5647 PivotGridDataSource: fix code snippets (#5646)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/headerFilter/search/editorOptions.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/headerFilter/search/search.md
Labels: cherry-pick, 23_2

#5623 Troubleshooting: add A Request Error Occurs After Filtering or Search…
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/00 Overview.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/15 A Request Error Occurs After Filtering or Searching.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 Overview.md
Labels: 23_1

#5650 Troubleshooting: add A Request Error Occurs After Filtering or Search…
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/00 Overview.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/15 A Request Error Occurs After Filtering or Searching.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 Overview.md
Labels: cherry-pick, 22_2

#5651 Troubleshooting: add A Request Error Occurs After Filtering or Search…
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/00 Overview.md
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/15 A Request Error Occurs After Filtering or Searching.md
  concepts/80 Troubleshooting/30 3rd-Party Frameworks Issues/00 Overview.md
Labels: cherry-pick, 23_2

#5657 Describe license key errors
  api-reference/50 Common/utils/zz Errors and Warnings/W0019.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0020.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0021.md
Labels: 23_2

#5660 DataGrid: update Server-Side Filtering topic
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/20 Server-Side Filtering.md
Labels: 23_1

#5661 DataGrid: update Server-Side Filtering topic (#5660)
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/20 Server-Side Filtering.md
Labels: cherry-pick, 22_2

#5662 DataGrid: update Server-Side Filtering topic (#5660)
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/5 Filtering Columns Bound to Collection/20 Server-Side Filtering.md
Labels: cherry-pick, 23_2

#5666 Fix link
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/05 Change the Default Focused Cell.md
Labels: 23_1

#5667 Fix link (#5666)
  concepts/05 UI Components/DataGrid/70 Custom Keyboard Navigation/05 Change the Default Focused Cell.md
Labels: cherry-pick, 23_2

#5658 Angular: add TypeScript Support topic
  MenuConfig.xml
  concepts/40 Angular Components/70 TypeScript Support/00 TypeScript Support.md
  concepts/40 Angular Components/70 TypeScript Support/05 Component Specific Types.md
  concepts/40 Angular Components/70 TypeScript Support/10 Generics Usage.md
Labels: 23_2

#5672 Fix CSP link
  concepts/Common/Security Considerations/40 Content Security Policy/00 Content Security Policy.md
Labels: 23_1

#5673 Fix CSP link (#5672)
  concepts/Common/Security Considerations/40 Content Security Policy/00 Content Security Policy.md
Labels: cherry-pick, 23_2

#5668 Fix Subresource Integrity Hashes
  concepts/Common/Distribution Channels/05 CDN/10 Subresource Integrity Hashes.md
Labels: 23_2

#5669 Fix Subresource Integrity Hashes
  concepts/Common/Distribution Channels/05 CDN/10 Subresource Integrity Hashes.md
Labels: 23_1

#5683 Describe W0022 warning
  api-reference/50 Common/utils/zz Errors and Warnings/W0022.md
Labels: 23_2

#5684 DataSource: add note
  api-reference/30 Data Layer/DataSource/DataSource.md
Labels: 23_1

#5686 DataSource: add note (#5684)
  api-reference/30 Data Layer/DataSource/DataSource.md
Labels: cherry-pick, 22_2

#5687 DataSource: add note (#5684)
  api-reference/30 Data Layer/DataSource/DataSource.md
Labels: cherry-pick, 23_2

#5688 Notify: add note about position
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: 23_1

#5690 Notify: add note about position (#5688)
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: cherry-pick, 22_2

#5691 Notify: add note about position (#5688)
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: cherry-pick, 23_2

#5689 Popup: update Getting Started tutorial
  concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
Labels: 23_1

#5695 Popup: update Getting Started tutorial (#5689)
  concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
Labels: cherry-pick, 22_2

#5696 Popup: update Getting Started tutorial (#5689)
  concepts/05 UI Components/Popup/00 Getting Started with Popup/03 Add Content to the Popup.md
Labels: cherry-pick, 23_2

#5700 New features: add fixes after Elena's review
  api-reference/10 UI Components/Editor/3 Methods/clear().md
  api-reference/10 UI Components/Editor/3 Methods/reset().md
  api-reference/10 UI Components/Editor/3 Methods/reset(value).md
  api-reference/10 UI Components/dxCalendar/1 Configuration/value.md
  api-reference/10 UI Components/dxForm/3 Methods/clear().md
  api-reference/10 UI Components/dxForm/3 Methods/reset(editorsData).md
  api-reference/10 UI Components/dxScheduler/1 Configuration/recurrenceRuleExpr.md
  api-reference/10 UI Components/dxTabs/1 Configuration/stylingMode.md
Labels: 23_2

#5701 Tabs/TabPanel: update iconPosition
  api-reference/10 UI Components/dxTabs/1 Configuration/iconPosition.md
Labels: 23_2

#5702 Gantt/Diagram: add jquery tag to GS tutorials
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/00 Getting Started with Diagram.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/10 Add the Diagram Component to a Page.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/20 Load and Save Diagram Content.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/00 Getting Started with Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/10 Add the Gantt Component to a Page.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/20 Bind the Gantt to Data.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/30 Add Columns to the Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/40 Enable Editing.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/50 Preselect a Task.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/60 Handle the Selection Change Event.md
Labels: 23_1

#5703 Gantt/Diagram: add jquery tag to GS tutorials (#5702)
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/00 Getting Started with Diagram.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/10 Add the Diagram Component to a Page.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/20 Load and Save Diagram Content.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/00 Getting Started with Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/10 Add the Gantt Component to a Page.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/20 Bind the Gantt to Data.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/30 Add Columns to the Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/40 Enable Editing.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/50 Preselect a Task.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/60 Handle the Selection Change Event.md
Labels: cherry-pick, 22_2

#5704 Gantt/Diagram: add jquery tag to GS tutorials (#5702)
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/00 Getting Started with Diagram.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/10 Add the Diagram Component to a Page.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/20 Load and Save Diagram Content.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/00 Getting Started with Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/10 Add the Gantt Component to a Page.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/20 Bind the Gantt to Data.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/30 Add Columns to the Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/40 Enable Editing.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/50 Preselect a Task.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/60 Handle the Selection Change Event.md
Labels: cherry-pick, 23_2

#5706 DataGrid: update onRowClick code snippet
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onRowClick.md
Labels: 23_1

#5707 DataGrid: update onRowClick code snippet (#5706)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onRowClick.md
Labels: cherry-pick, 22_2

#5708 DataGrid: update onRowClick code snippet (#5706)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onRowClick.md
Labels: cherry-pick, 23_2

#5709 CDN Files: update topic
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
Labels: 23_1

#5710 CDN Files: update topic (#5709)
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
Labels: cherry-pick, 22_2

#5711 CDN Files: update topic (#5709)
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
Labels: cherry-pick, 23_2

#5716 TextEditors: update labelMode
  applications/UIWidgets/TextEditor/labelModeFloating/index.css
  applications/UIWidgets/TextEditor/labelModeFloating/index.html
  applications/UIWidgets/TextEditor/labelModeFloating/index.js
  applications/UIWidgets/TextEditor/labelModeHidden/index.css
  applications/UIWidgets/TextEditor/labelModeHidden/index.html
  applications/UIWidgets/TextEditor/labelModeHidden/index.js
  applications/UIWidgets/TextEditor/labelModeOutside/index.css
  applications/UIWidgets/TextEditor/labelModeOutside/index.html
  applications/UIWidgets/TextEditor/labelModeOutside/index.js
  applications/UIWidgets/TextEditor/labelModeStatic/index.css
  applications/UIWidgets/TextEditor/labelModeStatic/index.html
  applications/UIWidgets/TextEditor/labelModeStatic/index.js
  images/UiWidgets/texteditor-floating-label.gif
  images/UiWidgets/texteditor-hidden-label.png
  images/UiWidgets/texteditor-static-label.png
  includes/texteditor-labelMode.md
Labels: 23_2
