Repository DevExpress/devextreme-documentation, pull requests merged in 2023-12, with the labels that each got.

#5830 Diagram - add examples to Node and Edge Arrays (#5829)
  concepts/05 UI Components/Diagram/10 Data Binding/10 Node and Edge Arrays.md
  concepts/05 UI Components/Diagram/10 Data Binding/Data Binding.md
Labels: cherry-pick, 23_1

#5831 DataGrid: add links to Predefined Aggregate Functions
  concepts/05 UI Components/DataGrid/65 Summaries/05 Predefined Aggregate Functions.md
Labels: 23_1

#5835 Grids: add note about filter panel (#5834)
  api-reference/10 UI Components/GridBase/1 Configuration/filterPanel/filterPanel.md
  api-reference/10 UI Components/GridBase/1 Configuration/syncLookupFilterValues.md
Labels: cherry-pick, 22_2

#5837 HtmlEditor: add info about tabs and spaces
  concepts/05 UI Components/HtmlEditor/05 Overview.md
Labels: 23_1

#5846 Licensing: add video
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
Labels: 23_2

#5847 Use nocookie youtube video link
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
Labels: 23_2

#5849 Tooltip: update link in Overview
  concepts/05 UI Components/Tooltip/00 Overview.md
Labels: 23_1

#5850 Tooltip: update link in Overview (#5849)
  concepts/05 UI Components/Tooltip/00 Overview.md
Labels: cherry-pick, 22_2

#5857 Grids: update syncLookupFilterValues
  api-reference/10 UI Components/GridBase/1 Configuration/syncLookupFilterValues.md
Labels: 23_1

#5858 Grids: update syncLookupFilterValues (#5857)
  api-reference/10 UI Components/GridBase/1 Configuration/syncLookupFilterValues.md
Labels: cherry-pick, 22_2

#5861 Licensing: add TOC and FAQ
  concepts/Common/Licensing/00 Licensing.md
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
  concepts/Common/Licensing/13 Deployment and Continuous Integration (CI).md
  concepts/Common/Licensing/30 FAQ.md
Labels: 23_2

#5863 Licensing: update FAQ after review
  concepts/Common/Licensing/30 FAQ.md
Labels: 23_2

#5676 React: update 'render' and 'component' descriptions
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/0 Markup Customization.md
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/3 Using a Rendering Function.md
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/5 Using a Custom Component.md
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/8 Using the Template Component.md
Labels: 23_1

#5866 React: update 'render' and 'component' descriptions (#5676)
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/0 Markup Customization.md
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/3 Using a Rendering Function.md
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/5 Using a Custom Component.md
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/8 Using the Template Component.md
Labels: cherry-pick, 23_2

#5865 DataGrid: add note to formItem
  api-reference/_hidden/GridBaseColumn/formItem.md
Labels: 23_1

#5867 DataGrid: add note to formItem (#5865)
  api-reference/_hidden/GridBaseColumn/formItem.md
Labels: cherry-pick, 23_2

#5828 Angular: replace toPromise with lastValueFrom
  api-reference/10 UI Components/GridBase/1 Configuration/onInitNewRow.md
  api-reference/10 UI Components/GridBase/1 Configuration/onRowRemoving.md
  api-reference/10 UI Components/GridBase/1 Configuration/onRowValidating.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onInitNewRow.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onRowRemoving.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onRowValidating.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onInitNewRow.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onRowRemoving.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onRowValidating.md
  api-reference/10 UI Components/dxTreeView/1 Configuration/createChildren.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/AsyncRule/validationCallback.md
  api-reference/30 Data Layer/CustomStore/1 Configuration/byKey.md
  api-reference/30 Data Layer/CustomStore/1 Configuration/insert.md
  api-reference/30 Data Layer/CustomStore/1 Configuration/remove.md
  api-reference/30 Data Layer/CustomStore/1 Configuration/update.md
  api-reference/_hidden/GridBaseColumn/setCellValue.md
  concepts/05 UI Components/DataGrid/99 How To/Bind a Lookup Column to a Custom Data Source.md
  concepts/05 UI Components/Lookup/03 Data Binding/20 Custom Sources.md
  concepts/05 UI Components/PivotGrid/035 Use CustomStore/20 Remote Operations.md
  concepts/05 UI Components/TagBox/02 Data Binding/20 Custom Sources.md
  concepts/05 UI Components/TreeList/99 How To/Bind a Lookup Column to a Custom Data Source.md
  concepts/05 UI Components/TreeView/32 Enhance Performance on Large Datasets.md
  concepts/70 Data Binding/00 Specify a Data Source/20 Read-Only Data in JSON Format.md
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/6 Edit Data.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/0 Connect to RESTful Service.md
  includes/common-code-customsource-rawmode-pagingdisabled.md
  includes/common-code-customsource-rawmode-withkey.md
  includes/datagrid-ref-confirm-action-and-validate-data.md
  includes/dataviz-code-customsource.md
Labels: 23_1

#5874 Angular: replace toPromise with lastValueFrom (#5828)
  api-reference/10 UI Components/GridBase/1 Configuration/onInitNewRow.md
  api-reference/10 UI Components/GridBase/1 Configuration/onRowRemoving.md
  api-reference/10 UI Components/GridBase/1 Configuration/onRowValidating.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onInitNewRow.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onRowRemoving.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onRowValidating.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onInitNewRow.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onRowRemoving.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onRowValidating.md
  api-reference/10 UI Components/dxTreeView/1 Configuration/createChildren.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/AsyncRule/validationCallback.md
  api-reference/30 Data Layer/CustomStore/1 Configuration/byKey.md
  api-reference/30 Data Layer/CustomStore/1 Configuration/insert.md
  api-reference/30 Data Layer/CustomStore/1 Configuration/remove.md
  api-reference/30 Data Layer/CustomStore/1 Configuration/update.md
  api-reference/_hidden/GridBaseColumn/setCellValue.md
  concepts/05 UI Components/DataGrid/99 How To/Bind a Lookup Column to a Custom Data Source.md
  concepts/05 UI Components/Lookup/03 Data Binding/20 Custom Sources.md
  concepts/05 UI Components/PivotGrid/035 Use CustomStore/20 Remote Operations.md
  concepts/05 UI Components/TagBox/02 Data Binding/20 Custom Sources.md
  concepts/05 UI Components/TreeList/99 How To/Bind a Lookup Column to a Custom Data Source.md
  concepts/05 UI Components/TreeView/32 Enhance Performance on Large Datasets.md
  concepts/70 Data Binding/00 Specify a Data Source/20 Read-Only Data in JSON Format.md
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/6 Edit Data.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/0 Connect to RESTful Service.md
  includes/common-code-customsource-rawmode-pagingdisabled.md
  includes/common-code-customsource-rawmode-withkey.md
  includes/datagrid-ref-confirm-action-and-validate-data.md
  includes/dataviz-code-customsource.md
Labels: cherry-pick, 23_2

#5876 LegendItem public
  api-reference/10 UI Components/BaseChart/7 Interfaces/LegendItem/LegendItem.md
  api-reference/10 UI Components/BaseChart/7 Interfaces/LegendItem/series.md
  api-reference/40 Common Types/05 charts/BaseChartLegend/customizeItems.md
  api-reference/40 Common Types/05 charts/BaseChartLegend/markerTemplate.md
  metadata/syntax-data.json
Labels: 23_2

#5852 Gantt: update Getting started tutorial
  MenuConfig.xml
  applications/GettingStartedWith/Gantt/index.css
  applications/GettingStartedWith/Gantt/index.html
  applications/GettingStartedWith/Gantt/index.js
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/00 Getting Started with Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/10 Add the Gantt Component to a Page.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/20 Bind the Gantt to Data.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/30 Add Columns to the Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/40 Enable Editing.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/50 Preselect a Task.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/60 Handle the Selection Change Event.md
Labels: 23_1

#5878 Gantt: update Getting started tutorial (#5852)
  MenuConfig.xml
  applications/GettingStartedWith/Gantt/index.css
  applications/GettingStartedWith/Gantt/index.html
  applications/GettingStartedWith/Gantt/index.js
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/00 Getting Started with Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/10 Add the Gantt Component to a Page.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/20 Bind the Gantt to Data.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/30 Add Columns to the Gantt.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/40 Enable Editing.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/50 Preselect a Task.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/60 Handle the Selection Change Event.md
Labels: cherry-pick, 23_2

#5875 CustomStore onLoaded
  api-reference/30 Data Layer/CustomStore/1 Configuration/onLoaded.md
  api-reference/30 Data Layer/CustomStore/4 Events/Events.md
  api-reference/30 Data Layer/CustomStore/4 Events/loaded.md
  api-reference/30 Data Layer/ODataStore/1 Configuration/onLoading.md
  api-reference/30 Data Layer/ODataStore/4 Events/Events.md
  api-reference/30 Data Layer/ODataStore/4 Events/loading.md
  api-reference/30 Data Layer/Store/Store.md
  api-reference/_hidden/Enums/EventName.md
Labels: 23_2

#5882 CustomStore onLoaded
  api-reference/30 Data Layer/CustomStore/1 Configuration/onLoaded.md
  api-reference/30 Data Layer/CustomStore/4 Events/Events.md
  api-reference/30 Data Layer/CustomStore/4 Events/loaded.md
  api-reference/30 Data Layer/ODataStore/1 Configuration/onLoading.md
  api-reference/30 Data Layer/ODataStore/4 Events/Events.md
  api-reference/30 Data Layer/ODataStore/4 Events/loading.md
Labels: cherry-pick, 23_1

#5889 Update supported framework versions
  concepts/40 Angular Components/80 Supported Versions.md
  concepts/50 React Components/80 Supported Versions.md
  concepts/55 Vue Components/80 Supported Versions.md
  concepts/58 jQuery Components/80 Supported Versions.md
Labels: 23_2

#5890 Fix devextreme-examples links
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/020 Lookup Optimization.md
  concepts/05 UI Components/PivotGrid/035 Use CustomStore/20 Remote Operations.md
  concepts/40 Angular Components/40 Common Features/05 Server-Side Rendering/00 Server-Side Rendering.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: 23_1

#5891 Fix devextreme-examples links (#5890)
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/020 Lookup Optimization.md
  concepts/05 UI Components/PivotGrid/035 Use CustomStore/20 Remote Operations.md
  concepts/40 Angular Components/40 Common Features/05 Server-Side Rendering/00 Server-Side Rendering.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: cherry-pick, 23_2

#5894 Fix devextreme-examples links (#5890)
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/020 Lookup Optimization.md
  concepts/05 UI Components/PivotGrid/035 Use CustomStore/20 Remote Operations.md
  concepts/40 Angular Components/40 Common Features/05 Server-Side Rendering/00 Server-Side Rendering.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: cherry-pick, 24_1

#5895 Update supported framework versions
  concepts/40 Angular Components/80 Supported Versions.md
  concepts/50 React Components/80 Supported Versions.md
  concepts/55 Vue Components/80 Supported Versions.md
  concepts/58 jQuery Components/80 Supported Versions.md
Labels: 24_1

#5896 Fix menuConfig
  MenuConfig.xml
Labels: 23_2

#5897 Fix menuConfig (#5896)
  MenuConfig.xml
Labels: cherry-pick, 23_1

#5898 Fix menuConfig (#5896)
  MenuConfig.xml
Labels: cherry-pick, 24_1

#5900 Fix GitHub links
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/get(componentPath).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getModule(moduleName).md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
  concepts/60 Themes and Styles/30 Icons/60 SVG Icons.md
  concepts/Common/Localization/01 Dictionaries/02 Create a New Dictionary.md
  concepts/Common/Localization/01 Dictionaries/07 Override Strings in a Dictionary.md
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
Labels: 23_2

#5901 Fix GitHub links (#5900)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/get(componentPath).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getModule(moduleName).md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
  concepts/60 Themes and Styles/30 Icons/60 SVG Icons.md
  concepts/Common/Localization/01 Dictionaries/02 Create a New Dictionary.md
  concepts/Common/Localization/01 Dictionaries/07 Override Strings in a Dictionary.md
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
Labels: cherry-pick, 24_1

#5886 Scheduler: update offset
  api-reference/10 UI Components/dxScheduler/1 Configuration/offset.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/offset.md
Labels: 23_2

#5904 Scheduler: update offset (#5886)
  api-reference/10 UI Components/dxScheduler/1 Configuration/offset.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/offset.md
Labels: cherry-pick, 24_1

#5888 Validator: add a note to PatternRule
  api-reference/10 UI Components/dxValidator/8 Validation Rules/PatternRule/PatternRule.md
Labels: 23_1

#5905 Validator: add a note to PatternRule (#5888)
  api-reference/10 UI Components/dxValidator/8 Validation Rules/PatternRule/PatternRule.md
Labels: cherry-pick, 23_2

#5899 Validator: update Email rule
  api-reference/10 UI Components/dxValidator/8 Validation Rules/EmailRule/EmailRule.md
Labels: 23_2

#5906 Validator: add a note to PatternRule (#5888)
  api-reference/10 UI Components/dxValidator/8 Validation Rules/PatternRule/PatternRule.md
Labels: cherry-pick, 24_1

#5907 Validator: update Email rule (#5899)
  api-reference/10 UI Components/dxValidator/8 Validation Rules/EmailRule/EmailRule.md
Labels: cherry-pick, 23_1

#5908 Validator: update Email rule (#5899)
  api-reference/10 UI Components/dxValidator/8 Validation Rules/EmailRule/EmailRule.md
Labels: cherry-pick, 24_1

#5909 LegendItem public
  api-reference/10 UI Components/BaseChart/7 Interfaces/LegendItem/LegendItem.md
  api-reference/10 UI Components/BaseChart/7 Interfaces/LegendItem/series.md
  api-reference/NewTopics/LegendItem/LegendItem.md
  api-reference/NewTopics/LegendItem/series.md
Labels: cherry-pick, 23_1

#5913 Licensing: update video link
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
Labels: 23_2

#5914 Licensing: update video link (#5913)
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
Labels: cherry-pick, 24_1
