Repository DevExpress/devextreme-documentation, pull requests merged in 2023-11, with the labels that each got.

#5720 Update icons GitHub links
  concepts/60 Themes and Styles/30 Icons/10 Built-In Icon Library.md
Labels: 23_2

#5721 DropDownButton/ButtonGroup: update style pictures
  api-reference/10 UI Components/dxButton/1 Configuration/type.md
  api-reference/10 UI Components/dxButtonGroup/1 Configuration/stylingMode.md
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/stylingMode.md
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/type.md
  api-reference/_hidden/dxButtonGroupItem/type.md
  images/UiWidgets/buttongroup.png
  images/UiWidgets/ddbutton.png
Labels: 23_2

#5724 Button: add Accessibility topic
  concepts/05 UI Components/Button/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Button/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Button/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Button/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Button/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/Button/15 Keyboard Support.md
Labels: 23_2

#5725 Calendar: add accessibility topic
  concepts/05 UI Components/Calendar/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Calendar/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Calendar/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Calendar/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Calendar/03 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5732 Box/ResponsiveBox: update baseSize
  api-reference/10 UI Components/dxResponsiveBox/1 Configuration/cols/baseSize.md
  api-reference/10 UI Components/dxResponsiveBox/1 Configuration/rows/baseSize.md
  api-reference/_hidden/dxBoxItem/baseSize.md
Labels: 23_1

#5734 Box/ResponsiveBox: update baseSize (#5732)
  api-reference/10 UI Components/dxResponsiveBox/1 Configuration/cols/baseSize.md
  api-reference/10 UI Components/dxResponsiveBox/1 Configuration/rows/baseSize.md
  api-reference/_hidden/dxBoxItem/baseSize.md
Labels: cherry-pick, 23_2

#5726 Common Types non grouped children
  MenuConfig.xml
Labels: 23_2

#5737 ButtonGroup/CheckBox: add accessibility topics
  concepts/05 UI Components/ButtonGroup/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/ButtonGroup/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/ButtonGroup/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ButtonGroup/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/ButtonGroup/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/CheckBox/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/CheckBox/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/CheckBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/CheckBox/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/CheckBox/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/CheckBox/20 Keyboard Support.md
Labels: 23_2

#5739 W0019/W0020: delete emails
  api-reference/50 Common/utils/zz Errors and Warnings/W0019.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0020.md
Labels: 23_2

#5740 CTP notes: remove emails
  includes/common-ctp-note-wo-devextreme.md
  includes/common-ctp-note.md
Labels: 22_1

#5741 CTP notes: remove emails (#5740)
  includes/common-ctp-note-wo-devextreme.md
  includes/common-ctp-note.md
Labels: cherry-pick, 21_2

#5742 CTP notes: remove emails (#5740)
  includes/common-ctp-note-wo-devextreme.md
  includes/common-ctp-note.md
Labels: 21_1, cherry-pick

#5743 CTP notes: remove emails (#5740)
  includes/common-ctp-note-wo-devextreme.md
  includes/common-ctp-note.md
Labels: 20_2, cherry-pick

#5744 CTP notes: remove emails (#5740)
  includes/common-ctp-note.md
Labels: cherry-pick, 20_1

#5745 ColorBox: add accessibility topic
  concepts/05 UI Components/ColorBox/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/ColorBox/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/ColorBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ColorBox/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/ColorBox/05 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5749 Update license warnings after review
  api-reference/50 Common/utils/zz Errors and Warnings/W0019.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0020.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0021.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0022.md
Labels: 23_2

#5624 Add Licensing section
  MenuConfig.xml
  concepts/Common/Licensing/00 Licensing.md
  concepts/Common/Licensing/05 Evaluation (Trial).md
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
  concepts/Common/Licensing/15 Updating License Keys.md
  concepts/Common/Licensing/20 Information Security.md
  concepts/Common/Licensing/25 Validation.md
Labels: 23_2

#5750 Add Fluent theme to docs
  concepts/60 Themes and Styles/05 Predefined Themes/00 Predefined Themes.md
  concepts/60 Themes and Styles/05 Predefined Themes/50 Apply a Theme/05 Using SCSS.md
  images/themes/fluent-compact.png
  images/themes/fluent-dark-compact.png
  images/themes/fluent-dark-default.png
  images/themes/fluent-default.png
Labels: 23_2

#5752 FileManager: update onItemRenaming
  api-reference/10 UI Components/dxFileManager/1 Configuration/onItemRenaming.md
Labels: 23_1

#5753 FileManager: update onItemRenaming (#5752)
  api-reference/10 UI Components/dxFileManager/1 Configuration/onItemRenaming.md
Labels: cherry-pick, 22_2

#5754 FileManager: update onItemRenaming (#5752)
  api-reference/10 UI Components/dxFileManager/1 Configuration/onItemRenaming.md
Labels: cherry-pick, 23_2

#5757 ContextMenu: add Accessibility topic
  concepts/05 UI Components/ColorBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ContextMenu/02 Accessibility/00 Accessibility.md
  concepts/05 UI Components/ContextMenu/02 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/ContextMenu/02 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ContextMenu/02 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/ContextMenu/02 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5751 Scheduler: describe offset property
  api-reference/10 UI Components/dxScheduler/1 Configuration/offset.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/offset.md
Labels: 23_2

#5755 DataGrid/TreeList: update accessibility topics
  concepts/05 UI Components/DataGrid/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TreeList/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
Labels: 23_2

#5759 DropDownButton: add accessibility topic
  concepts/05 UI Components/DropDownButton/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/DropDownButton/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/DropDownButton/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DropDownButton/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/DropDownButton/05 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5758 DateBox: add accessibility topic
  concepts/05 UI Components/DateBox/02 Accessibility/00 Accessibility.md
  concepts/05 UI Components/DateBox/02 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/DateBox/02 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DateBox/02 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/DateBox/02 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5761 Licensing: update warning links
  concepts/Common/Licensing/25 Validation.md
Labels: 23_2

#5762 Licensing: update after review
  concepts/Common/Licensing/00 Licensing.md
  concepts/Common/Licensing/05 Evaluation (Trial).md
  concepts/Common/Licensing/20 Information Security.md
  concepts/Common/Licensing/25 Validation.md
Labels: 23_2

#5764 Fluent: update theme names
  concepts/60 Themes and Styles/05 Predefined Themes/00 Predefined Themes.md
Labels: 23_2

#5763 Form: add accessibility topic
  concepts/05 UI Components/Form/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Form/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Form/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Form/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Form/03 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5767 Gallery: add accessibility topic
  concepts/05 UI Components/Gallery/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Gallery/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Gallery/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Gallery/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Gallery/03 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/Gallery/35 Keyboard Support.md
Labels: 23_2

#5769 Menu: add accessibility topic
  concepts/05 UI Components/Menu/02 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Menu/02 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Menu/02 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Menu/02 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Menu/02 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5771 MultiView: add accessibility topic
  concepts/05 UI Components/MultiView/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/MultiView/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/MultiView/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/MultiView/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/MultiView/03 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5772 NumberBox: add accessibility topic
  concepts/05 UI Components/NumberBox/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/NumberBox/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/NumberBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/NumberBox/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/NumberBox/05 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5768 List: add accessibility topic
  concepts/05 UI Components/List/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/List/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/List/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/List/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/List/03 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5774 Revert last docgen
  api-reference/10 UI Components/dxAutocomplete/3 Methods/reset(value).md
  api-reference/10 UI Components/dxCalendar/3 Methods/Methods.md
  api-reference/10 UI Components/dxCalendar/3 Methods/reset(value).md
  api-reference/10 UI Components/dxCheckBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxColorBox/3 Methods/Methods.md
  api-reference/10 UI Components/dxColorBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxDateBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxDateRangeBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxFileUploader/3 Methods/reset(value).md
  api-reference/10 UI Components/dxNumberBox/3 Methods/Methods.md
  api-reference/10 UI Components/dxNumberBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxProgressBar/3 Methods/reset(value).md
  api-reference/10 UI Components/dxRangeSlider/3 Methods/Methods.md
  api-reference/10 UI Components/dxRangeSlider/3 Methods/reset(value).md
  api-reference/10 UI Components/dxSlider/3 Methods/Methods.md
  api-reference/10 UI Components/dxSlider/3 Methods/reset(value).md
  api-reference/10 UI Components/dxSwitch/3 Methods/Methods.md
  api-reference/10 UI Components/dxSwitch/3 Methods/reset(value).md
  api-reference/10 UI Components/dxTextBox/3 Methods/Methods.md
  api-reference/10 UI Components/dxTextBox/3 Methods/reset(value).md
Labels: 23_2

#5765 Reset method
  api-reference/10 UI Components/dxAutocomplete/3 Methods/reset(value).md
  api-reference/10 UI Components/dxCalendar/3 Methods/Methods.md
  api-reference/10 UI Components/dxCalendar/3 Methods/reset(value).md
  api-reference/10 UI Components/dxCheckBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxColorBox/3 Methods/Methods.md
  api-reference/10 UI Components/dxColorBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxDateBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxDateRangeBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxFileUploader/3 Methods/reset(value).md
  api-reference/10 UI Components/dxNumberBox/3 Methods/Methods.md
  api-reference/10 UI Components/dxNumberBox/3 Methods/reset(value).md
  api-reference/10 UI Components/dxProgressBar/3 Methods/reset(value).md
  api-reference/10 UI Components/dxRangeSlider/3 Methods/Methods.md
  api-reference/10 UI Components/dxRangeSlider/3 Methods/reset(value).md
  api-reference/10 UI Components/dxSlider/3 Methods/Methods.md
  api-reference/10 UI Components/dxSlider/3 Methods/reset(value).md
  api-reference/10 UI Components/dxSwitch/3 Methods/Methods.md
  api-reference/10 UI Components/dxSwitch/3 Methods/reset(value).md
  api-reference/10 UI Components/dxTextBox/3 Methods/Methods.md
  api-reference/10 UI Components/dxTextBox/3 Methods/reset(value).md
Labels: 23_2

#5775 ProgressBar: add accessibility topic
  concepts/05 UI Components/ProgressBar/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/ProgressBar/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/ProgressBar/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ProgressBar/03 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5779 ThemeBuilder: add new images
  concepts/60 Themes and Styles/05 Predefined Themes/55 Color Swatches.md
  concepts/60 Themes and Styles/08 ThemeBuilder/10 Customize the Theme.md
  concepts/60 Themes and Styles/08 ThemeBuilder/20 Postpone Customization.md
  concepts/60 Themes and Styles/08 ThemeBuilder/40 Export the Resulting Theme.md
  concepts/60 Themes and Styles/08 ThemeBuilder/ThemeBuilder.md
  concepts/Common/Migrate to the New Version/20 Upgrade Themes Created in ThemeBuilder.md
  images/Common/ThemeBuilder/themebuilder-main.png
  images/Common/ThemeBuilder/themebuilder-main@2x.png
  images/Common/ThemeBuilder/themebuilder-mainview.png
  images/Common/ThemeBuilder/themebuilder-mainview@2x.png
  images/Common/ThemeBuilder/themebuilder-settings-tree.gif
  images/Common/ThemeBuilder/themebuilder-themeexport-css.png
  images/Common/ThemeBuilder/themebuilder-themeexport-format.png
  images/Common/ThemeBuilder/themebuilder-themeexport-format@2x.png
  images/Common/ThemeBuilder/themebuilder-themeexport-name.png
  images/Common/ThemeBuilder/themebuilder-themeexport-name@2x.png
  images/Common/ThemeBuilder/themebuilder-themeexport-widgets.png
  images/Common/ThemeBuilder/themebuilder-themeexport-widgets@2x.png
  images/Common/ThemeBuilder/themebuilder-themeimport.png
  images/Common/ThemeBuilder/themebuilder-themeimport@2x.png
Labels: 23_2

#5780 Fix tools version
  package.json
Labels: 23_2

#5778 Popup/Popover: accessibility
  concepts/05 UI Components/Popover/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Popover/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Popover/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Popover/03 Accessibility/15 Screen Reader Support.md
  concepts/05 UI Components/Popup/03 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5781 RadioGroup: add accessibility topic
  concepts/05 UI Components/RadioGroup/00 Overview.md
  concepts/05 UI Components/RadioGroup/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/RadioGroup/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/RadioGroup/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/RadioGroup/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/RadioGroup/03 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5782 Slider/RangeSlider: add accessibility topics
  concepts/05 UI Components/RangeSlider/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/RangeSlider/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/RangeSlider/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/RangeSlider/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/RangeSlider/03 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/Slider/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Slider/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Slider/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Slider/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Slider/03 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5783 Switch: add accessibility topic
  concepts/05 UI Components/Switch/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Switch/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Switch/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Switch/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Switch/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/Switch/20 Keyboard Support.md
Labels: 23_2

#5784 TabPanel: add accessibility topic
  concepts/05 UI Components/TabPanel/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/TabPanel/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/TabPanel/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TabPanel/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/TabPanel/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/TabPanel/20 Keyboard Support.md
Labels: 23_2

#5785 Toolbar: add accessibility topic
  concepts/05 UI Components/Toolbar/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Toolbar/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Toolbar/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Toolbar/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Toolbar/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/Toolbar/20 Keyboard Support.md
Labels: 23_2

#5786 TreeView: add accessibility topic
  concepts/05 UI Components/TreeView/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/TreeView/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/TreeView/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TreeView/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/TreeView/03 Accessibility/20 Screen Reader Support.md
Labels: 23_2

#5787 Accessibility: add component links
  concepts/Common/Accessibility/05 Documentation for Components.md
Labels: 23_2

#5790 External icons: add info about Fluent
  concepts/60 Themes and Styles/30 Icons/50 External Icon Libraries.md
Labels: 23_2

#5792 Update supported browsers
  concepts/Common/Supported Browsers.md
Labels: 23_2

#5793 Add Fluent mentions
  api-reference/10 UI Components/zz CSS Classes/dx-card.md
  concepts/60 Themes and Styles/05 Predefined Themes/55 Color Swatches.md
  concepts/60 Themes and Styles/08 ThemeBuilder/01 Get Started/3 Create a New Theme.md
Labels: 23_2

#5791 Describe globalConfig.licenseKey
  api-reference/50 Common/Object Structures/GlobalConfig/licenseKey.md
Labels: 23_2

#5794 DataGrid: add example to totalCount()
  api-reference/10 UI Components/dxDataGrid/3 Methods/totalCount().md
Labels: 23_1

#5795 DataGrid: add example to totalCount() (#5794)
  api-reference/10 UI Components/dxDataGrid/3 Methods/totalCount().md
Labels: cherry-pick, 22_2

#5796 DataGrid: add example to totalCount() (#5794)
  api-reference/10 UI Components/dxDataGrid/3 Methods/totalCount().md
Labels: cherry-pick, 23_2

#5797 Form: correct React imports
  concepts/05 UI Components/Form/05 Configure Simple Items/01 Create a Simple Item.md
Labels: 23_1

#5798 Form: correct React imports (#5797)
  concepts/05 UI Components/Form/05 Configure Simple Items/01 Create a Simple Item.md
Labels: cherry-pick, 22_2

#5799 Form: correct React imports (#5797)
  concepts/05 UI Components/Form/05 Configure Simple Items/01 Create a Simple Item.md
Labels: cherry-pick, 23_2

#5801 dxTreeListColumnButton.onClick: Use own field description
  api-reference/_hidden/dxTreeListColumnButton/onClick.md
Labels: 23_2

#5802 Fluent theme: add SaaS color scheme
  concepts/60 Themes and Styles/05 Predefined Themes/00 Predefined Themes.md
  images/themes/saas-compact-light.png
  images/themes/saas-compact.png
  images/themes/saas-default-light.png
  images/themes/saas-default.png
Labels: 23_2

#5804 Remove themes from demo links (#5803)
  api-reference/10 UI Components/dxActionSheet/1 Configuration/usePopover.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/customShapes/template.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/customShapes/toolboxTemplate.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/nodes/customDataExpr.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/nodes/widthExpr.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/onRequestEditOperation.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxSpeedDialAction/1 Configuration/icon.md
  api-reference/10 UI Components/dxSpeedDialAction/1 Configuration/label.md
  api-reference/10 UI Components/dxSpeedDialAction/1 Configuration/onClick.md
  api-reference/10 UI Components/dxSpeedDialAction/1 Configuration/visible.md
  api-reference/10 UI Components/dxSpeedDialAction/dxSpeedDialAction.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/remoteOperations.md
  api-reference/50 Common/Object Structures/ExcelExportPivotGridProps/exportColumnFieldHeaders.md
  api-reference/50 Common/Object Structures/ExcelExportPivotGridProps/exportDataFieldHeaders.md
  api-reference/50 Common/Object Structures/ExcelExportPivotGridProps/exportFilterFieldHeaders.md
  api-reference/50 Common/Object Structures/ExcelExportPivotGridProps/exportRowFieldHeaders.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/floatingActionButtonConfig.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/icon.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/position.md
  api-reference/50 Common/Object Structures/GlobalConfig/floatingActionButtonConfig/shading.md
  concepts/05 UI Components/ActionSheet/10 Specify Display Mode.md
  concepts/05 UI Components/Diagram/25 Templates/10 Shape Template.md
  concepts/05 UI Components/Diagram/25 Templates/20 Toolbox Shape Template.md
  concepts/05 UI Components/Diagram/28 Restrict Edit Operations/20 Prohibit Individual Operations.md
  concepts/40 Angular Components/20 Component Configuration Syntax/14 Properties of the Object Type.md
  concepts/40 Angular Components/20 Component Configuration Syntax/17 Collections.md
  concepts/40 Angular Components/20 Component Configuration Syntax/37 Templates/37 Templates.md
  concepts/40 Angular Components/20 Component Configuration Syntax/42 Call Methods.md
  concepts/40 Angular Components/30 Application Template/05 Generate a New Application.md
  concepts/50 React Components/02 Create a DevExtreme Application.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/60 Import DevExtreme Components.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/90 Demos and Code Examples.md
  concepts/50 React Components/40 Component Configuration Syntax/12 Properties of the Object Type.md
  concepts/50 React Components/40 Component Configuration Syntax/20 Collections.md
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/3 Using a Rendering Function.md
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/5 Using a Custom Component.md
  concepts/50 React Components/40 Component Configuration Syntax/70 Data Layer.md
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
  concepts/55 Vue Components/02 Create a DevExtreme Application.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/60 Import DevExtreme Components.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/90 Demos and Code Examples.md
  concepts/55 Vue Components/20 Component Configuration Syntax/14 Properties of the Object Type.md
  concepts/55 Vue Components/20 Component Configuration Syntax/17 Collections.md
  concepts/55 Vue Components/20 Component Configuration Syntax/37 Templates.md
  concepts/55 Vue Components/50 Application Template/05 Generate a New Application.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
  includes/ng-demos-and-code-examples.md
Labels: cherry-pick, 23_1

#5806 Fluent: add note about trademark
  concepts/60 Themes and Styles/05 Predefined Themes/00 Predefined Themes.md
  concepts/60 Themes and Styles/08 ThemeBuilder/01 Get Started/3 Create a New Theme.md
Labels: 23_2

#5807 Scheduler: add error descriptions
  api-reference/10 UI Components/Errors and Warnings/E1058.md
  api-reference/10 UI Components/Errors and Warnings/E1061.md
  api-reference/10 UI Components/Errors and Warnings/E1062.md
  api-reference/10 UI Components/Errors and Warnings/W1015.md
Labels: 23_2

#5808 Add 23.2 demo links
  api-reference/10 UI Components/dxCalendar/1 Configuration/selectWeekOnClick.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/selectionMode.md
  api-reference/10 UI Components/dxForm/1 Configuration/isDirty.md
  api-reference/10 UI Components/dxForm/3 Methods/reset(editorsData).md
  api-reference/10 UI Components/dxScheduler/1 Configuration/offset.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/offset.md
  api-reference/10 UI Components/dxTabPanel/1 Configuration/iconPosition.md
  api-reference/10 UI Components/dxTabPanel/1 Configuration/stylingMode.md
  api-reference/10 UI Components/dxTabPanel/1 Configuration/tabsPosition.md
  api-reference/10 UI Components/dxTabs/1 Configuration/iconPosition.md
  api-reference/10 UI Components/dxTabs/1 Configuration/orientation.md
  api-reference/10 UI Components/dxTabs/1 Configuration/stylingMode.md
Labels: 23_2

#5812 DataGrid: update groupCellTemplate
  api-reference/_hidden/dxDataGridColumn/groupCellTemplate.md
Labels: 23_1

#5813 DataGrid: update groupCellTemplate (#5812)
  api-reference/_hidden/dxDataGridColumn/groupCellTemplate.md
Labels: cherry-pick, 22_2

#5814 DataGrid: update groupCellTemplate (#5812)
  api-reference/_hidden/dxDataGridColumn/groupCellTemplate.md
Labels: cherry-pick, 23_2

#5816 FileManager: replace demo links with examples
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Custom/1 Configuration/uploadFileChunk.md
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Object/Object.md
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Remote/Remote.md
  api-reference/10 UI Components/dxFileManager/7 Interfaces/UploadInfo/customData.md
  concepts/05 UI Components/FileManager/10 Bind to File Systems/30 Custom File System.md
Labels: 23_2

#5815 Licensing: update topic
  concepts/Common/Licensing/00 Licensing.md
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
  images/Common/licensing-key@2x.png
Labels: 23_2

#5818 Web API Service: add/update marketing note
  api-reference/30 Data Layer/ODataContext/ODataContext.md
  api-reference/30 Data Layer/ODataStore/ODataStore.md
  concepts/05 UI Components/Chart/03 Data Binding/16 Web API Service.md
  concepts/05 UI Components/Funnel/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Funnel/03 Data Binding/16 Web API Service.md
  concepts/05 UI Components/Lookup/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Lookup/03 Data Binding/16 Web API Service.md
  concepts/05 UI Components/PieChart/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/PieChart/03 Data Binding/16 Web API Service.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Provide Data/20 Using the Client-Side Processing/30 Using an ODataStore.md
  concepts/05 UI Components/Sankey/03 Data Binding/15 OData Service.md
  concepts/05 UI Components/Sankey/03 Data Binding/16 Web API Service.md
  concepts/05 UI Components/TagBox/02 Data Binding/15 OData Service.md
  concepts/05 UI Components/TagBox/02 Data Binding/16 Web API Service.md
  concepts/70 Data Binding/00 Specify a Data Source/30 Web API, PHP, MongoDB.md
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
  concepts/70 Data Binding/51 Data Source Examples/2 OData/5 Invoking Service Operations.md
Labels: 23_2

#5819 Remove jsFiddle links and update versions in codepen
  api-reference/10 UI Components/BaseChart/1 Configuration/adaptiveLayout/adaptiveLayout.md
  api-reference/10 UI Components/dxFunnel/1 Configuration/adaptiveLayout/adaptiveLayout.md
  api-reference/10 UI Components/dxPieChart/1 Configuration/adaptiveLayout/adaptiveLayout.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/adaptiveLayout/adaptiveLayout.md
  concepts/05 UI Components/Chart/89 Adaptive Layout.md
  concepts/05 UI Components/Funnel/89 Adaptive Layout.md
  concepts/05 UI Components/PieChart/89 Adaptive Layout.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/customizeTooltip.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/encodeHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/html.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/noDataText.md
Labels: 23_1

#5820 Remove jsFiddle links and update versions in codepen (#5819)
  api-reference/10 UI Components/BaseChart/1 Configuration/adaptiveLayout/adaptiveLayout.md
  api-reference/10 UI Components/dxFunnel/1 Configuration/adaptiveLayout/adaptiveLayout.md
  api-reference/10 UI Components/dxPieChart/1 Configuration/adaptiveLayout/adaptiveLayout.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/adaptiveLayout/adaptiveLayout.md
  concepts/05 UI Components/Chart/89 Adaptive Layout.md
  concepts/05 UI Components/Funnel/89 Adaptive Layout.md
  concepts/05 UI Components/PieChart/89 Adaptive Layout.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/customizeTooltip.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/encodeHtml.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/html.md
  concepts/Common/Security Considerations/20 HTML Encoding/30 Potentially Vulnerable API/noDataText.md
Labels: cherry-pick, 23_2

#5821 Add notes about Dashboard and Reporting
  concepts/05 UI Components/Chart/00 Overview.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/00 Getting Started with DataGrid.md
  concepts/05 UI Components/Funnel/00 Overview.md
  concepts/05 UI Components/Map/00 Overview.md
  concepts/05 UI Components/PieChart/00 Getting Started with PieChart/00 Getting Started with PieChart.md
  concepts/05 UI Components/PivotGrid/00 Getting Started with PivotGrid/00 Getting Started with PivotGrid.md
  concepts/05 UI Components/TreeList/00 Getting Started with TreeList/00 Getting Started with TreeList.md
Labels: 23_2

#5822 Toolbar: add note about menuItemTemplate (#5817)
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/20 Create an Overflow Menu.md
Labels: cherry-pick, 22_2

#5823 Toolbar: add note about menuItemTemplate (#5817)
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/20 Create an Overflow Menu.md
Labels: cherry-pick, 23_2

#5825 Accessibility: fix link (#5824)
  concepts/Common/Accessibility/00 Overview/35 Standard Compliance.md
Labels: cherry-pick, 23_2
