Repository DevExpress/devextreme-documentation, pull requests merged in 2023-02, with the labels that each got.

#4621 Troubleshooting: fix code snippets in 'drop-down editors' article
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/10 DataField and ValueExpr Should Store The Same Keys.md
Labels: 22_2

#4622 Troubleshooting: fix code snippets in 'drop-down editors' article (#4621)
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/10 DataField and ValueExpr Should Store The Same Keys.md
Labels: cherry-pick, 22_1

#4623 Troubleshooting: fix code snippets in 'drop-down editors' article (#4621)
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/10 DataField and ValueExpr Should Store The Same Keys.md
Labels: cherry-pick, 23_1

#4615 Validator: update dispose() method description
  api-reference/10 UI Components/dxValidator/3 Methods/dispose().md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/70 Conditional Validation.md
Labels: 22_2

#4625 Validator: update dispose() method description (#4615)
  api-reference/10 UI Components/dxValidator/3 Methods/dispose().md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/70 Conditional Validation.md
Labels: cherry-pick, 22_1

#4626 Validator: update dispose() method description (#4615)
  api-reference/10 UI Components/dxValidator/3 Methods/dispose().md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/70 Conditional Validation.md
Labels: cherry-pick, 23_1

#4627 Remove unnecessary topics in component guides
  api-reference/10 UI Components/dxAccordion/1 Configuration/itemTemplate.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/itemTitleTemplate.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/cellTemplate.md
  concepts/05 UI Components/Accordion/05 Customize Item Appearance.md
  concepts/05 UI Components/Accordion/10 Control the Behavior.md
  concepts/05 UI Components/Autocomplete/05 Customize Item Appearance.md
  concepts/05 UI Components/Autocomplete/10 Configure Search Parameters.md
  concepts/05 UI Components/Calendar/05 Handle the Value Change Event.md
  concepts/05 UI Components/Calendar/10 Specify Zoom Level.md
  concepts/05 UI Components/Calendar/15 Customize Cell Appearance.md
  concepts/05 UI Components/CheckBox/10 Handle the Value Change Event.md
Labels: 23_1

#4624 Vue: add Additional Configuration for Vite topic
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/70 Additional Configuration for Vite/00 Additional Configuration for Vite.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/70 Additional Configuration for Vite/05 Using Nuxt.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/70 Additional Configuration for Vite/10 Using Quasar.md
Labels: 22_2

#4630 Vue: add Additional Configuration for Vite topic (#4624)
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/70 Additional Configuration for Vite/00 Additional Configuration for Vite.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/70 Additional Configuration for Vite/05 Using Nuxt.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/70 Additional Configuration for Vite/10 Using Quasar.md
Labels: cherry-pick, 23_1

#4632 ColorBox: update Configure Values topic
  concepts/05 UI Components/ColorBox/00 Getting Started with ColorBox/10 Configure Values.md
Labels: 23_1

#4634 Delete duplicated articles and change links
  api-reference/10 UI Components/dxDateBox/1 Configuration/max.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/min.md
  concepts/05 UI Components/ColorBox/10 Handle the Value Change Event.md
  concepts/05 UI Components/ColorBox/15 Support Alpha Channel.md
  concepts/05 UI Components/DateBox/03 Platform-Specific Value Pickers.md
  concepts/05 UI Components/DateBox/05 Control the Behavior.md
  concepts/05 UI Components/DateBox/10 Handle the Value Change Event.md
  concepts/05 UI Components/DateBox/15 Specify Value Range.md
  concepts/05 UI Components/DateBox/16 Synchronize Two DateBoxes.md
  concepts/05 UI Components/DropDownBox/20 Customize the Appearance.md
Labels: 23_1

#4636 Remove duplicated guides
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/validationRules.md
  api-reference/10 UI Components/dxLookup/1 Configuration/onPageLoading.md
  api-reference/10 UI Components/dxLookup/1 Configuration/searchEnabled.md
  concepts/05 UI Components/Button/10 Validate and Submit an HTML Form.md
  concepts/05 UI Components/Form/25 Handle the Value Change Event.md
  concepts/05 UI Components/Form/30 Update Form Data Using the API.md
  concepts/05 UI Components/Form/35 Generate a Data Object from Form Items.md
  concepts/05 UI Components/Form/40 Validate and Submit the Form.md
  concepts/05 UI Components/Lookup/03 Data Binding/20 Custom Sources.md
  concepts/05 UI Components/Lookup/05 Configure Search Parameters.md
  concepts/05 UI Components/Lookup/10 Enable Grouping.md
  concepts/05 UI Components/Lookup/15 Enable Paging.md
  concepts/05 UI Components/Lookup/25 Handle the Value Change Event.md
  concepts/05 UI Components/NumberBox/10 Handle the Value Change Event.md
  concepts/Common/Editors Concepts/How to Choose a Drop-Down Editor.md
Labels: 23_1

#4639 Delete duplicated articles
  api-reference/10 UI Components/dxTabPanel/1 Configuration/itemTitleTemplate.md
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/10 Events.md
  concepts/05 UI Components/Popup/15 Resize and Relocate.md
  concepts/05 UI Components/SelectBox/04 Handle the Value Change Event.md
  concepts/05 UI Components/SelectBox/10 Configure Search Parameters.md
  concepts/05 UI Components/SelectBox/15 Create a User-Defined Item.md
  concepts/05 UI Components/SelectBox/25 Keyboard Support.md
  concepts/05 UI Components/TabPanel/05 Customize Item Appearance.md
  concepts/05 UI Components/TabPanel/15 Control the Behavior.md
  concepts/05 UI Components/Tabs/05 Customize Item Appearance.md
  concepts/05 UI Components/Tabs/15 Control the Behavior.md
Labels: 23_1

#4640 Delete duplicated guides
  api-reference/10 UI Components/dxTextArea/1 Configuration/autoResizeEnabled.md
  concepts/05 UI Components/TagBox/03 Control the Behavior.md
  concepts/05 UI Components/TagBox/04 Handle the Value Change Event.md
  concepts/05 UI Components/TagBox/10 Configure Search Parameters.md
  concepts/05 UI Components/TagBox/15 Create a User-Defined Item.md
  concepts/05 UI Components/TextArea/05 Adapt the Size of the Text Area.md
  concepts/05 UI Components/TextArea/10 Handle the Value Change Event.md
  concepts/05 UI Components/TextArea/13 Handle the Keyboard Events.md
  concepts/05 UI Components/TextArea/15 Limit the Text Length.md
Labels: 23_1

#4637 deferRendering: update property description for Vue and Angular
  api-reference/10 UI Components/dxAccordion/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxMultiView/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/deferRendering.md
Labels: 22_2

#4643 deferRendering: update property description for Vue and Angular (#4637)
  api-reference/10 UI Components/dxAccordion/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxMultiView/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/deferRendering.md
Labels: cherry-pick, 22_1

#4644 deferRendering: update property description for Vue and Angular (#4637)
  api-reference/10 UI Components/dxAccordion/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxDropDownEditor/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxMultiView/1 Configuration/deferRendering.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/deferRendering.md
Labels: cherry-pick, 23_1

#4645 Remove duplicated articles
  api-reference/10 UI Components/dxToast/1 Configuration/contentTemplate.md
  concepts/05 UI Components/TextBox/05 Task-Specific Modes.md
  concepts/05 UI Components/TextBox/10 Handle the Value Change Event.md
  concepts/05 UI Components/TextBox/13 Handle the Keyboard Events.md
  concepts/05 UI Components/TextBox/15 Limit the String Length.md
  concepts/05 UI Components/Toast/05 Show and Hide the Toast/10 Events.md
  concepts/05 UI Components/Toast/10 Customize the Content.md
  concepts/05 UI Components/Toast/15 Resize and Relocate.md
Labels: 23_1

#4646 TabPanel: fix link to MultiView (T1145694)
  api-reference/10 UI Components/dxTabPanel/dxTabPanel.md
Labels: 22_2

#4647 TabPanel: fix link to MultiView (#4646)
  api-reference/10 UI Components/dxTabPanel/dxTabPanel.md
Labels: cherry-pick, 22_1

#4648 TabPanel: fix link to MultiView (#4646)
  api-reference/10 UI Components/dxTabPanel/dxTabPanel.md
Labels: cherry-pick, 23_1

#4650 Delete duplicated topics
  api-reference/10 UI Components/dxToolbar/1 Configuration/menuItemTemplate.md
  api-reference/10 UI Components/dxTreeView/1 Configuration/itemTemplate.md
  api-reference/_hidden/dxPopupToolbarItem/widget.md
  api-reference/_hidden/dxToolbarItem/location.md
  api-reference/_hidden/dxToolbarItem/options.md
  api-reference/_hidden/dxToolbarItem/widget.md
  api-reference/_hidden/dxTreeViewItem/items.md
  concepts/05 UI Components/Toolbar/05 Specify Item Type.md
  concepts/05 UI Components/Toolbar/10 Specify Item Location.md
  concepts/05 UI Components/Toolbar/15 Customize Item Appearance.md
  concepts/05 UI Components/TreeView/05 Use Hierarchical Data.md
  concepts/05 UI Components/TreeView/07 Use Plain Data.md
  concepts/05 UI Components/TreeView/30 Customize Node Appearance.md
Labels: 23_1

#4628 DataGrid: update Export Angular code snippet (T1144111)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
Labels: 22_2

#4656 DataGrid: update Export Angular code snippet (T1144111)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
Labels: cherry-pick, 22_1

#4662 UI: update the hideToasts() method import (T1147083)
  api-reference/50 Common/utils/ui/3 Methods/hideToasts().md
Labels: 22_2

#4663 UI: update the hideToasts() method import (T1147083)
  api-reference/50 Common/utils/ui/3 Methods/hideToasts().md
Labels: cherry-pick, 22_1

#4664 UI: update the hideToasts() method import (T1147083)
  api-reference/50 Common/utils/ui/3 Methods/hideToasts().md
Labels: cherry-pick, 23_1

#4668 DataGrid: update remoteOperations.groupPaging description T1058703
  api-reference/10 UI Components/dxDataGrid/1 Configuration/remoteOperations/groupPaging.md
Labels: 22_2

#4669 DataGrid: update remoteOperations.groupPaging description T1058703 (#…
  api-reference/10 UI Components/dxDataGrid/1 Configuration/remoteOperations/groupPaging.md
Labels: cherry-pick, 22_1

#4665 BarGauge: describe resolveLabelOverlapping
  api-reference/10 UI Components/dxBarGauge/1 Configuration/resolveLabelOverlapping.md
Labels: 23_1

#4674 Charts: delete aggregateByCategory description
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/aggregateByCategory.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/aggregateByCategory.md
  images/ChartJS/chart-aggregateByCategory.png
  images/ChartJS/range-selector-aggregateByCategory.png
Labels: 23_1

#4675 Custom Source: update Angular code snippets (T1149011)
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/5 Server-Side Data Processing.md
Labels: 22_2

#4678 Custom Source: update Angular code snippets (T1149011)
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/5 Server-Side Data Processing.md
Labels: cherry-pick, 22_1

#4679 Custom Source: update Angular code snippets (T1149011)
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/5 Server-Side Data Processing.md
Labels: cherry-pick, 23_1

#4676 Add new buttons
  includes/btn-open-codepen.md
  includes/btn-open-codesandbox.md
  includes/btn-open-demo.md
  includes/btn-open-github.md
Labels: 23_1

#4680 SelectBox: update Event Handling section (T1149482)
  concepts/05 UI Components/SelectBox/04 Handle the Value Change Event.md
Labels: 22_2

#4685 DataGrid: add crossreference link (T855629)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/column.md
Labels: 22_2

#4686 DataGrid: add crossreference link (T855629)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/column.md
Labels: cherry-pick, 22_1

#4687 DataGrid: add crossreference link (T855629) (#4685)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/column.md
Labels: cherry-pick, 23_1
