Repository DevExpress/devextreme-documentation, pull requests merged in 2023-03, with the labels that each got.

#4692 List: describe 'selectByClick'
  api-reference/10 UI Components/dxList/1 Configuration/selectByClick.md
  api-reference/10 UI Components/dxMenuBase/1 Configuration/selectByClick.md
  api-reference/10 UI Components/dxTreeView/1 Configuration/selectByClick.md
Labels: 23_1

#4697 Fix LuceneIndexGenerator
  api-reference/40 Common Types/40 Common Types.md
Labels: 23_1

#4695 DataGrid: update Rendering Optimzation + How To sections
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/00 Rendering Optimization.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/05 Render Only Visible Rows and Columns.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/10 Render Elements with Complex Content Last.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/15 Prevent Columns from Adjusting Their Widths to the Content.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/20 Do Not Use Checkboxes in Boolean Columns.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/25 Implement onCellPrepared Instead of cellTemplate for Conditional Formatting.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/30 Use repaintChangesOnly.md
  concepts/05 UI Components/DataGrid/99 How To/Dynamically Change Form Item Properties in the Editing State.md
Labels: 22_2

#4698 DataGrid: update Rendering Optimzation + How To sections (#4695)
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/00 Rendering Optimization.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/05 Render Only Visible Rows and Columns.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/10 Render Elements with Complex Content Last.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/15 Prevent Columns from Adjusting Their Widths to the Content.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/20 Do Not Use Checkboxes in Boolean Columns.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/25 Implement onCellPrepared Instead of cellTemplate for Conditional Formatting.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/30 Use repaintChangesOnly.md
  concepts/05 UI Components/DataGrid/99 How To/Dynamically Change Form Item Properties in the Editing State.md
Labels: cherry-pick, 22_1

#4699 DataGrid: update Rendering Optimzation + How To sections (#4695)
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/00 Rendering Optimization.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/05 Render Only Visible Rows and Columns.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/10 Render Elements with Complex Content Last.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/15 Prevent Columns from Adjusting Their Widths to the Content.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/20 Do Not Use Checkboxes in Boolean Columns.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/25 Implement onCellPrepared Instead of cellTemplate for Conditional Formatting.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/030 Rendering Optimization/30 Use repaintChangesOnly.md
  concepts/05 UI Components/DataGrid/99 How To/Dynamically Change Form Item Properties in the Editing State.md
Labels: cherry-pick, 23_1

#4704 DataGrid: add reference to the columnWidth prop (T1000281)
  api-reference/_hidden/GridBaseColumn/width.md
Labels: 22_2

#4705 DataGrid: add reference to the columnWidth prop (T1000281)
  api-reference/_hidden/GridBaseColumn/width.md
Labels: cherry-pick, 22_1

#4706 DataGrid: add reference to the columnWidth prop (T1000281)
  api-reference/_hidden/GridBaseColumn/width.md
Labels: cherry-pick, 23_1

#4703 DataGrid: add note about editing mode (T1123375)
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
Labels: 22_2

#4711 DataGrid: add note about editing mode (T1123375)
  api-reference/40 Common Types/00 Grids/00 Grids.md
  api-reference/40 Common Types/40 Common Types.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/40 Form Mode.md
Labels: cherry-pick, 23_1

#4713 Grids: fix images in ColumnChooser.mode
  api-reference/10 UI Components/GridBase/1 Configuration/columnChooser/mode.md
  api-reference/40 Common Types/15 grids/ColumnChooser/mode.md
Labels: 23_1

#4717 Troubleshooting Drop-Down editors: fix demo button
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/15 AspNet.Data.createStore() Method Specifics.md
Labels: 22_2

#4718 Troubleshooting Drop-Down editors: fix demo button (#4717)
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/15 AspNet.Data.createStore() Method Specifics.md
Labels: cherry-pick, 22_1

#4719 Troubleshooting Drop-Down editors: fix demo button (#4717)
  concepts/80 Troubleshooting/50 A Drop-Down Editor Does Not Show Data/15 AspNet.Data.createStore() Method Specifics.md
Labels: cherry-pick, 23_1

#4707 Vue Integration Guide: add tabs with Composition API
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/60 Import DevExtreme Components.md
  concepts/55 Vue Components/20 Component Configuration Syntax/14 Properties of the Object Type.md
  concepts/55 Vue Components/20 Component Configuration Syntax/17 Collections.md
  concepts/55 Vue Components/20 Component Configuration Syntax/20 Event Handling.md
  concepts/55 Vue Components/20 Component Configuration Syntax/25 Callback Functions.md
  concepts/55 Vue Components/20 Component Configuration Syntax/32 One-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/33 Two-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/36 Declare Content in the Markup.md
  concepts/55 Vue Components/20 Component Configuration Syntax/37 Templates.md
  concepts/55 Vue Components/20 Component Configuration Syntax/42 Call Methods.md
  concepts/55 Vue Components/20 Component Configuration Syntax/72 DevExtreme Validation Features.md
  concepts/55 Vue Components/20 Component Configuration Syntax/75 Vue Form Input Bindings Support.md
Labels: 22_2

#4720 Vue Integration Guide: add tabs with Composition API
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/60 Import DevExtreme Components.md
  concepts/55 Vue Components/20 Component Configuration Syntax/14 Properties of the Object Type.md
  concepts/55 Vue Components/20 Component Configuration Syntax/17 Collections.md
  concepts/55 Vue Components/20 Component Configuration Syntax/20 Event Handling.md
  concepts/55 Vue Components/20 Component Configuration Syntax/25 Callback Functions.md
  concepts/55 Vue Components/20 Component Configuration Syntax/32 One-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/33 Two-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/36 Declare Content in the Markup.md
  concepts/55 Vue Components/20 Component Configuration Syntax/37 Templates.md
  concepts/55 Vue Components/20 Component Configuration Syntax/42 Call Methods.md
  concepts/55 Vue Components/20 Component Configuration Syntax/72 DevExtreme Validation Features.md
  concepts/55 Vue Components/20 Component Configuration Syntax/75 Vue Form Input Bindings Support.md
Labels: cherry-pick, 22_1

#4721 Vue Integration Guide: add tabs with Composition API
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/60 Import DevExtreme Components.md
  concepts/55 Vue Components/20 Component Configuration Syntax/14 Properties of the Object Type.md
  concepts/55 Vue Components/20 Component Configuration Syntax/17 Collections.md
  concepts/55 Vue Components/20 Component Configuration Syntax/20 Event Handling.md
  concepts/55 Vue Components/20 Component Configuration Syntax/25 Callback Functions.md
  concepts/55 Vue Components/20 Component Configuration Syntax/32 One-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/33 Two-Way Property Binding.md
  concepts/55 Vue Components/20 Component Configuration Syntax/36 Declare Content in the Markup.md
  concepts/55 Vue Components/20 Component Configuration Syntax/37 Templates.md
  concepts/55 Vue Components/20 Component Configuration Syntax/42 Call Methods.md
  concepts/55 Vue Components/20 Component Configuration Syntax/72 DevExtreme Validation Features.md
  concepts/55 Vue Components/20 Component Configuration Syntax/75 Vue Form Input Bindings Support.md
Labels: cherry-pick, 23_1

#4727 Funnel: update Rearrange Legend Items code snippet (T1152571)
  concepts/05 UI Components/Funnel/35 Legend/20 Rearrange Legend Items.md
Labels: 22_2

#4728 Funnel: update Rearrange Legend Items code snippet (T1152571)
  concepts/05 UI Components/Funnel/35 Legend/20 Rearrange Legend Items.md
Labels: cherry-pick, 22_1

#4731 Funnel: update Rearrange Legend Items code snippet (T1152571)
  concepts/05 UI Components/Funnel/35 Legend/20 Rearrange Legend Items.md
Labels: cherry-pick, 23_1

#4732 DataGrid: add code snippet to the onAdaptiveDetailRowPreparing prop (T1142925)
  api-reference/10 UI Components/GridBase/1 Configuration/onAdaptiveDetailRowPreparing.md
Labels: 22_2

#4734 DataGrid: add code snippet to the onAdaptiveDetailRowPreparing prop (…
  api-reference/10 UI Components/GridBase/1 Configuration/onAdaptiveDetailRowPreparing.md
Labels: cherry-pick, 22_1

#4735 DataGrid: add code snippet to the onAdaptiveDetailRowPreparing prop
  api-reference/10 UI Components/GridBase/1 Configuration/onAdaptiveDetailRowPreparing.md
Labels: cherry-pick, 23_1

#4740 TreeView: add the collapseIcon and expandIcon properties description (23.1)
  api-reference/10 UI Components/dxTreeView/1 Configuration/collapseIcon.md
  api-reference/10 UI Components/dxTreeView/1 Configuration/expandIcon.md
  includes/treeview-custom-icons.md
Labels: 23_1

#4742 Correct framework usage in new docs (22.2)
  concepts/05 UI Components/Calendar/05 Handle the Value Change Event.md
  concepts/05 UI Components/Chart/10 Series/10 Hover/10 Events.md
  concepts/05 UI Components/Chart/10 Series/20 Selection/10 Events.md
  concepts/05 UI Components/Chart/14 Series Points/10 Hover/10 Events.md
  concepts/05 UI Components/Chart/14 Series Points/20 Selection/10 Events.md
  concepts/05 UI Components/Chart/30 Tooltips/20 Handle Tooltip Events.md
  concepts/05 UI Components/Chart/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/ContextMenu/03 Access the Clicked Item.md
  concepts/05 UI Components/ContextMenu/10 Open and Close the Context Menu/30 Events.md
  concepts/05 UI Components/DataGrid/20 Editing/30 Events/Events.md
  concepts/05 UI Components/DataGrid/45 Grouping/30 Events.md
  concepts/05 UI Components/DataGrid/50 Selection/30 Events.md
  concepts/05 UI Components/DataGrid/73 Focused Row.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/10 Open and Close the Drawer.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/10 Add an Embedded Element.md
  concepts/05 UI Components/DropDownBox/15 Synchronize with the Embedded Element.md
  concepts/05 UI Components/FileUploader/00 Overview.md
  concepts/05 UI Components/Form/10 Organize Simple Items/10 In Tabs/10 Custom Content within a Tab.md
  concepts/05 UI Components/Form/25 Handle the Value Change Event.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/07 Angular.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/10 AngularJS.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/20 Knockout.md
  concepts/05 UI Components/Funnel/14 Funnel Items/10 Hover/10 Events.md
  concepts/05 UI Components/Funnel/14 Funnel Items/20 Selection/10 Events.md
  concepts/05 UI Components/Funnel/35 Legend/30 User Interaction.md
  concepts/05 UI Components/Funnel/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/List/20 Scrolling/10 Events.md
  concepts/05 UI Components/List/25 Selection/10 Events.md
  concepts/05 UI Components/List/30 Item Reordering/10 Events.md
  concepts/05 UI Components/List/35 Item Deletion/10 Events.md
  concepts/05 UI Components/LoadPanel/05 Show and Hide Using the API.md
Labels: 22_2

#4743 Correct framework usage in new docs (22.2) (#4742)
  concepts/05 UI Components/Calendar/05 Handle the Value Change Event.md
  concepts/05 UI Components/Chart/10 Series/10 Hover/10 Events.md
  concepts/05 UI Components/Chart/10 Series/20 Selection/10 Events.md
  concepts/05 UI Components/Chart/14 Series Points/10 Hover/10 Events.md
  concepts/05 UI Components/Chart/14 Series Points/20 Selection/10 Events.md
  concepts/05 UI Components/Chart/30 Tooltips/20 Handle Tooltip Events.md
  concepts/05 UI Components/Chart/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/ContextMenu/03 Access the Clicked Item.md
  concepts/05 UI Components/ContextMenu/10 Open and Close the Context Menu/30 Events.md
  concepts/05 UI Components/DataGrid/20 Editing/30 Events/Events.md
  concepts/05 UI Components/DataGrid/45 Grouping/30 Events.md
  concepts/05 UI Components/DataGrid/50 Selection/30 Events.md
  concepts/05 UI Components/DataGrid/73 Focused Row.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/10 Open and Close the Drawer.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/10 Add an Embedded Element.md
  concepts/05 UI Components/DropDownBox/15 Synchronize with the Embedded Element.md
  concepts/05 UI Components/FileUploader/00 Overview.md
  concepts/05 UI Components/Form/10 Organize Simple Items/10 In Tabs/10 Custom Content within a Tab.md
  concepts/05 UI Components/Form/25 Handle the Value Change Event.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/07 Angular.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/10 AngularJS.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/20 Knockout.md
  concepts/05 UI Components/Funnel/14 Funnel Items/10 Hover/10 Events.md
  concepts/05 UI Components/Funnel/14 Funnel Items/20 Selection/10 Events.md
  concepts/05 UI Components/Funnel/35 Legend/30 User Interaction.md
  concepts/05 UI Components/Funnel/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/List/20 Scrolling/10 Events.md
  concepts/05 UI Components/List/25 Selection/10 Events.md
  concepts/05 UI Components/List/30 Item Reordering/10 Events.md
  concepts/05 UI Components/List/35 Item Deletion/10 Events.md
  concepts/05 UI Components/LoadPanel/05 Show and Hide Using the API.md
Labels: cherry-pick, 22_1

#4744 Correct framework usage in new docs
  concepts/05 UI Components/Calendar/05 Handle the Value Change Event.md
  concepts/05 UI Components/Chart/10 Series/10 Hover/10 Events.md
  concepts/05 UI Components/Chart/10 Series/20 Selection/10 Events.md
  concepts/05 UI Components/Chart/14 Series Points/10 Hover/10 Events.md
  concepts/05 UI Components/Chart/14 Series Points/20 Selection/10 Events.md
  concepts/05 UI Components/Chart/30 Tooltips/20 Handle Tooltip Events.md
  concepts/05 UI Components/Chart/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/ContextMenu/03 Access the Clicked Item.md
  concepts/05 UI Components/ContextMenu/10 Open and Close the Context Menu/30 Events.md
  concepts/05 UI Components/DataGrid/20 Editing/30 Events/Events.md
  concepts/05 UI Components/DataGrid/45 Grouping/30 Events.md
  concepts/05 UI Components/DataGrid/50 Selection/30 Events.md
  concepts/05 UI Components/DataGrid/73 Focused Row.md
  concepts/05 UI Components/Drawer/Getting Started with Navigation Drawer/10 Open and Close the Drawer.md
  concepts/05 UI Components/DropDownBox/00 Getting Started with DropDownBox/10 Add an Embedded Element.md
  concepts/05 UI Components/DropDownBox/15 Synchronize with the Embedded Element.md
  concepts/05 UI Components/FileUploader/00 Overview.md
  concepts/05 UI Components/Form/10 Organize Simple Items/10 In Tabs/10 Custom Content within a Tab.md
  concepts/05 UI Components/Form/25 Handle the Value Change Event.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/07 Angular.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/10 AngularJS.md
  concepts/05 UI Components/Funnel/03 Data Binding/26 Update Data/05 JavaScript Array/20 Knockout.md
  concepts/05 UI Components/Funnel/14 Funnel Items/10 Hover/10 Events.md
  concepts/05 UI Components/Funnel/14 Funnel Items/20 Selection/10 Events.md
  concepts/05 UI Components/Funnel/35 Legend/30 User Interaction.md
  concepts/05 UI Components/Funnel/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/List/20 Scrolling/10 Events.md
  concepts/05 UI Components/List/25 Selection/10 Events.md
  concepts/05 UI Components/List/30 Item Reordering/10 Events.md
  concepts/05 UI Components/List/35 Item Deletion/10 Events.md
  concepts/05 UI Components/LoadPanel/05 Show and Hide Using the API.md
Labels: cherry-pick, 23_1

#4736 Correct framework usage in new docs: CSS classes, templates, data layer
  api-reference/10 UI Components/dxForm/3 Methods/itemOption(id_option_value).md
  api-reference/10 UI Components/zz CSS Classes/dx-field-label.md
  api-reference/10 UI Components/zz CSS Classes/dx-field-value-static.md
  api-reference/10 UI Components/zz CSS Classes/dx-field-value.md
  api-reference/10 UI Components/zz CSS Classes/dx-field.md
  api-reference/10 UI Components/zz CSS Classes/dx-fieldset-header.md
  api-reference/10 UI Components/zz CSS Classes/dx-fieldset.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/05 Create a Toolbar and its Items.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/15 Customize Items.md
  concepts/05 UI Components/Tooltip/05 Show and Hide the Tooltip/10 Events.md
  concepts/05 UI Components/TreeList/20 Editing/30 Events/Events.md
  concepts/05 UI Components/TreeList/50 Selection/30 Events.md
  concepts/05 UI Components/TreeList/60 Expand and Collapse Rows/30 Events.md
  concepts/05 UI Components/TreeList/69 Focused Row.md
  concepts/05 UI Components/TreeView/20 Expand and Collapse Nodes/10 Events.md
  concepts/05 UI Components/VectorMap/40 End-User Interaction/40 Click Handling/40 Generic Click.md
  concepts/05 UI Components/zz Common/30 Templates/30 3rd-Party Template Engines.md
  concepts/60 Themes and Styles/30 Icons/40 Custom Images as Icons.md
  concepts/70 Data Binding/5 Data Layer/05 Asynchrony.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/1 From url.md
  concepts/70 Data Binding/5 Data Layer/55 Handling Errors.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/0 Connect to RESTful Service.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/Custom Sources.md
  includes/custom-templates.md
  includes/data-binding-promise.md
Labels: 22_2

#4746 Correct framework usage in new docs: CSS classes, templates, data lay…
  api-reference/10 UI Components/dxForm/3 Methods/itemOption(id_option_value).md
  api-reference/10 UI Components/zz CSS Classes/dx-field-label.md
  api-reference/10 UI Components/zz CSS Classes/dx-field-value-static.md
  api-reference/10 UI Components/zz CSS Classes/dx-field-value.md
  api-reference/10 UI Components/zz CSS Classes/dx-field.md
  api-reference/10 UI Components/zz CSS Classes/dx-fieldset-header.md
  api-reference/10 UI Components/zz CSS Classes/dx-fieldset.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/05 Create a Toolbar and its Items.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/15 Customize Items.md
  concepts/05 UI Components/Tooltip/05 Show and Hide the Tooltip/10 Events.md
  concepts/05 UI Components/TreeList/20 Editing/30 Events/Events.md
  concepts/05 UI Components/TreeList/50 Selection/30 Events.md
  concepts/05 UI Components/TreeList/60 Expand and Collapse Rows/30 Events.md
  concepts/05 UI Components/TreeList/69 Focused Row.md
  concepts/05 UI Components/TreeView/20 Expand and Collapse Nodes/10 Events.md
  concepts/05 UI Components/VectorMap/40 End-User Interaction/40 Click Handling/40 Generic Click.md
  concepts/05 UI Components/zz Common/30 Templates/30 3rd-Party Template Engines.md
  concepts/60 Themes and Styles/30 Icons/40 Custom Images as Icons.md
  concepts/70 Data Binding/5 Data Layer/05 Asynchrony.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/1 From url.md
  concepts/70 Data Binding/5 Data Layer/55 Handling Errors.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/0 Connect to RESTful Service.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/Custom Sources.md
  includes/custom-templates.md
  includes/data-binding-promise.md
Labels: cherry-pick, 23_1

#4752 Toast: update stack methods fields
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: 23_1

#4753 DataGrid: update Add a Custom Button section (T1153956)
  concepts/05 UI Components/DataGrid/15 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/3 Add a Custom Button.md
Labels: 22_2

#4756 DataGrid: update Add a Custom Button section (T1153956) (#4753)
  concepts/05 UI Components/DataGrid/15 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/3 Add a Custom Button.md
Labels: cherry-pick, 21_2

#4757 Components: update incorrect framework usage
  concepts/05 UI Components/PieChart/35 Legend/30 User Interaction.md
  concepts/05 UI Components/PieChart/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Data Binding.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/10 Events.md
  concepts/05 UI Components/ProgressBar/10 Handle the Value Change Event.md
  concepts/05 UI Components/RadioGroup/05 Handle the Value Change Event.md
  concepts/05 UI Components/RangeSlider/10 Handle the Value Change Event.md
  concepts/05 UI Components/Sankey/03 Data Binding/10 JSON Data.md
  concepts/05 UI Components/Sankey/03 Data Binding/26 Update Data/05 JavaScript Array.md
  concepts/05 UI Components/Sankey/05 Nodes and Links/10 Hover/10 Events.md
  concepts/05 UI Components/Sankey/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/020 Add Appointments/030 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/030 Update Appointments/030 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/040 Delete Appointments/030 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/050 Customize Appointment.md
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
  concepts/05 UI Components/Scheduler/050 Timetable.md
  concepts/05 UI Components/Slider/10 Handle the Value Change Event.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/10 Create Custom Tabs.md
  concepts/05 UI Components/TagBox/02 Data Binding/10 JSON Data.md
  concepts/05 UI Components/TextArea/13 Handle the Keyboard Events.md
  concepts/05 UI Components/TextBox/10 Handle the Value Change Event.md
  concepts/05 UI Components/TextBox/20 Specify a Mask for the Input.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/10 Show and Hide the Toast.md
Labels: 22_2

#4758 Components: update incorrect framework usage (#4757)
  concepts/05 UI Components/PieChart/35 Legend/30 User Interaction.md
  concepts/05 UI Components/PieChart/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Data Binding.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/10 Events.md
  concepts/05 UI Components/ProgressBar/10 Handle the Value Change Event.md
  concepts/05 UI Components/RadioGroup/05 Handle the Value Change Event.md
  concepts/05 UI Components/RangeSlider/10 Handle the Value Change Event.md
  concepts/05 UI Components/Sankey/03 Data Binding/10 JSON Data.md
  concepts/05 UI Components/Sankey/03 Data Binding/26 Update Data/05 JavaScript Array.md
  concepts/05 UI Components/Sankey/05 Nodes and Links/10 Hover/10 Events.md
  concepts/05 UI Components/Sankey/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/020 Add Appointments/030 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/030 Update Appointments/030 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/040 Delete Appointments/030 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/050 Customize Appointment.md
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
  concepts/05 UI Components/Scheduler/050 Timetable.md
  concepts/05 UI Components/Slider/10 Handle the Value Change Event.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/10 Create Custom Tabs.md
  concepts/05 UI Components/TagBox/02 Data Binding/10 JSON Data.md
  concepts/05 UI Components/TextArea/13 Handle the Keyboard Events.md
  concepts/05 UI Components/TextBox/10 Handle the Value Change Event.md
  concepts/05 UI Components/TextBox/20 Specify a Mask for the Input.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/10 Show and Hide the Toast.md
Labels: cherry-pick, 22_1

#4759 Components: update incorrect framework usage (#4757)
  concepts/05 UI Components/PieChart/35 Legend/30 User Interaction.md
  concepts/05 UI Components/PieChart/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/PivotGrid/030 Data Binding/10 Data Binding.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/10 Events.md
  concepts/05 UI Components/ProgressBar/10 Handle the Value Change Event.md
  concepts/05 UI Components/RadioGroup/05 Handle the Value Change Event.md
  concepts/05 UI Components/RangeSlider/10 Handle the Value Change Event.md
  concepts/05 UI Components/Sankey/03 Data Binding/10 JSON Data.md
  concepts/05 UI Components/Sankey/03 Data Binding/26 Update Data/05 JavaScript Array.md
  concepts/05 UI Components/Sankey/05 Nodes and Links/10 Hover/10 Events.md
  concepts/05 UI Components/Sankey/99 Client-Side Exporting and Printing/10 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/020 Add Appointments/030 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/030 Update Appointments/030 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/040 Delete Appointments/030 Events.md
  concepts/05 UI Components/Scheduler/030 Appointments/050 Customize Appointment.md
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
  concepts/05 UI Components/Scheduler/050 Timetable.md
  concepts/05 UI Components/Slider/10 Handle the Value Change Event.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/10 Create Custom Tabs.md
  concepts/05 UI Components/TagBox/02 Data Binding/10 JSON Data.md
  concepts/05 UI Components/TextArea/13 Handle the Keyboard Events.md
  concepts/05 UI Components/TextBox/10 Handle the Value Change Event.md
  concepts/05 UI Components/TextBox/20 Specify a Mask for the Input.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/10 Show and Hide the Toast.md
Labels: cherry-pick, 23_1

#4760 Chart: update demo link (T1151384)
  concepts/05 UI Components/Chart/65 Constant Lines.md
Labels: 22_2

#4761 Chart: update demo link (T1151384)
  concepts/05 UI Components/Chart/65 Constant Lines.md
Labels: cherry-pick, 22_1

#4762 Chart: update demo link (T1151384)
  concepts/05 UI Components/Chart/65 Constant Lines.md
Labels: cherry-pick, 23_1

#4748 Gauges: add centerTemplate properties description
  api-reference/10 UI Components/dxBarGauge/1 Configuration/centerTemplate.md
  api-reference/10 UI Components/dxCircularGauge/1 Configuration/centerTemplate.md
  includes/gauges-centertemplate-code.md
Labels: 23_1

#4770 Vue Configuration Syntax: fix typo
  concepts/55 Vue Components/20 Component Configuration Syntax/72 DevExtreme Validation Features.md
Labels: 22_2

#4771 Vue Configuration Syntax: fix typo (#4770)
  concepts/55 Vue Components/20 Component Configuration Syntax/72 DevExtreme Validation Features.md
Labels: cherry-pick, 22_1

#4772 Vue Configuration Syntax: fix typo (#4770)
  concepts/55 Vue Components/20 Component Configuration Syntax/72 DevExtreme Validation Features.md
Labels: cherry-pick, 23_1

#4773 Popup: describe enableBodyScroll
  api-reference/10 UI Components/dxPopup/1 Configuration/enableBodyScroll.md
Labels: 23_1

#4480 CLI: update commands and tags
  concepts/05 UI Components/zz Common/15 Advanced/40 3rd-Party Frameworks Integration API/3rd-Party Frameworks Integration API.md
  concepts/40 Angular Components/10 Getting Started/02 Create a DevExtreme Application.md
  concepts/40 Angular Components/30 Application Template/05 Generate a New Application.md
  concepts/50 React Components/02 Create a DevExtreme Application.md
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
  concepts/55 Vue Components/02 Create a DevExtreme Application.md
  concepts/55 Vue Components/50 Application Template/05 Generate a New Application.md
  concepts/Common/DevExtreme CLI/00 DevExtreme CLI.md
  concepts/Common/DevExtreme CLI/00 Requirements.md
  concepts/Common/DevExtreme CLI/01 Installation.md
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/10 Create a New Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/20 Add the DevExtreme Layout to an Existing Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/30 Add a View to the Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/DevExtreme Application.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/05 Build a Custom Color Scheme.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/07 Export Theme Variables.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/08 Export Theme Metadata.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/20 Examples.md
Labels: 22_2

#4774 CLI: update commands and tags (#4480)
  concepts/05 UI Components/zz Common/15 Advanced/40 3rd-Party Frameworks Integration API/3rd-Party Frameworks Integration API.md
  concepts/40 Angular Components/10 Getting Started/02 Create a DevExtreme Application.md
  concepts/40 Angular Components/30 Application Template/05 Generate a New Application.md
  concepts/50 React Components/02 Create a DevExtreme Application.md
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
  concepts/55 Vue Components/02 Create a DevExtreme Application.md
  concepts/55 Vue Components/50 Application Template/05 Generate a New Application.md
  concepts/Common/DevExtreme CLI/00 DevExtreme CLI.md
  concepts/Common/DevExtreme CLI/00 Requirements.md
  concepts/Common/DevExtreme CLI/01 Installation.md
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/10 Create a New Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/20 Add the DevExtreme Layout to an Existing Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/30 Add a View to the Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/DevExtreme Application.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/05 Build a Custom Color Scheme.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/07 Export Theme Variables.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/08 Export Theme Metadata.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/20 Examples.md
Labels: cherry-pick, 22_1

#4775 CLI: update commands and tags (#4480)
  concepts/05 UI Components/zz Common/15 Advanced/40 3rd-Party Frameworks Integration API/3rd-Party Frameworks Integration API.md
  concepts/40 Angular Components/10 Getting Started/02 Create a DevExtreme Application.md
  concepts/40 Angular Components/30 Application Template/05 Generate a New Application.md
  concepts/50 React Components/02 Create a DevExtreme Application.md
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
  concepts/55 Vue Components/02 Create a DevExtreme Application.md
  concepts/55 Vue Components/50 Application Template/05 Generate a New Application.md
  concepts/Common/DevExtreme CLI/00 DevExtreme CLI.md
  concepts/Common/DevExtreme CLI/00 Requirements.md
  concepts/Common/DevExtreme CLI/01 Installation.md
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/10 Create a New Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/20 Add the DevExtreme Layout to an Existing Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/30 Add a View to the Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/DevExtreme Application.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/05 Build a Custom Color Scheme.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/07 Export Theme Variables.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/08 Export Theme Metadata.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/20 Examples.md
Labels: cherry-pick, 23_1

#4763 Correct framework usage in new docs
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/25 Customize Item Appearance.md
  concepts/05 UI Components/Lookup/03 Data Binding/10 JSON Data.md
  concepts/05 UI Components/Map/20 Configure Markers/15 Handle the Related Events.md
  concepts/05 UI Components/Map/25 Configure Routes/15 Handle the Related Events.md
  concepts/05 UI Components/Menu/00 Getting Started with Menu/10 Create Submenus.md
  concepts/05 UI Components/Menu/03 Access the Clicked Item.md
  concepts/05 UI Components/PieChart/03 Data Binding/10 JSON Data.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/07 Angular.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/10 AngularJS.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/20 Knockout.md
  concepts/05 UI Components/PieChart/10 Series/10 Hover/10 Events.md
  concepts/05 UI Components/PieChart/10 Series/20 Selection/10 Events.md
  concepts/05 UI Components/PieChart/30 Tooltips/20 Handle Tooltip Events.md
  concepts/Common/Security Considerations/20 HTML Encoding/20 Encode Template Data.md
Labels: 22_2

#4776 Correct framework usage in new docs (#4763)
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/25 Customize Item Appearance.md
  concepts/05 UI Components/Lookup/03 Data Binding/10 JSON Data.md
  concepts/05 UI Components/Map/20 Configure Markers/15 Handle the Related Events.md
  concepts/05 UI Components/Map/25 Configure Routes/15 Handle the Related Events.md
  concepts/05 UI Components/Menu/00 Getting Started with Menu/10 Create Submenus.md
  concepts/05 UI Components/Menu/03 Access the Clicked Item.md
  concepts/05 UI Components/PieChart/03 Data Binding/10 JSON Data.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/05 jQuery.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/07 Angular.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/10 AngularJS.md
  concepts/05 UI Components/PieChart/03 Data Binding/26 Update Data/05 JavaScript Array/20 Knockout.md
  concepts/05 UI Components/PieChart/10 Series/10 Hover/10 Events.md
  concepts/05 UI Components/PieChart/10 Series/20 Selection/10 Events.md
  concepts/05 UI Components/PieChart/30 Tooltips/20 Handle Tooltip Events.md
  concepts/Common/Security Considerations/20 HTML Encoding/20 Encode Template Data.md
Labels: cherry-pick, 22_1

#4785 DataGrid: update deleteRow(rowIndex) (T1116403)
  api-reference/10 UI Components/GridBase/3 Methods/deleteRow(rowIndex).md
Labels: 22_2

#4786 DataGrid: update deleteRow(rowIndex) (T1116403)
  api-reference/10 UI Components/GridBase/3 Methods/deleteRow(rowIndex).md
Labels: cherry-pick, 22_1

#4787 DataGrid: update deleteRow(rowIndex) (T1116403)
  api-reference/10 UI Components/GridBase/3 Methods/deleteRow(rowIndex).md
Labels: cherry-pick, 23_1

#4788 DataGrid: update toolbar description (T1155240/T1155237)
  api-reference/10 UI Components/dxToolbar/1 Configuration/multiline.md
  api-reference/_hidden/dxDataGridToolbar/dxDataGridToolbar.md
Labels: 22_2

#4789 DataGrid: update toolbar description (T1155237)
  api-reference/_hidden/dxDataGridToolbar/dxDataGridToolbar.md
Labels: cherry-pick, 22_1

#4790 DataGrid: update toolbar description (T1155240/T1155237)
  api-reference/10 UI Components/dxToolbar/1 Configuration/multiline.md
  api-reference/_hidden/dxDataGridToolbar/dxDataGridToolbar.md
Labels: cherry-pick, 23_1

#4783 PieChart: add code snippets for centerTemplate
  api-reference/10 UI Components/dxPieChart/1 Configuration/centerTemplate.md
  includes/gauges-centertemplate-code.md
Labels: 23_1

#4791 PivotGridDataSource: update the remoteOperations property
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/remoteOperations.md
Labels: 22_2

#4795 PivotGridDataSource: update the remoteOperations property (#4791)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/remoteOperations.md
Labels: cherry-pick, 22_1

#4796 PivotGridDataSource: update the remoteOperations property (#4791)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/remoteOperations.md
Labels: cherry-pick, 23_1

#4798 Correct framework usage in new docs (#4782)
  concepts/05 UI Components/ButtonGroup/00 Getting Started with ButtonGroup/1 Create the ButtonGroup.md
  concepts/05 UI Components/Funnel/03 Data Binding/10 JSON Data.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/0 Connect to RESTful Service.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/1 Load Data in Raw Mode.md
  concepts/Common/Distribution Channels/05 CDN/05 CDN.md
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
  concepts/Common/Migrate to the New Version/10 Upgrade DevExtreme Sources/4 CDN Services.md
  concepts/Common/Migrate to the New Version/10 Upgrade DevExtreme Sources/7 npm Packages.md
  concepts/Common/Modularity/01 Link Modules/10 Use Webpack.md
  concepts/Common/Modularity/01 Link Modules/20 Use jspm.md
  concepts/Common/Modularity/01 Link Modules/30 Use RequireJS.md
Labels: cherry-pick, 23_1

#4797 Correct framework usage in new docs (#4782)
  concepts/05 UI Components/ButtonGroup/00 Getting Started with ButtonGroup/1 Create the ButtonGroup.md
  concepts/05 UI Components/Funnel/03 Data Binding/10 JSON Data.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/0 Connect to RESTful Service.md
  concepts/70 Data Binding/51 Data Source Examples/3 Custom Sources/1 Load Data in Raw Mode.md
  concepts/Common/Distribution Channels/05 CDN/05 CDN.md
  concepts/Common/Localization/01 Dictionaries/Dictionaries.md
  concepts/Common/Migrate to the New Version/10 Upgrade DevExtreme Sources/4 CDN Services.md
  concepts/Common/Migrate to the New Version/10 Upgrade DevExtreme Sources/7 npm Packages.md
  concepts/Common/Modularity/01 Link Modules/10 Use Webpack.md
  concepts/Common/Modularity/01 Link Modules/20 Use jspm.md
  concepts/Common/Modularity/01 Link Modules/30 Use RequireJS.md
Labels: cherry-pick, 22_1

#4803 Correct framework usage in new docs: Distribution Channels
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
  concepts/Common/Distribution Channels/01 npm.md
  concepts/Common/Distribution Channels/03 Yarn.md
  concepts/Common/Distribution Channels/05 CDN/10 Subresource Integrity Hashes.md
  concepts/Common/Distribution Channels/15 ZIP Archive.md
Labels: 22_2

#4804 Correct framework usage in new docs: Distribution Channels (updated versions)
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
  concepts/Common/Distribution Channels/01 npm.md
  concepts/Common/Distribution Channels/03 Yarn.md
  concepts/Common/Distribution Channels/05 CDN/10 Subresource Integrity Hashes.md
  concepts/Common/Distribution Channels/15 ZIP Archive.md
Labels: cherry-pick, 22_1

#4805 Correct framework usage in new docs: Distribution Channels (updated versions)
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
  concepts/Common/Distribution Channels/01 npm.md
  concepts/Common/Distribution Channels/03 Yarn.md
  concepts/Common/Distribution Channels/05 CDN/10 Subresource Integrity Hashes.md
  concepts/Common/Distribution Channels/15 ZIP Archive.md
Labels: cherry-pick, 23_1

#4808 SelectBox/TagBox: Update notes and code snippets (T1156423)
  api-reference/10 UI Components/dxSelectBox/1 Configuration/fieldTemplate.md
Labels: 22_2

#4811 SelectBox/TagBox: Update notes and code snippets (T1156423) (#4808)
  api-reference/10 UI Components/dxSelectBox/1 Configuration/fieldTemplate.md
Labels: cherry-pick, 23_1

#4817 Form and Chart: add missing cross references (T983973,T948372)
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/visualRange/visualRange.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/validationRules.md
Labels: 22_2

#4818 Form and Chart: add missing cross references (T983973,T948372) (#4817)
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/visualRange/visualRange.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/validationRules.md
Labels: 22_1

#4819 Form and Chart: add missing cross references (T983973,T948372) (#4817)
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/visualRange/visualRange.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/validationRules.md
Labels: cherry-pick, 23_1
