Repository DevExpress/devextreme-documentation, pull requests merged in 2024-07, with the labels that each got.

#6437 DateRangeBox: open editor in GS
  applications/GettingStartedWith/DateRangeBox/index.js
Labels: 24_1

#6439 DateRangeBox: open editor in GS (#6437)
  applications/GettingStartedWith/DateRangeBox/index.js
Labels: cherry-pick, 24_2

#6440 Update Themes and Styles
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: 24_1

#6441 Update Themes and Styles (#6440)
  concepts/60 Themes and Styles/05 Predefined Themes/60 Switch Between Themes at Runtime/2 Without Page Reload.md
Labels: cherry-pick, 23_2

#6444 Chart: add info about aggregation types
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/aggregatedPointsPosition.md
Labels: 24_1

#6445 Chart: add info about aggregation types (#6444)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/aggregatedPointsPosition.md
Labels: cherry-pick, 23_2

#6446 Chart: add info about aggregation types (#6444)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/aggregatedPointsPosition.md
Labels: cherry-pick, 24_2

#6443 Application template: add note about themes
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/10 Switch the Theme.md
Labels: 24_1

#6447 Application template: add note about themes (#6443)
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/10 Switch the Theme.md
Labels: cherry-pick, 23_2

#6448 Application template: add note about themes (#6443)
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/10 Switch the Theme.md
Labels: cherry-pick, 24_2

#6449 Angular: update Signals CSB link
  concepts/40 Angular Components/10 Getting Started/90 Support for Angular Signals.md
Labels: 24_1

#6450 Angular: update Signals CSB link (#6449)
  concepts/40 Angular Components/10 Getting Started/90 Support for Angular Signals.md
Labels: cherry-pick, 23_2

#6451 Angular: update Signals CSB link (#6449)
  concepts/40 Angular Components/10 Getting Started/90 Support for Angular Signals.md
Labels: cherry-pick, 24_2

#6453 DataGrid: add Overview
  concepts/05 UI Components/DataGrid/03 Overview/00 Overview.md
  concepts/05 UI Components/DataGrid/03 Overview/05 Elements.md
  concepts/05 UI Components/DataGrid/03 Overview/10 Key Features.md
  concepts/05 UI Components/DataGrid/03 Overview/15 Explore More.md
  images/DataGrid/datagrid-elements.png
Labels: 24_1

#6456 DataGrid: add Overview (#6453)
  concepts/05 UI Components/DataGrid/03 Overview/00 Overview.md
  concepts/05 UI Components/DataGrid/03 Overview/05 Elements.md
  concepts/05 UI Components/DataGrid/03 Overview/10 Key Features.md
  concepts/05 UI Components/DataGrid/03 Overview/15 Explore More.md
  images/DataGrid/datagrid-elements.png
Labels: cherry-pick, 23_2

#6457 DataGrid: add Overview (#6453)
  concepts/05 UI Components/DataGrid/03 Overview/00 Overview.md
  concepts/05 UI Components/DataGrid/03 Overview/05 Elements.md
  concepts/05 UI Components/DataGrid/03 Overview/10 Key Features.md
  concepts/05 UI Components/DataGrid/03 Overview/15 Explore More.md
  images/DataGrid/datagrid-elements.png
Labels: cherry-pick, 24_2

#6452 Legend, LegendItem: inheritance
  api-reference/10 UI Components/BaseChart/7 Interfaces/LegendItem/LegendItem.md
  api-reference/10 UI Components/dxChart/9 Types/Legend/Legend.md
  api-reference/40 Common Types/05 charts/BaseChartLegend/BaseChartLegend.md
Labels: 24_1

#6455 Utils.query - array
  api-reference/30 Data Layer/Query/Query.md
  api-reference/30 Data Layer/Utils/query(array_queryOptions).md
Labels: 24_1

#6464 Utils.query - array (#6455)
  api-reference/30 Data Layer/Query/Query.md
  api-reference/30 Data Layer/Utils/query(array_queryOptions).md
Labels: cherry-pick, 24_2

#6460 Legend, LegendItem: inheritance attrs (#6452)
  api-reference/10 UI Components/BaseChart/7 Interfaces/LegendItem/LegendItem.md
  api-reference/10 UI Components/dxChart/9 Types/Legend/Legend.md
  api-reference/40 Common Types/05 charts/BaseChartLegend/BaseChartLegend.md
Labels: cherry-pick, 24_2

#6467 Legend, LegendItem: inheritance attrs
  api-reference/10 UI Components/BaseChart/7 Interfaces/LegendItem/LegendItem.md
  api-reference/10 UI Components/dxChart/9 Types/Legend/Legend.md
  api-reference/40 Common Types/05 charts/BaseChartLegend/BaseChartLegend.md
Labels: cherry-pick, 23_2

#6468 Legend, LegendItem: inheritance attrs
  api-reference/10 UI Components/BaseChart/7 Interfaces/LegendItem/LegendItem.md
  api-reference/10 UI Components/dxChart/9 Types/Legend/Legend.md
  api-reference/40 Common Types/05 charts/BaseChartLegend/BaseChartLegend.md
Labels: cherry-pick, 23_1

#6470 DocGen: migrate to pnpm
  .github/workflows/docgen.yml
Labels: 24_2

#6471 cloud integration guides (Azure, Amazon) (#6403)
  MenuConfig.xml
  concepts/Common/Integration Guides/10 Create a DevExtreme application with Gatsby/10 Create a DevExtreme application with Gatsby.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
  concepts/Common/Integration Guides/30 Create a DevExtreme application with Vite.js/30 Create a DevExtreme application with Vite.js.md
  concepts/Common/Integration Guides/40 Bind DevExtreme components to GraphQL/40 Bind DevExtreme components to GraphQL.md
  concepts/Common/Integration Guides/50 Use MUI components in your DevExtreme application/50 Use MUI components in your DevExtreme application.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/0 Manage Amazon S3 Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/10 Amazon Setup.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/20 Back-End Application Walkthrough.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/30 Configure Multi-Part Upload (Client-Side).md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/40 Common Techniques.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/50 FileManager.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/60 FileUploader.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/0 Manage Azure Blob Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/10 Configure Azure.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/20 Back-End Applicatoin (Basic Configuration).md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/30 FileManager.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/40 FileUploader.md
Labels: cherry-pick, 23_2

#6472 cloud integration guides (Azure, Amazon) (#6403)
  MenuConfig.xml
  concepts/Common/Integration Guides/10 Create a DevExtreme application with Gatsby/10 Create a DevExtreme application with Gatsby.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
  concepts/Common/Integration Guides/30 Create a DevExtreme application with Vite.js/30 Create a DevExtreme application with Vite.js.md
  concepts/Common/Integration Guides/40 Bind DevExtreme components to GraphQL/40 Bind DevExtreme components to GraphQL.md
  concepts/Common/Integration Guides/50 Use MUI components in your DevExtreme application/50 Use MUI components in your DevExtreme application.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/0 Manage Amazon S3 Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/10 Amazon Setup.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/20 Back-End Application Walkthrough.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/30 Configure Multi-Part Upload (Client-Side).md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/40 Common Techniques.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/50 FileManager.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/60 FileUploader.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/0 Manage Azure Blob Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/10 Configure Azure.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/20 Back-End Applicatoin (Basic Configuration).md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/30 FileManager.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/40 FileUploader.md
Labels: cherry-pick, 24_2

#6473 Licensing: change video link
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
Labels: 24_1

#6474 Licensing: change video link (#6473)
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
Labels: cherry-pick, 24_2

#6475 DataGrid: update Customize Edit Form
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/10 Form Layout Customization.md
Labels: 24_1

#6477 DataGrid: update Customize Edit Form (#6475)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/10 Form Layout Customization.md
Labels: cherry-pick, 24_2

#6476 DataGrid: update Customize Edit Form (#6475)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/10 Appearance and Editing/10 Form Layout Customization.md
Labels: cherry-pick, 23_2

#6478 Grids: update filterType
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/filterType.md
  api-reference/_hidden/GridBaseColumn/filterType.md
Labels: 24_1

#6479 Grids: update filterType (#6478)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/filterType.md
  api-reference/_hidden/GridBaseColumn/filterType.md
Labels: cherry-pick, 23_2

#6480 Grids: update filterType (#6478)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/filterType.md
  api-reference/_hidden/GridBaseColumn/filterType.md
Labels: cherry-pick, 24_2

#6481 DataGrid: update state(state)
  api-reference/10 UI Components/GridBase/3 Methods/state(state).md
Labels: 24_1

#6482 DataGrid: update state(state) (#6481)
  api-reference/10 UI Components/GridBase/3 Methods/state(state).md
Labels: cherry-pick, 23_2

#6483 DataGrid: update state(state) (#6481)
  api-reference/10 UI Components/GridBase/3 Methods/state(state).md
Labels: cherry-pick, 24_2

#6484 Bump devextreme-internal-tools to "^14.0.0"
  package.json
Labels: 24_2

#6489 Grids: fix buttons.template snippet
  api-reference/_hidden/dxDataGridColumnButton/template.md
Labels: 24_1

#6490 Grids: fix buttons.template snippet (#6489)
  api-reference/_hidden/dxDataGridColumnButton/template.md
Labels: cherry-pick, 23_2

#6491 Grids: fix buttons.template snippet (#6489)
  api-reference/_hidden/dxDataGridColumnButton/template.md
Labels: cherry-pick, 24_2

#6492 Fix links to icons after moving them to a separate package
  concepts/60 Themes and Styles/30 Icons/10 Built-In Icon Library.md
Labels: 24_1

#6493 Fix links to icons after moving them to a separate package (cherry-pick)
  concepts/60 Themes and Styles/30 Icons/10 Built-In Icon Library.md
Labels: cherry-pick, 24_2

#6494 DataGrid: update code snippets in Grouping
  concepts/05 UI Components/DataGrid/45 Grouping/20 API/20 Expand and Collapse Groups.md
Labels: 24_1

#6495 DataGrid: update code snippets in Grouping (#6494)
  concepts/05 UI Components/DataGrid/45 Grouping/20 API/20 Expand and Collapse Groups.md
Labels: cherry-pick, 23_2

#6496 DataGrid: update code snippets in Grouping (#6494)
  concepts/05 UI Components/DataGrid/45 Grouping/20 API/20 Expand and Collapse Groups.md
Labels: cherry-pick, 24_2
