Repository DevExpress/devextreme-documentation, pull requests merged in 2024-06, with the labels that each got.

#6348 DataGrid: update PageUp/PageDown description
  concepts/05 UI Components/DataGrid/05 Accessibility/15 Keyboard Navigation.md
Labels: 23_2

#6351 DataGrid: update PageUp/PageDown description (#6348)
  concepts/05 UI Components/DataGrid/05 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 23_1

#6352 DataGrid: update PageUp/PageDown description (#6348)
  concepts/05 UI Components/DataGrid/05 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 24_1

#6353 Splitter: update Getting Started and template after review
  api-reference/_hidden/CollectionWidgetItem/text.md
  applications/GettingStartedWith/Splitter/index.js
  concepts/05 UI Components/Splitter/00 Getting Started with Splitter/15 Fill Panes with Content.md
Labels: 24_1

#6354 Splitter: add Overview topic
  MenuConfig.xml
  concepts/05 UI Components/Splitter/10 Overview/00 Overview.md
  concepts/05 UI Components/Splitter/10 Overview/05 Elements.md
  concepts/05 UI Components/Splitter/10 Overview/10 Key Features.md
  concepts/05 UI Components/Splitter/10 Overview/15 Explore More.md
  images/Splitter/splitter-elements.png
Labels: 24_1

#6357 Add links to demos
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/template.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/captionTemplate.md
  api-reference/10 UI Components/dxMenu/1 Configuration/onSubmenuShowing.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/items/items.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/orientation.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/separatorSize.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/collapsedSize.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/collapsible.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/maxSize.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/minSize.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/resizable.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/size.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/splitter.md
  api-reference/10 UI Components/dxSplitter/dxSplitter.md
Labels: 24_1

#6360 Update iOS supported version
  concepts/Common/Supported Browsers.md
Labels: 24_1

#6359 Describe W0023
  api-reference/10 UI Components/dxSplitter/1 Configuration/repaintChangesOnly.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0023.md
Labels: 24_1

#6350 Update Licensing topic for 24.1
  concepts/Common/Licensing/05 Evaluation (Trial).md
  concepts/Common/Licensing/25 Validation.md
  concepts/Common/Licensing/30 FAQ.md
Labels: 24_1

#6365 DataGrid: replace classes with hooks in Filtering and Searching
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/1 Filter Row.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/2 Header Filter.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/3 Search Panel.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/4 Filter Panel with Filter Builder.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/5 Standalone Filter Builder.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/1 Initial and Runtime Filtering.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/8 Clear Filtering Settings.md
Labels: 24_1

#6366 DataGrid: replace classes with hooks in Filtering and Searching (#6365)
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/1 Filter Row.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/2 Header Filter.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/3 Search Panel.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/4 Filter Panel with Filter Builder.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/5 Standalone Filter Builder.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/1 Initial and Runtime Filtering.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/6 API/8 Clear Filtering Settings.md
Labels: cherry-pick, 23_2

#6367 HtmlEditor: add a GitHub example button
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/imageUpload/imageUpload.md
Labels: 23_2

#6368 HtmlEditor: add a GitHub example button (#6367)
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/imageUpload/imageUpload.md
Labels: cherry-pick, 24_1

#6369 Troubleshooting: minor fix in Date Issues
  concepts/80 Troubleshooting/10 Date String Handling Issues/05 Supported Formats, Exceptions, and Settings.md
Labels: 23_2

#6370 Troubleshooting: minor fix in Date Issues (#6369)
  concepts/80 Troubleshooting/10 Date String Handling Issues/05 Supported Formats, Exceptions, and Settings.md
Labels: cherry-pick, 23_1

#6371 Troubleshooting: minor fix in Date Issues (#6369)
  concepts/80 Troubleshooting/10 Date String Handling Issues/05 Supported Formats, Exceptions, and Settings.md
Labels: cherry-pick, 24_1

#6373 TagBox: add a note to maxDisplayedTags
  api-reference/10 UI Components/dxTagBox/1 Configuration/maxDisplayedTags.md
Labels: 23_2

#6375 Form: add 'Customize a Validation Icon'
  concepts/05 UI Components/Form/40 Customize a Validation Icon.md
Labels: 23_2

#6376 Form: add 'Customize a Validation Icon' (#6375)
  concepts/05 UI Components/Form/40 Customize a Validation Icon.md
Labels: cherry-pick, 23_1

#6377 Form: add 'Customize a Validation Icon' (#6375)
  concepts/05 UI Components/Form/40 Customize a Validation Icon.md
Labels: cherry-pick, 24_1

#6381 Form: add imports to editorType
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorType.md
Labels: 24_1

#6385 Form: add imports to editorType (#6381)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/editorType.md
Labels: cherry-pick, 24_2

#6388 Update version in npm scripts, ng-install doc
  includes/ng-install-devextreme.md
  package.json
Labels: 24_2

#6382 Form: add a note about readOnly
  api-reference/10 UI Components/dxForm/1 Configuration/readOnly.md
Labels: 24_1

#6390 Form: add a note about readOnly (#6382)
  api-reference/10 UI Components/dxForm/1 Configuration/readOnly.md
Labels: cherry-pick, 23_2

#6391 Form: add a note about readOnly (#6382)
  api-reference/10 UI Components/dxForm/1 Configuration/readOnly.md
Labels: cherry-pick, 24_2

#6395 Map: add a note about Bing deprecation
  api-reference/10 UI Components/dxMap/1 Configuration/provider.md
  concepts/05 UI Components/Map/10 Specify the Provider and Type.md
Labels: 24_1

#6396 Map: add a note about Bing deprecation (#6395)
  api-reference/10 UI Components/dxMap/1 Configuration/provider.md
  concepts/05 UI Components/Map/10 Specify the Provider and Type.md
Labels: cherry-pick, 23_2

#6397 Fix accessibility compliance
  concepts/05 UI Components/Accordion/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ActionSheet/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Button/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ButtonGroup/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Calendar/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/CheckBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ColorBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ContextMenu/02 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DateBox/02 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DateRangeBox/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DropDownBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DropDownButton/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/FileUploader/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Form/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Gallery/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/List/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/LoadPanel/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Lookup/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Menu/02 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/MultiView/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/NumberBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Popover/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Popup/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ProgressBar/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/RadioGroup/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/RangeSlider/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/SelectBox/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Slider/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Splitter/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Switch/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TabPanel/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Tabs/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TagBox/01 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TextArea/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TextBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Toast/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Toolbar/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Tooltip/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TreeView/03 Accessibility/10 Accessibility Standards Compliance.md
Labels: 24_1

#6398 Fix accessibility compliance (#6397)
  concepts/05 UI Components/Accordion/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ActionSheet/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Button/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ButtonGroup/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Calendar/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/CheckBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ColorBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ContextMenu/02 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DateBox/02 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DateRangeBox/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DropDownBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DropDownButton/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/FileUploader/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Form/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Gallery/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/List/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/LoadPanel/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Lookup/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Menu/02 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/MultiView/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/NumberBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Popover/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Popup/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ProgressBar/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/RadioGroup/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/RangeSlider/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/SelectBox/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Slider/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Splitter/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Switch/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TabPanel/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Tabs/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TagBox/01 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TextArea/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TextBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Toast/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Toolbar/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Tooltip/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TreeView/03 Accessibility/10 Accessibility Standards Compliance.md
Labels: cherry-pick, 24_2

#6404 Describe W0023
  api-reference/50 Common/utils/zz Errors and Warnings/W0023.md
Labels: 23_2

#6407 React TS: add info about templates
  concepts/50 React Components/70 TypeScript Support/05 Component-Specific Types.md
Labels: 24_1

#6408 React TS: add info about templates (#6407)
  concepts/50 React Components/70 TypeScript Support/05 Component-Specific Types.md
Labels: cherry-pick, 23_2

#6409 React TS: add info about templates (#6407)
  concepts/50 React Components/70 TypeScript Support/05 Component-Specific Types.md
Labels: cherry-pick, 24_2

#6410 Form: add a note to validationRules
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/validationRules.md
Labels: 24_1

#6411 Form: add a note to validationRules (#6410)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/validationRules.md
Labels: cherry-pick, 23_2

#6412 Form: add a note to validationRules (#6410)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/validationRules.md
Labels: cherry-pick, 24_2

#6414 Replace 23.2 with 24.1
  concepts/Common/Migrate to the New Version/40 Learn What's New.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/0 Learn Breaking Changes and Deprecated API.md
Labels: 24_1

#6415 Form: add a note to TabbedItem
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/TabbedItem.md
Labels: 24_1

#6416 Form: add a note to TabbedItem (#6415)
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/TabbedItem.md
Labels: cherry-pick, 23_2

#6417 Form: add a note to TabbedItem (#6415)
  api-reference/10 UI Components/dxForm/5 Item Types/TabbedItem/TabbedItem.md
Labels: cherry-pick, 24_2

#6413 Splitter: update item.size and item.visible
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/size.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/visible.md
Labels: 24_1

#6421 Splitter: update item.size and item.visible (#6413)
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/size.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/visible.md
Labels: cherry-pick, 24_2

#6424 Form: update template
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
Labels: 24_1

#6425 Form: update template (#6424)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
Labels: cherry-pick, 23_2

#6426 Form: update template (#6424)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/template.md
Labels: cherry-pick, 24_2

#6427 Gantt: add button to demo
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
Labels: 24_1

#6428 Gantt: add button to demo (#6427)
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
Labels: cherry-pick, 23_2

#6429 Gantt: add button to demo (#6427)
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
Labels: cherry-pick, 24_2

#6422 DxHttpModule: add a note about XHR restrictions
  api-reference/10 UI Components/dxFileUploader/9 Types/BeforeSendEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/ProgressEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/UploadAbortedEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/UploadErrorEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/UploadStartedEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/UploadedEvent/request.md
  concepts/40 Angular Components/40 Common Features/15 Intercept HTTP Requests.md
Labels: 24_1

#6430 DxHttpModule: add a note about XHR restrictions (#6422)
  api-reference/10 UI Components/dxFileUploader/9 Types/BeforeSendEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/ProgressEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/UploadAbortedEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/UploadErrorEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/UploadStartedEvent/request.md
  api-reference/10 UI Components/dxFileUploader/9 Types/UploadedEvent/request.md
  concepts/40 Angular Components/40 Common Features/15 Intercept HTTP Requests.md
Labels: cherry-pick, 24_2

#6431 DataGrid: fix export.formats snippets
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
Labels: 24_1

#6432 DataGrid: fix export.formats snippets (#6431)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
Labels: cherry-pick, 23_2

#6433 DataGrid: fix export.formats snippets (#6431)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
Labels: cherry-pick, 24_2
