Repository DevExpress/devextreme-documentation, pull requests merged in 2024-10, with the labels that each got.

#6666 HtmlEditor: add note to register(components)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/register(components).md
Labels: 24_1

#6667 HtmlEditor: add note to register(components) (#6666)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/register(components).md
Labels: cherry-pick, 23_2

#6668 HtmlEditor: add note to register(components) (#6666)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/register(components).md
Labels: cherry-pick, 24_2

#6669 Grid: add a note to summary.valueFormat
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/groupItems/valueFormat.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/valueFormat.md
Labels: 24_1

#6671 Grid: add a note to summary.valueFormat (#6669)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/groupItems/valueFormat.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/valueFormat.md
Labels: cherry-pick, 23_2

#6672 Grid: add a note to summary.valueFormat (#6669)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/groupItems/valueFormat.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/valueFormat.md
Labels: cherry-pick, 24_2

#6670 Grids: update stateStoring limitations
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/stateStoring.md
Labels: 24_1

#6673 Grids: update stateStoring limitations (#6670)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/stateStoring.md
Labels: cherry-pick, 23_2

#6674 Grids: update stateStoring limitations (#6670)
  api-reference/10 UI Components/GridBase/1 Configuration/stateStoring/stateStoring.md
Labels: cherry-pick, 24_2

#6675 Chart: add notes to labels settings
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/textOverflow.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/wordWrap.md
Labels: 24_1

#6676 Chart: add notes to labels settings (#6675)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/textOverflow.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/wordWrap.md
Labels: cherry-pick, 23_2

#6677 Chart: add notes to labels settings (#6675)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/textOverflow.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/wordWrap.md
Labels: cherry-pick, 24_2

#6678 ColumnFixingIcons
  api-reference/10 UI Components/GridBase/1 Configuration/columnFixing/icons/fix.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnFixing/icons/icons.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnFixing/icons/leftPosition.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnFixing/icons/rightPosition.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnFixing/icons/stickyPosition.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnFixing/icons/unfix.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnFixing/texts/stickPosition.md
  api-reference/40 Common Types/15 grids/ColumnFixingIcons/ColumnFixingIcons.md
  api-reference/40 Common Types/15 grids/ColumnFixingIcons/fix.md
  api-reference/40 Common Types/15 grids/ColumnFixingIcons/leftPosition.md
  api-reference/40 Common Types/15 grids/ColumnFixingIcons/rightPosition.md
  api-reference/40 Common Types/15 grids/ColumnFixingIcons/stickyPosition.md
  api-reference/40 Common Types/15 grids/ColumnFixingIcons/unfix.md
  metadata/syntax-data.json
Labels: 24_2

#6679 TypeScript Guides: additions and fixes
  concepts/Common/TypeScript Guides/05 Scopes of Types/10 Component-Specific Types.md
  concepts/Common/TypeScript Guides/90 Syntax Elements/15 Aggregated Export.md
Labels: 24_1

#6685 TypeScript Guides: additions and fixes (#6679)
  concepts/Common/TypeScript Guides/05 Scopes of Types/10 Component-Specific Types.md
  concepts/Common/TypeScript Guides/90 Syntax Elements/15 Aggregated Export.md
Labels: cherry-pick, 24_2

#6689 TextBox: add Overview
  concepts/05 UI Components/TextBox/02 Overview/00 Overview.md
  concepts/05 UI Components/TextBox/02 Overview/05 Elements.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/15 Explore More.md
  images/textbox/textbox-elements.png
Labels: 24_1

#6690 TextBox: add Overview (#6689)
  concepts/05 UI Components/TextBox/02 Overview/00 Overview.md
  concepts/05 UI Components/TextBox/02 Overview/05 Elements.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/15 Explore More.md
  images/textbox/textbox-elements.png
Labels: cherry-pick, 23_2

#6691 TextBox: add Overview (#6689)
  concepts/05 UI Components/TextBox/02 Overview/00 Overview.md
  concepts/05 UI Components/TextBox/02 Overview/05 Elements.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/15 Explore More.md
  images/textbox/textbox-elements.png
Labels: cherry-pick, 24_2

#6695 Update Overview topics
  concepts/05 UI Components/DataGrid/03 Overview/10 Key Features.md
  concepts/05 UI Components/Form/00 Overview/10 Key Features.md
  concepts/05 UI Components/List/02 Overview/10 Key Features.md
  concepts/05 UI Components/SelectBox/01 Overview/10 Key Features.md
Labels: 23_2

#6699 Update Overview topics (#6695)
  concepts/05 UI Components/DataGrid/03 Overview/10 Key Features.md
  concepts/05 UI Components/Form/00 Overview/10 Key Features.md
  concepts/05 UI Components/List/02 Overview/10 Key Features.md
  concepts/05 UI Components/SelectBox/01 Overview/10 Key Features.md
Labels: cherry-pick, 24_1

#6700 Update Overview topics (#6695)
  concepts/05 UI Components/DataGrid/03 Overview/10 Key Features.md
  concepts/05 UI Components/Form/00 Overview/10 Key Features.md
  concepts/05 UI Components/List/02 Overview/10 Key Features.md
  concepts/05 UI Components/SelectBox/01 Overview/10 Key Features.md
Labels: cherry-pick, 24_2

#6710 React: update Gatsby and Next.js guides
  concepts/Common/Integration Guides/10 Create a DevExtreme application with Gatsby/10 Create a DevExtreme application with Gatsby.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
Labels: 24_1

#6711 React: update Gatsby and Next.js guides (#6710)
  concepts/Common/Integration Guides/10 Create a DevExtreme application with Gatsby/10 Create a DevExtreme application with Gatsby.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
Labels: cherry-pick, 23_2

#6712 React: update Gatsby and Next.js guides (#6710)
  concepts/Common/Integration Guides/10 Create a DevExtreme application with Gatsby/10 Create a DevExtreme application with Gatsby.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
Labels: cherry-pick, 24_2

#6713 Gantt: update onTaskEditDialogShowing
  api-reference/10 UI Components/dxGantt/1 Configuration/onTaskEditDialogShowing.md
Labels: 24_1

#6714 Gantt: update onTaskEditDialogShowing (#6713)
  api-reference/10 UI Components/dxGantt/1 Configuration/onTaskEditDialogShowing.md
Labels: cherry-pick, 23_2

#6715 Gantt: update onTaskEditDialogShowing (#6713)
  api-reference/10 UI Components/dxGantt/1 Configuration/onTaskEditDialogShowing.md
Labels: cherry-pick, 24_2

#6717 Hide SelectionChangingEvent
  api-reference/10 UI Components/CollectionWidget/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangeInfo/SelectionChangeInfo.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangeInfo/addedItems.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangeInfo/removedItems.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangedInfo/SelectionChangedInfo.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangedInfo/addedItems.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangingInfo/addedItems.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangingInfo/removedItems.md
  api-reference/10 UI Components/dxAccordion/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxAutocomplete/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxButtonGroup/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxContextMenu/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxDropDownList/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxDropDownList/9 Types/SelectionChangingInfo/SelectionChangingInfo.md
  api-reference/10 UI Components/dxDropDownList/9 Types/SelectionChangingInfo/selectedItem.md
  api-reference/10 UI Components/dxGallery/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxList/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxList/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxLookup/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxLookup/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxMenu/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxMultiView/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxSelectBox/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxTabPanel/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxTabPanel/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxTabs/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxTabs/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxTagBox/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxTagBox/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxTagBox/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  metadata/syntax-data.json
Labels: 24_2

#6707 Pagination: describe API
  api-reference/10 UI Components/dxPagination/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxPagination/1 Configuration/allowedPageSizes.md
  api-reference/10 UI Components/dxPagination/1 Configuration/itemCount.md
  api-reference/10 UI Components/dxPagination/1 Configuration/pageIndex.md
  api-reference/10 UI Components/dxPagination/1 Configuration/pageSize.md
  api-reference/10 UI Components/dxPagination/3 Methods/Methods.md
  api-reference/10 UI Components/dxPagination/3 Methods/getPageCount().md
  api-reference/10 UI Components/dxPagination/dxPagination.md
  api-reference/40 Common Types/PagerBase/PagerBase.md
  api-reference/40 Common Types/PagerBase/displayMode.md
  api-reference/40 Common Types/PagerBase/infoText.md
  api-reference/40 Common Types/PagerBase/label.md
  api-reference/40 Common Types/PagerBase/showInfo.md
  api-reference/40 Common Types/PagerBase/showNavigationButtons.md
  api-reference/40 Common Types/PagerBase/showPageSizeSelector.md
  api-reference/NewTopics/dxPagination/1 Configuration/allowedPageSizes.md
  api-reference/NewTopics/dxPagination/1 Configuration/pageIndex.md
  api-reference/NewTopics/dxPagination/3 Methods/Methods.md
  api-reference/NewTopics/dxPagination/dxPagination.md
Labels: 24_2

#6724 DataSource: add a note about Next.js
  api-reference/30 Data Layer/DataSource/DataSource.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
Labels: 24_1

#6723 Map: bing -> azure
  api-reference/10 UI Components/dxMap/1 Configuration/apiKey/apiKey.md
  concepts/05 UI Components/Map/10 Specify the Provider and Type.md
Labels: 24_2

#6726 DataSource: add a note about Next.js (#6724)
  api-reference/30 Data Layer/DataSource/DataSource.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
Labels: cherry-pick, 23_2

#6727 DataSource: add a note about Next.js (#6724)
  api-reference/30 Data Layer/DataSource/DataSource.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
Labels: cherry-pick, 24_2

#6722 Describe onSelectionChanging event
  api-reference/10 UI Components/CollectionWidget/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/CollectionWidget/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/CollectionWidget/4 Events/selectionChanged.md
  api-reference/10 UI Components/CollectionWidget/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxContextMenu/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxGallery/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxList/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxList/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxList/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxMenu/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxMenu/4 Events/selectionChange.md
  api-reference/10 UI Components/dxMultiView/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxTabPanel/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxTabPanel/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxTabPanel/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxTabs/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxTabs/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxTabs/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxTagBox/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxTagBox/4 Events/selectionChanging.md
  concepts/05 UI Components/List/25 Selection/05 API.md
Labels: 24_2

#6732 ContextMenu / TabPanel onSelectionChanging
  api-reference/10 UI Components/dxContextMenu/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxTabPanel/4 Events/selectionChanging.md
Labels: 24_2

#6734 Update "Supported Versions"
  concepts/40 Angular Components/80 Supported Versions.md
  concepts/50 React Components/80 Supported Versions.md
  concepts/55 Vue Components/80 Supported Versions.md
  concepts/58 jQuery Components/80 Supported Versions.md
  concepts/Common/Migrate to the New Version/40 Learn What's New.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/0 Learn Breaking Changes and Deprecated API.md
Labels: 24_2

#6738 Angular: update SSR section and all doc links
  api-reference/10 UI Components/DOMComponent/3 Methods/dispose().md
  api-reference/_hidden/dxMenuItem/url.md
  concepts/05 UI Components/Diagram/05 Add the Diagram Component to an Angular CLI Application.md
  concepts/05 UI Components/Drawer/00 Getting Started with Navigation Drawer/15 Implement Navigation.md
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/Add DevExtreme to an Angular CLI Application.md
  concepts/40 Angular Components/20 Component Configuration Syntax/17 Collections.md
  concepts/40 Angular Components/20 Component Configuration Syntax/37 Templates/External Templates.md
  concepts/40 Angular Components/20 Component Configuration Syntax/42 Call Methods.md
  concepts/40 Angular Components/20 Component Configuration Syntax/44 Get a UI Component Instance.md
  concepts/40 Angular Components/20 Component Configuration Syntax/75 Angular Forms Support.md
  concepts/40 Angular Components/20 Component Configuration Syntax/85 Angular Change Detection Specifics.md
  concepts/40 Angular Components/40 Common Features/05 Server-Side Rendering/00 Server-Side Rendering.md
  concepts/40 Angular Components/40 Common Features/15 Intercept HTTP Requests.md
  concepts/Common/Security Considerations/Security Considerations.md
Labels: 24_1

#6740 Splitter: add live demo to API
  api-reference/10 UI Components/dxSplitter/dxSplitter.md
Labels: 24_1

#6737 Popup: rewrite Show and Hide the Popup
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/03 Using DxPopupService.md
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/05 User Interaction.md
Labels: 24_2

#6653 Add Reactive migration guides
  MenuConfig.xml
  concepts/50 React Components/65 Migrate from DevExtreme Reactive/00 Migrate from DevExtreme Reactive.md
  concepts/50 React Components/65 Migrate from DevExtreme Reactive/05 Examples to Review.md
  concepts/50 React Components/65 Migrate from DevExtreme Reactive/10 Structure and Imports.md
  concepts/50 React Components/65 Migrate from DevExtreme Reactive/15 Transition Approaches.md
  concepts/50 React Components/65 Migrate from DevExtreme Reactive/20 Themes.md
Labels: 24_2

#6728 Update component overviews
  concepts/05 UI Components/Button/02 Overview/10 Key Features.md
  concepts/05 UI Components/Button/02 Overview/15 Explore More.md
  concepts/05 UI Components/DataGrid/03 Overview/15 Explore More.md
  concepts/05 UI Components/Form/00 Overview/15 Explore More.md
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/HtmlEditor/02 Overview/15 Explore More.md
  concepts/05 UI Components/List/02 Overview/15 Explore More.md
  concepts/05 UI Components/Popup/02 Overview/10 Key Features.md
  concepts/05 UI Components/Popup/02 Overview/15 Explore More.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/Scheduler/02 Overview/15 Explore More.md
  concepts/05 UI Components/SelectBox/01 Overview/15 Explore More.md
  concepts/05 UI Components/Splitter/10 Overview/15 Explore More.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/15 Explore More.md
  concepts/05 UI Components/TreeList/02 Overview/10 Key Features.md
  concepts/05 UI Components/TreeList/02 Overview/15 Explore More.md
Labels: 24_1

#6744 Update component overviews (#6728)
  concepts/05 UI Components/Button/02 Overview/10 Key Features.md
  concepts/05 UI Components/Button/02 Overview/15 Explore More.md
  concepts/05 UI Components/DataGrid/03 Overview/15 Explore More.md
  concepts/05 UI Components/Form/00 Overview/15 Explore More.md
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/HtmlEditor/02 Overview/15 Explore More.md
  concepts/05 UI Components/List/02 Overview/15 Explore More.md
  concepts/05 UI Components/Popup/02 Overview/10 Key Features.md
  concepts/05 UI Components/Popup/02 Overview/15 Explore More.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/Scheduler/02 Overview/15 Explore More.md
  concepts/05 UI Components/SelectBox/01 Overview/15 Explore More.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/15 Explore More.md
  concepts/05 UI Components/TreeList/02 Overview/10 Key Features.md
  concepts/05 UI Components/TreeList/02 Overview/15 Explore More.md
Labels: cherry-pick, 23_2

#6745 Update component overviews (#6728)
  concepts/05 UI Components/Button/02 Overview/10 Key Features.md
  concepts/05 UI Components/Button/02 Overview/15 Explore More.md
  concepts/05 UI Components/DataGrid/03 Overview/15 Explore More.md
  concepts/05 UI Components/Form/00 Overview/15 Explore More.md
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/HtmlEditor/02 Overview/15 Explore More.md
  concepts/05 UI Components/List/02 Overview/15 Explore More.md
  concepts/05 UI Components/Popup/02 Overview/10 Key Features.md
  concepts/05 UI Components/Popup/02 Overview/15 Explore More.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/Scheduler/02 Overview/15 Explore More.md
  concepts/05 UI Components/SelectBox/01 Overview/15 Explore More.md
  concepts/05 UI Components/Splitter/10 Overview/15 Explore More.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/15 Explore More.md
  concepts/05 UI Components/TreeList/02 Overview/10 Key Features.md
  concepts/05 UI Components/TreeList/02 Overview/15 Explore More.md
Labels: cherry-pick, 24_2

#6751 Map: add provider/marker corrections
  api-reference/10 UI Components/dxMap/1 Configuration/onMarkerAdded.md
  api-reference/10 UI Components/dxMap/1 Configuration/onRouteAdded.md
  api-reference/10 UI Components/dxMap/1 Configuration/providerConfig/mapId.md
  api-reference/10 UI Components/dxMap/1 Configuration/providerConfig/useAdvancedMarkers.md
Labels: 24_2

#6752 RangeSelector: update tick properties
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/tick/color.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/tick/opacity.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/tick/width.md
Labels: 24_1

#6753 RangeSelector: update tick properties (#6752)
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/tick/color.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/tick/opacity.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/tick/width.md
Labels: cherry-pick, 23_2

#6754 RangeSelector: update tick properties (#6752)
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/tick/color.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/tick/opacity.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/scale/tick/width.md
Labels: cherry-pick, 24_2

#6755 DataGrid: update Client-Side Data Aggregation topic
  concepts/05 UI Components/DataGrid/65 Summaries/07 Custom Aggregate Function/10 Client-Side Data Aggregation.md
Labels: 24_1

#6756 DataGrid: update Client-Side Data Aggregation topic (#6755)
  concepts/05 UI Components/DataGrid/65 Summaries/07 Custom Aggregate Function/10 Client-Side Data Aggregation.md
Labels: cherry-pick, 23_2

#6757 DataGrid: update Client-Side Data Aggregation topic (#6755)
  concepts/05 UI Components/DataGrid/65 Summaries/07 Custom Aggregate Function/10 Client-Side Data Aggregation.md
Labels: cherry-pick, 24_2

#6758 DataGrid: update focused row code snippet
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/3 Customize Row Apperance.md
Labels: 24_1

#6759 DataGrid: update focused row code snippet (#6758)
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/3 Customize Row Apperance.md
Labels: cherry-pick, 23_2

#6760 DataGrid: update focused row code snippet (#6758)
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/3 Customize Row Apperance.md
Labels: cherry-pick, 24_2

#6746 TreeList: add notes to selection methods
  api-reference/10 UI Components/dxTreeList/3 Methods/getSelectedRowKeys(mode).md
  api-reference/10 UI Components/dxTreeList/3 Methods/getSelectedRowsData(mode).md
Labels: 24_1

#6765 TreeList: add notes to selection methods (#6746)
  api-reference/10 UI Components/dxTreeList/3 Methods/getSelectedRowKeys(mode).md
  api-reference/10 UI Components/dxTreeList/3 Methods/getSelectedRowsData(mode).md
Labels: cherry-pick, 24_2

#6764 TreeList: add notes to selection methods (#6746)
  api-reference/10 UI Components/dxTreeList/3 Methods/getSelectedRowKeys(mode).md
  api-reference/10 UI Components/dxTreeList/3 Methods/getSelectedRowsData(mode).md
Labels: cherry-pick, 23_2

#6766 Form: update Change Properties at Runtime
  concepts/05 UI Components/Form/20 Change Properties at Runtime/15 Editor Properties.md
Labels: 24_1

#6767 Form: update Change Properties at Runtime (#6766)
  concepts/05 UI Components/Form/20 Change Properties at Runtime/15 Editor Properties.md
Labels: cherry-pick, 23_2

#6768 Form: update Change Properties at Runtime (#6766)
  concepts/05 UI Components/Form/20 Change Properties at Runtime/15 Editor Properties.md
Labels: cherry-pick, 24_2

#6750 HtmlEditor: add a converter option
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/converter.md
  api-reference/10 UI Components/dxHtmlEditor/9 Types/Converter/Converter.md
  api-reference/10 UI Components/dxHtmlEditor/9 Types/Converter/fromHtml.md
  api-reference/10 UI Components/dxHtmlEditor/9 Types/Converter/toHtml.md
Labels: 24_2

#6769 DataGrid: update Custom Sorting topic
  concepts/05 UI Components/DataGrid/25 Sorting/20 API/5 Custom Sorting.md
Labels: 24_1

#6771 DataGrid: update Custom Sorting topic (#6769)
  concepts/05 UI Components/DataGrid/25 Sorting/20 API/5 Custom Sorting.md
Labels: cherry-pick, 23_2

#6772 DataGrid: update Custom Sorting topic (#6769)
  concepts/05 UI Components/DataGrid/25 Sorting/20 API/5 Custom Sorting.md
Labels: cherry-pick, 24_2

#6773 PivotGrid: update Bind Data topic (#6770)
  concepts/05 UI Components/PivotGrid/030 Data Binding/20 Bind Data.md
Labels: cherry-pick, 23_2

#6774 PivotGrid: update Bind Data topic (#6770)
  concepts/05 UI Components/PivotGrid/030 Data Binding/20 Bind Data.md
Labels: cherry-pick, 24_2

#6778 Lookup: update dropDownCentered
  api-reference/10 UI Components/dxLookup/1 Configuration/dropDownCentered.md
  applications/UIWidgets/Lookup/dropDownCentered.css
  applications/UIWidgets/Lookup/dropDownCentered.html
  applications/UIWidgets/Lookup/dropDownCentered.js
  images/Lookup/drop-down-centered-false.gif
  images/Lookup/drop-down-centered-true.gif
Labels: 24_1

#6779 Lookup: update dropDownCentered (#6778)
  api-reference/10 UI Components/dxLookup/1 Configuration/dropDownCentered.md
  applications/UIWidgets/Lookup/dropDownCentered.css
  applications/UIWidgets/Lookup/dropDownCentered.html
  applications/UIWidgets/Lookup/dropDownCentered.js
  images/Lookup/drop-down-centered-false.gif
  images/Lookup/drop-down-centered-true.gif
Labels: cherry-pick, 23_2

#6780 Lookup: update dropDownCentered (#6778)
  api-reference/10 UI Components/dxLookup/1 Configuration/dropDownCentered.md
  applications/UIWidgets/Lookup/dropDownCentered.css
  applications/UIWidgets/Lookup/dropDownCentered.html
  applications/UIWidgets/Lookup/dropDownCentered.js
  images/Lookup/drop-down-centered-false.gif
  images/Lookup/drop-down-centered-true.gif
Labels: cherry-pick, 24_2
