Repository DevExpress/devextreme-documentation, pull requests merged in 2024-05, with the labels that each got.

#6294 Menu: update show/hide event parameters
  api-reference/10 UI Components/dxMenu/1 Configuration/onSubmenuHidden.md
  api-reference/10 UI Components/dxMenu/1 Configuration/onSubmenuHiding.md
  api-reference/10 UI Components/dxMenu/1 Configuration/onSubmenuShowing.md
  api-reference/10 UI Components/dxMenu/1 Configuration/onSubmenuShown.md
Labels: 24_1

#5733 Employ Modern Trends: GraphQL, Gatsby, Vite, Next.js, MUI
  MenuConfig.xml
  concepts/Common/Integration Guides/10 Create a DevExtreme application with Gatsby/10 Create a DevExtreme application with Gatsby.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
  concepts/Common/Integration Guides/30 Create a DevExtreme application with Vite.js/30 Create a DevExtreme application with Vite.js.md
  concepts/Common/Integration Guides/40 Bind DevExtreme components to GraphQL/40 Bind DevExtreme components to GraphQL.md
  concepts/Common/Integration Guides/50 Use MUI components in your DevExtreme application/50 Use MUI components in your DevExtreme application.md
  images/Gatsby/blank-page.png
  images/Gatsby/cmd-url.png
  images/Gatsby/grid-with-a-theme.png
  images/Gatsby/grid-without-a-theme.png
  images/Gatsby/lipsum-page.png
  images/Gatsby/new-website.png
  images/Gatsby/ssr-example.png
  images/GraphQL/data-sources.png
  images/GraphQL/run-dev.png
  images/GraphQL/vite-create.png
  images/MUI/sample-app.png
  images/NextJS/client-side-grid.png
  images/NextJS/create-next-app.png
  images/NextJS/disable-javascript.png
  images/NextJS/empty-div.png
  images/NextJS/modified-page.png
  images/NextJS/original-front-page.png
  images/NextJS/ssr-example.png
  images/Vite/create-vite.png
  images/Vite/vite-final-result.png
  images/Vite/vite-ready.png
Labels: 24_1

#6295 Update Shadow DOM topic
  concepts/Common/Shadow DOM/10 Benefits.md
  concepts/Common/Shadow DOM/20 Support.md
  concepts/Common/Shadow DOM/Shadow DOM.md
Labels: 24_1

#6174 Accessibility: add table for all components
  concepts/Common/Accessibility/05 Documentation for Components.md
Labels: 24_1

#6304 HtmlEditor: add a note to imageUpload
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/imageUpload/imageUpload.md
  images/htmlEditor/image-upload-dialog.png
Labels: 23_2

#6306 HtmlEditor: add a note to imageUpload (#6304)
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/imageUpload/imageUpload.md
  images/htmlEditor/image-upload-dialog.png
Labels: cherry-pick, 24_1

#6311 Splitter: API fixes
  api-reference/10 UI Components/dxSplitter/1 Configuration/allowKeyboardNavigation.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/separatorSize.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/splitter.md
  api-reference/10 UI Components/dxSplitter/dxSplitter.md
Labels: 24_1

#6313 FileManager: update onFileUploading code
  api-reference/10 UI Components/dxFileManager/1 Configuration/onFileUploading.md
Labels: 23_2

#6314 FileManager: update onFileUploading code (#6313)
  api-reference/10 UI Components/dxFileManager/1 Configuration/onFileUploading.md
Labels: cherry-pick, 23_1

#6315 FileManager: update onFileUploading code (#6313)
  api-reference/10 UI Components/dxFileManager/1 Configuration/onFileUploading.md
Labels: cherry-pick, 24_1

#6318 PivotGrid: hide links to jQuery topic (#6316)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/summaryDisplayMode.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/summaryType.md
Labels: cherry-pick, 24_1

#6319 Small structure and text fixes
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
  concepts/05 UI Components/PivotGrid/035 Use CustomStore/20 Remote Operations.md
Labels: 23_2

#6320 Small structure and text fixes (#6319)
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
  concepts/05 UI Components/PivotGrid/035 Use CustomStore/20 Remote Operations.md
Labels: cherry-pick, 23_1

#6321 Small structure and text fixes (#6319)
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/valueExpr.md
  concepts/05 UI Components/PivotGrid/035 Use CustomStore/20 Remote Operations.md
Labels: cherry-pick, 24_1

#6302 Diagram Command Types
  api-reference/10 UI Components/dxDiagram/1 Configuration/autoZoomMode.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/contextMenu/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/contextToolbox/category.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/contextToolbox/displayMode.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/contextToolbox/shapes.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/customShapes/baseType.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/defaultItemProperties/connectorLineEnd.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/defaultItemProperties/connectorLineStart.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/defaultItemProperties/connectorLineType.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/historyToolbar/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/mainToolbar/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/nodes/autoLayout/autoLayout.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/nodes/autoLayout/type.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/onRequestEditOperation.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/propertiesPanel/tabs/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/propertiesPanel/tabs/groups/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/propertiesPanel/visibility.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/groups/category.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/groups/displayMode.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/groups/groups.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/groups/shapes.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/visibility.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/units.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/viewToolbar/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/viewUnits.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/CustomCommand.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/icon.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/items.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/location.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/name.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/text.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramAddShapeFromToolboxArgs/shapeType.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramChangeConnectionArgs/connectorPosition.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramCustomCommand/items.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramItem/itemType.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramShape/type.md
  api-reference/10 UI Components/dxDiagram/9 Types/AutoZoomMode.md
  api-reference/10 UI Components/dxDiagram/9 Types/Command.md
  api-reference/10 UI Components/dxDiagram/9 Types/ConnectorLineEnd.md
  api-reference/10 UI Components/dxDiagram/9 Types/ConnectorLineType.md
  api-reference/10 UI Components/dxDiagram/9 Types/ConnectorPosition.md
  api-reference/10 UI Components/dxDiagram/9 Types/DataLayoutType.md
  api-reference/10 UI Components/dxDiagram/9 Types/ItemType.md
  api-reference/10 UI Components/dxDiagram/9 Types/ModelOperation.md
  api-reference/10 UI Components/dxDiagram/9 Types/PanelVisibility.md
  api-reference/10 UI Components/dxDiagram/9 Types/RequestEditOperationEvent/operation.md
  api-reference/10 UI Components/dxDiagram/9 Types/RequestEditOperationEvent/reason.md
  api-reference/10 UI Components/dxDiagram/9 Types/RequestEditOperationReason.md
  api-reference/10 UI Components/dxDiagram/9 Types/ShapeCategory.md
  api-reference/10 UI Components/dxDiagram/9 Types/ShapeType.md
  api-reference/10 UI Components/dxDiagram/9 Types/ToolboxDisplayMode.md
  api-reference/10 UI Components/dxDiagram/9 Types/Units.md
  api-reference/40 Common Types/ToolbarItemLocation.md
Labels: 24_1

#6323 Diagram Command Types
  api-reference/10 UI Components/dxDiagram/1 Configuration/autoZoomMode.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/contextMenu/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/contextToolbox/category.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/contextToolbox/displayMode.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/contextToolbox/shapes.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/customShapes/baseType.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/defaultItemProperties/connectorLineEnd.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/defaultItemProperties/connectorLineStart.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/defaultItemProperties/connectorLineType.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/historyToolbar/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/mainToolbar/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/nodes/autoLayout/autoLayout.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/nodes/autoLayout/type.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/onRequestEditOperation.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/propertiesPanel/tabs/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/propertiesPanel/tabs/groups/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/propertiesPanel/visibility.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/groups/category.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/groups/displayMode.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/groups/groups.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/groups/shapes.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/toolbox/visibility.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/units.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/viewToolbar/commands.md
  api-reference/10 UI Components/dxDiagram/1 Configuration/viewUnits.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/CustomCommand.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/icon.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/items.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/location.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/name.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/CustomCommand/text.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramAddShapeFromToolboxArgs/shapeType.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramChangeConnectionArgs/connectorPosition.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramCustomCommand/items.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramItem/itemType.md
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramShape/type.md
  api-reference/10 UI Components/dxDiagram/9 Types/AutoZoomMode.md
  api-reference/10 UI Components/dxDiagram/9 Types/Command.md
  api-reference/10 UI Components/dxDiagram/9 Types/ConnectorLineEnd.md
  api-reference/10 UI Components/dxDiagram/9 Types/ConnectorLineType.md
  api-reference/10 UI Components/dxDiagram/9 Types/ConnectorPosition.md
  api-reference/10 UI Components/dxDiagram/9 Types/DataLayoutType.md
  api-reference/10 UI Components/dxDiagram/9 Types/ItemType.md
  api-reference/10 UI Components/dxDiagram/9 Types/ModelOperation.md
  api-reference/10 UI Components/dxDiagram/9 Types/PanelVisibility.md
  api-reference/10 UI Components/dxDiagram/9 Types/RequestEditOperationEvent/operation.md
  api-reference/10 UI Components/dxDiagram/9 Types/RequestEditOperationEvent/reason.md
  api-reference/10 UI Components/dxDiagram/9 Types/RequestEditOperationReason.md
  api-reference/10 UI Components/dxDiagram/9 Types/ShapeCategory.md
  api-reference/10 UI Components/dxDiagram/9 Types/ShapeType.md
  api-reference/10 UI Components/dxDiagram/9 Types/ToolboxDisplayMode.md
  api-reference/10 UI Components/dxDiagram/9 Types/Units.md
  api-reference/40 Common Types/ToolbarItemLocation.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/15 Specify a Command's Location on the Main Toolbar.md
  metadata/syntax-data.json
Labels: cherry-pick, 23_2

#6325 HtmlEditor: add code to getSelection
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getSelection().md
Labels: 23_2

#6326 HtmlEditor: add code to getSelection (#6325)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getSelection().md
Labels: cherry-pick, 23_1

#6327 HtmlEditor: add code to getSelection (#6325)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getSelection().md
Labels: cherry-pick, 24_1

#6331 HtmlEditor: add a note to GS tutorial
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
Labels: 23_2

#6332 HtmlEditor: add a note to GS tutorial (#6331)
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
Labels: cherry-pick, 23_1

#6333 HtmlEditor: add a note to GS tutorial (#6331)
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
Labels: cherry-pick, 24_1

#6338 jQuery: fix version (#6337)
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
Labels: cherry-pick, 23_1

#6339 jQuery: fix version (#6337)
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
Labels: cherry-pick, 24_1

#6340 Editors: omit 'value' from isDirty code
  api-reference/10 UI Components/Editor/1 Configuration/isDirty.md
Labels: 23_2

#6341 Editors: omit 'value' from isDirty code (#6340)
  api-reference/10 UI Components/Editor/1 Configuration/isDirty.md
Labels: cherry-pick, 24_1

#6342 DataGrid: fix the 'width' option
  api-reference/10 UI Components/dxDataGrid/1 Configuration/width.md
Labels: 23_2

#6343 DataGrid: fix the 'width' option (#6342)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/width.md
Labels: cherry-pick, 23_1

#6345 React: add a note to 'One-Command Setup'
  concepts/50 React Components/05 Add DevExtreme to a React Application/01 One-Command Setup.md
Labels: 23_2

#6266 Getting Started with Splitter
  applications/GettingStartedWith/Splitter/index.css
  applications/GettingStartedWith/Splitter/index.html
  applications/GettingStartedWith/Splitter/index.js
  concepts/05 UI Components/Splitter/00 Getting Started with Splitter/00 Getting Started with Splitter.md
  concepts/05 UI Components/Splitter/00 Getting Started with Splitter/05 Build a Layout.md
  concepts/05 UI Components/Splitter/00 Getting Started with Splitter/10 Configure Panes.md
  concepts/05 UI Components/Splitter/00 Getting Started with Splitter/15 Fill Panes with Content.md
Labels: 24_1

#6346 React: add a note to 'One-Command Setup' (#6345)
  concepts/50 React Components/05 Add DevExtreme to a React Application/01 One-Command Setup.md
Labels: cherry-pick, 23_1

#6347 React: add a note to 'One-Command Setup' (#6345)
  concepts/50 React Components/05 Add DevExtreme to a React Application/01 One-Command Setup.md
Labels: cherry-pick, 24_1
