Repository DevExpress/devextreme-documentation, pull requests merged in 2024-08, with the labels that each got.

#6507 TextArea: add a note about input
  concepts/05 UI Components/TextArea/13 Handle the Keyboard Events.md
Labels: 24_1

#6513 TextArea: add a note about input (#6507)
  concepts/05 UI Components/TextArea/13 Handle the Keyboard Events.md
Labels: cherry-pick, 23_2

#6508 Licensing: add info about subscriptions
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
Labels: 24_1

#6514 TextArea: add a note about input (#6507)
  concepts/05 UI Components/TextArea/13 Handle the Keyboard Events.md
Labels: cherry-pick, 24_2

#6509 DataGrid: update editCellTemplate
  api-reference/_hidden/dxDataGridColumn/editCellTemplate.md
Labels: 24_1

#6515 Licensing: add info about subscriptions (#6508)
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
Labels: cherry-pick, 23_2

#6516 Licensing: add info about subscriptions (#6508)
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
Labels: cherry-pick, 24_2

#6517 DataGrid: update editCellTemplate (#6509)
  api-reference/_hidden/dxDataGridColumn/editCellTemplate.md
Labels: cherry-pick, 23_2

#6518 DataGrid: update editCellTemplate (#6509)
  api-reference/_hidden/dxDataGridColumn/editCellTemplate.md
Labels: cherry-pick, 24_2

#6510 Add topics for Chat
  api-reference/10 UI Components/dxChat/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxChat/1 Configuration/accessKey.md
  api-reference/10 UI Components/dxChat/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxChat/1 Configuration/focusStateEnabled.md
  api-reference/10 UI Components/dxChat/1 Configuration/hint.md
  api-reference/10 UI Components/dxChat/1 Configuration/items.md
  api-reference/10 UI Components/dxChat/1 Configuration/onContentReady.md
  api-reference/10 UI Components/dxChat/1 Configuration/onDisposing.md
  api-reference/10 UI Components/dxChat/1 Configuration/onInitialized.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageSend.md
  api-reference/10 UI Components/dxChat/1 Configuration/onOptionChanged.md
  api-reference/10 UI Components/dxChat/1 Configuration/tabIndex.md
  api-reference/10 UI Components/dxChat/1 Configuration/title.md
  api-reference/10 UI Components/dxChat/4 Events/Events.md
  api-reference/10 UI Components/dxChat/4 Events/contentReady.md
  api-reference/10 UI Components/dxChat/4 Events/messageSend.md
  api-reference/10 UI Components/dxChat/9 Types/DisposingEvent/DisposingEvent.md
  api-reference/10 UI Components/dxChat/9 Types/InitializedEvent/InitializedEvent.md
  api-reference/10 UI Components/dxChat/9 Types/Message/Message.md
  api-reference/10 UI Components/dxChat/9 Types/Message/author.md
  api-reference/10 UI Components/dxChat/9 Types/Message/text.md
  api-reference/10 UI Components/dxChat/9 Types/Message/timestamp.md
  api-reference/10 UI Components/dxChat/9 Types/Message/typing.md
  api-reference/10 UI Components/dxChat/9 Types/MessageSendEvent/MessageSendEvent.md
  api-reference/10 UI Components/dxChat/9 Types/OptionChangedEvent/OptionChangedEvent.md
  api-reference/10 UI Components/dxChat/9 Types/Types.md
  api-reference/10 UI Components/dxChat/9 Types/User/User.md
  api-reference/10 UI Components/dxChat/9 Types/User/avatarUrl.md
  api-reference/10 UI Components/dxChat/9 Types/User/id.md
  api-reference/10 UI Components/dxChat/9 Types/User/name.md
  api-reference/10 UI Components/dxChat/dxChat.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/ui/chat.md
  metadata/syntax-data.json
  typesPathMap.json
Labels: 24_2

#6520 Form: add Overview
  concepts/05 UI Components/Form/00 Overview/00 Overview.md
  concepts/05 UI Components/Form/00 Overview/05 Elements.md
  concepts/05 UI Components/Form/00 Overview/10 Key Features.md
  concepts/05 UI Components/Form/00 Overview/15 Explore More.md
  images/Form/form-elements.png
Labels: 24_1

#6522 Form: add Overview (#6520)
  concepts/05 UI Components/Form/00 Overview/00 Overview.md
  concepts/05 UI Components/Form/00 Overview/05 Elements.md
  concepts/05 UI Components/Form/00 Overview/10 Key Features.md
  concepts/05 UI Components/Form/00 Overview/15 Explore More.md
  images/Form/form-elements.png
Labels: cherry-pick, 23_2

#6523 Form: add Overview (#6520)
  concepts/05 UI Components/Form/00 Overview/00 Overview.md
  concepts/05 UI Components/Form/00 Overview/05 Elements.md
  concepts/05 UI Components/Form/00 Overview/10 Key Features.md
  concepts/05 UI Components/Form/00 Overview/15 Explore More.md
  images/Form/form-elements.png
Labels: cherry-pick, 24_2

#6521 Form: update dataField description
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/dataField.md
Labels: 24_1

#6524 Form: update dataField description (#6521)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/dataField.md
Labels: cherry-pick, 23_2

#6525 Form: update dataField description (#6521)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/dataField.md
Labels: cherry-pick, 24_2

#6529 Update Amazon and Azure integration guides
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/0 Manage Amazon S3 Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/10 Amazon Setup.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/20 Back-End Application Walkthrough.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/30 Configure Multi-Part Upload (Client-Side).md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/40 Common Techniques.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/50 FileManager.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/60 FileUploader.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/0 Manage Azure Blob Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/10 Configure Azure.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/20 Back-End Applicatoin (Basic Configuration).md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/30 FileManager.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/40 FileUploader.md
Labels: 24_1

#6530 Update Amazon and Azure integration guides (#6529)
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/0 Manage Amazon S3 Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/10 Amazon Setup.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/20 Back-End Application Walkthrough.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/30 Configure Multi-Part Upload (Client-Side).md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/40 Common Techniques.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/50 FileManager.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/60 FileUploader.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/0 Manage Azure Blob Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/10 Configure Azure.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/20 Back-End Applicatoin (Basic Configuration).md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/30 FileManager.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/40 FileUploader.md
Labels: cherry-pick, 23_2

#6531 Update Amazon and Azure integration guides (#6529)
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/0 Manage Amazon S3 Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/10 Amazon Setup.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/20 Back-End Application Walkthrough.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/30 Configure Multi-Part Upload (Client-Side).md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/40 Common Techniques.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/50 FileManager.md
  concepts/Common/Integration Guides/60 Manage Amazon S3 Storage with DevExtreme Components/60 FileUploader.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/0 Manage Azure Blob Storage with DevExtreme Components.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/10 Configure Azure.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/20 Back-End Applicatoin (Basic Configuration).md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/30 FileManager.md
  concepts/Common/Integration Guides/70 Manage Azure Blob Storage with DevExtreme Components/40 FileUploader.md
Labels: cherry-pick, 24_2

#6535 Update devextreme-cli article
  concepts/50 React Components/50 Application Template/50 Create an Empty Application.md
Labels: 24_1

#6536 Update devextreme-cli article (#6535)
  concepts/50 React Components/50 Application Template/50 Create an Empty Application.md
Labels: cherry-pick, 23_2

#6537 Update devextreme-cli article (#6535)
  concepts/50 React Components/50 Application Template/50 Create an Empty Application.md
Labels: cherry-pick, 24_2

#6538 SelectBox: add Overview
  concepts/05 UI Components/SelectBox/01 Overview/00 Overview.md
  concepts/05 UI Components/SelectBox/01 Overview/05 Elements.md
  concepts/05 UI Components/SelectBox/01 Overview/10 Key Features.md
  concepts/05 UI Components/SelectBox/01 Overview/15 Explore More.md
  images/SelectBox/select-box-elements.png
Labels: 24_1

#6539 SelectBox: add Overview (#6538)
  concepts/05 UI Components/SelectBox/01 Overview/00 Overview.md
  concepts/05 UI Components/SelectBox/01 Overview/05 Elements.md
  concepts/05 UI Components/SelectBox/01 Overview/10 Key Features.md
  concepts/05 UI Components/SelectBox/01 Overview/15 Explore More.md
  images/SelectBox/select-box-elements.png
Labels: cherry-pick, 23_2

#6540 SelectBox: add Overview (#6538)
  concepts/05 UI Components/SelectBox/01 Overview/00 Overview.md
  concepts/05 UI Components/SelectBox/01 Overview/05 Elements.md
  concepts/05 UI Components/SelectBox/01 Overview/10 Key Features.md
  concepts/05 UI Components/SelectBox/01 Overview/15 Explore More.md
  images/SelectBox/select-box-elements.png
Labels: cherry-pick, 24_2

#6545 Form: fix labelMode description
  api-reference/10 UI Components/dxForm/1 Configuration/labelMode.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/labelMode.md
  images/UiWidgets/texteditor-default-label.png
  includes/texteditor-labelMode.md
Labels: 24_1

#6546 Form: fix labelMode description (#6545)
  api-reference/10 UI Components/dxForm/1 Configuration/labelMode.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/labelMode.md
  images/UiWidgets/texteditor-default-label.png
  includes/texteditor-labelMode.md
Labels: cherry-pick, 23_2

#6547 Form: fix labelMode description (#6545)
  api-reference/10 UI Components/dxForm/1 Configuration/labelMode.md
  api-reference/10 UI Components/dxTextEditor/1 Configuration/labelMode.md
  images/UiWidgets/texteditor-default-label.png
  includes/texteditor-labelMode.md
Labels: cherry-pick, 24_2

#6541 Update viz.refreshTheme() method description
  api-reference/50 Common/utils/viz/refreshTheme().md
Labels: 24_1

#6553 Update viz.refreshTheme() method description (#6541)
  api-reference/50 Common/utils/viz/refreshTheme().md
Labels: cherry-pick, 23_2

#6554 Update viz.refreshTheme() method description (#6541)
  api-reference/50 Common/utils/viz/refreshTheme().md
Labels: cherry-pick, 24_2

#6555 Menu: update closeMenuOnClick
  api-reference/_hidden/dxMenuBaseItem/closeMenuOnClick.md
Labels: 24_1

#6557 Menu: update closeMenuOnClick (#6555)
  api-reference/_hidden/dxMenuBaseItem/closeMenuOnClick.md
Labels: cherry-pick, 23_2

#6558 Menu: update closeMenuOnClick (#6555)
  api-reference/_hidden/dxMenuBaseItem/closeMenuOnClick.md
Labels: cherry-pick, 24_2

#6559 DataGrid: update editing.changes.key (#6556)
  api-reference/_hidden/DataChange/key.md
Labels: cherry-pick, 23_2

#6560 DataGrid: update editing.changes.key (#6556)
  api-reference/_hidden/DataChange/key.md
Labels: cherry-pick, 24_2

#6548 jQuery: add Uncaught TypeError troubleshooting
  concepts/80 Troubleshooting/55 Uncaught TypeError 'dxWidget is not a function'.md
  images/Troubleshooting/uncaught-typeerror.png
Labels: 24_1

#6565 jQuery: add Uncaught TypeError troubleshooting (#6548)
  concepts/80 Troubleshooting/55 Uncaught TypeError 'dxWidget is not a function'.md
  images/Troubleshooting/uncaught-typeerror.png
Labels: cherry-pick, 23_2

#6566 jQuery: add Uncaught TypeError troubleshooting (#6548)
  concepts/80 Troubleshooting/55 Uncaught TypeError 'dxWidget is not a function'.md
  images/Troubleshooting/uncaught-typeerror.png
Labels: cherry-pick, 24_2

#6570 Add List Overview
  concepts/05 UI Components/List/02 Overview/00 Overview.md
  concepts/05 UI Components/List/02 Overview/05 Elements.md
  concepts/05 UI Components/List/02 Overview/10 Key Features.md
  concepts/05 UI Components/List/02 Overview/15 Explore More.md
  images/List/list-elements.png
Labels: 24_1

#6571 Add List Overview (#6570)
  concepts/05 UI Components/List/02 Overview/00 Overview.md
  concepts/05 UI Components/List/02 Overview/05 Elements.md
  concepts/05 UI Components/List/02 Overview/10 Key Features.md
  concepts/05 UI Components/List/02 Overview/15 Explore More.md
  images/List/list-elements.png
Labels: cherry-pick, 23_2

#6576 E1037: update code snippet
  api-reference/10 UI Components/Errors and Warnings/E1037.md
Labels: 24_1

#6577 E1037: update code snippet (#6576)
  api-reference/10 UI Components/Errors and Warnings/E1037.md
Labels: cherry-pick, 23_2

#6578 E1037: update code snippet (#6576)
  api-reference/10 UI Components/Errors and Warnings/E1037.md
Labels: cherry-pick, 24_2

#6579 Popup: add Overview
  concepts/05 UI Components/Popup/02 Overview/00 Overview.md
  concepts/05 UI Components/Popup/02 Overview/05 Elements.md
  concepts/05 UI Components/Popup/02 Overview/10 Key Features.md
  concepts/05 UI Components/Popup/02 Overview/15 Explore More.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/7 Add Scrolling.md
  images/Popup/popup-elements.png
Labels: 24_1

#6581 Popup: add Overview (#6579)
  concepts/05 UI Components/Popup/02 Overview/00 Overview.md
  concepts/05 UI Components/Popup/02 Overview/05 Elements.md
  concepts/05 UI Components/Popup/02 Overview/10 Key Features.md
  concepts/05 UI Components/Popup/02 Overview/15 Explore More.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/7 Add Scrolling.md
  images/Popup/popup-elements.png
Labels: cherry-pick, 23_2

#6582 Popup: add Overview (#6579)
  concepts/05 UI Components/Popup/02 Overview/00 Overview.md
  concepts/05 UI Components/Popup/02 Overview/05 Elements.md
  concepts/05 UI Components/Popup/02 Overview/10 Key Features.md
  concepts/05 UI Components/Popup/02 Overview/15 Explore More.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/7 Add Scrolling.md
  images/Popup/popup-elements.png
Labels: cherry-pick, 24_2
