Repository DevExpress/devextreme-documentation, pull requests merged in 2024-09, with the labels that each got.

#6586 Collection: onSelectionChanging
  api-reference/10 UI Components/CollectionWidget/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/CollectionWidget/4 Events/selectionChanging.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangingInfo/SelectionChangingInfo.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangingInfo/addedItems.md
  api-reference/10 UI Components/CollectionWidget/9 Types/SelectionChangingInfo/removedItems.md
  api-reference/10 UI Components/dxAccordion/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxAccordion/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxActionSheet/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxActionSheet/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxAutocomplete/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxBox/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxBox/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxContextMenu/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxDropDownList/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxDropDownList/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxDropDownList/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxDropDownList/9 Types/SelectionChangingInfo/SelectionChangingInfo.md
  api-reference/10 UI Components/dxDropDownList/9 Types/SelectionChangingInfo/selectedItem.md
  api-reference/10 UI Components/dxGallery/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxGallery/4 Events/Events.md
  api-reference/10 UI Components/dxGallery/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxList/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxList/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxLookup/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxLookup/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxLookup/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxLookup/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxMenu/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxMenu/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxMultiView/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxMultiView/4 Events/Events.md
  api-reference/10 UI Components/dxMultiView/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxResponsiveBox/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxResponsiveBox/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxSelectBox/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxSelectBox/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxSplitter/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxTabPanel/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxTabPanel/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxTabs/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxTabs/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxTagBox/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxTagBox/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxTagBox/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxTileView/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxTileView/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxToolbar/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxToolbar/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxTreeView/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxTreeView/4 Events/selectionChanging.md
  api-reference/10 UI Components/dxValidationSummary/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxValidationSummary/4 Events/selectionChanging.md
  api-reference/40 Common Types/13 events/AsyncCancelable/AsyncCancelable.md
  api-reference/40 Common Types/13 events/AsyncCancelable/cancel.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/ui/drop_down_editor/ui.drop_down_list.md
Labels: 24_2

#6590 Grids: fix bugs
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/remoteOperations.md
  concepts/05 UI Components/TreeList/05 Accessibility/15 Keyboard Navigation.md
Labels: 24_1

#6591 Grids: fix bugs (#6590)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/remoteOperations.md
  concepts/05 UI Components/TreeList/05 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 23_2

#6592 Grids: fix bugs (#6590)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/remoteOperations.md
  concepts/05 UI Components/TreeList/05 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 24_2

#6597 Icons: update icon names list
  applications/Icons/script.js
Labels: 24_2

#6600 MultiView/TabPanel: add "visible" options
  api-reference/10 UI Components/dxChat/1 Configuration/message.md
  api-reference/NewTopics/MessageSendEvent/MessageSendEvent.md
  api-reference/_hidden/dxMultiViewItem/visible.md
  api-reference/_hidden/dxTabPanelItem/visible.md
Labels: 24_2

#6599 DataGrid: describe 'sensitivity'
  api-reference/10 UI Components/dxDataGrid/1 Configuration/selection/sensitivity.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SelectionSensitivity.md
Labels: 24_1

#6604 DataGrid: describe 'sensitivity' (#6599)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/selection/sensitivity.md
  api-reference/10 UI Components/dxDataGrid/9 Types/SelectionSensitivity.md
Labels: cherry-pick, 24_2

#6605 MessageSendEvent.message
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageSend.md
  api-reference/10 UI Components/dxChat/9 Types/MessageSendEvent/message.md
Labels: 24_2

#6603 Angular Popup: add info about DxPopupService
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/15 Using DxPopupService.md
Labels: 24_2

#6561 DataGrid: add examples with 'watch' for templates
  api-reference/10 UI Components/dxDataGrid/1 Configuration/masterDetail/template.md
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
Labels: 24_1

#6609 DataGrid: add examples with 'watch' for templates (#6561)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/masterDetail/template.md
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
Labels: cherry-pick, 23_2

#6610 DataGrid: add examples with 'watch' for templates (#6561)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/masterDetail/template.md
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
Labels: cherry-pick, 24_2

#6611 Rename troubleshooting article
  concepts/80 Troubleshooting/55 Uncaught TypeError dxWidget is not a function.md
Labels: 24_1

#6612 Rename troubleshooting article (#6611)
  concepts/80 Troubleshooting/55 Uncaught TypeError dxWidget is not a function.md
Labels: cherry-pick, 23_2

#6613 Rename troubleshooting article (#6611)
  concepts/80 Troubleshooting/55 Uncaught TypeError dxWidget is not a function.md
Labels: cherry-pick, 24_2

#6615 HtmlEditor: fix formats and modules links
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/get(componentPath).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getModule(moduleName).md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
Labels: 24_1

#6616 HtmlEditor: fix formats and modules links (#6615)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/get(componentPath).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getModule(moduleName).md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
Labels: cherry-pick, 24_2

#6617 Update contentReady description
  api-reference/10 UI Components/Widget/4 Events/contentReady.md
Labels: 24_1

#6618 Update contentReady description (#6617)
  api-reference/10 UI Components/Widget/4 Events/contentReady.md
Labels: cherry-pick, 23_2

#6619 Update contentReady description (#6617)
  api-reference/10 UI Components/Widget/4 Events/contentReady.md
Labels: cherry-pick, 24_2

#6614 Diagram - add snippets to Linear Array section
  concepts/05 UI Components/Diagram/10 Data Binding/20 Linear Array.md
Labels: 24_1

#6620 Diagram - add snippets to Linear Array section (#6614)
  concepts/05 UI Components/Diagram/10 Data Binding/20 Linear Array.md
Labels: cherry-pick, 23_2

#6621 Diagram - add snippets to Linear Array section (#6614)
  concepts/05 UI Components/Diagram/10 Data Binding/20 Linear Array.md
Labels: cherry-pick, 24_2

#6622 Button: add Overview
  concepts/05 UI Components/Button/02 Overview/00 Overview.md
  concepts/05 UI Components/Button/02 Overview/05 Elements.md
  concepts/05 UI Components/Button/02 Overview/10 Key Features.md
  concepts/05 UI Components/Button/02 Overview/15 Explore More.md
  images/Button/button-elements.png
Labels: 24_1

#6623 Button: add Overview (#6622)
  concepts/05 UI Components/Button/02 Overview/00 Overview.md
  concepts/05 UI Components/Button/02 Overview/05 Elements.md
  concepts/05 UI Components/Button/02 Overview/10 Key Features.md
  concepts/05 UI Components/Button/02 Overview/15 Explore More.md
  images/Button/button-elements.png
Labels: cherry-pick, 23_2

#6624 Button: add Overview (#6622)
  concepts/05 UI Components/Button/02 Overview/00 Overview.md
  concepts/05 UI Components/Button/02 Overview/05 Elements.md
  concepts/05 UI Components/Button/02 Overview/10 Key Features.md
  concepts/05 UI Components/Button/02 Overview/15 Explore More.md
  images/Button/button-elements.png
Labels: cherry-pick, 24_2

#6625 Scheduler: add Overview
  concepts/05 UI Components/Scheduler/02 Overview/00 Overview.md
  concepts/05 UI Components/Scheduler/02 Overview/05 Elements.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/Scheduler/02 Overview/15 Explore More.md
  images/Scheduler/scheduler-elements.png
Labels: 24_1

#6631 Scheduler: add Overview (#6625)
  concepts/05 UI Components/Scheduler/02 Overview/00 Overview.md
  concepts/05 UI Components/Scheduler/02 Overview/05 Elements.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/Scheduler/02 Overview/15 Explore More.md
  images/Scheduler/scheduler-elements.png
Labels: cherry-pick, 23_2

#6632 Scheduler: add Overview (#6625)
  concepts/05 UI Components/Scheduler/02 Overview/00 Overview.md
  concepts/05 UI Components/Scheduler/02 Overview/05 Elements.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/Scheduler/02 Overview/15 Explore More.md
  images/Scheduler/scheduler-elements.png
Labels: cherry-pick, 24_2

#6633 TreeList: add Overview
  concepts/05 UI Components/TreeList/02 Overview/00 Overview.md
  concepts/05 UI Components/TreeList/02 Overview/05 Elements.md
  concepts/05 UI Components/TreeList/02 Overview/10 Key Features.md
  concepts/05 UI Components/TreeList/02 Overview/15 Explore More.md
  images/treelist/tree-list-elements.png
Labels: 24_1

#6634 TreeList: add Overview (#6633)
  concepts/05 UI Components/TreeList/02 Overview/00 Overview.md
  concepts/05 UI Components/TreeList/02 Overview/05 Elements.md
  concepts/05 UI Components/TreeList/02 Overview/10 Key Features.md
  concepts/05 UI Components/TreeList/02 Overview/15 Explore More.md
  images/treelist/tree-list-elements.png
Labels: cherry-pick, 23_2

#6635 TreeList: add Overview (#6633)
  concepts/05 UI Components/TreeList/02 Overview/00 Overview.md
  concepts/05 UI Components/TreeList/02 Overview/05 Elements.md
  concepts/05 UI Components/TreeList/02 Overview/10 Key Features.md
  concepts/05 UI Components/TreeList/02 Overview/15 Explore More.md
  images/treelist/tree-list-elements.png
Labels: cherry-pick, 24_2

#6644 DataGrid: update focsuedRow properties
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowIndex.md
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowKey.md
Labels: 24_1

#6645 DataGrid: update focsuedRow properties (#6644)
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowIndex.md
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowKey.md
Labels: cherry-pick, 23_2

#6646 DataGrid: update focsuedRow properties (#6644)
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowIndex.md
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowKey.md
Labels: cherry-pick, 24_2

#6647 Fix bugs (application template, grid editing)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/60 Edit Form Limitations.md
  concepts/40 Angular Components/30 Application Template/50 Create an Empty Application.md
  concepts/55 Vue Components/50 Application Template/50 Create an Empty Application.md
Labels: 24_1

#6649 Fix bugs (application template, grid editing) (#6647)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/60 Edit Form Limitations.md
  concepts/40 Angular Components/30 Application Template/50 Create an Empty Application.md
  concepts/55 Vue Components/50 Application Template/50 Create an Empty Application.md
Labels: cherry-pick, 24_2

#6648 Fix bugs (application template, grid editing) (#6647)
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/60 Edit Form Limitations.md
  concepts/40 Angular Components/30 Application Template/50 Create an Empty Application.md
  concepts/55 Vue Components/50 Application Template/50 Create an Empty Application.md
Labels: cherry-pick, 23_2

#6656 Fix diagram 24_1
  concepts/05 UI Components/Diagram/10 Data Binding/20 Linear Array.md
Labels: 24_1

#6655 Fix diagram 23_2
  concepts/05 UI Components/Diagram/10 Data Binding/20 Linear Array.md
Labels: 23_2

#6657 Add TypeScript Guides (#6454)
  MenuConfig.xml
  api-reference/40 Common Types/13 events/EventInfo/EventInfo.md
  api-reference/40 Common Types/13 events/NativeEventInfo/NativeEventInfo.md
  api-reference/40 Common Types/13 events/NativeEventInfo/event.md
  concepts/40 Angular Components/70 TypeScript Support/00 TypeScript Support.md
  concepts/40 Angular Components/70 TypeScript Support/05 Component Specific Types.md
  concepts/40 Angular Components/70 TypeScript Support/10 Generics Usage.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/50 React Components/70 TypeScript Support/00 TypeScript Support.md
  concepts/50 React Components/70 TypeScript Support/05 Component-Specific Types.md
  concepts/50 React Components/70 TypeScript Support/10 Generics Usage.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/55 Vue Components/70 TypeScript Support/00 TypeScript Support.md
  concepts/55 Vue Components/70 TypeScript Support/05 Component Specific Types.md
  concepts/55 Vue Components/70 TypeScript Support/10 Generics Usage.md
  concepts/Common/TypeScript Guides/00 Getting Started.md
  concepts/Common/TypeScript Guides/05 Scopes of Types/00 Scopes of Types.md
  concepts/Common/TypeScript Guides/05 Scopes of Types/10 Component-Specific Types.md
  concepts/Common/TypeScript Guides/05 Scopes of Types/15 Common Types.md
  concepts/Common/TypeScript Guides/05 Scopes of Types/20 Internal Types.md
  concepts/Common/TypeScript Guides/10 Best Practices/00 Best Practices.md
  concepts/Common/TypeScript Guides/10 Best Practices/05 Using Unions Instead of Base Classes.md
  concepts/Common/TypeScript Guides/10 Best Practices/10 Generic Parameters.md
  concepts/Common/TypeScript Guides/10 Best Practices/15 Types for Templates.md
  concepts/Common/TypeScript Guides/15 Events/00 Events.md
  concepts/Common/TypeScript Guides/15 Events/05 Event Objects.md
  concepts/Common/TypeScript Guides/15 Events/10 Writable Fields.md
  concepts/Common/TypeScript Guides/15 Events/15 Event Object Parts.md
  concepts/Common/TypeScript Guides/90 Syntax Elements/00 Syntax Elements.md
  concepts/Common/TypeScript Guides/90 Syntax Elements/15 Aggregated Export.md
  concepts/Common/TypeScript Guides/90 Syntax Elements/90 Conditional Types.md
  concepts/Common/TypeScript Support/01 Reference TypeScript Definitions.md
  concepts/Common/TypeScript Support/05 Configure a UI Component.md
  concepts/Common/TypeScript Support/10 Access a UI Component.md
Labels: cherry-pick, 24_2

#6654 Map: describe providerConfig
  api-reference/10 UI Components/dxMap/1 Configuration/markers/markers.md
  api-reference/10 UI Components/dxMap/1 Configuration/onReady.md
  api-reference/10 UI Components/dxMap/1 Configuration/providerConfig/mapId.md
  api-reference/10 UI Components/dxMap/1 Configuration/providerConfig/providerConfig.md
  api-reference/10 UI Components/dxMap/1 Configuration/providerConfig/useAdvancedMarkers.md
Labels: 24_2

#6660 Form: update isDirty notes
  api-reference/10 UI Components/dxForm/1 Configuration/isDirty.md
Labels: 24_1

#6662 Form: update isDirty notes (#6660)
  api-reference/10 UI Components/dxForm/1 Configuration/isDirty.md
Labels: cherry-pick, 23_2

#6663 Form: update isDirty notes (#6660)
  api-reference/10 UI Components/dxForm/1 Configuration/isDirty.md
Labels: cherry-pick, 24_2
