Repository DevExpress/devextreme-documentation, pull requests merged in 2024-12, with the labels that each got.

#6833 Update Application Template pictures
  concepts/40 Angular Components/30 Application Template/00 Application Template.md
  concepts/40 Angular Components/30 Application Template/10 Layouts.md
  concepts/50 React Components/50 Application Template/00 Application Template.md
  concepts/50 React Components/50 Application Template/10 Layouts.md
  concepts/55 Vue Components/50 Application Template/00 Application Template.md
  concepts/55 Vue Components/50 Application Template/10 Layouts.md
  images/dx-application-templates/angular-app-template-inner-toolbar.png
  images/dx-application-templates/angular-app-template-outer-toolbar.png
  images/dx-application-templates/angular-app-template.png
  images/dx-application-templates/inner.png
  images/dx-application-templates/outer.png
  images/dx-application-templates/react-app-template-inner-toolbar.png
  images/dx-application-templates/react-app-template-outer-toolbar.png
  images/dx-application-templates/react-app-template.png
  images/dx-application-templates/vue-app-template-inner-toolbar.png
  images/dx-application-templates/vue-app-template-outer-toolbar.png
  images/dx-application-templates/vue-app-template.png
Labels: 24_2

#6834 jQuery: rewrite Create a Custom Bundle
  concepts/Common/Modularity/015 Create a Custom Bundle/Create a Custom Bundle.md
Labels: 24_1

#6835 Scheduler: fix Customize Appointment Tooltip code
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
Labels: 24_1

#6836 jQuery: rewrite Create a Custom Bundle (#6834)
  concepts/Common/Modularity/015 Create a Custom Bundle/Create a Custom Bundle.md
Labels: cherry-pick, 23_2

#6837 jQuery: rewrite Create a Custom Bundle (#6834)
  concepts/Common/Modularity/015 Create a Custom Bundle/Create a Custom Bundle.md
Labels: cherry-pick, 24_2

#6838 Scheduler: fix Customize Appointment Tooltip code (#6835)
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
Labels: cherry-pick, 23_2

#6839 Scheduler: fix Customize Appointment Tooltip code (#6835)
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
Labels: cherry-pick, 24_2

#6841 Update demo links for release
  api-reference/10 UI Components/GridBase/1 Configuration/columnFixing/columnFixing.md
  api-reference/10 UI Components/dxChat/1 Configuration/items.md
  api-reference/10 UI Components/dxChat/1 Configuration/messageTemplate.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageEntered.md
  api-reference/10 UI Components/dxChat/1 Configuration/onTypingEnd.md
  api-reference/10 UI Components/dxChat/1 Configuration/onTypingStart.md
  api-reference/10 UI Components/dxChat/1 Configuration/reloadOnChange.md
  api-reference/10 UI Components/dxChat/1 Configuration/showAvatar.md
  api-reference/10 UI Components/dxChat/1 Configuration/showDayHeaders.md
  api-reference/10 UI Components/dxChat/1 Configuration/showMessageTimestamp.md
  api-reference/10 UI Components/dxChat/1 Configuration/showUserName.md
  api-reference/10 UI Components/dxChat/1 Configuration/typingUsers.md
  api-reference/10 UI Components/dxChat/1 Configuration/user.md
  api-reference/10 UI Components/dxChat/3 Methods/renderMessage(message).md
  api-reference/10 UI Components/dxChat/dxChat.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/converter.md
  api-reference/10 UI Components/dxMap/1 Configuration/apiKey/apiKey.md
  api-reference/10 UI Components/dxMap/1 Configuration/markers/markers.md
  api-reference/10 UI Components/dxPagination/1 Configuration/allowedPageSizes.md
  api-reference/10 UI Components/dxPagination/1 Configuration/itemCount.md
  api-reference/10 UI Components/dxPagination/1 Configuration/pageIndex.md
  api-reference/10 UI Components/dxPagination/1 Configuration/pageSize.md
  api-reference/10 UI Components/dxPagination/dxPagination.md
  api-reference/_hidden/GridBaseColumn/fixed.md
  api-reference/_hidden/GridBaseColumn/fixedPosition.md
Labels: 24_2

#6842 Gantt: add info about accepted colors
  api-reference/10 UI Components/dxGantt/1 Configuration/resources/resources.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/tasks.md
Labels: 24_1

#6843 Grids: add a note to filterOperations
  api-reference/_hidden/GridBaseColumn/filterOperations.md
Labels: 24_1

#6845 Gantt: add info about accepted colors (#6842)
  api-reference/10 UI Components/dxGantt/1 Configuration/resources/resources.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/tasks.md
Labels: cherry-pick, 23_2

#6847 Grids: add a note to filterOperations (#6843)
  api-reference/_hidden/GridBaseColumn/filterOperations.md
Labels: cherry-pick, 23_2

#6848 Grids: add a note to filterOperations (#6843)
  api-reference/_hidden/GridBaseColumn/filterOperations.md
Labels: cherry-pick, 24_2

#6849 Chat: add Overview
  concepts/05 UI Components/Chat/00 Overview/00 Overview.md
  concepts/05 UI Components/Chat/00 Overview/05 Elements.md
  concepts/05 UI Components/Chat/00 Overview/10 Key Features.md
  concepts/05 UI Components/Chat/00 Overview/15 Explore More.md
  images/Chat/chat-elements.png
Labels: 24_2

#6850 Fix Overviews + rename HTML Editor
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/02 Create an HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/20 Configure the Toolbar.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/40 Resize Images.md
  concepts/05 UI Components/HtmlEditor/02 Overview/00 Overview.md
  concepts/05 UI Components/HtmlEditor/02 Overview/05 Elements.md
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/HtmlEditor/02 Overview/15 Explore More.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/HtmlEditor/05 Tags and Attributes.md
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/20 Format the Content Programmatically.md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
  concepts/05 UI Components/HtmlEditor/20 Toolbar/00 Predefined Items/00 Predefined Items.md
  concepts/05 UI Components/HtmlEditor/20 Toolbar/35 Relocate the Toolbar.md
  concepts/05 UI Components/HtmlEditor/90 Limitations.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
  images/treelist/tree-list-elements.png
Labels: 24_1

#6851 Fix Overviews + rename HTML Editor (#6850)
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/02 Create an HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/20 Configure the Toolbar.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/40 Resize Images.md
  concepts/05 UI Components/HtmlEditor/02 Overview/00 Overview.md
  concepts/05 UI Components/HtmlEditor/02 Overview/05 Elements.md
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/HtmlEditor/02 Overview/15 Explore More.md
  concepts/05 UI Components/HtmlEditor/05 Tags and Attributes.md
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/20 Format the Content Programmatically.md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
  concepts/05 UI Components/HtmlEditor/20 Toolbar/00 Predefined Items/00 Predefined Items.md
  concepts/05 UI Components/HtmlEditor/20 Toolbar/35 Relocate the Toolbar.md
  concepts/05 UI Components/HtmlEditor/90 Limitations.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
  images/treelist/tree-list-elements.png
Labels: cherry-pick, 23_2

#6852 Fix Overviews + rename HTML Editor (#6850)
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/02 Create an HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Initial Value.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/20 Configure the Toolbar.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/40 Resize Images.md
  concepts/05 UI Components/HtmlEditor/02 Overview/00 Overview.md
  concepts/05 UI Components/HtmlEditor/02 Overview/05 Elements.md
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/HtmlEditor/02 Overview/15 Explore More.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/HtmlEditor/05 Tags and Attributes.md
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/20 Format the Content Programmatically.md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
  concepts/05 UI Components/HtmlEditor/20 Toolbar/00 Predefined Items/00 Predefined Items.md
  concepts/05 UI Components/HtmlEditor/20 Toolbar/35 Relocate the Toolbar.md
  concepts/05 UI Components/HtmlEditor/90 Limitations.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
  images/treelist/tree-list-elements.png
Labels: cherry-pick, 24_2

#6856 Chat: add a note about pagination
  api-reference/10 UI Components/dxChat/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxChat/1 Configuration/reloadOnChange.md
Labels: 24_2

#6860 Map: add CSP info about Azure
  concepts/Common/Security Considerations/40 Content Security Policy/20 CSP Directives for Map Integrations.md
Labels: 24_2

#6861 Remove old versions
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/filterType.md
  concepts/05 UI Components/Button/00 Getting Started with Button/02 Create a Button.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/05 Create the DateBox.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/10 Add the Diagram Component to a Page.md
  concepts/05 UI Components/Form/01 Getting Started with Form/10 Create a Form.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/10 Add the Gantt Component to a Page.md
  concepts/05 UI Components/HtmlEditor/10 Formats/33 Customize Built-In Formats and Modules/20 Extend.md
  concepts/05 UI Components/List/00 Getting Started with List/02 Create a List.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
  concepts/05 UI Components/Menu/00 Getting Started with Menu/05 Create Base Menu Level.md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/02 Create a Popup.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/05 Create a Switch.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/05 Create Predefined Tabs.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/05 Create a TextBox.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/05 Use the 'notify' Method.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/05 Create a Toolbar and its Items.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/08 Export Theme Metadata.md
  concepts/Common/Distribution Channels/10 NuGet.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/05 Using Intl.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/0 Learn Breaking Changes and Deprecated API.md
  includes/tutorials-editors-create-an-editor.md
Labels: 24_2

#6864 Remove old versions
  concepts/05 UI Components/Button/00 Getting Started with Button/02 Create a Button.md
  concepts/05 UI Components/DateBox/00 Getting Started with DateBox/05 Create the DateBox.md
  concepts/05 UI Components/Form/01 Getting Started with Form/10 Create a Form.md
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/10 Add the Gantt Component to a Page.md
  concepts/05 UI Components/List/00 Getting Started with List/02 Create a List.md
  concepts/05 UI Components/Lookup/00 Getting Started with Lookup/05 Create a Lookup Component.md
  concepts/05 UI Components/Menu/00 Getting Started with Menu/05 Create Base Menu Level.md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/02 Create a Popup.md
  concepts/05 UI Components/Switch/00 Getting Started with Switch/05 Create a Switch.md
  concepts/05 UI Components/Tabs/00 Getting Started with Tabs/05 Create Predefined Tabs.md
  concepts/05 UI Components/TextBox/00 Getting Started with TextBox/05 Create a TextBox.md
  concepts/05 UI Components/Toast/00 Getting Started with Toast/05 Display a Toast notification/05 Use the 'notify' Method.md
  concepts/05 UI Components/Toolbar/00 Getting Started with Toolbar/05 Create a Toolbar and its Items.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/08 Export Theme Metadata.md
  concepts/Common/Distribution Channels/10 NuGet.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/05 Using Intl.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/0 Learn Breaking Changes and Deprecated API.md
  includes/tutorials-editors-create-an-editor.md
Labels: 24_1

#6863 Diagram: add Getting Started tutorial
  MenuConfig.xml
  applications/GettingStartedWith/Diagram/index.css
  applications/GettingStartedWith/Diagram/index.html
  applications/GettingStartedWith/Diagram/index.js
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/00 Getting Started with Diagram.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/05 Add the Diagram Component to a Page.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/10 Add the Diagram Component to a Page.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/10 Bind Diagram to Data.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/15 Configure Tools and Customize.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/20 Load and Save Diagram Content.md
  concepts/05 UI Components/Diagram/05 Add the Diagram Component to an Angular CLI Application.md
Labels: 24_1

#6867 Diagram: add Getting Started tutorial (#6863)
  MenuConfig.xml
  applications/GettingStartedWith/Diagram/index.css
  applications/GettingStartedWith/Diagram/index.html
  applications/GettingStartedWith/Diagram/index.js
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/00 Getting Started with Diagram.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/05 Add the Diagram Component to a Page.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/10 Add the Diagram Component to a Page.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/10 Bind Diagram to Data.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/15 Configure Tools and Customize.md
  concepts/05 UI Components/Diagram/00 Getting Started with Diagram/20 Load and Save Diagram Content.md
  concepts/05 UI Components/Diagram/05 Add the Diagram Component to an Angular CLI Application.md
Labels: cherry-pick, 24_2

#6870 React: fix useMemo
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
Labels: 24_1

#6871 React: fix useMemo (#6870)
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
Labels: cherry-pick, 23_2

#6872 React: fix useMemo (#6870)
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
Labels: cherry-pick, 24_2

#6873 Licensing: add info about renewals
  concepts/Common/Licensing/15 Updating License Keys.md
Labels: 24_1

#6874 Licensing: add info about renewals (#6873)
  concepts/Common/Licensing/15 Updating License Keys.md
Labels: cherry-pick, 23_2

#6875 Licensing: add info about renewals (#6873)
  concepts/Common/Licensing/15 Updating License Keys.md
Labels: cherry-pick, 24_2

#6869 TreeView: describe KBN limitations
  api-reference/10 UI Components/dxTreeView/1 Configuration/selectByClick.md
  concepts/05 UI Components/TreeView/03 Accessibility/15 Keyboard Navigation.md
Labels: 24_1

#6877 TreeView: describe KBN limitations (#6869)
  api-reference/10 UI Components/dxTreeView/1 Configuration/selectByClick.md
  concepts/05 UI Components/TreeView/03 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 23_2

#6878 TreeView: describe KBN limitations (#6869)
  api-reference/10 UI Components/dxTreeView/1 Configuration/selectByClick.md
  concepts/05 UI Components/TreeView/03 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 24_2

#6876 Grids: add a note about repainting changes
  api-reference/10 UI Components/GridBase/3 Methods/cellValue(rowIndex_dataField_value).md
Labels: 24_1

#6879 Grids: add a note about repainting changes (#6876)
  api-reference/10 UI Components/GridBase/3 Methods/cellValue(rowIndex_dataField_value).md
Labels: cherry-pick, 23_2

#6880 Grids: add a note about repainting changes (#6876)
  api-reference/10 UI Components/GridBase/3 Methods/cellValue(rowIndex_dataField_value).md
Labels: cherry-pick, 24_2

#6884 Demos.md for new components
  concepts/05 UI Components/Chat/Demos.md
  concepts/05 UI Components/HtmlEditor/Demos.md
  concepts/05 UI Components/Pagination/Demos.md
Labels: 24_2

#6865 Pagination: add Overview
  MenuConfig.xml
  concepts/05 UI Components/Pagination/00 Overview/00 Overview.md
  concepts/05 UI Components/Pagination/00 Overview/05 Elements.md
  concepts/05 UI Components/Pagination/00 Overview/10 Key Features.md
  concepts/05 UI Components/Pagination/00 Overview/15 Explore More.md
  images/Pagination/pagination-elements.png
Labels: 24_2

#6889 Pagination: minor API fixes
  api-reference/10 UI Components/dxPagination/1 Configuration/displayMode.md
  api-reference/10 UI Components/dxPagination/1 Configuration/infoText.md
Labels: 24_2

#6891 Chat: update image in GS
  applications/GettingStartedWith/Chat/index.js
Labels: 24_2

#6892 Fix Overviews
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
Labels: 24_1

#6893 Fix Overviews (#6892)
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
Labels: cherry-pick, 23_2

#6894 Fix Overviews
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/Scheduler/02 Overview/10 Key Features.md
  concepts/05 UI Components/TextBox/02 Overview/10 Key Features.md
Labels: 24_2

#6895 Grids: update onAdd description
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onAdd.md
Labels: 24_1

#6896 Grids: update onAdd description (#6895)
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onAdd.md
Labels: cherry-pick, 23_2

#6897 Grids: update onAdd description (#6895)
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/onAdd.md
Labels: cherry-pick, 24_2

#6902 CustomStore: fix userData code snippet
  api-reference/30 Data Layer/CustomStore/LoadOptions/userData.md
Labels: 24_1

#6903 CustomStore: fix userData code snippet (#6902)
  api-reference/30 Data Layer/CustomStore/LoadOptions/userData.md
Labels: cherry-pick, 23_2

#6904 CustomStore: fix userData code snippet (#6902)
  api-reference/30 Data Layer/CustomStore/LoadOptions/userData.md
Labels: cherry-pick, 24_2

#6906 Diagram: update dataItem description (#6901)
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramShape/dataItem.md
Labels: cherry-pick, 23_2

#6907 Diagram: update dataItem description (#6901)
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramShape/dataItem.md
Labels: cherry-pick, 24_2

#6905 Add a note about using Globalize
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/08 Register 3rd-Party Dependencies/02 Globalize Registration.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/63 Register 3rd-Party Dependencies/2 Globalize Registration.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/localization/globalize/globalize.md
Labels: 24_1

#6908 Add a note about using Globalize (#6905)
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/08 Register 3rd-Party Dependencies/02 Globalize Registration.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/63 Register 3rd-Party Dependencies/2 Globalize Registration.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/localization/globalize/globalize.md
Labels: cherry-pick, 24_2

#6911 DeferRendering: add a note about deprecation
  api-reference/10 UI Components/dxDeferRendering/dxDeferRendering.md
Labels: 24_2

#6912 DataGrid: add info about sticky headers
  concepts/05 UI Components/DataGrid/15 Columns/15 Customize Column Headers.md
Labels: 24_1

#6913 DataGrid: add info about sticky headers (#6912)
  concepts/05 UI Components/DataGrid/15 Columns/15 Customize Column Headers.md
Labels: cherry-pick, 23_2

#6914 DataGrid: add info about sticky headers (#6912)
  concepts/05 UI Components/DataGrid/15 Columns/15 Customize Column Headers.md
Labels: cherry-pick, 24_2

#6917 Licensing: fix link
  concepts/Common/Licensing/27 Redistribution.md
Labels: 24_2

#6916 Diagram: add a note about overriding shape settings
  concepts/05 UI Components/Diagram/10 Data Binding/40 Optional Binding Expressions.md
Labels: 24_1

#6918 Diagram: add a note about overriding shape settings (#6916)
  concepts/05 UI Components/Diagram/10 Data Binding/40 Optional Binding Expressions.md
Labels: cherry-pick, 23_2

#6919 Diagram: add a note about overriding shape settings (#6916)
  concepts/05 UI Components/Diagram/10 Data Binding/40 Optional Binding Expressions.md
Labels: cherry-pick, 24_2

#6920 Diagram: update Data Binding code samples
  concepts/05 UI Components/Diagram/10 Data Binding/10 Node and Edge Arrays.md
  concepts/05 UI Components/Diagram/10 Data Binding/20 Linear Array.md
  concepts/05 UI Components/Diagram/10 Data Binding/30 Hierarchical Array.md
  concepts/05 UI Components/Diagram/10 Data Binding/35 Diagram Layout.md
Labels: 24_1

#6921 Diagram: update Data Binding code samples
  concepts/05 UI Components/Diagram/10 Data Binding/10 Node and Edge Arrays.md
  concepts/05 UI Components/Diagram/10 Data Binding/20 Linear Array.md
  concepts/05 UI Components/Diagram/10 Data Binding/30 Hierarchical Array.md
  concepts/05 UI Components/Diagram/10 Data Binding/35 Diagram Layout.md
Labels: cherry-pick, 23_2

#6922 Diagram: update Data Binding code samples (#6920)
  concepts/05 UI Components/Diagram/10 Data Binding/10 Node and Edge Arrays.md
  concepts/05 UI Components/Diagram/10 Data Binding/20 Linear Array.md
  concepts/05 UI Components/Diagram/10 Data Binding/30 Hierarchical Array.md
  concepts/05 UI Components/Diagram/10 Data Binding/35 Diagram Layout.md
Labels: cherry-pick, 24_2

#6927 Diagram: fix last sample
  concepts/05 UI Components/Diagram/10 Data Binding/35 Diagram Layout.md
  concepts/05 UI Components/Diagram/10 Data Binding/40 Optional Binding Expressions.md
Labels: 24_1

#6928 Diagram: fix last sample (#6927)
  concepts/05 UI Components/Diagram/10 Data Binding/35 Diagram Layout.md
  concepts/05 UI Components/Diagram/10 Data Binding/40 Optional Binding Expressions.md
Labels: cherry-pick, 23_2

#6929 Diagram: fix last sample (#6927)
  concepts/05 UI Components/Diagram/10 Data Binding/35 Diagram Layout.md
  concepts/05 UI Components/Diagram/10 Data Binding/40 Optional Binding Expressions.md
Labels: cherry-pick, 24_2

#6932 DataGrid: fix Angular code in Customize Buttons
  concepts/05 UI Components/DataGrid/15 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/1 Customize Buttons.md
Labels: 24_2

#6933 DataGrid: fix Angular code in Customize Buttons (#6932)
  concepts/05 UI Components/DataGrid/15 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/1 Customize Buttons.md
Labels: cherry-pick, 24_1

#6934 DataGrid: fix Angular code in Customize Buttons (#6932)
  concepts/05 UI Components/DataGrid/15 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/1 Customize Buttons.md
Labels: cherry-pick, 25_1

#6935 HTML Editor: section Formats topic
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/HtmlEditor/10 Formats/00 Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/05 Inline (Or Text) Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Block Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/15 Embedded Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/20 Image Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/25 Table Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/40 Format the Content Programmatically.md
  concepts/05 UI Components/HtmlEditor/10 Formats/60 Customize Built-In Formats and Modules/10 Modify.md
  concepts/05 UI Components/HtmlEditor/10 Formats/60 Customize Built-In Formats and Modules/20 Extend.md
  concepts/05 UI Components/HtmlEditor/10 Formats/60 Customize Built-In Formats and Modules/Customize Built-In Formats and Modules.md
Labels: 24_2

#6936 HTML Editor: section Formats topic (#6935)
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/HtmlEditor/10 Formats/00 Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/05 Inline (Or Text) Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Block Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/15 Embedded Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/20 Image Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/25 Table Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/40 Format the Content Programmatically.md
  concepts/05 UI Components/HtmlEditor/10 Formats/60 Customize Built-In Formats and Modules/10 Modify.md
  concepts/05 UI Components/HtmlEditor/10 Formats/60 Customize Built-In Formats and Modules/20 Extend.md
  concepts/05 UI Components/HtmlEditor/10 Formats/60 Customize Built-In Formats and Modules/Customize Built-In Formats and Modules.md
Labels: cherry-pick, 24_1

#6937 HTML Editor: section Formats topic (#6935)
  concepts/05 UI Components/HtmlEditor/02 Overview/10 Key Features.md
  concepts/05 UI Components/HtmlEditor/10 Formats/00 Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/05 Inline (Or Text) Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Block Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/15 Embedded Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/20 Image Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/25 Table Formats.md
  concepts/05 UI Components/HtmlEditor/10 Formats/40 Format the Content Programmatically.md
  concepts/05 UI Components/HtmlEditor/10 Formats/60 Customize Built-In Formats and Modules/10 Modify.md
  concepts/05 UI Components/HtmlEditor/10 Formats/60 Customize Built-In Formats and Modules/20 Extend.md
  concepts/05 UI Components/HtmlEditor/10 Formats/60 Customize Built-In Formats and Modules/Customize Built-In Formats and Modules.md
Labels: cherry-pick, 25_1

#6890 Pagination: add Getting Started tutorial
  applications/GettingStartedWith/Pagination/index.css
  applications/GettingStartedWith/Pagination/index.html
  applications/GettingStartedWith/Pagination/index.js
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/00 Getting Started with Pagination.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/05 Create Pagination.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/10 Configure Pagination.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/00 Implement Remote Pagination.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/05 Fetch Data.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/10 Render Items.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/15 Handle Page Size and Index Changes.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/20 Integrate LoadPanel.md
Labels: 24_2

#6938 Pagination: add Getting Started tutorial
  applications/GettingStartedWith/Pagination/index.css
  applications/GettingStartedWith/Pagination/index.html
  applications/GettingStartedWith/Pagination/index.js
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/00 Getting Started with Pagination.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/05 Create Pagination.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/10 Configure Pagination.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/00 Implement Remote Pagination.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/05 Fetch Data.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/10 Render Items.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/15 Handle Page Size and Index Changes.md
  concepts/05 UI Components/Pagination/05 Getting Started with Pagination/15 Implement Remote Pagination/20 Integrate LoadPanel.md
Labels: cherry-pick, 25_1
