Repository DevExpress/devextreme-documentation, pull requests merged in 2024-01, with the labels that each got.

#5915 Chart: add a note to label.customizeText (#5887)
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/customizeText.md
Labels: cherry-pick, 23_2

#5916 Chart: add a note to label.customizeText (#5887)
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/customizeText.md
Labels: cherry-pick, 24_1

#5917 TreeList: update Focused Row topic
  concepts/05 UI Components/TreeList/69 Focused Row.md
Labels: 23_2

#5919 TreeList: update Focused Row topic (#5917)
  concepts/05 UI Components/TreeList/69 Focused Row.md
Labels: cherry-pick, 23_1

#5920 TreeList: update Focused Row topic (#5917)
  concepts/05 UI Components/TreeList/69 Focused Row.md
Labels: cherry-pick, 24_1

#5918 Grids: update calculateCellValue
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
Labels: 23_2

#5922 Grids: update calculateCellValue (#5918)
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
Labels: cherry-pick, 24_1

#5921 Grids: update calculateCellValue (#5918)
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
Labels: cherry-pick, 23_1

#5926 Update UI Events API
  MenuConfig.xml
  api-reference/50 Common/utils/events/off(element).md
  api-reference/50 Common/utils/events/off(element_eventName).md
  api-reference/50 Common/utils/events/off(element_eventName_handler).md
  api-reference/50 Common/utils/events/off(element_eventName_selector).md
  api-reference/50 Common/utils/events/off(element_eventName_selector_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_data_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_selector_data_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_selector_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_data_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_selector_data_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_selector_handler).md
  api-reference/50 Common/utils/events/trigger(element_event).md
  api-reference/50 Common/utils/events/trigger(element_event_extraParameters).md
Labels: 23_2

#5927 Update UI Events API (#5926)
  MenuConfig.xml
  api-reference/50 Common/utils/events/off(element).md
  api-reference/50 Common/utils/events/off(element_eventName).md
  api-reference/50 Common/utils/events/off(element_eventName_handler).md
  api-reference/50 Common/utils/events/off(element_eventName_selector).md
  api-reference/50 Common/utils/events/off(element_eventName_selector_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_data_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_selector_data_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_selector_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_data_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_selector_data_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_selector_handler).md
  api-reference/50 Common/utils/events/trigger(element_event).md
  api-reference/50 Common/utils/events/trigger(element_event_extraParameters).md
Labels: cherry-pick, 23_1

#5928 Update UI Events API (#5926)
  MenuConfig.xml
  api-reference/50 Common/utils/events/off(element).md
  api-reference/50 Common/utils/events/off(element_eventName).md
  api-reference/50 Common/utils/events/off(element_eventName_handler).md
  api-reference/50 Common/utils/events/off(element_eventName_selector).md
  api-reference/50 Common/utils/events/off(element_eventName_selector_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_data_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_selector_data_handler).md
  api-reference/50 Common/utils/events/on(element_eventName_selector_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_data_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_selector_data_handler).md
  api-reference/50 Common/utils/events/one(element_eventName_selector_handler).md
  api-reference/50 Common/utils/events/trigger(element_event).md
  api-reference/50 Common/utils/events/trigger(element_event_extraParameters).md
Labels: cherry-pick, 24_1

#5929 Make 'Link Modules' jQuery-only
  concepts/Common/Modularity/01 Link Modules/Link Modules.md
  concepts/Common/Modularity/015 Create a Custom Bundle/Create a Custom Bundle.md
Labels: 23_2

#5930 Make 'Link Modules' jQuery-only (#5929)
  concepts/Common/Modularity/01 Link Modules/Link Modules.md
  concepts/Common/Modularity/015 Create a Custom Bundle/Create a Custom Bundle.md
Labels: cherry-pick, 23_1

#5931 Make 'Link Modules' jQuery-only (#5929)
  concepts/Common/Modularity/01 Link Modules/Link Modules.md
  concepts/Common/Modularity/015 Create a Custom Bundle/Create a Custom Bundle.md
Labels: cherry-pick, 24_1

#5932 Troubleshooting: add ASP.NET Core code snippet
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/15 A Request Error Occurs After Filtering or Searching.md
Labels: 23_2

#5933 Troubleshooting: add ASP.NET Core code snippet (#5932)
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/15 A Request Error Occurs After Filtering or Searching.md
Labels: cherry-pick, 23_1

#5934 Troubleshooting: add ASP.NET Core code snippet (#5932)
  concepts/80 Troubleshooting/05 DataGrid and TreeList Issues/15 A Request Error Occurs After Filtering or Searching.md
Labels: cherry-pick, 24_1

#5935 Remove obsolete example link from onContentReady
  api-reference/10 UI Components/Widget/1 Configuration/onContentReady.md
Labels: 23_2

#5936 Remove obsolete example link from onContentReady (#5935)
  api-reference/10 UI Components/Widget/1 Configuration/onContentReady.md
Labels: cherry-pick, 23_1

#5937 Remove obsolete example link from onContentReady (#5935)
  api-reference/10 UI Components/Widget/1 Configuration/onContentReady.md
Labels: cherry-pick, 24_1

#5939 SelectBox: fix Grouping code snippet
  concepts/05 UI Components/SelectBox/07 Grouping/01 In the Data Source.md
Labels: 23_2

#5940 SelectBox: fix Grouping code snippet (#5939)
  concepts/05 UI Components/SelectBox/07 Grouping/01 In the Data Source.md
Labels: cherry-pick, 23_1

#5941 SelectBox: fix Grouping code snippet (#5939)
  concepts/05 UI Components/SelectBox/07 Grouping/01 In the Data Source.md
Labels: cherry-pick, 24_1

#5942 Chart: fix demo link
  concepts/05 UI Components/Chart/65 Constant Lines.md
Labels: 23_2

#5944 Chart: fix demo link (#5942)
  concepts/05 UI Components/Chart/65 Constant Lines.md
Labels: cherry-pick, 24_1

#5945 HtmlEditor: update Formats section
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
Labels: 23_2

#5946 HtmlEditor: update Formats section (#5945)
  concepts/05 UI Components/HtmlEditor/10 Formats/10 Formats.md
Labels: cherry-pick, 23_1

#5948 DataGrid: change demo link
  api-reference/10 UI Components/GridBase/1 Configuration/editing/refreshMode.md
  concepts/05 UI Components/FileUploader/40 File Validation.md
Labels: 23_2

#5949 DataGrid: change demo link (#5948)
  api-reference/10 UI Components/GridBase/1 Configuration/editing/refreshMode.md
  concepts/05 UI Components/FileUploader/40 File Validation.md
Labels: cherry-pick, 23_1

#5951 React: fix code snippet
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/8 Using the Template Component.md
Labels: 23_2

#5952 React: fix code snippet (#5951)
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/8 Using the Template Component.md
Labels: cherry-pick, 23_1

#5953 React: fix code snippet (#5951)
  concepts/50 React Components/40 Component Configuration Syntax/55 Markup Customization/8 Using the Template Component.md
Labels: cherry-pick, 24_1

#5955 Chart: update Scale Breaks section
  concepts/05 UI Components/Chart/20 Axes/33 Scale Breaks.md
Labels: 23_2

#5956 Chart: update Scale Breaks section (#5955)
  concepts/05 UI Components/Chart/20 Axes/33 Scale Breaks.md
Labels: cherry-pick, 23_1

#5957 Chart: update Scale Breaks section (#5955)
  concepts/05 UI Components/Chart/20 Axes/33 Scale Breaks.md
Labels: cherry-pick, 24_1

#5958 SelectBox: update Configure Search Parameters article
  concepts/05 UI Components/SelectBox/10 Configure Search Parameters.md
Labels: 23_2

#5960 SelectBox: update Configure Search Parameters article (#5958)
  concepts/05 UI Components/SelectBox/10 Configure Search Parameters.md
Labels: cherry-pick, 23_1

#5961 SelectBox: update Configure Search Parameters article (#5958)
  concepts/05 UI Components/SelectBox/10 Configure Search Parameters.md
Labels: cherry-pick, 24_1

#5959 DateRangeBox: add a note to 'value'
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/value.md
Labels: 23_2

#5962 DateRangeBox: add a note to 'value' (#5959)
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/value.md
Labels: cherry-pick, 23_1

#5963 DateRangeBox: add a note to 'value' (#5959)
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/value.md
Labels: cherry-pick, 24_1

#5954 Add pinmap icon
  applications/Icons/script.js
Labels: 24_1

#5968 Diagram, Validation, Troubleshooting: update navigation tree
  MenuConfig.xml
  api-reference/10 UI Components/Editor/1 Configuration/isValid.md
  concepts/05 UI Components/Diagram/50 How To/How To.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/70 Conditional Validation.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/80 Knockout Only - Validate a View Model.md
  concepts/80 Troubleshooting/40 Components are Rendered Incorrectly if a Container State is Changed/00 Components are Rendered Incorrectly if a Container State is Changed.md
Labels: 23_2

#5969 Diagram, Validation, Troubleshooting: update navigation tree (#5968)
  MenuConfig.xml
  api-reference/10 UI Components/Editor/1 Configuration/isValid.md
  concepts/05 UI Components/Diagram/50 How To/How To.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/70 Conditional Validation.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/80 Knockout Only - Validate a View Model.md
  concepts/80 Troubleshooting/40 Components are Rendered Incorrectly if a Container State is Changed/00 Components are Rendered Incorrectly if a Container State is Changed.md
Labels: cherry-pick, 24_1

#5970 Diagram, Validation, Troubleshooting: update navigation tree (#5968)
  MenuConfig.xml
  api-reference/10 UI Components/Editor/1 Configuration/isValid.md
  concepts/05 UI Components/Diagram/50 How To/How To.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/70 Conditional Validation.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/80 Knockout Only - Validate a View Model.md
  concepts/80 Troubleshooting/40 Components are Rendered Incorrectly if a Container State is Changed/00 Components are Rendered Incorrectly if a Container State is Changed.md
Labels: cherry-pick, 23_1
