Repository DevExpress/devextreme-documentation, pull requests merged in 2024-11, with the labels that each got.

#6790 Map: minor azure fixes
  api-reference/10 UI Components/dxMap/1 Configuration/apiKey/azure.md
  concepts/05 UI Components/Map/10 Specify the Provider and Type.md
Labels: 24_2

#6792 HtmlEditor: remove Markdown support mentions
  api-reference/10 UI Components/dxHtmlEditor/dxHtmlEditor.md
  applications/GettingStartedWith/HtmlEditor/index.html
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/00 Getting Started with HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Initial Value.md
  concepts/05 UI Components/HtmlEditor/02 Overview/00 Overview.md
  concepts/05 UI Components/HtmlEditor/90 Limitations.md
Labels: 24_2

#6793 Remove DevExtreme Installer mentions
  concepts/Common/.NET Backend Solutions/Office File API/Office File API.md
  concepts/Common/Licensing/00 Licensing.md
Labels: 24_2

#6796 NumberBox: remove outdated reset method description (#6795)
  api-reference/10 UI Components/dxNumberBox/3 Methods/reset().md
Labels: cherry-pick, 23_2

#6797 NumberBox: remove outdated reset method description (#6795)
  api-reference/10 UI Components/dxNumberBox/3 Methods/reset().md
Labels: cherry-pick, 24_2

#6801 React: add info about custom nested configuration components
  concepts/50 React Components/40 Component Configuration Syntax/12 Properties of the Object Type.md
  concepts/50 React Components/40 Component Configuration Syntax/20 Collections.md
  concepts/50 React Components/40 Component Configuration Syntax/80 Custom Nested Configuration Components.md
Labels: 24_2

#6802 Bump "devextreme-internal-tools" to "16.0.0-beta.11"
  package.json
Labels: 24_2

#6642 Fixed columns: add icons for context menu
  applications/Icons/script.js
Labels: 24_2

#6805 Update links to SVG colors
  api-reference/10 UI Components/dxFunnel/1 Configuration/colorField.md
  api-reference/10 UI Components/dxTreeMap/1 Configuration/colorField.md
  includes/common-colorlist.md
  includes/dataviz-ref-palette.md
Labels: 24_1

#6806 Update links to SVG colors (#6805)
  api-reference/10 UI Components/dxFunnel/1 Configuration/colorField.md
  api-reference/10 UI Components/dxTreeMap/1 Configuration/colorField.md
  includes/common-colorlist.md
  includes/dataviz-ref-palette.md
Labels: cherry-pick, 23_2

#6807 Update links to SVG colors (#6805)
  api-reference/10 UI Components/dxFunnel/1 Configuration/colorField.md
  api-reference/10 UI Components/dxTreeMap/1 Configuration/colorField.md
  includes/common-colorlist.md
  includes/dataviz-ref-palette.md
Labels: cherry-pick, 24_2

#6808 DataGrid/TreeList: update Column Fixing topics
  concepts/05 UI Components/DataGrid/15 Columns/30 Column Fixing.md
  concepts/05 UI Components/TreeList/10 Columns/30 Column Fixing.md
Labels: 24_2

#6809 TreeView: add a note about rootValue
  api-reference/10 UI Components/dxTreeView/1 Configuration/dataStructure.md
  api-reference/10 UI Components/dxTreeView/1 Configuration/rootValue.md
Labels: 24_1

#6811 TreeView: add a note about rootValue (#6809)
  api-reference/10 UI Components/dxTreeView/1 Configuration/dataStructure.md
  api-reference/10 UI Components/dxTreeView/1 Configuration/rootValue.md
Labels: cherry-pick, 24_2

#6820 DataGrid: add a note about toolbar
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/65 Customize the Toolbar.md
Labels: 24_1

#6821 DataGrid: add a note about toolbar (#6820)
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/65 Customize the Toolbar.md
Labels: cherry-pick, 23_2

#6822 DataGrid: add a note about toolbar (#6820)
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/65 Customize the Toolbar.md
Labels: cherry-pick, 24_2

#6825 Scheduler: update recurrenceRule code snippet
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerAppointment/recurrenceRule.md
Labels: 24_1

#6826 Scheduler: update recurrenceRule code snippet (#6825)
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerAppointment/recurrenceRule.md
Labels: cherry-pick, 23_2

#6827 Scheduler: update recurrenceRule code snippet (#6825)
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerAppointment/recurrenceRule.md
Labels: cherry-pick, 24_2

#6824 Scheduler: add a note to scrolling.mode
  api-reference/_hidden/dxSchedulerScrolling/mode.md
Labels: 24_1

#6828 Scheduler: add a note to scrolling.mode (#6824)
  api-reference/_hidden/dxSchedulerScrolling/mode.md
Labels: cherry-pick, 23_2

#6829 Scheduler: add a note to scrolling.mode (#6824)
  api-reference/_hidden/dxSchedulerScrolling/mode.md
Labels: cherry-pick, 24_2

#6818 Chat: add Getting Started tutorial
  MenuConfig.xml
  applications/GettingStartedWith/Chat/index.css
  applications/GettingStartedWith/Chat/index.html
  applications/GettingStartedWith/Chat/index.js
  concepts/05 UI Components/Chat/05 Getting Started with Chat/00 Getting Started with Chat.md
  concepts/05 UI Components/Chat/05 Getting Started with Chat/05 Create a Chat.md
  concepts/05 UI Components/Chat/05 Getting Started with Chat/10 Render Sent Messages.md
  concepts/05 UI Components/Chat/05 Getting Started with Chat/15 Manage Users.md
  concepts/05 UI Components/Chat/05 Getting Started with Chat/20 Set Initial Messages.md
  concepts/05 UI Components/Chat/05 Getting Started with Chat/25 Post-Processing.md
  images/Chat/bot.png
Labels: 24_2
