Repository DevExpress/devextreme-documentation, pull requests merged in 2024-03, with the labels that each got.

#6089 DefaultOptions: update code snippet
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: 23_2

#6098 DefaultOptions: update code snippet (#6089)
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: cherry-pick, 23_1

#6099 DefaultOptions: update code snippet (#6089)
  api-reference/10 UI Components/DOMComponent/3 Methods/defaultOptions(rule).md
Labels: cherry-pick, 24_1

#6100 PivotGrid: update images in calculateSummaryValue
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/calculateSummaryValue.md
  images/pivotgrid/calculate-summary-value-1.png
  images/pivotgrid/calculate-summary-value-2.png
Labels: 23_2

#6101 PivotGrid: update images in calculateSummaryValue (#6100)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/calculateSummaryValue.md
  images/pivotgrid/calculate-summary-value-1.png
  images/pivotgrid/calculate-summary-value-2.png
Labels: cherry-pick, 23_1

#6102 PivotGrid: update images in calculateSummaryValue (#6100)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/calculateSummaryValue.md
  images/pivotgrid/calculate-summary-value-1.png
  images/pivotgrid/calculate-summary-value-2.png
Labels: cherry-pick, 24_1

#6062 Form: describe groupItem.captionTemplate
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/captionTemplate.md
Labels: 24_1

#6104 PivotGrid: update dataFieldArea
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/dataFieldArea.md
Labels: 23_2

#6105 PivotGrid: update dataFieldArea (#6104)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/dataFieldArea.md
Labels: cherry-pick, 23_1

#6106 PivotGrid: update dataFieldArea (#6104)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/dataFieldArea.md
Labels: cherry-pick, 24_1

#6073 DropDownButton: describe `template`
  api-reference/10 UI Components/dxDropDownButton/1 Configuration/template.md
Labels: 24_1

#6110 Menu: update Keyboard Navigation
  concepts/05 UI Components/Menu/02 Accessibility/15 Keyboard Navigation.md
Labels: 23_2

#6111 Menu: update Keyboard Navigation (#6110)
  concepts/05 UI Components/Menu/02 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 24_1

#6112 HtmlEditor: add a note about spellcheck
  concepts/05 UI Components/HtmlEditor/05 Overview.md
Labels: 24_1

#5877 Add Data Analytics and Backend sections
  MenuConfig.xml
  concepts/Common/.NET Backend Solutions/Office File API/Office File API.md
  concepts/Common/.NET Backend Solutions/Web API Service (CRUD)/Web API Service (CRUD).md
  concepts/Common/Data Analytics and BI/Embedded Dashboard/Embedded Dashboard.md
  concepts/Common/Data Analytics and BI/Embedded Reports/Embedded Reports.md
  images/Common/Embedded_Dashboard.png
  images/Common/Embedded_Reports.png
  images/Common/backend-web-api-article-main.png
  images/Common/office-file-api.png
Labels: 23_2

#6116 Add Data Analytics and Backend sections (#5877)
  MenuConfig.xml
  concepts/Common/.NET Backend Solutions/Office File API/Office File API.md
  concepts/Common/.NET Backend Solutions/Web API Service (CRUD)/Web API Service (CRUD).md
  concepts/Common/Data Analytics and BI/Embedded Dashboard/Embedded Dashboard.md
  concepts/Common/Data Analytics and BI/Embedded Reports/Embedded Reports.md
  images/Common/Embedded_Dashboard.png
  images/Common/Embedded_Reports.png
  images/Common/backend-web-api-article-main.png
  images/Common/office-file-api.png
Labels: cherry-pick, 24_1

#6117 Add 'handlevertical', 'handlehorizontal', 'triangleup', 'triangledown', 'triangleright', 'triangleleft', 'optionsgear', 'send' icons
  applications/Icons/script.js
Labels: 24_1

#6126 Fix invalid info in docs (#6124)
  api-reference/10 UI Components/dxChart/1 Configuration/commonPaneSettings/backgroundColor.md
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/30 Change the Generated Data Source.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/30 Disable Validation Dynamically.md
Labels: cherry-pick, 24_1

#6115 Grids: update deprecated options
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/headerFilter/allowSearch.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/headerFilter/searchTimeout.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/headerFilter/allowSearch.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/headerFilter/searchTimeout.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/headerFilter/allowSearch.md
  api-reference/40 Common Types/15 grids/ColumnChooser/allowSearch.md
  api-reference/40 Common Types/15 grids/ColumnChooser/searchTimeout.md
  api-reference/40 Common Types/15 grids/HeaderFilter/allowSearch.md
  api-reference/40 Common Types/15 grids/HeaderFilter/searchTimeout.md
  api-reference/_hidden/GridBaseColumn/headerFilter/allowSearch.md
  api-reference/_hidden/GridBaseColumn/headerFilter/searchMode.md
  api-reference/_hidden/dxGanttHeaderFilter/allowSearch.md
  api-reference/_hidden/dxGanttHeaderFilter/searchTimeout.md
Labels: 23_2

#6127 Grids: update deprecated options (#6115)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/headerFilter/allowSearch.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/headerFilter/searchTimeout.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/headerFilter/allowSearch.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/headerFilter/searchTimeout.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/headerFilter/allowSearch.md
  api-reference/40 Common Types/15 grids/ColumnChooser/allowSearch.md
  api-reference/40 Common Types/15 grids/ColumnChooser/searchTimeout.md
  api-reference/40 Common Types/15 grids/HeaderFilter/allowSearch.md
  api-reference/40 Common Types/15 grids/HeaderFilter/searchTimeout.md
  api-reference/_hidden/GridBaseColumn/headerFilter/allowSearch.md
  api-reference/_hidden/GridBaseColumn/headerFilter/searchMode.md
  api-reference/_hidden/dxGanttHeaderFilter/allowSearch.md
  api-reference/_hidden/dxGanttHeaderFilter/searchTimeout.md
Labels: cherry-pick, 23_1

#6128 Grids: update deprecated options (#6115)
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/headerFilter/allowSearch.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/headerFilter/searchTimeout.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/headerFilter/allowSearch.md
  api-reference/10 UI Components/dxPivotGridFieldChooser/1 Configuration/headerFilter/searchTimeout.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/headerFilter/allowSearch.md
  api-reference/40 Common Types/15 grids/ColumnChooser/allowSearch.md
  api-reference/40 Common Types/15 grids/ColumnChooser/searchTimeout.md
  api-reference/40 Common Types/15 grids/HeaderFilter/allowSearch.md
  api-reference/40 Common Types/15 grids/HeaderFilter/searchTimeout.md
  api-reference/_hidden/GridBaseColumn/headerFilter/allowSearch.md
  api-reference/_hidden/GridBaseColumn/headerFilter/searchMode.md
  api-reference/_hidden/dxGanttHeaderFilter/allowSearch.md
  api-reference/_hidden/dxGanttHeaderFilter/searchTimeout.md
Labels: cherry-pick, 24_1

#6132 TreeMap: add a code snippet to group.label
  api-reference/10 UI Components/dxTreeMap/1 Configuration/group/label/label.md
Labels: 23_2

#6133 TreeMap: add a code snippet to group.label (#6132)
  api-reference/10 UI Components/dxTreeMap/1 Configuration/group/label/label.md
Labels: cherry-pick, 23_1

#6134 TreeMap: add a code snippet to group.label (#6132)
  api-reference/10 UI Components/dxTreeMap/1 Configuration/group/label/label.md
Labels: cherry-pick, 24_1

#6135 DateBox/NumberBox: add a note to validationStatus
  api-reference/10 UI Components/dxDateBox/1 Configuration/validationStatus.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/validationStatus.md
Labels: 23_2

#6136 DateBox/NumberBox: add a note to validationStatus (#6135)
  api-reference/10 UI Components/dxDateBox/1 Configuration/validationStatus.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/validationStatus.md
Labels: cherry-pick, 23_1

#6137 DateBox/NumberBox: add a note to validationStatus (#6135)
  api-reference/10 UI Components/dxDateBox/1 Configuration/validationStatus.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/validationStatus.md
Labels: cherry-pick, 24_1

#6141 Gantt: fix search properties redirect (#6140)
  api-reference/_hidden/GridBaseColumn/headerFilter/allowSearch.md
  api-reference/_hidden/GridBaseColumn/headerFilter/searchMode.md
Labels: cherry-pick, 23_1

#6142 Gantt: fix search properties redirect (#6140)
  api-reference/_hidden/GridBaseColumn/headerFilter/allowSearch.md
  api-reference/_hidden/GridBaseColumn/headerFilter/searchMode.md
Labels: cherry-pick, 24_1

#6146 Data Analytics: move Embedded Reports section
  concepts/Common/Data Analytics and BI/00 Embedded Reports/Embedded Reports.md
  concepts/Common/Data Analytics and BI/05 Embedded JS Reports/Embedded JS Reports.md
  concepts/Common/Data Analytics and BI/10 Embedded Dashboard/Embedded Dashboard.md
Labels: 23_2

#6147 Data Analytics: move Embedded Reports section (#6146)
  concepts/Common/Data Analytics and BI/00 Embedded Reports/Embedded Reports.md
  concepts/Common/Data Analytics and BI/05 Embedded JS Reports/Embedded JS Reports.md
  concepts/Common/Data Analytics and BI/10 Embedded Dashboard/Embedded Dashboard.md
Labels: cherry-pick, 24_1

#6148 W0004: add info about a theme name
  api-reference/50 Common/utils/zz Errors and Warnings/W0004.md
Labels: 23_2

#6149 W0004: add info about a theme name (#6148)
  api-reference/50 Common/utils/zz Errors and Warnings/W0004.md
Labels: cherry-pick, 23_1

#6150 W0004: add info about a theme name (#6148)
  api-reference/50 Common/utils/zz Errors and Warnings/W0004.md
Labels: cherry-pick, 24_1

#6151 Diagram: describe the focus() method
  api-reference/10 UI Components/dxDiagram/3 Methods/focus().md
Labels: 23_2

#6152 Diagram: describe the focus() method (#6151)
  api-reference/10 UI Components/dxDiagram/3 Methods/focus().md
Labels: cherry-pick, 23_1

#6153 Diagram: describe the focus() method (#6151)
  api-reference/10 UI Components/dxDiagram/3 Methods/focus().md
Labels: cherry-pick, 24_1

#6154 ActionSheet: add Accessibility topic
  concepts/05 UI Components/ActionSheet/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/ActionSheet/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/ActionSheet/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/ActionSheet/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/ActionSheet/03 Accessibility/20 Screen Reader Support.md
Labels: 24_1

#6155 FileUploader: add Accessibility topic
  concepts/05 UI Components/FileUploader/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/FileUploader/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/FileUploader/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/FileUploader/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/FileUploader/05 Accessibility/20 Screen Reader Support.md
Labels: 24_1

#6156 LoadPanel: add Accessibility topic
  concepts/05 UI Components/LoadPanel/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/LoadPanel/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/LoadPanel/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/LoadPanel/03 Accessibility/15 Screen Reader Support.md
Labels: 24_1

#6157 Map: add apiKey to Configuration
  api-reference/10 UI Components/dxMap/dxMap.md
Labels: 24_1

#6158 Map: add apiKey to Configuration (#6157)
  api-reference/10 UI Components/dxMap/dxMap.md
Labels: cherry-pick, 23_2

#6162 PolarChart: update useSpiderWeb
  api-reference/10 UI Components/dxPolarChart/1 Configuration/useSpiderWeb.md
  images/ChartJS/UseSpiderWeb.png
  images/ChartJS/spider-web.png
Labels: 23_2

#6163 PolarChart: update useSpiderWeb (#6162)
  api-reference/10 UI Components/dxPolarChart/1 Configuration/useSpiderWeb.md
  images/ChartJS/UseSpiderWeb.png
  images/ChartJS/spider-web.png
Labels: cherry-pick, 23_1

#6164 PolarChart: update useSpiderWeb (#6162)
  api-reference/10 UI Components/dxPolarChart/1 Configuration/useSpiderWeb.md
  images/ChartJS/UseSpiderWeb.png
  images/ChartJS/spider-web.png
Labels: cherry-pick, 24_1

#6160 Tooltip: add Accessibility topic
  concepts/05 UI Components/Tooltip/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Tooltip/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Tooltip/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Tooltip/03 Accessibility/15 Screen Reader Support.md
Labels: 24_1

#6161 DateBox: add info about AM/PM switch
  concepts/05 UI Components/DateBox/02 Accessibility/15 Keyboard Navigation.md
Labels: 23_2

#6165 DateBox: add info about AM/PM switch (#6161)
  concepts/05 UI Components/DateBox/20 Keyboard Support.md
Labels: cherry-pick, 23_1

#6166 DateBox: add info about AM/PM switch (#6161)
  concepts/05 UI Components/DateBox/02 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 24_1

#6167 Toast: add Accessibility topic
  concepts/05 UI Components/Toast/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Toast/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Toast/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Toast/03 Accessibility/15 Screen Reader Support.md
Labels: 24_1

#6168 TextArea: add Accessibility topic
  concepts/05 UI Components/TextArea/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/TextArea/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/TextArea/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TextArea/05 Accessibility/15 Screen Reader Support.md
Labels: 24_1

#6169 TextBox: add Accessibility topic
  concepts/05 UI Components/TextBox/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/TextBox/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/TextBox/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TextBox/05 Accessibility/15 Screen Reader Support.md
Labels: 24_1

#6170 Map: add Accessibility topic
  concepts/05 UI Components/Map/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Map/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Map/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Map/03 Accessibility/15 Screen Reader Support.md
Labels: 24_1

#6171 HtmlEditor: add Accessibility topic
  concepts/05 UI Components/HtmlEditor/03 Accessibility/00 Accessibility.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/HtmlEditor/03 Accessibility/20 Screen Reader Support.md
Labels: 24_1

#6175 Angular: add info about DxHttpModule
  concepts/40 Angular Components/40 Common Features/15 Intercept HTTP Requests.md
Labels: 24_1

#6180 Fix spelling issue
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
Labels: 23_2

#6181 Fix spelling issue (#6180)
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
Labels: cherry-pick, 23_1

#6182 Fix spelling issue (#6180)
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
Labels: cherry-pick, 24_1

#6069 New Troubleshooting Guide: Date Handling
  .gitignore
  api-reference/10 UI Components/DateBoxBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/GridBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateSerializationFormat.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/dataType.md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/_hidden/GridBaseColumn/dataType.md
  api-reference/_hidden/GridBaseColumn/filterValue.md
  api-reference/_hidden/GridBaseColumn/filterValues.md
  concepts/70 Data Binding/90 Troubleshooting/0 Troubleshooting.md
  concepts/70 Data Binding/90 Troubleshooting/Date values are parsed or serialized incorrectly.md
  concepts/80 Troubleshooting/10 Date String Handling Issues/00 Date String Handling Issues.md
  concepts/80 Troubleshooting/10 Date String Handling Issues/05 Supported Formats, Exceptions, and Settings.md
Labels: 24_1

#6067 Export PDF files with non-ASCII characters
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportGantt(options).md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/80 Troubleshooting/15 PDF Export/00 PDF Export.md
  concepts/80 Troubleshooting/15 PDF Export/05 Non-Latin Glyph Support.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/pdf_exporter.md
Labels: 24_1
