Repository DevExpress/devextreme-documentation, pull requests merged in 2024-04, with the labels that each got.

#6177 Splitter: add Accessibility topic
  concepts/05 UI Components/Splitter/05 Accessibility/00 Accessibility.md
  concepts/05 UI Components/Splitter/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Splitter/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Splitter/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Splitter/05 Accessibility/20 Screen Reader Support.md
Labels: 24_1

#6184 React: fix links to React docs
  api-reference/10 UI Components/DOMComponent/3 Methods/dispose().md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/70 Conditional Validation.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/50 React Components/20 State Management/3 Controlled Mode.md
  concepts/50 React Components/20 State Management/7 Uncontrolled Mode.md
  concepts/50 React Components/40 Component Configuration Syntax/12 Properties of the Object Type.md
  concepts/50 React Components/40 Component Configuration Syntax/60 Call Methods.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/10 Functions.md
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
  concepts/Common/Security Considerations/Security Considerations.md
Labels: 23_2

#6185 React: fix links to React docs (#6184)
  api-reference/10 UI Components/DOMComponent/3 Methods/dispose().md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/70 Conditional Validation.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/50 React Components/20 State Management/3 Controlled Mode.md
  concepts/50 React Components/20 State Management/7 Uncontrolled Mode.md
  concepts/50 React Components/40 Component Configuration Syntax/12 Properties of the Object Type.md
  concepts/50 React Components/40 Component Configuration Syntax/60 Call Methods.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/10 Functions.md
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
  concepts/Common/Security Considerations/Security Considerations.md
Labels: cherry-pick, 23_1

#6186 React: fix links to React docs (#6184)
  api-reference/10 UI Components/DOMComponent/3 Methods/dispose().md
  concepts/05 UI Components/Popup/00 Getting Started with Popup/04 Show and Hide the Popup.md
  concepts/05 UI Components/zz Common/05 UI Widgets/20 Data Validation/70 Conditional Validation.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/50 React Components/40 Component Configuration Syntax/12 Properties of the Object Type.md
  concepts/50 React Components/40 Component Configuration Syntax/60 Call Methods.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/05 Object Literals.md
  concepts/50 React Components/45 Optimize Performance/05 Do not pass inline functions and objects as component props/10 Functions.md
  concepts/50 React Components/45 Optimize Performance/10 Define Keys For Element Collections.md
  concepts/70 Data Binding/03 Update Data/20 Local Array/Local Array.md
  concepts/Common/Security Considerations/Security Considerations.md
Labels: cherry-pick, 24_1

#6070 Lazy Loading Scheduler Guide
  concepts/05 UI Components/Scheduler/085 Optimize Scheduler Performance with Lazy Loading.md
Labels: 24_1

#6187 DataGrid: update dataRowTemplate
  api-reference/10 UI Components/dxDataGrid/1 Configuration/dataRowTemplate.md
Labels: 23_2

#6199 DataGrid: update dataRowTemplate (#6187)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/dataRowTemplate.md
Labels: cherry-pick, 23_1

#6200 DataGrid: update dataRowTemplate (#6187)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/dataRowTemplate.md
Labels: cherry-pick, 24_1

#6201 Remove beta CDN links
  concepts/Common/Distribution Channels/05 CDN/10 Subresource Integrity Hashes.md
Labels: 23_2

#6193 Cherry-pick: Date Handling Guide (23_1)
  .gitignore
  api-reference/10 UI Components/DateBoxBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/GridBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateSerializationFormat.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/dataType.md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/_hidden/GridBaseColumn/dataType.md
  api-reference/_hidden/GridBaseColumn/filterValue.md
  api-reference/_hidden/GridBaseColumn/filterValues.md
  concepts/70 Data Binding/90 Troubleshooting/0 Troubleshooting.md
  concepts/70 Data Binding/90 Troubleshooting/Date values are parsed or serialized incorrectly.md
  concepts/80 Troubleshooting/10 Date String Handling Issues/00 Date String Handling Issues.md
  concepts/80 Troubleshooting/10 Date String Handling Issues/05 Supported Formats, Exceptions, and Settings.md
Labels: cherry-pick, 23_1

#6196 Cherry-pick: React State Management update (23_1)
  concepts/50 React Components/20 State Management/0 State Management.md
  concepts/50 React Components/20 State Management/3 Controlled Mode.md
  concepts/50 React Components/20 State Management/7 Uncontrolled Mode.md
Labels: cherry-pick, 23_1

#6188 Cherry-pick: Lazy Loading Scheduler Guide (23_2)
  concepts/05 UI Components/Scheduler/085 Optimize Scheduler Performance with Lazy Loading.md
Labels: cherry-pick, 23_2

#6189 Cherry-pick: React State Management (23_2)
  concepts/50 React Components/20 State Management/0 State Management.md
  concepts/50 React Components/20 State Management/3 Controlled Mode.md
  concepts/50 React Components/20 State Management/7 Uncontrolled Mode.md
Labels: cherry-pick, 23_2

#6195 Cherry-pick: non ascii pdf (23_1)
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportGantt(options).md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/80 Troubleshooting/15 PDF Export/00 PDF Export.md
  concepts/80 Troubleshooting/15 PDF Export/05 Non-Latin Glyph Support.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/pdf_exporter.md
Labels: cherry-pick, 23_1

#6192 Cherry-pick: Non-ASCII PDF export (23_2)
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportGantt(options).md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/80 Troubleshooting/15 PDF Export/00 PDF Export.md
  concepts/80 Troubleshooting/15 PDF Export/05 Non-Latin Glyph Support.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/pdf_exporter.md
Labels: cherry-pick, 23_2

#6191 Cherry-pick: Date Handling (23_2)
  .gitignore
  api-reference/10 UI Components/DateBoxBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/GridBase/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxCalendar/1 Configuration/dateSerializationFormat.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dateSerializationFormat.md
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/dataType.md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/_hidden/GridBaseColumn/dataType.md
  api-reference/_hidden/GridBaseColumn/filterValue.md
  api-reference/_hidden/GridBaseColumn/filterValues.md
  concepts/70 Data Binding/90 Troubleshooting/0 Troubleshooting.md
  concepts/70 Data Binding/90 Troubleshooting/Date values are parsed or serialized incorrectly.md
  concepts/80 Troubleshooting/10 Date String Handling Issues/00 Date String Handling Issues.md
  concepts/80 Troubleshooting/10 Date String Handling Issues/05 Supported Formats, Exceptions, and Settings.md
Labels: cherry-pick, 23_2

#6204 ThemeBuilder: add info about Fluent icons
  concepts/60 Themes and Styles/08 ThemeBuilder/40 Export the Resulting Theme.md
Labels: 23_2

#6205 ThemeBuilder: add info about Fluent icons (#6204)
  concepts/60 Themes and Styles/08 ThemeBuilder/40 Export the Resulting Theme.md
Labels: cherry-pick, 24_1

#6206 HtmlEditor: fix typo
  api-reference/10 UI Components/dxHtmlEditor/4 Events/focusOut.md
Labels: 23_2

#6207 HtmlEditor: fix typo (#6206)
  api-reference/10 UI Components/dxHtmlEditor/4 Events/focusOut.md
Labels: cherry-pick, 23_1

#6208 HtmlEditor: fix typo (#6206)
  api-reference/10 UI Components/dxHtmlEditor/4 Events/focusOut.md
Labels: cherry-pick, 24_1

#6209 Grids: update hidingPriority description
  api-reference/_hidden/GridBaseColumn/hidingPriority.md
Labels: 23_2

#6211 Grids: update hidingPriority description (#6209)
  api-reference/_hidden/GridBaseColumn/hidingPriority.md
Labels: cherry-pick, 23_1

#6210 Grids: update showColumnChooser
  api-reference/10 UI Components/GridBase/3 Methods/showColumnChooser().md
Labels: 23_2

#6213 Grids: update showColumnChooser (#6210)
  api-reference/10 UI Components/GridBase/3 Methods/showColumnChooser().md
Labels: cherry-pick, 23_1

#6214 Grids: update showColumnChooser (#6210)
  api-reference/10 UI Components/GridBase/3 Methods/showColumnChooser().md
Labels: cherry-pick, 24_1

#6194 Cherry-pick: Angular Signals support (23_1)
  MenuConfig.xml
  concepts/40 Angular Components/10 Getting Started/90 Support for Angular Signals.md
Labels: cherry-pick, 23_1

#6219 Doc.ctor make-compact-docs command
  .gitignore
  package.json
Labels: 24_1

#6220 Doc.ctor make-compact-docs command
  .gitignore
  package.json
Labels: cherry-pick, 23_2

#6221 Doc.ctor make-compact-docs command
  .gitignore
  package.json
Labels: cherry-pick, 23_1

#6222 Doc.ctor make-compact-docs command
  .gitignore
  package.json
Labels: cherry-pick, 22_2

#6223 HtmlEditor: replace 'devextreme-showdown' with 'showdown'
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/valueType.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
Labels: 23_2

#6224 HtmlEditor: replace 'devextreme-showdown' with 'showdown' (#6223)
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/valueType.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
Labels: cherry-pick, 23_1

#6225 HtmlEditor: replace 'devextreme-showdown' with 'showdown' (#6223)
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/valueType.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
Labels: cherry-pick, 24_1

#6226 HtmlEditor: replace 'devextreme-showdown' with 'showdown' (#6223)
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/valueType.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
Labels: cherry-pick, 22_2

#6227 HtmlEditor: replace 'devextreme-showdown' with 'showdown' (#6223)
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/valueType.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Output Markup Language.md
Labels: cherry-pick, 22_1

#6218 Diagram: move "How to" topics into root
  MenuConfig.xml
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramCustomCommand/location.md
  api-reference/10 UI Components/dxDiagram/dxDiagram.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/01 Change the Component's Background Color.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/05 Change the Color of Connector Points.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/10 Customize the Context Menu's Items.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/15 Specify a Command's Location on the Main Toolbar.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/Customize the Diagram Component.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/01 Prohibit Creating Loops.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/05 Prohibit Adding Shapes Twice.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/10 Remove Shapes from Toolboxes.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/15 Prohibit Moving Shapes Between Containers.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/20 Customize Shape Collection in the Context Toolbox.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/Restrict Operations.md
Labels: 23_1

#6228 Diagram: move "How to" topics into root (#6218)
  MenuConfig.xml
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramCustomCommand/location.md
  api-reference/10 UI Components/dxDiagram/dxDiagram.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/01 Change the Component's Background Color.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/05 Change the Color of Connector Points.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/10 Customize the Context Menu's Items.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/15 Specify a Command's Location on the Main Toolbar.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/Customize the Diagram Component.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/01 Prohibit Creating Loops.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/05 Prohibit Adding Shapes Twice.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/10 Remove Shapes from Toolboxes.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/15 Prohibit Moving Shapes Between Containers.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/20 Customize Shape Collection in the Context Toolbox.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/Restrict Operations.md
Labels: cherry-pick, 23_2

#6229 Diagram: move "How to" topics into root (#6218)
  MenuConfig.xml
  api-reference/10 UI Components/dxDiagram/7 Interfaces/dxDiagramCustomCommand/location.md
  api-reference/10 UI Components/dxDiagram/dxDiagram.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/01 Change the Component's Background Color.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/05 Change the Color of Connector Points.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/10 Customize the Context Menu's Items.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/15 Specify a Command's Location on the Main Toolbar.md
  concepts/05 UI Components/Diagram/23 Customize the Diagram Component/Customize the Diagram Component.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/01 Prohibit Creating Loops.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/05 Prohibit Adding Shapes Twice.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/10 Remove Shapes from Toolboxes.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/15 Prohibit Moving Shapes Between Containers.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/20 Customize Shape Collection in the Context Toolbox.md
  concepts/05 UI Components/Diagram/27 Restrict Operations/Restrict Operations.md
Labels: cherry-pick, 24_1

#6234 DataGrid: fix columns.format (#6233)
  api-reference/_hidden/GridBaseColumn/format.md
  api-reference/_hidden/dxDataGridColumn/format.md
Labels: cherry-pick, 23_1

#6235 DataGrid: fix columns.format (#6233)
  api-reference/_hidden/GridBaseColumn/format.md
  api-reference/_hidden/dxDataGridColumn/format.md
Labels: cherry-pick, 24_1

#6236 DataGrid: add custom logic code (the Edit button)
  concepts/05 UI Components/DataGrid/15 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/1 Customize Buttons.md
Labels: 23_2

#6237 DataGrid: add custom logic code (the Edit button) (#6236)
  concepts/05 UI Components/DataGrid/15 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/1 Customize Buttons.md
Labels: cherry-pick, 23_1

#6238 DataGrid: add custom logic code (the Edit button) (#6236)
  concepts/05 UI Components/DataGrid/15 Columns/10 Column Types/4 Command Columns/15 Customize the Edit Column/1 Customize Buttons.md
Labels: cherry-pick, 24_1

#6239 CSP: add a topic about themes and icons
  concepts/Common/Security Considerations/40 Content Security Policy/25 CSP Directives for Themes and Icons.md
Labels: 23_2

#6240 CSP: add a topic about themes and icons (#6239)
  concepts/Common/Security Considerations/40 Content Security Policy/25 CSP Directives for Themes and Icons.md
Labels: cherry-pick, 23_1

#6241 CSP: add a topic about themes and icons (#6239)
  concepts/Common/Security Considerations/40 Content Security Policy/25 CSP Directives for Themes and Icons.md
Labels: cherry-pick, 24_1

#6243 Licensing: fix link (#6242)
  concepts/Common/Licensing/25 Validation.md
Labels: cherry-pick, 24_1

#6244 DateRangeBox: delete superfluous space
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/20 Add Labels.md
Labels: 23_2

#6245 DateRangeBox: delete superfluous space (#6244)
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/20 Add Labels.md
Labels: cherry-pick, 23_1

#6246 DateRangeBox: delete superfluous space (#6244)
  concepts/05 UI Components/DateRangeBox/00 Getting Started with DateRangeBox/20 Add Labels.md
Labels: cherry-pick, 24_1

#6250 Remove AngularJS from docs
  api-reference/10 UI Components/Markup Components/dxTemplate/dxTemplate.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/integration/angular.md
Labels: 24_1

#6251 Popup: update Resize article for React
  concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Resize the Popup.md
Labels: 23_2

#6252 FileManager: add demo link to one of the methods
  api-reference/10 UI Components/dxFileManager/7 Interfaces/FileSystemItem/3 Methods/getFileExtension().md
Labels: 23_2

#6253 Popup: update Resize article for React (#6251)
  concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Resize the Popup.md
Labels: cherry-pick, 23_1

#6254 Popup: update Resize article for React (#6251)
  concepts/05 UI Components/Popup/00 Getting Started with Popup/06 Resize the Popup.md
Labels: cherry-pick, 24_1

#6255 FileManager: add demo link to one of the methods (#6252)
  api-reference/10 UI Components/dxFileManager/7 Interfaces/FileSystemItem/3 Methods/getFileExtension().md
Labels: cherry-pick, 23_1

#6261 Themes: add a note about commonSeriesSettings (#6260)
  concepts/60 Themes and Styles/20 SVG-Based Components Customization/15 Themes/30 Create a Custom Theme.md
Labels: cherry-pick, 23_1

#6262 Themes: add a note about commonSeriesSettings (#6260)
  concepts/60 Themes and Styles/20 SVG-Based Components Customization/15 Themes/30 Create a Custom Theme.md
Labels: cherry-pick, 24_1

#6264 DateBox: update min/max/value
  api-reference/10 UI Components/dxDateBox/1 Configuration/max.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/min.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/value.md
Labels: 23_2

#6268 DateBox: update min/max/value (#6264)
  api-reference/10 UI Components/dxDateBox/1 Configuration/max.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/min.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/value.md
Labels: cherry-pick, 23_1

#6269 DateBox: update min/max/value (#6264)
  api-reference/10 UI Components/dxDateBox/1 Configuration/max.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/min.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/value.md
Labels: cherry-pick, 24_1

#6270 Localization: hide React note
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: 23_2

#6271 Localization: hide React note (#6270)
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: cherry-pick, 23_1

#6272 Localization: hide React note (#6270)
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: cherry-pick, 24_1

#6273 Gantt: add tasks code snippets
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/colorExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/endExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/keyExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/parentIdExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/progressExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/startExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/tasks.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/titleExpr.md
Labels: 23_2

#6274 Gantt: add tasks code snippets (#6273)
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/colorExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/endExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/keyExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/parentIdExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/progressExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/startExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/tasks.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/titleExpr.md
Labels: cherry-pick, 23_1

#6275 Gantt: add tasks code snippets (#6273)
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/colorExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/endExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/keyExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/parentIdExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/progressExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/startExpr.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/tasks.md
  api-reference/10 UI Components/dxGantt/1 Configuration/tasks/titleExpr.md
Labels: cherry-pick, 24_1

#6276 Menu Scrolling - New Members
  api-reference/10 UI Components/dxMenu/1 Configuration/onSubmenuHidden.md
  api-reference/10 UI Components/dxMenu/1 Configuration/onSubmenuHiding.md
  api-reference/10 UI Components/dxMenu/1 Configuration/onSubmenuShowing.md
  api-reference/10 UI Components/dxMenu/1 Configuration/onSubmenuShown.md
  api-reference/10 UI Components/dxMenu/9 Types/SubmenuHiddenEvent/itemData.md
  api-reference/10 UI Components/dxMenu/9 Types/SubmenuHiddenEvent/submenuContainer.md
  api-reference/10 UI Components/dxMenu/9 Types/SubmenuHidingEvent/itemData.md
  api-reference/10 UI Components/dxMenu/9 Types/SubmenuHidingEvent/submenuContainer.md
  api-reference/10 UI Components/dxMenu/9 Types/SubmenuShowingEvent/itemData.md
  api-reference/10 UI Components/dxMenu/9 Types/SubmenuShowingEvent/submenuContainer.md
  api-reference/10 UI Components/dxMenu/9 Types/SubmenuShownEvent/itemData.md
  api-reference/10 UI Components/dxMenu/9 Types/SubmenuShownEvent/submenuContainer.md
Labels: 24_1

#6279 Add Shadow DOM limitations
  MenuConfig.xml
  concepts/Common/Shadow DOM/Shadow DOM.md
Labels: 24_1

#6280 DateBox: add example links
  api-reference/10 UI Components/dxDateBox/1 Configuration/displayFormat.md
  concepts/05 UI Components/DateBox/04 Value Formatting and Masked Input.md
Labels: 23_2

#6282 HtmlEditor: update getText method
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getText(index_length).md
Labels: 23_2

#6283 HtmlEditor: update getText method (#6282)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getText(index_length).md
Labels: cherry-pick, 23_1

#6284 HtmlEditor: update getText method (#6282)
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getText(index_length).md
Labels: cherry-pick, 24_1

#6265 Splitter: how to implement custom scrolling
  applications/UIWidgets/Splitter/scrolling/index.css
  applications/UIWidgets/Splitter/scrolling/index.html
  applications/UIWidgets/Splitter/scrolling/index.js
  concepts/05 UI Components/Splitter/20 Implement Custom Scrolling/00 Implement Custom Scrolling.md
Labels: 24_1

#6118 Splitter: describe API
  api-reference/10 UI Components/dxSplitter/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/allowKeyboardNavigation.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/itemTemplate.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/items.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/items/items.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onContentReady.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onDisposing.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onInitialized.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onItemClick.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onItemCollapsed.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onItemContextMenu.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onItemExpanded.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onItemRendered.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onOptionChanged.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onResize.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onResizeEnd.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/onResizeStart.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/orientation.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/repaintChangesOnly.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/resizeMode.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/separatorSize.md
  api-reference/10 UI Components/dxSplitter/3 Methods/Methods.md
  api-reference/10 UI Components/dxSplitter/4 Events/itemCollapsed.md
  api-reference/10 UI Components/dxSplitter/4 Events/itemExpanded.md
  api-reference/10 UI Components/dxSplitter/4 Events/resize.md
  api-reference/10 UI Components/dxSplitter/4 Events/resizeEnd.md
  api-reference/10 UI Components/dxSplitter/4 Events/resizeStart.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/collapsed.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/collapsedSize.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/collapsible.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/dxSplitterItem.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/maxSize.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/minSize.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/resizable.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/size.md
  api-reference/10 UI Components/dxSplitter/7 Interfaces/dxSplitterItem/splitter.md
  api-reference/10 UI Components/dxSplitter/9 Types/ContentReadyEvent/ContentReadyEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/DisposingEvent/DisposingEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/InitializedEvent/InitializedEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/ItemClickEvent/ItemClickEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/ItemCollapsedEvent/ItemCollapsedEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/ItemContextMenuEvent/ItemContextMenuEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/ItemExpandedEvent/ItemExpandedEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/ItemRenderedEvent/ItemRenderedEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/OptionChangedEvent/OptionChangedEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/ResizeEndEvent/ResizeEndEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/ResizeEvent/ResizeEvent.md
  api-reference/10 UI Components/dxSplitter/9 Types/ResizeInfo/handleElement.md
  api-reference/10 UI Components/dxSplitter/9 Types/ResizeMode.md
  api-reference/10 UI Components/dxSplitter/9 Types/ResizeStartEvent/ResizeStartEvent.md
  api-reference/10 UI Components/dxSplitter/dxSplitter.md
  api-reference/_hidden/CollectionWidgetItem/template.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/ui/splitter.md
  images/Splitter/collapsible.gif
  images/Splitter/orientation.png
  images/Splitter/resizable.gif
  images/Splitter/splitter.png
  includes/common-dataSource-description.md
Labels: 24_1

#6285 Angular: update Intercept HTTP Requests
  concepts/40 Angular Components/40 Common Features/15 Intercept HTTP Requests.md
Labels: 24_1

#6290 Gantt: update taskTooltipContentTemplate
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTooltipContentTemplate.md
Labels: 23_2

#6291 Gantt: update taskTooltipContentTemplate (#6290)
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTooltipContentTemplate.md
Labels: cherry-pick, 23_1

#6292 Gantt: update taskTooltipContentTemplate (#6290)
  api-reference/10 UI Components/dxGantt/1 Configuration/taskTooltipContentTemplate.md
Labels: cherry-pick, 24_1
