Repository DevExpress/devextreme-documentation, pull requests merged in 2025-09, with the labels that each got.

#7940 Update ExcelJS Angular tsconfig definitions
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/05 UI Components/PivotGrid/090 Export/05 Install Dependencies.md
  includes/tutorials-export-data-to-excel.md
Labels: 25_1

#7946 Grids: Update autoNavigateToFocusedRow notes
  api-reference/10 UI Components/GridBase/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
Labels: 25_1

#7947 Grids: Update autoNavigateToFocusedRow notes (#7946)
  api-reference/10 UI Components/GridBase/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
Labels: cherry-pick, 24_2

#7948 Grids: Update autoNavigateToFocusedRow notes (#7946)
  api-reference/10 UI Components/GridBase/1 Configuration/autoNavigateToFocusedRow.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/autoNavigateToFocusedRow.md
Labels: cherry-pick, 25_2

#7938 chore: update nodejs and add pnpm
  .github/actions/setup-env/action.yml
  .github/workflows/docgen.yml
  .github/workflows/nodejs.yml
  .gitignore
  package.json
  pnpm-lock.yaml
Labels: 25_2

#7950 Form: Add smartPaste error descriptions
  api-reference/10 UI Components/Errors and Warnings/E1063.md
  api-reference/10 UI Components/Errors and Warnings/E1064.md
Labels: 25_2

#7944 DataGrid: Add summary column info
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/calculateCustomSummary.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/summary/totalItems/column.md
Labels: 25_1

#7975 HTMLEditor: Remove W1016 Error (#7974)
  api-reference/10 UI Components/Errors and Warnings/W1016.md
Labels: cherry-pick, 25_2

#7973 Grids: Add W1028 error description (#7907)
  api-reference/10 UI Components/Errors and Warnings/W1028.md
Labels: cherry-pick, 24_2

#7972 EventObject: Add originalEvent & Fields props (#7920)
  api-reference/50 Common/Object Structures/EventObject/2 Fields/Fields.md
  api-reference/50 Common/Object Structures/EventObject/2 Fields/originalEvent.md
Labels: cherry-pick, 24_2

#7971 Grids: Update focus() description (#7955)
  api-reference/10 UI Components/dxDataGrid/3 Methods/focus().md
  api-reference/10 UI Components/dxTreeList/3 Methods/focus().md
Labels: cherry-pick, 25_2

#7969 Grids: Update column width API descriptions
  api-reference/10 UI Components/GridBase/1 Configuration/columnAutoWidth.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnWidth.md
Labels: 25_1

#7985 DataGrid: Add hierarchical header filter image
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/00 Implement a Hierarchical Header Filter.md
  images/DataGrid/datagrid-hierarchical-header-filter.png
Labels: 25_1

#7979 Grids: Update column width API descriptions (#7969)
  api-reference/10 UI Components/GridBase/1 Configuration/columnAutoWidth.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnWidth.md
Labels: cherry-pick, 24_2

#7980 Grids: Update column width API descriptions (#7969)
  api-reference/10 UI Components/GridBase/1 Configuration/columnAutoWidth.md
  api-reference/10 UI Components/GridBase/1 Configuration/columnWidth.md
Labels: cherry-pick, 25_2

#7520 TagBox: Add Overview
  concepts/05 UI Components/TagBox/03 Overview/00 Overview.md
  concepts/05 UI Components/TagBox/03 Overview/05 Elements.md
  concepts/05 UI Components/TagBox/03 Overview/10 Key Features.md
  concepts/05 UI Components/TagBox/03 Overview/15 Explore More.md
  images/TagBox/tagbox-elements.png
Labels: 25_1

#7987 DataGrid: Add hierarchical header filter image (#7985)
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/00 Implement a Hierarchical Header Filter.md
  images/DataGrid/datagrid-hierarchical-header-filter.png
Labels: cherry-pick, 25_2

#8004 Diagram: Update Diagram Tools topic
  concepts/05 UI Components/Diagram/30 Diagram Tools.md
Labels: 25_1

#8013 Diagram: Update Diagram Tools topic (#8004)
  concepts/05 UI Components/Diagram/30 Diagram Tools.md
Labels: cherry-pick, 25_2

#8018 Revert "Rollback to prev tools version / .net6 (#7956)" (update devextreme-internal-tools)
  .github/actions/setup-env/action.yml
  .github/workflows/docgen.yml
  package.json
  pnpm-lock.yaml
Labels: 25_2

#8020 CardView: Update Overview (style)
  concepts/05 UI Components/CardView/00 Overview/00 Overview.md
  concepts/05 UI Components/CardView/00 Overview/10 Key Features.md
Labels: 25_1

#8031 TreeMap: Update Node topic
  api-reference/10 UI Components/dxTreeMap/6 Node/Node.md
  images/TreeMap/treemap-node.png
Labels: 25_1

#8026 CardView: Update Overview (style) (#8020)
  concepts/05 UI Components/CardView/00 Overview/00 Overview.md
  concepts/05 UI Components/CardView/00 Overview/10 Key Features.md
Labels: cherry-pick, 25_2

#8033 FloatingActionButton - Use generic theme / built-in icons
  applications/GettingStartedWith/FloatingActionButton/HandleScreenTransitions/index.html
  applications/GettingStartedWith/FloatingActionButton/HandleScreenTransitions/index.js
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.html
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.js
  applications/GettingStartedWith/FloatingActionButton/SingleAction/index.js
Labels: 25_1

#8037 FloatingActionButton - Use generic theme / built-in icons (#8033)
  applications/GettingStartedWith/FloatingActionButton/HandleScreenTransitions/index.html
  applications/GettingStartedWith/FloatingActionButton/HandleScreenTransitions/index.js
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.html
  applications/GettingStartedWith/FloatingActionButton/MultipleActions/index.js
  applications/GettingStartedWith/FloatingActionButton/SingleAction/index.js
Labels: cherry-pick, 25_2

#8035 TreeMap: Update Node topic (#8031)
  api-reference/10 UI Components/dxTreeMap/6 Node/Node.md
  images/TreeMap/treemap-node.png
Labels: cherry-pick, 24_2

#8036 TreeMap: Update Node topic (#8031)
  api-reference/10 UI Components/dxTreeMap/6 Node/Node.md
  images/TreeMap/treemap-node.png
Labels: cherry-pick, 25_2

#8032 Chat: Add Customize Empty View how to
  applications/UIWidgets/Chat/EmptyView/index.css
  applications/UIWidgets/Chat/EmptyView/index.html
  applications/UIWidgets/Chat/EmptyView/index.js
  concepts/05 UI Components/Chat/40 Customize the Empty View.md
Labels: 25_2

#8043 Grids: Add e1066 error description
  api-reference/10 UI Components/Errors and Warnings/E1066.md
Labels: 25_2

#8044 SpeechToText: Add e1065 error description
  api-reference/10 UI Components/Errors and Warnings/E1065.md
Labels: 25_2

#7631 Gantt: Add Overview
  concepts/05 UI Components/Gantt/05 Overview/00 Overview.md
  concepts/05 UI Components/Gantt/05 Overview/05 Elements.md
  concepts/05 UI Components/Gantt/05 Overview/10 Key Features.md
  concepts/05 UI Components/Gantt/05 Overview/15 Explore More.md
  images/Gantt/gantt-overview-elements.png
Labels: 25_1

#8051 Gantt: Add Overview (#7631)
  concepts/05 UI Components/Gantt/05 Overview/00 Overview.md
  concepts/05 UI Components/Gantt/05 Overview/05 Elements.md
  concepts/05 UI Components/Gantt/05 Overview/10 Key Features.md
  concepts/05 UI Components/Gantt/05 Overview/15 Explore More.md
  images/Gantt/gantt-overview-elements.png
Labels: cherry-pick, 24_2

#8052 Gantt: Add Overview (#7631)
  concepts/05 UI Components/Gantt/05 Overview/00 Overview.md
  concepts/05 UI Components/Gantt/05 Overview/05 Elements.md
  concepts/05 UI Components/Gantt/05 Overview/10 Key Features.md
  concepts/05 UI Components/Gantt/05 Overview/15 Explore More.md
  images/Gantt/gantt-overview-elements.png
Labels: cherry-pick, 25_2

#8054 DropDownEditor & TagBox: update reset(value) (#8053)
  api-reference/10 UI Components/dxDropDownEditor/3 Methods/reset(value).md
  api-reference/10 UI Components/dxTagBox/3 Methods/reset(value).md
Labels: cherry-pick, 25_2

#7528 Diagram: Add Overview
  concepts/05 UI Components/Diagram/05 Overview/00 Overview.md
  concepts/05 UI Components/Diagram/05 Overview/05 Elements.md
  concepts/05 UI Components/Diagram/05 Overview/10 Key Features.md
  concepts/05 UI Components/Diagram/05 Overview/15 Explore More.md
  images/diagram/diagram-elements.png
Labels: 25_1

#7601 FileManager: Add Overview
  concepts/05 UI Components/FileManager/05 Overview/00 Overview.md
  concepts/05 UI Components/FileManager/05 Overview/05 Elements.md
  concepts/05 UI Components/FileManager/05 Overview/10 Key Features.md
  concepts/05 UI Components/FileManager/05 Overview/15 Explore More.md
  images/FileManager/filemanager-elements.png
  images/FileManager/filemanager-item-states.png
Labels: 25_1

#8011 Form: describe Smart Paste API
  api-reference/10 UI Components/dxForm/1 Configuration/aiIntegration.md
  api-reference/10 UI Components/dxForm/1 Configuration/onSmartPasted.md
  api-reference/10 UI Components/dxForm/1 Configuration/onSmartPasting.md
  api-reference/10 UI Components/dxForm/3 Methods/smartPaste(text).md
  api-reference/10 UI Components/dxForm/4 Events/smartPasted.md
  api-reference/10 UI Components/dxForm/4 Events/smartPasting.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/aiOptions/aiOptions.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/aiOptions/disabled.md
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/aiOptions/instruction.md
  api-reference/10 UI Components/dxForm/9 Types/ContentReadyEvent/ContentReadyEvent.md
  api-reference/10 UI Components/dxForm/9 Types/DisposingEvent/DisposingEvent.md
  api-reference/10 UI Components/dxForm/9 Types/EditorEnterKeyEvent/EditorEnterKeyEvent.md
  api-reference/10 UI Components/dxForm/9 Types/FieldDataChangedEvent/FieldDataChangedEvent.md
  api-reference/10 UI Components/dxForm/9 Types/FormPredefinedButtonItem.md
  api-reference/10 UI Components/dxForm/9 Types/InitializedEvent/InitializedEvent.md
  api-reference/10 UI Components/dxForm/9 Types/OptionChangedEvent/OptionChangedEvent.md
  api-reference/10 UI Components/dxForm/9 Types/SmartPasteInfo/aiResult.md
  api-reference/10 UI Components/dxForm/9 Types/SmartPastedEvent/SmartPastedEvent.md
  api-reference/10 UI Components/dxForm/9 Types/SmartPastingEvent/SmartPastingEvent.md
Labels: 25_2

#8057 Diagram: Add Overview (#7528)
  concepts/05 UI Components/Diagram/05 Overview/00 Overview.md
  concepts/05 UI Components/Diagram/05 Overview/05 Elements.md
  concepts/05 UI Components/Diagram/05 Overview/10 Key Features.md
  concepts/05 UI Components/Diagram/05 Overview/15 Explore More.md
  images/diagram/diagram-elements.png
Labels: cherry-pick, 24_2

#8058 Diagram: Add Overview (#7528)
  concepts/05 UI Components/Diagram/05 Overview/00 Overview.md
  concepts/05 UI Components/Diagram/05 Overview/05 Elements.md
  concepts/05 UI Components/Diagram/05 Overview/10 Key Features.md
  concepts/05 UI Components/Diagram/05 Overview/15 Explore More.md
  images/diagram/diagram-elements.png
Labels: cherry-pick, 25_2

#8055 Add MCP Integration docs (#8028)
  MenuConfig.xml
  concepts/Common/Integration Guides/05 DevExpress MCP Server Configuration/00 DevExpress MCP Server Configuration.md
  concepts/Common/Integration Guides/05 DevExpress MCP Server Configuration/10 Why Use the DevExpress MCP Server.md
  concepts/Common/Integration Guides/05 DevExpress MCP Server Configuration/20 Prerequisites and Installation.md
  concepts/Common/Integration Guides/05 DevExpress MCP Server Configuration/30 Custom Instructions.md
Labels: cherry-pick, 24_2

#8056 Add MCP Integration docs (#8028)
  MenuConfig.xml
  concepts/Common/Integration Guides/05 DevExpress MCP Server Configuration/00 DevExpress MCP Server Configuration.md
  concepts/Common/Integration Guides/05 DevExpress MCP Server Configuration/10 Why Use the DevExpress MCP Server.md
  concepts/Common/Integration Guides/05 DevExpress MCP Server Configuration/20 Prerequisites and Installation.md
  concepts/Common/Integration Guides/05 DevExpress MCP Server Configuration/30 Custom Instructions.md
Labels: cherry-pick, 25_2

#7753 DropDownButton: Add Overview
  concepts/05 UI Components/DropDownButton/03 Overview/00 Overview.md
  concepts/05 UI Components/DropDownButton/03 Overview/05 Elements.md
  concepts/05 UI Components/DropDownButton/03 Overview/10 Key Features.md
  concepts/05 UI Components/DropDownButton/03 Overview/15 Explore More.md
  images/DropDownButton/dropdownbutton-elements.png
Labels: 25_1
