Repository DevExpress/devextreme-documentation, pull requests merged in 2025-07, with the labels that each got.

#7547 Chart: Update Enhance Performance How To
  concepts/05 UI Components/Chart/10 Series/50 Show and Hide a Series.md
  concepts/05 UI Components/Chart/88 Data Aggregation/01 Enable Data Aggregation.md
  concepts/05 UI Components/Chart/93 Enhance Performance on Large Datasets.md
  concepts/05 UI Components/Chart/95 Zooming and Panning/15 Set the Initial Zoom.md
Labels: 25_1

#7555 Scheduler: update W0008 description (#7554)
  api-reference/50 Common/utils/zz Errors and Warnings/W0008.md
Labels: cherry-pick, 24_2

#7448 Add What's New v25.1
  concepts/Common/Whats New/00 v25.1 Release Notes.md
  concepts/Common/Whats New/10 Version History.md
Labels: 25_1

#7556 VectorMap: Update bounds topic
  api-reference/10 UI Components/dxVectorMap/1 Configuration/bounds.md
Labels: 25_1

#7566 CardView: fix GS code snippet
  concepts/05 UI Components/CardView/05 Getting Started with CardView/35 Configure Column Chooser.md
Labels: 25_1

#7563 Grids: Add filterSyncEnabled note
  api-reference/10 UI Components/GridBase/1 Configuration/filterSyncEnabled.md
Labels: 25_1

#7546 PivotGrid: Add Enhance Performance How To topic
  concepts/05 UI Components/PivotGrid/155 Enhance Performance on Large Datasets.md
Labels: WIP, 25_1

#7568 Grids: Add filterSyncEnabled note (#7563)
  api-reference/10 UI Components/GridBase/1 Configuration/filterSyncEnabled.md
Labels: cherry-pick, 24_2

#7569 PivotGrid: Add Enhance Performance How To topic (#7546)
  concepts/05 UI Components/PivotGrid/155 Enhance Performance on Large Datasets.md
Labels: cherry-pick, 24_2

#7570 Scheduler: Add allowDragging & allowResizing notes (#7564)
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowDragging.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/editing/allowResizing.md
Labels: cherry-pick, 24_2

#7572 Angular: add a note about Angular 20
  concepts/40 Angular Components/80 Supported Versions.md
Labels: 25_1

#7573 TabPanel: describe itemIndex in title events
  api-reference/10 UI Components/dxTabPanel/1 Configuration/onTitleClick.md
  api-reference/10 UI Components/dxTabPanel/1 Configuration/onTitleHold.md
  api-reference/10 UI Components/dxTabPanel/1 Configuration/onTitleRendered.md
Labels: 25_1

#7579 Scheduler: Update timeZone topic (#7578)
  api-reference/10 UI Components/dxScheduler/1 Configuration/timeZone.md
Labels: cherry-pick, 24_2

#7574 DataLayer: Update E4021 & E4022 error docs
  api-reference/30 Data Layer/zz Errors and Warnings/E4021.md
  api-reference/30 Data Layer/zz Errors and Warnings/E4022.md
Labels: 25_1

#7577 SelectBox: Update onCustomItemCreating topic
  api-reference/10 UI Components/dxSelectBox/1 Configuration/onCustomItemCreating.md
Labels: 25_1

#7582 SelectBox: Update onCustomItemCreating topic (#7577)
  api-reference/10 UI Components/dxSelectBox/1 Configuration/onCustomItemCreating.md
Labels: cherry-pick, 24_2

#7583 TS Guides: Update code snippets
  concepts/Common/TypeScript Guides/05 Scopes of Types/10 Component-Specific Types.md
  concepts/Common/TypeScript Guides/05 Scopes of Types/15 Common Types.md
  concepts/Common/TypeScript Guides/10 Best Practices/05 Using Unions Instead of Base Classes.md
  concepts/Common/TypeScript Guides/10 Best Practices/10 Generic Parameters.md
  concepts/Common/TypeScript Guides/10 Best Practices/15 Types for Templates.md
Labels: 25_1

#7580 List: Update searchEditorOptions topic
  api-reference/10 UI Components/SearchBoxMixin/1 Configuration/searchEditorOptions.md
Labels: 25_1

#7588 List: Update searchEditorOptions topic (#7580)
  api-reference/10 UI Components/SearchBoxMixin/1 Configuration/searchEditorOptions.md
Labels: cherry-pick, 24_2

#7589 Grids: Update refresh() topic
  api-reference/10 UI Components/GridBase/3 Methods/refresh().md
Labels: 25_1

#7595 Grids: Update Filter Row how to topics (#7590)
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/1 Filter Row.md
  concepts/05 UI Components/TreeList/40 Filtering and Searching/1 Filter Row.md
Labels: cherry-pick, 24_2

#7598 Grids: Update refresh() topic (#7589)
  api-reference/10 UI Components/GridBase/3 Methods/refresh().md
Labels: cherry-pick, 25_2

#7604 Chat: add Render Images topic (#7600)
  concepts/05 UI Components/Chat/35 Render Images.md
Labels: cherry-pick, 25_2

#7606 Chart: Add demo button to tooltip topic
  api-reference/10 UI Components/dxChart/1 Configuration/tooltip/tooltip.md
Labels: 25_1

#7607 Chart: Add demo button to tooltip topic (#7606)
  api-reference/10 UI Components/dxChart/1 Configuration/tooltip/tooltip.md
Labels: cherry-pick, 24_2

#7612 Small jQuery fixes (#7611)
  applications/GettingStartedWith/Stepper/index.css
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
Labels: cherry-pick, 25_2

#7616 Chart: update legend.customizeItems
  api-reference/10 UI Components/BaseChart/1 Configuration/legend/customizeItems.md
  api-reference/40 Common Types/05 charts/BaseChartLegend/customizeItems.md
Labels: 25_1

#7614 Chart: Add axis breakStyle code snippets
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/breakStyle/breakStyle.md
Labels: 25_1

#7621 Chart: Add axis breakStyle code snippets (#7614)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/breakStyle/breakStyle.md
Labels: cherry-pick, 24_2

#7622 Chart: Add axis breakStyle code snippets (#7614)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/breakStyle/breakStyle.md
Labels: cherry-pick, 25_2

#7623 Rename Autocomplete -> AutoComplete
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/value.md
  api-reference/10 UI Components/dxAutocomplete/dxAutocomplete.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/00 Getting Started with Autocomplete.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/05 Create Autocomplete and Bind It to Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/10 Group Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/15 Configure Search Settings.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/20 Customize Field Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/25 Customize Item Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/30 Handle Value Change.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/Autocomplete/10 Configure Search Parameters.md
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/5 Server-Side Data Processing.md
  concepts/Common/Accessibility/05 Documentation for Components.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/ui/autocomplete.md
  concepts/Common/Security Considerations/20 HTML Encoding/10 Encode User Input.md
  includes/editors-how-to-choose.md
Labels: 25_1

#7624 Rename Autocomplete -> AutoComplete (#7623)
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxAutocomplete/1 Configuration/value.md
  api-reference/10 UI Components/dxAutocomplete/dxAutocomplete.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/00 Getting Started with Autocomplete.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/05 Create Autocomplete and Bind It to Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/10 Group Data.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/15 Configure Search Settings.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/20 Customize Field Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/25 Customize Item Appearance.md
  concepts/05 UI Components/Autocomplete/00 Getting Started with Autocomplete/30 Handle Value Change.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/Autocomplete/05 Accessibility/20 Screen Reader Support.md
  concepts/05 UI Components/Autocomplete/10 Configure Search Parameters.md
  concepts/70 Data Binding/00 Specify a Data Source/60 Custom Data Sources/2 Load Data/5 Server-Side Data Processing.md
  concepts/Common/Accessibility/05 Documentation for Components.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/ui/autocomplete.md
  concepts/Common/Security Considerations/20 HTML Encoding/10 Encode User Input.md
  includes/editors-how-to-choose.md
Labels: cherry-pick, 24_2

#7615 PolarChart: Update series.border topic
  api-reference/10 UI Components/dxPolarChart/5 Series Types/CommonPolarChartSeries/border/border.md
Labels: 25_1

#7633 Charts: Update range property topics (#7605)
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/visualRange/visualRange.md
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/wholeRange/wholeRange.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/visualRange/visualRange.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/wholeRange/wholeRange.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/valueAxis/visualRange/visualRange.md
  api-reference/10 UI Components/dxPolarChart/1 Configuration/valueAxis/wholeRange/wholeRange.md
  api-reference/10 UI Components/dxRangeSelector/1 Configuration/value/value.md
  includes/dataviz-ref-vizrangevariants.md
Labels: cherry-pick, 25_2

#7635 PolarChart: Update series.border topic (#7615)
  api-reference/10 UI Components/dxPolarChart/5 Series Types/CommonPolarChartSeries/border/border.md
Labels: cherry-pick, 25_2

#7640 Troubleshooting: Add See Also to Examine CSS topic (#7639)
  concepts/80 Troubleshooting/00 Basics/15 Examine CSS.md
Labels: cherry-pick, 24_2

#7641 Troubleshooting: Add See Also to Examine CSS topic (#7639)
  concepts/80 Troubleshooting/00 Basics/15 Examine CSS.md
Labels: cherry-pick, 25_2

#7613 Chart: Add Getting Started topic
  applications/GettingStartedWith/Chart/index.css
  applications/GettingStartedWith/Chart/index.html
  applications/GettingStartedWith/Chart/index.js
  concepts/05 UI Components/Chart/00 Getting Started with Chart/00 Getting Started with Chart.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/05 Create a Chart.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/10 Display Chart Data.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/15 Configure Chart Series.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/20 Specify Multiple Series.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/25 Add and Customize Tooltips.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/30 Specify a Custom Gradient Background.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/35 Add a Constant Line.md
Labels: 25_1

#7645 Chart: Add Getting Started topic (#7613)
  applications/GettingStartedWith/Chart/index.css
  applications/GettingStartedWith/Chart/index.html
  applications/GettingStartedWith/Chart/index.js
  concepts/05 UI Components/Chart/00 Getting Started with Chart/00 Getting Started with Chart.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/05 Create a Chart.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/10 Display Chart Data.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/15 Configure Chart Series.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/20 Specify Multiple Series.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/25 Add and Customize Tooltips.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/30 Specify a Custom Gradient Background.md
  concepts/05 UI Components/Chart/00 Getting Started with Chart/35 Add a Constant Line.md
Labels: cherry-pick, 25_2

#7647 Describe W0024 (#7638)
  api-reference/50 Common/utils/zz Errors and Warnings/W0024.md
  concepts/Common/Licensing/25 Validation.md
Labels: cherry-pick, 25_2

#7651 VectorMap: Add background code snippets (#7649)
  api-reference/10 UI Components/dxVectorMap/1 Configuration/background/background.md
Labels: cherry-pick, 24_2

#7652 VectorMap: Add background code snippets (#7649)
  api-reference/10 UI Components/dxVectorMap/1 Configuration/background/background.md
Labels: cherry-pick, 25_2

#7653 Box/ResponsiveBox: update baseSize
  api-reference/10 UI Components/dxResponsiveBox/1 Configuration/cols/baseSize.md
  api-reference/10 UI Components/dxResponsiveBox/1 Configuration/rows/baseSize.md
  api-reference/_hidden/dxBoxItem/baseSize.md
  concepts/Common/Licensing/25 Validation.md
Labels: 25_1

#7655 ContextMenu: Update target & showEvent topics
  api-reference/10 UI Components/dxContextMenu/1 Configuration/showEvent/showEvent.md
  api-reference/10 UI Components/dxContextMenu/1 Configuration/target.md
Labels: 25_1

#7654 Chart: Update axis ticks topics
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/minorTick/minorTick.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/tick/tick.md
Labels: 25_1

#7648 Scheduler: Add css class notes
  api-reference/10 UI Components/zz CSS Classes/dx-scheduler-cell-sizes-horizontal.md
  api-reference/10 UI Components/zz CSS Classes/dx-scheduler-cell-sizes-vertical.md
Labels: 25_1

#7665 ContextMenu: Update target & showEvent topics (#7655)
  api-reference/10 UI Components/dxContextMenu/1 Configuration/showEvent/showEvent.md
  api-reference/10 UI Components/dxContextMenu/1 Configuration/target.md
Labels: cherry-pick, 24_2

#7666 ContextMenu: Update target & showEvent topics (#7655)
  api-reference/10 UI Components/dxContextMenu/1 Configuration/showEvent/showEvent.md
  api-reference/10 UI Components/dxContextMenu/1 Configuration/target.md
Labels: cherry-pick, 25_2

#7667 Chart: Update axis ticks topics (#7654)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/minorTick/minorTick.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/tick/tick.md
Labels: cherry-pick, 24_2

#7669 Chart: Update axis grid topics (#7650)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/grid/grid.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/minorGrid/minorGrid.md
Labels: cherry-pick, 24_2

#7670 Chart: Update axis grid topics (#7650)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/grid/grid.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/minorGrid/minorGrid.md
Labels: cherry-pick, 25_2

#7671 Scheduler: Add css class notes (#7648)
  api-reference/10 UI Components/zz CSS Classes/dx-scheduler-cell-sizes-horizontal.md
  api-reference/10 UI Components/zz CSS Classes/dx-scheduler-cell-sizes-vertical.md
Labels: cherry-pick, 24_2

#7673 List: Update Selection How To topic (#7646)
  concepts/05 UI Components/List/25 Selection/05 API.md
Labels: cherry-pick, 24_2

#7680 Scheduler: Update Customize Views How To topic (#7675)
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/views.md
  concepts/05 UI Components/Scheduler/060 Views/020 Customize Individual Views.md
Labels: cherry-pick, 25_2

#7659 SelectBox: Update searchMode topic
  api-reference/10 UI Components/dxSelectBox/1 Configuration/searchMode.md
Labels: 25_1

#7660 Popover: Update target topic
  api-reference/10 UI Components/dxPopover/1 Configuration/target.md
Labels: 25_1

#7685 SelectBox: Update searchMode topic (#7659)
  api-reference/10 UI Components/dxSelectBox/1 Configuration/searchMode.md
Labels: cherry-pick, 25_2

#7630 DataGrid/Gantt: Rewrite PDF troubleshooting topic
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportGantt(options).md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 DataGrid/00 DataGrid.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 DataGrid/05 Choose a Font and Encode It in Base64.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 DataGrid/10 Add the Font to a jsPDF Instance.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 Gantt/00 Gantt.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 Gantt/05 Choose a Font and Encode It in Base64.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 Gantt/10 Add the Font to a jsPDF Instance.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 Gantt/15 Implement the Font in exportGantt().md
  concepts/80 Troubleshooting/15 PDF Export/00 PDF Export.md
  concepts/80 Troubleshooting/15 PDF Export/05 Non-Latin Glyph Support.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/pdf_exporter.md
Labels: 25_1

#7700 DataGrid/Gantt: Rewrite PDF troubleshooting topic (#7630)
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportGantt(options).md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 DataGrid/00 DataGrid.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 DataGrid/05 Choose a Font and Encode It in Base64.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 DataGrid/10 Add the Font to a jsPDF Instance.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 Gantt/00 Gantt.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 Gantt/05 Choose a Font and Encode It in Base64.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 Gantt/10 Add the Font to a jsPDF Instance.md
  concepts/80 Troubleshooting/15 PDF Export Issues/00 Export Unicode Characters/00 Gantt/15 Implement the Font in exportGantt().md
  concepts/80 Troubleshooting/15 PDF Export/00 PDF Export.md
  concepts/80 Troubleshooting/15 PDF Export/05 Non-Latin Glyph Support.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/common/export/pdf.md
Labels: cherry-pick, 24_2

#7698 Update value shared topic (#7676)
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/value.md
Labels: cherry-pick, 24_2

#7699 Update value shared topic (#7676)
  api-reference/10 UI Components/DataExpressionMixin/1 Configuration/value.md
Labels: cherry-pick, 25_2

#7702 Chart: Update autoHidePointMarkers topic (#7697)
  api-reference/10 UI Components/dxChart/1 Configuration/autoHidePointMarkers.md
  images/ChartJS/chart-autohidepointmarkers-example.png
Labels: cherry-pick, 24_2

#7696 Toast: Add icon visibility note to type topic
  api-reference/10 UI Components/dxToast/1 Configuration/type.md
Labels: 25_1

#7706 Update all ExcelJS links to DevExtreme fork
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/50 Common/Object Structures/ExcelExportDataGridProps/customizeCell.md
  api-reference/50 Common/Object Structures/PivotGridExportOptions/customizeCell.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/excelExporter/exportPivotGrid(options).md
  api-reference/_hidden/ExcelExportBaseOptions/worksheet.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/05 UI Components/PivotGrid/090 Export/05 Install Dependencies.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/20 ExcelJS CSP Threats.md
  includes/tutorials-export-data-to-excel.md
Labels: WIP, 25_1

#7708 Update all ExcelJS links to DevExtreme fork (#7706)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/50 Common/Object Structures/ExcelExportDataGridProps/customizeCell.md
  api-reference/50 Common/Object Structures/PivotGridExportOptions/customizeCell.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/excelExporter/exportPivotGrid(options).md
  api-reference/_hidden/ExcelExportBaseOptions/worksheet.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/05 UI Components/PivotGrid/090 Export/05 Install Dependencies.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/20 ExcelJS CSP Threats.md
  includes/tutorials-export-data-to-excel.md
Labels: cherry-pick, 25_2

#7709 Revert "Update all ExcelJS links to DevExtreme fork"
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/50 Common/Object Structures/ExcelExportDataGridProps/customizeCell.md
  api-reference/50 Common/Object Structures/PivotGridExportOptions/customizeCell.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/excelExporter/exportPivotGrid(options).md
  api-reference/_hidden/ExcelExportBaseOptions/worksheet.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/05 UI Components/PivotGrid/090 Export/05 Install Dependencies.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/20 ExcelJS CSP Threats.md
  includes/tutorials-export-data-to-excel.md
Labels: 25_1

#7688 DataGrid: Add Hierarchical HeaderFilters how to
  api-reference/40 Common Types/15 grids/ColumnHeaderFilter/groupInterval.md
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/00 Implement a Hierarchical Header Filter.md
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/05 Configure the Header Filter.md
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/10 Update Component Data.md
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/15 Implement calculateFilterExpression().md
Labels: 25_1

#7710 DataGrid: Add Hierarchical HeaderFilters how to (#7688)
  api-reference/40 Common Types/15 grids/ColumnHeaderFilter/groupInterval.md
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/00 Implement a Hierarchical Header Filter.md
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/05 Configure the Header Filter.md
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/10 Update Component Data.md
  concepts/05 UI Components/DataGrid/75 Implement a Hierarchical Header Filter/15 Implement calculateFilterExpression().md
Labels: cherry-pick, 25_2

#7693 FileUploader: Add Getting Started topic
  applications/GettingStartedWith/FileUploader/index.css
  applications/GettingStartedWith/FileUploader/index.html
  applications/GettingStartedWith/FileUploader/index.js
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/00 Getting Started with FileUploader.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/05 Create and Configure FileUploader.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/10 Connect FileUploader to a Backend.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/15 Configure Upload Permissions.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/20 Customize FileUploader.md
Labels: 25_1

#7712 PieChart: Update pointHoverChanged info
  api-reference/10 UI Components/dxPieChart/1 Configuration/onPointHoverChanged.md
  concepts/05 UI Components/PieChart/35 Legend/30 User Interaction.md
Labels: 25_1

#7718 FileUploader: Add Getting Started topic (#7693)
  applications/GettingStartedWith/FileUploader/index.css
  applications/GettingStartedWith/FileUploader/index.html
  applications/GettingStartedWith/FileUploader/index.js
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/00 Getting Started with FileUploader.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/05 Create and Configure FileUploader.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/10 Connect FileUploader to a Backend.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/15 Configure Upload Permissions.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/20 Customize FileUploader.md
Labels: cherry-pick, 24_2

#7719 FileUploader: Add Getting Started topic (#7693)
  applications/GettingStartedWith/FileUploader/index.css
  applications/GettingStartedWith/FileUploader/index.html
  applications/GettingStartedWith/FileUploader/index.js
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/00 Getting Started with FileUploader.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/05 Create and Configure FileUploader.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/10 Connect FileUploader to a Backend.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/15 Configure Upload Permissions.md
  concepts/05 UI Components/FileUploader/10 Getting Started with FileUploader/20 Customize FileUploader.md
Labels: cherry-pick, 25_2

#7725 Grids: Add example link to onToolbarPreparing (#7717)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onToolbarPreparing.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/onToolbarPreparing.md
Labels: cherry-pick, 25_2

#7722 DataGrid: Add onSelectionChanged note (#7715)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onSelectionChanged.md
Labels: cherry-pick, 24_2

#7723 DataGrid: Add onSelectionChanged note (#7715)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onSelectionChanged.md
Labels: cherry-pick, 25_2

#7721 PieChart: Update pointHoverChanged info (#7712)
  api-reference/10 UI Components/dxPieChart/1 Configuration/onPointHoverChanged.md
  concepts/05 UI Components/PieChart/35 Legend/30 User Interaction.md
Labels: cherry-pick, 25_2

#7728 Chart: Add legend padding notes
  api-reference/10 UI Components/BaseLegend/paddingLeftRight.md
  api-reference/10 UI Components/BaseLegend/paddingTopBottom.md
Labels: 25_1

#7729 Chart: Add legend padding notes (#7728)
  api-reference/10 UI Components/BaseLegend/paddingLeftRight.md
  api-reference/10 UI Components/BaseLegend/paddingTopBottom.md
Labels: cherry-pick, 24_2

#7730 Chart: Add legend padding notes (#7728)
  api-reference/10 UI Components/BaseLegend/paddingLeftRight.md
  api-reference/10 UI Components/BaseLegend/paddingTopBottom.md
Labels: cherry-pick, 25_2

#7733 Update all ExcelJS mentions and code
  api-reference/10 UI Components/Errors and Warnings/E1041.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/dataRowTemplate.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/formats.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onExporting.md
  api-reference/10 UI Components/dxPivotGrid/1 Configuration/export/export.md
  api-reference/50 Common/Object Structures/ExcelExportDataGridProps/customizeCell.md
  api-reference/50 Common/Object Structures/PivotGridExportOptions/customizeCell.md
  api-reference/50 Common/utils/excelExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/excelExporter/exportPivotGrid(options).md
  api-reference/_hidden/ExcelExportBaseOptions/worksheet.md
  api-reference/_hidden/dxDataGridColumn/cellTemplate.md
  api-reference/_hidden/dxDataGridColumn/groupCellTemplate.md
  api-reference/_hidden/dxDataGridColumn/headerCellTemplate.md
  applications/GettingStartedWith/DataGrid/index.js
  applications/GettingStartedWith/PivotGrid/index.js
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/05 UI Components/PivotGrid/090 Export/05 Install Dependencies.md
  concepts/05 UI Components/PivotGrid/090 Export/20 Export to CSV.md
  concepts/05 UI Components/PivotGrid/090 Export/30 Customize Cells.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/05 CSV Injection.md
  concepts/Common/Security Considerations/30 Export Vulnerabilities/20 ExcelJS CSP Threats.md
  includes/tutorials-export-data-to-excel.md
Labels: 25_2

#7734 Chart: Update barPadding & ignoreEmptyPoints (#7716)
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/barPadding.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/ignoreEmptyPoints.md
Labels: cherry-pick, 24_2

#7738 DataGrid: Update totalCount() note
  api-reference/10 UI Components/dxDataGrid/3 Methods/totalCount().md
Labels: 25_1

#7748 Gantt: Update taskListWidth image (#7747)
  api-reference/10 UI Components/dxGantt/1 Configuration/taskListWidth.md
  images/Gantt/task-list.png
Labels: cherry-pick, 24_2

#7749 Gantt: Update taskListWidth image (#7747)
  api-reference/10 UI Components/dxGantt/1 Configuration/taskListWidth.md
  images/Gantt/task-list.png
Labels: cherry-pick, 25_2

#7750 Update Angular Unit Testing snippet
  concepts/40 Angular Components/50 Components Testing/10 Unit Testing.md
Labels: 25_1

#7751 Update Angular Unit Testing snippet (#7750)
  concepts/40 Angular Components/50 Components Testing/10 Unit Testing.md
Labels: cherry-pick, 24_2

#7752 Update Angular Unit Testing snippet (#7750)
  concepts/40 Angular Components/50 Components Testing/10 Unit Testing.md
Labels: cherry-pick, 25_2

#7744 Form: Remove deprecated resetValues
  api-reference/10 UI Components/dxForm/3 Methods/resetValues().md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/1 Deprecated Properties and Methods.md
Labels: 25_1

#7743 Chart: Update axis valueMarginsEnabled topics
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/valueMarginsEnabled.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/valueMarginsEnabled.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/valueMarginsEnabled.md
  api-reference/10 UI Components/dxChart/9 Types/CommonAxisSettings/valueMarginsEnabled.md
Labels: 25_1

#7757 DataGrid: Add note to cell & batch editing topics
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/20 Cell Mode.md
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/30 Batch Mode.md
Labels: 25_1

#7761 Chart: Update axis valueMarginsEnabled topics (#7743)
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/valueMarginsEnabled.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/valueMarginsEnabled.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/valueMarginsEnabled.md
  api-reference/10 UI Components/dxChart/9 Types/CommonAxisSettings/valueMarginsEnabled.md
Labels: cherry-pick, 24_2

#7762 Chart: Update axis valueMarginsEnabled topics (#7743)
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/valueMarginsEnabled.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/valueMarginsEnabled.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/valueMarginsEnabled.md
  api-reference/10 UI Components/dxChart/9 Types/CommonAxisSettings/valueMarginsEnabled.md
Labels: cherry-pick, 25_2

#7760 DataGrid: Add Cell Mode "cancel" button info
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/20 Cell Mode.md
Labels: 25_1

#7765 DataGrid: Add Cell Mode "cancel" button info (#7760)
  concepts/05 UI Components/DataGrid/20 Editing/10 User Interaction/20 Cell Mode.md
Labels: cherry-pick, 24_2

#7780 TextBox: Add this keyword note
  api-reference/10 UI Components/dxTextBox/1 Configuration/onFocusOut.md
Labels: 25_1

#7782 TextBox: Add this keyword note (#7780)
  api-reference/10 UI Components/dxTextBox/1 Configuration/onFocusOut.md
Labels: cherry-pick, 25_2

#7781 TextBox: Add this keyword note (#7780)
  api-reference/10 UI Components/dxTextBox/1 Configuration/onFocusOut.md
Labels: cherry-pick, 24_2
