Repository DevExpress/devextreme-documentation, pull requests merged in 2025-10, with the labels that each got.

#8068 DropDownButton: Add Overview (#7753)
  concepts/05 UI Components/DropDownButton/03 Overview/00 Overview.md
  concepts/05 UI Components/DropDownButton/03 Overview/05 Elements.md
  concepts/05 UI Components/DropDownButton/03 Overview/10 Key Features.md
  concepts/05 UI Components/DropDownButton/03 Overview/15 Explore More.md
  images/DropDownButton/dropdownbutton-elements.png
Labels: cherry-pick, 25_2

#8074 Fix Licensing mailto links (#8073)
  api-reference/50 Common/utils/zz Errors and Warnings/W0019.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0020.md
  concepts/Common/Licensing/00 Licensing.md
  concepts/Common/Licensing/05 Evaluation (Trial).md
  concepts/Common/Licensing/25 Validation.md
  concepts/Common/Licensing/30 FAQ.md
Labels: cherry-pick, 24_2

#8075 Fix Licensing mailto links (#8073)
  api-reference/50 Common/utils/zz Errors and Warnings/W0019.md
  api-reference/50 Common/utils/zz Errors and Warnings/W0020.md
  concepts/Common/Licensing/00 Licensing.md
  concepts/Common/Licensing/05 Evaluation (Trial).md
  concepts/Common/Licensing/25 Validation.md
  concepts/Common/Licensing/30 FAQ.md
Labels: cherry-pick, 25_2

#8078 Scheduler: remove dropDownAppointmentTemplate and scrollToTime
  api-reference/10 UI Components/Errors and Warnings/W1008.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dropDownAppointmentComponent.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dropDownAppointmentRender.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/dropDownAppointmentTemplate.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/dropDownAppointmentComponent.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/dropDownAppointmentRender.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/views/dropDownAppointmentTemplate.md
  api-reference/10 UI Components/dxScheduler/3 Methods/scrollToTime(hours_minutes_date).md
Labels: 25_2

#8079 dxSpeechToText/Types Root | shortDescription
  api-reference/10 UI Components/dxSpeechToText/9 Types/Types.md
Labels: 25_2

#7839 Chart: Update argumentAxis.strip value docs
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/strips/endValue.md
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/strips/startValue.md
  images/ChartJS/argumentaxis-strip.png
Labels: WIP, 25_1

#8082 Chart: Update argumentAxis.strip value docs (#7839)
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/strips/endValue.md
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/strips/startValue.md
  images/ChartJS/argumentaxis-strip.png
Labels: cherry-pick, 24_2

#8077 Shadow DOM: describe copyStylesToShadowDom
  MenuConfig.xml
  api-reference/50 Common/Object Structures/GlobalConfig/copyStylesToShadowDom.md
Labels: 25_1

#8084 Form: Update isRequired and RequiredRule
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/isRequired.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/RequiredRule/RequiredRule.md
Labels: 25_1

#8090 Form: Update isRequired and RequiredRule (#8084)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/isRequired.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/RequiredRule/RequiredRule.md
Labels: cherry-pick, 24_2

#8091 Form: Update isRequired and RequiredRule (#8084)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/isRequired.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/RequiredRule/RequiredRule.md
Labels: cherry-pick, 25_2

#8092 List: Update A11y Standards Compliance exceptions
  concepts/05 UI Components/List/03 Accessibility/10 Accessibility Standards Compliance.md
Labels: 25_1

#8096 List: Update A11y Standards Compliance exceptions (#8092)
  concepts/05 UI Components/List/03 Accessibility/10 Accessibility Standards Compliance.md
Labels: cherry-pick, 25_2

#8098 DateBox: Update Overview (#8017)
  concepts/05 UI Components/DateBox/01 Overview/00 Overview.md
  concepts/05 UI Components/DateBox/01 Overview/05 Elements.md
  concepts/05 UI Components/DateBox/01 Overview/10 Key Features.md
  concepts/05 UI Components/DateBox/01 Overview/15 Explore More.md
  images/DateBox/date-box-elements.png
Labels: cherry-pick, 24_2

#8099 DateBox: Update Overview (#8017)
  concepts/05 UI Components/DateBox/01 Overview/00 Overview.md
  concepts/05 UI Components/DateBox/01 Overview/05 Elements.md
  concepts/05 UI Components/DateBox/01 Overview/10 Key Features.md
  concepts/05 UI Components/DateBox/01 Overview/15 Explore More.md
  images/DateBox/date-box-elements.png
Labels: cherry-pick, 25_2

#8104 Grids: Remove vague getSelectedRowsData info (#8101)
  api-reference/10 UI Components/dxDataGrid/3 Methods/getSelectedRowsData().md
  api-reference/10 UI Components/dxTreeList/3 Methods/getSelectedRowsData().md
  api-reference/10 UI Components/dxTreeList/3 Methods/getSelectedRowsData(mode).md
Labels: cherry-pick, 25_2
