Repository DevExpress/devextreme-documentation, pull requests merged in 2025-05, with the labels that each got.

#7285 Stepper: add Overview
  concepts/05 UI Components/Stepper/00 Overview/00 Overview.md
  concepts/05 UI Components/Stepper/00 Overview/05 Elements.md
  concepts/05 UI Components/Stepper/00 Overview/10 Key Features.md
  concepts/05 UI Components/Stepper/00 Overview/15 Explore More.md
  images/Stepper/stepper-elements.png
Labels: 25_1

#7292 Chart: add multi-axis resetVisualRange & Zoom&Pan notes
  api-reference/10 UI Components/dxChart/3 Methods/resetVisualRange().md
  concepts/05 UI Components/Chart/20 Axes/70 Multi-Axis Chart.md
  concepts/05 UI Components/Chart/95 Zooming and Panning/Zooming and Panning.md
Labels: 24_2

#7296 Chart: add multi-axis resetVisualRange & Zoom&Pan notes (#7292)
  api-reference/10 UI Components/dxChart/3 Methods/resetVisualRange().md
  concepts/05 UI Components/Chart/20 Axes/70 Multi-Axis Chart.md
  concepts/05 UI Components/Chart/95 Zooming and Panning/Zooming and Panning.md
Labels: cherry-pick, 24_1

#7297 Chart: add multi-axis resetVisualRange & Zoom&Pan notes (#7292)
  api-reference/10 UI Components/dxChart/3 Methods/resetVisualRange().md
  concepts/05 UI Components/Chart/20 Axes/70 Multi-Axis Chart.md
  concepts/05 UI Components/Chart/95 Zooming and Panning/Zooming and Panning.md
Labels: cherry-pick, 25_1

#7305 Add new icons
  applications/Icons/script.js
Labels: 25_1

#7307 Add 'dxButtonGroup.Options' non existing / inherited member
  api-reference/10 UI Components/dxScheduler/9 Types/dxButtonGroup_Options/dxButtonGroup_Options.md
Labels: 25_1

#7316 Grids: describe GridsContextMenuTarget
  api-reference/40 Common Types/15 grids/GridsContextMenuTarget.md
Labels: 25_1

#7319 AIIntegration: add imports for jQuery
  api-reference/40 Common Types/AIIntegration/AIIntegration.md
  api-reference/40 Common Types/AIProvider/sendRequest.md
Labels: 25_1

#7317 Scheduler: describe toolbar option
  api-reference/10 UI Components/dxScheduler/1 Configuration/toolbar.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbar/disabled.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbar/dxSchedulerToolbar.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbar/items.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbar/multiline.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbar/visible.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbarItem/dxSchedulerToolbarItem.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbarItem/location.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbarItem/name.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbarItem/options.md
  api-reference/10 UI Components/dxScheduler/9 Types/DateNavigatorItemProperties/DateNavigatorItemProperties.md
  api-reference/10 UI Components/dxScheduler/9 Types/DateNavigatorItemProperties/items.md
  api-reference/10 UI Components/dxScheduler/9 Types/SchedulerPredefinedDateNavigatorItem.md
  api-reference/10 UI Components/dxScheduler/9 Types/SchedulerPredefinedToolbarItem.md
  api-reference/10 UI Components/dxScheduler/9 Types/dxButtonGroup_Options/dxButtonGroup_Options.md
  api-reference/NewTopics/dxSchedulerToolbar/items.md
  api-reference/NewTopics/dxSchedulerToolbar/multiline.md
  api-reference/NewTopics/dxSchedulerToolbar/visible.md
  api-reference/NewTopics/dxSchedulerToolbarItem/dxSchedulerToolbarItem.md
  api-reference/NewTopics/dxSchedulerToolbarItem/name.md
  images/Scheduler/toolbar/date-navigator.png
  images/Scheduler/toolbar/today-button.png
  images/Scheduler/toolbar/view-switcher.png
Labels: 25_1

#7102 FileUploader: update Overview
  concepts/05 UI Components/FileUploader/00 Overview.md
  concepts/05 UI Components/FileUploader/00 Overview/00 Overview.md
  concepts/05 UI Components/FileUploader/00 Overview/05 Elements.md
  concepts/05 UI Components/FileUploader/00 Overview/10 Key Features.md
  concepts/05 UI Components/FileUploader/00 Overview/15 Explore More.md
  concepts/05 UI Components/FileUploader/20 Upload Files/05 Client-Side Settings/05 Upload Mode.md
  images/FileUploader/file-uploader-elements.png
Labels: 24_2

#7323 FileUploader: update Overview (#7102)
  concepts/05 UI Components/FileUploader/00 Overview.md
  concepts/05 UI Components/FileUploader/00 Overview/00 Overview.md
  concepts/05 UI Components/FileUploader/00 Overview/05 Elements.md
  concepts/05 UI Components/FileUploader/00 Overview/10 Key Features.md
  concepts/05 UI Components/FileUploader/00 Overview/15 Explore More.md
  concepts/05 UI Components/FileUploader/20 Upload Files/05 Client-Side Settings/05 Upload Mode.md
  images/FileUploader/file-uploader-elements.png
Labels: cherry-pick, 24_1

#7324 FileUploader: update Overview (#7102)
  concepts/05 UI Components/FileUploader/00 Overview.md
  concepts/05 UI Components/FileUploader/00 Overview/00 Overview.md
  concepts/05 UI Components/FileUploader/00 Overview/05 Elements.md
  concepts/05 UI Components/FileUploader/00 Overview/10 Key Features.md
  concepts/05 UI Components/FileUploader/00 Overview/15 Explore More.md
  concepts/05 UI Components/FileUploader/20 Upload Files/05 Client-Side Settings/05 Upload Mode.md
  images/FileUploader/file-uploader-elements.png
Labels: cherry-pick, 25_1

#7325 PivotGrid: add Overview (#7107)
  concepts/05 UI Components/PivotGrid/02 Overview/00 Overview.md
  concepts/05 UI Components/PivotGrid/02 Overview/05 Elements.md
  concepts/05 UI Components/PivotGrid/02 Overview/10 Key Features.md
  concepts/05 UI Components/PivotGrid/02 Overview/15 Explore More.md
  images/pivotgrid/pivot-grid-overview.png
Labels: cherry-pick, 24_1

#7108 DateBox: add Overview
  concepts/05 UI Components/DateBox/01 Overview/00 Overview.md
  concepts/05 UI Components/DateBox/01 Overview/05 Elements.md
  concepts/05 UI Components/DateBox/01 Overview/10 Key Features.md
  concepts/05 UI Components/DateBox/01 Overview/15 Explore More.md
  images/DateBox/date-box-elements.png
Labels: 24_2

#7026 TreeView: add Overview
  concepts/05 UI Components/TreeView/02 Overview/00 Overview.md
  concepts/05 UI Components/TreeView/02 Overview/05 Elements.md
  concepts/05 UI Components/TreeView/02 Overview/10 Key Features.md
  concepts/05 UI Components/TreeView/02 Overview/15 Explore More.md
  images/TreeView/treeview-elements.png
Labels: 24_2

#7327 DateBox: add Overview (#7108)
  concepts/05 UI Components/DateBox/01 Overview/00 Overview.md
  concepts/05 UI Components/DateBox/01 Overview/05 Elements.md
  concepts/05 UI Components/DateBox/01 Overview/10 Key Features.md
  concepts/05 UI Components/DateBox/01 Overview/15 Explore More.md
  images/DateBox/date-box-elements.png
Labels: cherry-pick, 24_1

#7328 DateBox: add Overview (#7108)
  concepts/05 UI Components/DateBox/01 Overview/00 Overview.md
  concepts/05 UI Components/DateBox/01 Overview/05 Elements.md
  concepts/05 UI Components/DateBox/01 Overview/10 Key Features.md
  concepts/05 UI Components/DateBox/01 Overview/15 Explore More.md
  images/DateBox/date-box-elements.png
Labels: cherry-pick, 25_1

#7329 TreeView: add Overview (#7026)
  concepts/05 UI Components/TreeView/02 Overview/00 Overview.md
  concepts/05 UI Components/TreeView/02 Overview/05 Elements.md
  concepts/05 UI Components/TreeView/02 Overview/10 Key Features.md
  concepts/05 UI Components/TreeView/02 Overview/15 Explore More.md
  images/TreeView/treeview-elements.png
Labels: cherry-pick, 24_1

#7336 Fix MenuConfig (Visual Elements)
  MenuConfig.xml
Labels: 24_1

#7335 Chat: add image message info
  api-reference/10 UI Components/dxChat/9 Types/ImageMessage/ImageMessage.md
  api-reference/10 UI Components/dxChat/9 Types/ImageMessage/alt.md
  api-reference/10 UI Components/dxChat/9 Types/ImageMessage/src.md
  api-reference/10 UI Components/dxChat/9 Types/Message.md
  api-reference/10 UI Components/dxChat/9 Types/Message/isDeleted.md
  api-reference/10 UI Components/dxChat/9 Types/Message/isEdited.md
  api-reference/10 UI Components/dxChat/9 Types/Message/text.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/MessageBase.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/author.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/id.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/isDeleted.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/timestamp.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/type.md
  api-reference/10 UI Components/dxChat/9 Types/TextMessage/TextMessage.md
  api-reference/10 UI Components/dxChat/9 Types/TextMessage/isEdited.md
  api-reference/10 UI Components/dxChat/9 Types/TextMessage/text.md
  api-reference/NewTopics/ImageMessage/alt.md
  api-reference/NewTopics/ImageMessage/src.md
  api-reference/NewTopics/MessageBase/author.md
  api-reference/NewTopics/MessageBase/id.md
  api-reference/NewTopics/MessageBase/timestamp.md
  api-reference/NewTopics/MessageBase/type.md
  api-reference/NewTopics/TextMessage/text.md
Labels: 25_1

#7295 DevExtreme CLI: add React Next.js info
  MenuConfig.xml
  concepts/50 React Components/50 Application Template/00 Application Template.md
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
  concepts/50 React Components/50 Application Template/10 Layouts.md
  concepts/50 React Components/50 Application Template/20 Add a New View.md
  concepts/50 React Components/50 Application Template/30 Configure the Navigation Menu/10 Configure Menu Items.md
  concepts/50 React Components/50 Application Template/30 Configure the Navigation Menu/20 Hide the Menu in the Closed State.md
  concepts/50 React Components/50 Application Template/35 Add a Custom Toolbar Item.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/20 Create a Custom Theme.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/30 Apply a Color Swatch.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/40 Apply Theme Variables to Custom Elements.md
  concepts/50 React Components/50 Application Template/45 Authentication/00 Authentication.md
  concepts/50 React Components/50 Application Template/45 Authentication/10 Vite Authentication/00 Vite Authentication.md
  concepts/50 React Components/50 Application Template/45 Authentication/10 Vite Authentication/10 Implement Authentication Functions.md
  concepts/50 React Components/50 Application Template/45 Authentication/10 Vite Authentication/20 Get User Information.md
  concepts/50 React Components/50 Application Template/45 Authentication/20 Next.js Authentication/00 Next.js Authentication.md
  concepts/50 React Components/50 Application Template/45 Authentication/20 Next.js Authentication/10 Generate Session Key.md
  concepts/50 React Components/50 Application Template/45 Authentication/20 Next.js Authentication/20 Implement Authentication Functions.md
  concepts/50 React Components/50 Application Template/45 Authentication/20 Next.js Authentication/30 Implement Authorization Functions.md
  concepts/50 React Components/50 Application Template/50 Create an Empty Application.md
  concepts/Common/DevExtreme CLI/00 Requirements.md
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/10 Create a New Application.md
  concepts/Common/Integration Guides/20 Create a DevExtreme application with Next.js/20 Create a DevExtreme application with Next.js.md
Labels: 25_1

#7337 Scheduler: add toolbar dateNavigator options info
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbarItem/dxSchedulerToolbarItem.md
Labels: 25_1

#7338 Angular: update Call Methods
  concepts/40 Angular Components/20 Component Configuration Syntax/42 Call Methods.md
Labels: 24_2

#7339 Angular: update Call Methods (#7338)
  concepts/40 Angular Components/20 Component Configuration Syntax/42 Call Methods.md
Labels: cherry-pick, 24_1

#7340 Angular: update Call Methods (#7338)
  concepts/40 Angular Components/20 Component Configuration Syntax/42 Call Methods.md
Labels: cherry-pick, 25_1

#7321 Angular: add info about standalone components
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/01 One-Command Setup.md
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/40 Import DevExtreme Components.md
  concepts/Common/DevExtreme CLI/10 Add DevExtreme to an Existing Application.md
  includes/ng-import-devextreme-modules.md
Labels: 25_1

#7344 Chat Editing / Messages: Patches to recover DocGen
  api-reference/10 UI Components/dxChat/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxChat/9 Types/ImageMessage/ImageMessage.md
  api-reference/10 UI Components/dxChat/9 Types/ImageMessage/alt.md
  api-reference/10 UI Components/dxChat/9 Types/ImageMessage/src.md
  api-reference/10 UI Components/dxChat/9 Types/Message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/MessageBase.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/type.md
  api-reference/10 UI Components/dxChat/9 Types/TextMessage/TextMessage.md
  api-reference/10 UI Components/dxChat/9 Types/TextMessage/text.md
Labels: 25_1

#7346 Grids: update getRowElement(rowIndex)
  api-reference/10 UI Components/GridBase/3 Methods/getRowElement(rowIndex).md
Labels: 24_2

#7347 Grids: update getRowElement(rowIndex) (#7346)
  api-reference/10 UI Components/GridBase/3 Methods/getRowElement(rowIndex).md
Labels: cherry-pick, 25_1

#7342 CardView: describe API (part 2, editing, paging)
  api-reference/10 UI Components/dxCardView/1 Configuration/columns.md
  api-reference/10 UI Components/dxCardView/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxCardView/1 Configuration/editing.md
  api-reference/10 UI Components/dxCardView/1 Configuration/keyExpr.md
  api-reference/10 UI Components/dxCardView/1 Configuration/onContextMenuPreparing.md
  api-reference/10 UI Components/dxCardView/1 Configuration/onEditCanceled.md
  api-reference/10 UI Components/dxCardView/1 Configuration/onEditCanceling.md
  api-reference/10 UI Components/dxCardView/1 Configuration/onEditingStart.md
  api-reference/10 UI Components/dxCardView/1 Configuration/pager.md
  api-reference/10 UI Components/dxCardView/1 Configuration/paging.md
  api-reference/10 UI Components/dxCardView/1 Configuration/remoteOperations.md
  api-reference/10 UI Components/dxCardView/1 Configuration/scrolling.md
  api-reference/10 UI Components/dxCardView/1 Configuration/searchPanel.md
  api-reference/10 UI Components/dxCardView/1 Configuration/toolbar.md
  api-reference/10 UI Components/dxCardView/1 Configuration/wordWrapEnabled.md
  api-reference/10 UI Components/dxCardView/3 Methods/addCard.md
  api-reference/10 UI Components/dxCardView/3 Methods/cancelEditData().md
  api-reference/10 UI Components/dxCardView/3 Methods/deleteCard(cardIndex).md
  api-reference/10 UI Components/dxCardView/3 Methods/editCard(cardIndex).md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/alignment.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowEditing.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowFiltering.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowHeaderFiltering.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowHiding.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowReordering.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowSearch.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowSorting.md
  api-reference/10 UI Components/dxCardView/9 Types/Paging/Paging.md
  api-reference/10 UI Components/dxCardView/9 Types/Paging/enabled.md
  api-reference/10 UI Components/dxCardView/9 Types/Paging/pageIndex.md
  api-reference/10 UI Components/dxCardView/9 Types/Paging/pageSize.md
  api-reference/10 UI Components/dxCardView/9 Types/RemoteOperations/RemoteOperations.md
  api-reference/10 UI Components/dxCardView/9 Types/RemoteOperations/filtering.md
  api-reference/10 UI Components/dxCardView/9 Types/RemoteOperations/grouping.md
  api-reference/10 UI Components/dxCardView/9 Types/RemoteOperations/paging.md
  api-reference/10 UI Components/dxCardView/9 Types/RemoteOperations/sorting.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/allowAdding.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/allowDeleting.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/allowUpdating.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/changes.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/confirmDelete.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/dxCardViewEditing.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/editCardKey.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/form.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/popup.md
Labels: 25_1

#7343 Grids: update focusedRowEnabled
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowEnabled.md
Labels: 24_2

#7349 Grids: update focusedRowEnabled (#7343)
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowEnabled.md
Labels: cherry-pick, 24_1

#7350 Grids: update focusedRowEnabled (#7343)
  api-reference/10 UI Components/GridBase/1 Configuration/focusedRowEnabled.md
Labels: cherry-pick, 25_1

#7293 Chat: describe Editing feature
  api-reference/10 UI Components/dxChat/1 Configuration/allowDeleting.md
  api-reference/10 UI Components/dxChat/1 Configuration/allowUpdating.md
  api-reference/10 UI Components/dxChat/1 Configuration/editing.md
  api-reference/10 UI Components/dxChat/1 Configuration/editing/allowDeleting.md
  api-reference/10 UI Components/dxChat/1 Configuration/editing/allowUpdating.md
  api-reference/10 UI Components/dxChat/1 Configuration/editing/editing.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageDeleted.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageDeleting.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageEditCanceled.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageEditingStart.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageUpdated.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageUpdating.md
  api-reference/10 UI Components/dxChat/4 Events/messageDeleted.md
  api-reference/10 UI Components/dxChat/4 Events/messageDeleting.md
  api-reference/10 UI Components/dxChat/4 Events/messageEditCanceled.md
  api-reference/10 UI Components/dxChat/4 Events/messageEditingStart.md
  api-reference/10 UI Components/dxChat/4 Events/messageUpdated.md
  api-reference/10 UI Components/dxChat/4 Events/messageUpdating.md
  api-reference/10 UI Components/dxChat/9 Types/Editing/Editing.md
  api-reference/10 UI Components/dxChat/9 Types/Editing/allowDeleting.md
  api-reference/10 UI Components/dxChat/9 Types/Editing/allowUpdating.md
  api-reference/10 UI Components/dxChat/9 Types/Message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/author.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/isDeleted.md
  api-reference/10 UI Components/dxChat/9 Types/MessageDeletedEvent/MessageDeletedEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageDeletedEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageDeletingEvent/MessageDeletingEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageDeletingEvent/cancel.md
  api-reference/10 UI Components/dxChat/9 Types/MessageDeletingEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEditCanceledEvent/MessageEditCanceledEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEditCanceledEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEditingStartEvent/MessageEditingStartEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEditingStartEvent/cancel.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEditingStartEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEnteredEvent/MessageEnteredEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatedEvent/MessageUpdatedEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatedEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatedEvent/text.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatingEvent/MessageUpdatingEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatingEvent/cancel.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatingEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatingEvent/text.md
  api-reference/10 UI Components/dxChat/9 Types/OptionChangedEvent/OptionChangedEvent.md
  api-reference/10 UI Components/dxChat/9 Types/TextMessage/isEdited.md
  api-reference/10 UI Components/dxChat/9 Types/TypingEndEvent/TypingEndEvent.md
  api-reference/10 UI Components/dxChat/9 Types/TypingStartEvent/TypingStartEvent.md
  concepts/05 UI Components/Chat/10 Accessibility/15 Keyboard Navigation.md
Labels: 25_1

#7348 Tooltip: Update target
  includes/uiwidgets-ref-target.md
Labels: 24_2

#7354 Accessibility: update standards
  concepts/05 UI Components/Chat/10 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/DataGrid/05 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/Scheduler/10 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/TreeList/05 Accessibility/10 Accessibility Standards Compliance.md
Labels: 25_1

#7355 CardView: add Accessibility
  concepts/05 UI Components/CardView/10 Accessibility/00 Accessibility.md
  concepts/05 UI Components/CardView/10 Accessibility/05 Accessibility Features Overview.md
  concepts/05 UI Components/CardView/10 Accessibility/10 Accessibility Standards Compliance.md
  concepts/05 UI Components/CardView/10 Accessibility/15 Keyboard Navigation.md
  concepts/05 UI Components/CardView/10 Accessibility/20 Screen Reader Support.md
  concepts/Common/Accessibility/05 Documentation for Components.md
Labels: 25_1

#7360 DataGrid: add Keyboard Navigation limitations
  concepts/05 UI Components/DataGrid/05 Accessibility/15 Keyboard Navigation.md
Labels: 25_1

#7363 Scheduler/HTML Editor: fix minor code snippet errors
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerAppointment/recurrenceRule.md
  api-reference/_hidden/dxHtmlEditorImageUpload/fileUploaderOptions.md
Labels: 24_2

#7364 Scheduler/HTML Editor: fix minor code snippet errors (#7363)
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerAppointment/recurrenceRule.md
  api-reference/_hidden/dxHtmlEditorImageUpload/fileUploaderOptions.md
Labels: cherry-pick, 24_1

#7365 Scheduler/HTML Editor: fix minor code snippet errors (#7363)
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerAppointment/recurrenceRule.md
  api-reference/_hidden/dxHtmlEditorImageUpload/fileUploaderOptions.md
Labels: cherry-pick, 25_1

#7366 Angular Best Practices: Add Configuration Components
  concepts/Common/TypeScript Guides/10 Best Practices/20 Configuration Components.md
Labels: 24_2

#7368 Angular Best Practices: Add Configuration Components
  concepts/Common/TypeScript Guides/10 Best Practices/20 Configuration Components.md
Labels: cherry-pick, 25_1

#7371 Diagram: add code to nodes.typeExpr (#7369)
  api-reference/10 UI Components/dxDiagram/1 Configuration/nodes/typeExpr.md
Labels: cherry-pick, 25_1

#7372 SelectBox: fix searchMode description
  api-reference/10 UI Components/dxSelectBox/1 Configuration/searchMode.md
Labels: 24_2

#7373 SelectBox: update searchMode
  api-reference/10 UI Components/dxSelectBox/1 Configuration/searchMode.md
Labels: cherry-pick, 25_1

#7374 SelectBox: update searchMode
  api-reference/10 UI Components/dxSelectBox/1 Configuration/searchMode.md
Labels: cherry-pick, 24_1

#7377 CardView: describe API (part 5 - methods, header panel, columns)
  api-reference/10 UI Components/dxCardView/1 Configuration/columns.md
  api-reference/10 UI Components/dxCardView/1 Configuration/filterBuilderPopup.md
  api-reference/10 UI Components/dxCardView/1 Configuration/headerPanel.md
  api-reference/10 UI Components/dxCardView/1 Configuration/noDataTemplate.md
  api-reference/10 UI Components/dxCardView/1 Configuration/onContextMenuPreparing.md
  api-reference/10 UI Components/dxCardView/3 Methods/byKey().md
  api-reference/10 UI Components/dxCardView/3 Methods/clearFilter().md
  api-reference/10 UI Components/dxCardView/3 Methods/clearSorting().md
  api-reference/10 UI Components/dxCardView/3 Methods/getCardElement(cardIndex).md
  api-reference/10 UI Components/dxCardView/3 Methods/getCardIndexByKey(key).md
  api-reference/10 UI Components/dxCardView/3 Methods/getCombinedFilter().md
  api-reference/10 UI Components/dxCardView/3 Methods/getDataSource().md
  api-reference/10 UI Components/dxCardView/3 Methods/getKeyByCardIndex(cardIndex).md
  api-reference/10 UI Components/dxCardView/3 Methods/getScrollable().md
  api-reference/10 UI Components/dxCardView/3 Methods/getVisibleCards().md
  api-reference/10 UI Components/dxCardView/3 Methods/hasEditData().md
  api-reference/10 UI Components/dxCardView/3 Methods/hideColumnChooser().md
  api-reference/10 UI Components/dxCardView/3 Methods/keyOf(obj).md
  api-reference/10 UI Components/dxCardView/3 Methods/pageCount().md
  api-reference/10 UI Components/dxCardView/3 Methods/pageIndex().md
  api-reference/10 UI Components/dxCardView/3 Methods/pageIndex(value).md
  api-reference/10 UI Components/dxCardView/3 Methods/pageSize().md
  api-reference/10 UI Components/dxCardView/3 Methods/pageSize(value).md
  api-reference/10 UI Components/dxCardView/3 Methods/saveEditData().md
  api-reference/10 UI Components/dxCardView/3 Methods/searchByText(text).md
  api-reference/10 UI Components/dxCardView/3 Methods/showColumnChooser().md
  api-reference/10 UI Components/dxCardView/3 Methods/totalCount().md
  api-reference/10 UI Components/dxCardView/9 Types/Column/Column.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/alignment.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowEditing.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowFiltering.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowHeaderFiltering.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/calculateDisplayValue.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/calculateFieldValue.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnTemplateData/ColumnTemplateData.md
  api-reference/10 UI Components/dxCardView/9 Types/ContextMenuPreparingEvent/card.md
  api-reference/10 UI Components/dxCardView/9 Types/ContextMenuPreparingEvent/cardIndex.md
  api-reference/10 UI Components/dxCardView/9 Types/ContextMenuPreparingEvent/column.md
  api-reference/10 UI Components/dxCardView/9 Types/ContextMenuPreparingEvent/columnIndex.md
  api-reference/10 UI Components/dxCardView/9 Types/ContextMenuPreparingEvent/items.md
  api-reference/10 UI Components/dxCardView/9 Types/ContextMenuPreparingEvent/target.md
  api-reference/10 UI Components/dxCardView/9 Types/ContextMenuPreparingEvent/targetElement.md
  api-reference/10 UI Components/dxCardView/9 Types/EditCanceledEvent/changes.md
  api-reference/10 UI Components/dxCardView/9 Types/EditCancelingEvent/changes.md
  api-reference/10 UI Components/dxCardView/9 Types/EditingStartEvent/data.md
  api-reference/10 UI Components/dxCardView/9 Types/EditingStartEvent/key.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/HeaderPanel.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/itemTemplate.md
  api-reference/10 UI Components/dxCardView/9 Types/InitNewCardEvent/data.md
  api-reference/10 UI Components/dxCardView/9 Types/InitNewCardEvent/promise.md
Labels: 25_1
