Repository DevExpress/devextreme-documentation, pull requests merged in 2025-04, with the labels that each got.

#6661 Change main overview pages
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/40 Angular Components/10 Getting Started/02 Create a DevExtreme Application.md
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/Add DevExtreme to an Angular CLI Application.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/50 React Components/02 Create a DevExtreme Application.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/00 Add DevExtreme to a React Application.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/55 Vue Components/02 Create a DevExtreme Application.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/00 Add DevExtreme to a Vue Application.md
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
Labels: 24_2

#7175 Change main overview pages (#6661)
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/40 Angular Components/10 Getting Started/02 Create a DevExtreme Application.md
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/Add DevExtreme to an Angular CLI Application.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/50 React Components/02 Create a DevExtreme Application.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/00 Add DevExtreme to a React Application.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/55 Vue Components/02 Create a DevExtreme Application.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/00 Add DevExtreme to a Vue Application.md
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
Labels: cherry-pick, 25_1

#7181 Angular and Vue: add named/non-named template examples (#7179)
  includes/custom-templates.md
Labels: cherry-pick, 24_1

#7182 Angular and Vue: add named/non-named template examples (#7179)
  includes/custom-templates.md
Labels: cherry-pick, 25_1

#7180 DateBox: minor pickerType fix
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: 24_2

#7183 DateBox: minor pickerType fix (#7180)
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: cherry-pick, 24_1

#7184 DateBox: minor pickerType fix (#7180)
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: cherry-pick, 25_1

#7185 Add a note to Styling Methods
  concepts/60 Themes and Styles/00 Styling Methods.md
Labels: 24_2

#7186 Add a note to Styling Methods (#7185)
  concepts/60 Themes and Styles/00 Styling Methods.md
Labels: cherry-pick, 24_1

#7187 Add a note to Styling Methods (#7185)
  concepts/60 Themes and Styles/00 Styling Methods.md
Labels: cherry-pick, 25_1

#6887 Add What's New section
  MenuConfig.xml
  concepts/Common/Whats New/00 v24.2 Release Notes.md
  concepts/Common/Whats New/10 Version History.md
  concepts/Common/Whats New/20 June 2025 Roadmap (v25.1).md
Labels: 24_2

#7191 Fix What's New section visibility
  MenuConfig.xml
Labels: 24_2

#7056 Chart: update Overview
  concepts/05 UI Components/Chart/00 Overview.md
  concepts/05 UI Components/Chart/02 Overview/00 Overview.md
  concepts/05 UI Components/Chart/02 Overview/05 Elements.md
  concepts/05 UI Components/Chart/02 Overview/10 Key Features.md
  concepts/05 UI Components/Chart/02 Overview/15 Explore More.md
  concepts/05 UI Components/Chart/10 Series/00 Overview.md
  concepts/05 UI Components/Chart/14 Series Points/00 Overview.md
  concepts/05 UI Components/Chart/15 Point Labels/00 Overview.md
  concepts/05 UI Components/Chart/20 Axes/00 Overview.md
  concepts/05 UI Components/Chart/30 Tooltips/00 Overview.md
  concepts/05 UI Components/Chart/35 Legend/00 Overview.md
  concepts/05 UI Components/Chart/40 Panes/00 Overview.md
  images/ChartJS/chart-elements.png
Labels: 24_2

#7192 Chart: update Overview (#7056)
  concepts/05 UI Components/Chart/00 Overview.md
  concepts/05 UI Components/Chart/02 Overview/00 Overview.md
  concepts/05 UI Components/Chart/02 Overview/05 Elements.md
  concepts/05 UI Components/Chart/02 Overview/10 Key Features.md
  concepts/05 UI Components/Chart/02 Overview/15 Explore More.md
  concepts/05 UI Components/Chart/10 Series/00 Overview.md
  concepts/05 UI Components/Chart/14 Series Points/00 Overview.md
  concepts/05 UI Components/Chart/15 Point Labels/00 Overview.md
  concepts/05 UI Components/Chart/20 Axes/00 Overview.md
  concepts/05 UI Components/Chart/30 Tooltips/00 Overview.md
  concepts/05 UI Components/Chart/35 Legend/00 Overview.md
  concepts/05 UI Components/Chart/40 Panes/00 Overview.md
  images/ChartJS/chart-elements.png
Labels: cherry-pick, 24_1

#7194 Remove ZIP Archive
  api-reference/10 UI Components/BaseChart/1 Configuration/tooltip/argumentFormat.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/argumentFormat.md
  api-reference/10 UI Components/dxPieChart/5 Series Types/CommonPieChartSeries/label/argumentFormat.md
  api-reference/10 UI Components/dxPolarChart/5 Series Types/CommonPolarChartSeries/label/argumentFormat.md
  api-reference/40 Common Types/05 charts/BaseChartTooltip/argumentFormat.md
  concepts/05 UI Components/VectorMap/20 Providing Data/10 Data for Areas/20 Using a Script.md
  concepts/Common/Distribution Channels/15 ZIP Archive.md
  concepts/Common/TypeScript Guides/00 Getting Started.md
Labels: 24_2

#7195 Remove ZIP Archive (#7194)
  api-reference/10 UI Components/BaseChart/1 Configuration/tooltip/argumentFormat.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/argumentFormat.md
  api-reference/10 UI Components/dxPieChart/5 Series Types/CommonPieChartSeries/label/argumentFormat.md
  api-reference/10 UI Components/dxPolarChart/5 Series Types/CommonPolarChartSeries/label/argumentFormat.md
  api-reference/40 Common Types/05 charts/BaseChartTooltip/argumentFormat.md
  concepts/05 UI Components/VectorMap/20 Providing Data/10 Data for Areas/20 Using a Script.md
  concepts/Common/Distribution Channels/15 ZIP Archive.md
  concepts/Common/TypeScript Guides/00 Getting Started.md
Labels: cherry-pick, 25_1

#7174 Map: update routes[].mode
  api-reference/10 UI Components/dxMap/1 Configuration/routes/mode.md
Labels: 25_1

#7196 Change the note about Globalize
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/08 Register 3rd-Party Dependencies/02 Globalize Registration.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/63 Register 3rd-Party Dependencies/2 Globalize Registration.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/localization/globalize/globalize.md
Labels: 25_1

#7199 Popover/Tooltip: add info about target (#7198)
  api-reference/10 UI Components/dxPopover/1 Configuration/hideEvent/hideEvent.md
  api-reference/10 UI Components/dxPopover/1 Configuration/showEvent/showEvent.md
Labels: cherry-pick, 24_1

#7200 Popover/Tooltip: add info about target (#7198)
  api-reference/10 UI Components/dxPopover/1 Configuration/hideEvent/hideEvent.md
  api-reference/10 UI Components/dxPopover/1 Configuration/showEvent/showEvent.md
Labels: cherry-pick, 25_1

#7202 SelectBox: update Keyboard Navigation (#7201)
  concepts/05 UI Components/SelectBox/03 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 24_1

#7203 SelectBox: update Keyboard Navigation (#7201)
  concepts/05 UI Components/SelectBox/03 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 25_1

#7208 Add jsPDF version (#7207)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportGantt(options).md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/05 UI Components/Gantt/50 Export Data.md
  concepts/80 Troubleshooting/15 PDF Export/00 PDF Export.md
Labels: cherry-pick, 24_1

#7209 Add jsPDF version (#7207)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/export/export.md
  api-reference/50 Common/utils/pdfExporter/exportDataGrid(options).md
  api-reference/50 Common/utils/pdfExporter/exportGantt(options).md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/80 Export Data.md
  concepts/05 UI Components/Gantt/50 Export Data.md
  concepts/80 Troubleshooting/15 PDF Export/00 PDF Export.md
Labels: cherry-pick, 25_1

#7210 CI: Use PAT in docgen
  .github/workflows/docgen.yml
Labels: 25_1

#7211 CI: Use PAT in docgen
  .github/workflows/docgen.yml
Labels: 24_2

#7212 CI: Use PAT in docgen
  .github/workflows/docgen.yml
Labels: 24_1

#7213 CI: Improve docgen
  .github/workflows/docgen.yml
Labels: 23_2

#7218 CLI: edits related to CLI/React migration from CRA to Vite (#7197)
  concepts/50 React Components/50 Application Template/40 Configure Themes/40 Apply Theme Variables to Custom Elements.md
  concepts/Common/DevExtreme CLI/00 Requirements.md
Labels: cherry-pick, 24_1

#7217 CLI: edits related to CLI/React migration from CRA to Vite (#7197)
  concepts/50 React Components/50 Application Template/40 Configure Themes/40 Apply Theme Variables to Custom Elements.md
  concepts/Common/DevExtreme CLI/00 Requirements.md
Labels: cherry-pick, 24_2

#7216 List: add a note to displayExpr
  api-reference/10 UI Components/dxList/1 Configuration/showSelectionControls.md
Labels: 24_2

#7220 List: add a note to displayExpr (#7216)
  api-reference/10 UI Components/dxList/1 Configuration/showSelectionControls.md
Labels: cherry-pick, 24_1

#7221 List: add a note to displayExpr (#7216)
  api-reference/10 UI Components/dxList/1 Configuration/showSelectionControls.md
Labels: cherry-pick, 25_1

#7226 OData: add demo button
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
Labels: 24_2

#7227 OData: add demo button (#7226)
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
Labels: cherry-pick, 24_1

#7228 OData: add demo button (#7226)
  concepts/70 Data Binding/00 Specify a Data Source/40 OData.md
Labels: cherry-pick, 25_1

#7230 PivotGridDataSource: add unique (#7229)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/name.md
Labels: cherry-pick, 24_1

#7241 Scheduler: add AppointmentCollectorTemplateData
  api-reference/10 UI Components/dxScheduler/9 Types/AppointmentCollectorTemplateData/AppointmentCollectorTemplateData.md
  api-reference/10 UI Components/dxScheduler/9 Types/AppointmentCollectorTemplateData/appointmentCount.md
  api-reference/10 UI Components/dxScheduler/9 Types/AppointmentCollectorTemplateData/isCompact.md
  api-reference/10 UI Components/dxScheduler/9 Types/AppointmentCollectorTemplateData/items.md
  api-reference/NewTopics/AppointmentCollectorTemplateData/isCompact.md
Labels: 25_1

#7242 Splitter/Chat: update dataSource descriptions
  api-reference/10 UI Components/dxChat/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/dataSource.md
Labels: 24_2

#7243 Splitter/Chat: update dataSource descriptions (#7242)
  api-reference/10 UI Components/dxChat/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxSplitter/1 Configuration/dataSource.md
Labels: cherry-pick, 25_1

#7245 Add / duplicate shortDescription / changes/key
  api-reference/10 UI Components/dxDataGrid/1 Configuration/editing/changes/key.md
Labels: 25_1

#7248 DataGrid/DataSource: add note about mapping (#7240)
  api-reference/10 UI Components/GridBase/1 Configuration/dataSource.md
  api-reference/30 Data Layer/DataSource/1 Configuration/map.md
Labels: cherry-pick, 24_1

#7249 DataGrid/DataSource: add note about mapping (#7240)
  api-reference/10 UI Components/GridBase/1 Configuration/dataSource.md
  api-reference/30 Data Layer/DataSource/1 Configuration/map.md
Labels: cherry-pick, 25_1

#7236 DataGrid: update editing.refreshMode section
  api-reference/10 UI Components/GridBase/1 Configuration/editing/refreshMode.md
Labels: 24_2

#7250 DataGrid: update editing.refreshMode section (#7236)
  api-reference/10 UI Components/GridBase/1 Configuration/editing/refreshMode.md
Labels: cherry-pick, 24_1

#7251 DataGrid: update editing.refreshMode section (#7236)
  api-reference/10 UI Components/GridBase/1 Configuration/editing/refreshMode.md
Labels: cherry-pick, 25_1

#7244 Localization: edit Globalize and CRA note
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
Labels: 25_1

#7252 Icons: Add restore & dropzone icons
  applications/Icons/script.js
Labels: 25_1

#7234 DataGrid: update editing.form "do not specify" section
  api-reference/10 UI Components/GridBase/1 Configuration/editing/form.md
Labels: 24_2

#7259 DataGrid: update editing.form "do not specify" section (#7234)
  api-reference/10 UI Components/GridBase/1 Configuration/editing/form.md
Labels: cherry-pick, 24_1

#7260 DataGrid: update editing.form "do not specify" section (#7234)
  api-reference/10 UI Components/GridBase/1 Configuration/editing/form.md
Labels: cherry-pick, 25_1

#7262 FileUploader: update accept property
  api-reference/10 UI Components/dxFileUploader/1 Configuration/accept.md
Labels: 24_2

#7261 Add missing example links
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/rowDragging.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/dataRowTemplate.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onCellPrepared.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/variables/variables.md
  api-reference/10 UI Components/dxMap/1 Configuration/provider.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentTooltipTemplate.md
  api-reference/_hidden/dxDataGridColumn/editCellTemplate.md
  api-reference/_hidden/dxTabPanelItem/title.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/40 Edit and Validate Data.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/50 Advanced Customization.md
  concepts/05 UI Components/Map/20 Configure Markers/05 Add and Remove.md
  concepts/05 UI Components/Scheduler/00 Getting Started with Scheduler/15 Edit Appointments.md
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
  concepts/05 UI Components/TabPanel/01 Getting Started with TabPanel/30 Specify View Content.md
Labels: 24_2

#7267 FileUploader: update accept property (#7262)
  api-reference/10 UI Components/dxFileUploader/1 Configuration/accept.md
Labels: cherry-pick, 25_1

#7266 FileUploader: update accept property (#7262)
  api-reference/10 UI Components/dxFileUploader/1 Configuration/accept.md
Labels: cherry-pick, 24_1

#7269 Add missing example links (#7261)
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/rowDragging.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/dataRowTemplate.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onCellPrepared.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/variables/variables.md
  api-reference/10 UI Components/dxMap/1 Configuration/provider.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentTooltipTemplate.md
  api-reference/_hidden/dxDataGridColumn/editCellTemplate.md
  api-reference/_hidden/dxTabPanelItem/title.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/40 Edit and Validate Data.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/50 Advanced Customization.md
  concepts/05 UI Components/Map/20 Configure Markers/05 Add and Remove.md
  concepts/05 UI Components/Scheduler/00 Getting Started with Scheduler/15 Edit Appointments.md
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
  concepts/05 UI Components/TabPanel/01 Getting Started with TabPanel/30 Specify View Content.md
Labels: cherry-pick, 24_1

#7270 Add missing example links (#7261)
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/rowDragging.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/dataRowTemplate.md
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onCellPrepared.md
  api-reference/10 UI Components/dxGantt/1 Configuration/taskContentTemplate.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/variables/variables.md
  api-reference/10 UI Components/dxMap/1 Configuration/provider.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentTooltipTemplate.md
  api-reference/_hidden/dxDataGridColumn/editCellTemplate.md
  api-reference/_hidden/dxTabPanelItem/title.md
  concepts/05 UI Components/DataGrid/00 Getting Started with DataGrid/40 Edit and Validate Data.md
  concepts/05 UI Components/DataGrid/20 Editing/43 Customize Edit Form/50 Advanced Customization.md
  concepts/05 UI Components/Map/20 Configure Markers/05 Add and Remove.md
  concepts/05 UI Components/Scheduler/00 Getting Started with Scheduler/15 Edit Appointments.md
  concepts/05 UI Components/Scheduler/030 Appointments/060 Customize Appointment Tooltip.md
  concepts/05 UI Components/TabPanel/01 Getting Started with TabPanel/30 Specify View Content.md
Labels: cherry-pick, 25_1

#7272 Add info about selectedFilterOperation in note
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: 24_2

#7273 Add info about selectedFilterOperation in note (#7272)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: cherry-pick, 24_1

#7274 Add info about selectedFilterOperation in note (#7272)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: cherry-pick, 25_1

#7275 Update getTimeZones description
  api-reference/50 Common/utils/utils/getTimeZones(date_timeZones).md
Labels: 25_1

#7280 DataGrid: clarify returnDataField & calculateCellValue
  api-reference/10 UI Components/GridBase/3 Methods/getCombinedFilter(returnDataField).md
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
Labels: 24_2

#7281 DataGrid: clarify returnDataField & calculateCellValue (#7280)
  api-reference/10 UI Components/GridBase/3 Methods/getCombinedFilter(returnDataField).md
  api-reference/_hidden/GridBaseColumn/calculateCellValue.md
Labels: cherry-pick, 25_1

#7279 DataGrid: update setCellValue repaint text
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: 24_2

#7284 DataGrid: update setCellValue repaint text (#7279)
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: cherry-pick, 24_1

#7286 DataGrid: update setCellValue repaint text (#7279)
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: cherry-pick, 25_1

#7288 Chat Editing topics
  api-reference/10 UI Components/dxChat/1 Configuration/editing.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageDeleted.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageDeleting.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageEditCanceled.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageEditingStart.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageUpdated.md
  api-reference/10 UI Components/dxChat/1 Configuration/onMessageUpdating.md
  api-reference/10 UI Components/dxChat/4 Events/messageDeleted.md
  api-reference/10 UI Components/dxChat/4 Events/messageDeleting.md
  api-reference/10 UI Components/dxChat/4 Events/messageEditCanceled.md
  api-reference/10 UI Components/dxChat/4 Events/messageEditingStart.md
  api-reference/10 UI Components/dxChat/4 Events/messageUpdated.md
  api-reference/10 UI Components/dxChat/4 Events/messageUpdating.md
  api-reference/10 UI Components/dxChat/9 Types/Editing/Editing.md
  api-reference/10 UI Components/dxChat/9 Types/Editing/allowDeleting.md
  api-reference/10 UI Components/dxChat/9 Types/Editing/allowUpdating.md
  api-reference/10 UI Components/dxChat/9 Types/Message/isDeleted.md
  api-reference/10 UI Components/dxChat/9 Types/Message/isEdited.md
  api-reference/10 UI Components/dxChat/9 Types/MessageDeletedEvent/MessageDeletedEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageDeletedEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageDeletingEvent/MessageDeletingEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageDeletingEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEditCanceledEvent/MessageEditCanceledEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEditCanceledEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEditingStartEvent/MessageEditingStartEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageEditingStartEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatedEvent/MessageUpdatedEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatedEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatedEvent/text.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatingEvent/MessageUpdatingEvent.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatingEvent/message.md
  api-reference/10 UI Components/dxChat/9 Types/MessageUpdatingEvent/text.md
  metadata/syntax-data.json
Labels: 25_1
