Repository DevExpress/devextreme-documentation, pull requests merged in 2025-08, with the labels that each got.

#7767 Grids: Add editing.form TabbedItem validation note
  api-reference/10 UI Components/GridBase/1 Configuration/editing/form.md
Labels: 25_1

#7787 Grids: Add editing.form TabbedItem validation note (#7767)
  api-reference/10 UI Components/GridBase/1 Configuration/editing/form.md
Labels: cherry-pick, 24_2

#7788 Grids: Add editing.form TabbedItem validation note (#7767)
  api-reference/10 UI Components/GridBase/1 Configuration/editing/form.md
Labels: cherry-pick, 25_2

#7789 TextBox: Update mask topic
  api-reference/10 UI Components/dxTextEditor/1 Configuration/mask.md
Labels: 25_1

#7800 Button: Update onContentReady Angular snippet
  api-reference/10 UI Components/dxButton/1 Configuration/onContentReady.md
Labels: 25_1

#7801 Button: Update onContentReady Angular snippet (#7800)
  api-reference/10 UI Components/dxButton/1 Configuration/onContentReady.md
Labels: cherry-pick, 24_2

#7806 TabPanel: describe keyExpr
  api-reference/10 UI Components/dxTabPanel/1 Configuration/keyExpr.md
Labels: 25_1

#7796 Update E1040 error doc
  api-reference/10 UI Components/Errors and Warnings/E1040.md
Labels: 25_1

#7810 Form: Update Overview demo links
  api-reference/10 UI Components/dxForm/1 Configuration/formData.md
  api-reference/10 UI Components/dxForm/1 Configuration/items.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/colSpan.md
  api-reference/10 UI Components/dxForm/5 Item Types/GroupItem/cssClass.md
  concepts/05 UI Components/Form/05 Configure Simple Items/05 Customize a Simple Item.md
Labels: 25_1

#7815 LoadIndicator: Add animationType
  api-reference/10 UI Components/dxLoadIndicator/1 Configuration/animationType.md
  api-reference/40 Common Types/LoadingAnimationType.md
  applications/UIWidgets/LoadIndicator/animationCircle/index.html
  applications/UIWidgets/LoadIndicator/animationCircle/index.js
  applications/UIWidgets/LoadIndicator/animationSparkle/index.html
  applications/UIWidgets/LoadIndicator/animationSparkle/index.js
Labels: 25_2

#7818 DataGrid: Update Get Current Cell Values how to
  concepts/05 UI Components/DataGrid/20 Editing/20 API/40 Get Current Cell Values.md
Labels: 25_1

#7819 VectorMap: Add selection notes
  api-reference/10 UI Components/dxVectorMap/1 Configuration/layers/selectionMode.md
  api-reference/10 UI Components/dxVectorMap/1 Configuration/onSelectionChanged.md
Labels: 25_1

#7822 VectorMap: Add selection notes (#7819)
  api-reference/10 UI Components/dxVectorMap/1 Configuration/layers/selectionMode.md
  api-reference/10 UI Components/dxVectorMap/1 Configuration/onSelectionChanged.md
Labels: cherry-pick, 24_2

#7823 VectorMap: Add selection notes (#7819)
  api-reference/10 UI Components/dxVectorMap/1 Configuration/layers/selectionMode.md
  api-reference/10 UI Components/dxVectorMap/1 Configuration/onSelectionChanged.md
Labels: cherry-pick, 25_2

#7820 DataGrid: Update Get Current Cell Values how to (#7818)
  concepts/05 UI Components/DataGrid/20 Editing/20 API/40 Get Current Cell Values.md
Labels: cherry-pick, 24_2

#7827 Chat: add Integrate with AI Service (#7737)
  concepts/05 UI Components/Chat/15 Integrate with AI Service/00 Integrate with AI Service.md
  concepts/05 UI Components/Chat/15 Integrate with AI Service/05 OpenAI/00 OpenAI.md
  concepts/05 UI Components/Chat/15 Integrate with AI Service/05 OpenAI/05 Prerequisites and Installation.md
  concepts/05 UI Components/Chat/15 Integrate with AI Service/05 OpenAI/10 AI Configuration.md
  concepts/05 UI Components/Chat/15 Integrate with AI Service/05 OpenAI/15 Chat Configuration.md
Labels: cherry-pick, 24_2

#7828 Chat: add Integrate with AI Service (#7737)
  concepts/05 UI Components/Chat/15 Integrate with AI Service/00 Integrate with AI Service.md
  concepts/05 UI Components/Chat/15 Integrate with AI Service/05 OpenAI/00 OpenAI.md
  concepts/05 UI Components/Chat/15 Integrate with AI Service/05 OpenAI/05 Prerequisites and Installation.md
  concepts/05 UI Components/Chat/15 Integrate with AI Service/05 OpenAI/10 AI Configuration.md
  concepts/05 UI Components/Chat/15 Integrate with AI Service/05 OpenAI/15 Chat Configuration.md
Labels: cherry-pick, 25_2

#7833 TagBox/SelectBox: Update onCustomItemCreating (#7825)
  api-reference/10 UI Components/dxSelectBox/1 Configuration/onCustomItemCreating.md
  api-reference/10 UI Components/dxTagBox/1 Configuration/onCustomItemCreating.md
Labels: cherry-pick, 25_2

#7829 TreeList: Update expandedRowKeys & autoExpandAll (#7826)
  api-reference/10 UI Components/dxTreeList/1 Configuration/autoExpandAll.md
  api-reference/10 UI Components/dxTreeList/1 Configuration/expandedRowKeys.md
Labels: cherry-pick, 24_2

#7837 Validator: Update CompareRule (#7834)
  api-reference/10 UI Components/dxValidator/8 Validation Rules/CompareRule/CompareRule.md
Labels: cherry-pick, 24_2

#7831 Tooltip: Add Getting Started
  applications/GettingStartedWith/Tooltip/index.css
  applications/GettingStartedWith/Tooltip/index.html
  applications/GettingStartedWith/Tooltip/index.js
  concepts/05 UI Components/Tooltip/02 Getting Started with Tooltip/00 Getting Started with Tooltip.md
  concepts/05 UI Components/Tooltip/02 Getting Started with Tooltip/05 Create and Configure Tooltip.md
  concepts/05 UI Components/Tooltip/02 Getting Started with Tooltip/10 Customize Tooltip.md
Labels: 25_1

#7844 Tooltip: Add Getting Started (#7831)
  applications/GettingStartedWith/Tooltip/index.css
  applications/GettingStartedWith/Tooltip/index.html
  applications/GettingStartedWith/Tooltip/index.js
  concepts/05 UI Components/Tooltip/02 Getting Started with Tooltip/00 Getting Started with Tooltip.md
  concepts/05 UI Components/Tooltip/02 Getting Started with Tooltip/05 Create and Configure Tooltip.md
  concepts/05 UI Components/Tooltip/02 Getting Started with Tooltip/10 Customize Tooltip.md
Labels: cherry-pick, 25_2

#7845 Chart: Update axis label.textOverflow
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/textOverflow.md
Labels: 25_1

#7847 Chart: Update axis label.textOverflow (#7845)
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/textOverflow.md
Labels: cherry-pick, 25_2

#7858 Grids: Update rowDragging dropFeedbackMode (#7852)
  api-reference/10 UI Components/GridBase/1 Configuration/rowDragging/dropFeedbackMode.md
Labels: cherry-pick, 25_2

#7860 DataGrid: Update remoteOperations (#7851)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/remoteOperations/remoteOperations.md
Labels: cherry-pick, 24_2

#7866 Form: Add onFieldDataChanged note
  api-reference/10 UI Components/dxForm/1 Configuration/onFieldDataChanged.md
Labels: 25_1

#7859 FileUploader: Update Customize how to
  applications/UIWidgets/FileUploader/Customization/index.css
  applications/UIWidgets/FileUploader/Customization/index.html
  applications/UIWidgets/FileUploader/Customization/index.js
  concepts/05 UI Components/FileUploader/50 Customize FileUploader.md
Labels: 25_1

#7868 Menu: Add onItemRendered note
  api-reference/10 UI Components/dxMenu/1 Configuration/onItemRendered.md
Labels: 25_1

#7881 Chat: Fix Editing Messages with Functions snippet
  concepts/05 UI Components/Chat/30 Editing Messages with Functions.md
Labels: 25_1

#7873 TreeList: Update loadDescendants() descriptions (#7863)
  api-reference/10 UI Components/dxTreeList/3 Methods/loadDescendants().md
  api-reference/10 UI Components/dxTreeList/3 Methods/loadDescendants(keys).md
  api-reference/10 UI Components/dxTreeList/3 Methods/loadDescendants(keys_childrenOnly).md
Labels: cherry-pick, 24_2

#7874 TreeList: Update loadDescendants() descriptions (#7863)
  api-reference/10 UI Components/dxTreeList/3 Methods/loadDescendants().md
  api-reference/10 UI Components/dxTreeList/3 Methods/loadDescendants(keys).md
  api-reference/10 UI Components/dxTreeList/3 Methods/loadDescendants(keys_childrenOnly).md
Labels: cherry-pick, 25_2

#7876 FileUploader: Update Customize how to (#7859)
  applications/UIWidgets/FileUploader/Customization/index.css
  applications/UIWidgets/FileUploader/Customization/index.html
  applications/UIWidgets/FileUploader/Customization/index.js
  concepts/05 UI Components/FileUploader/50 Customize FileUploader.md
Labels: cherry-pick, 25_2

#7880 Scheduler: Update appointmentCollectorTemplate (#7877)
  api-reference/10 UI Components/dxScheduler/1 Configuration/appointmentCollectorTemplate.md
Labels: cherry-pick, 25_2

#7882 Chat: Fix Editing Messages with Functions snippet (#7881)
  concepts/05 UI Components/Chat/30 Editing Messages with Functions.md
Labels: cherry-pick, 25_2

#7878 Menu: Add onItemRendered note (#7868)
  api-reference/10 UI Components/dxMenu/1 Configuration/onItemRendered.md
Labels: cherry-pick, 24_2

#7886 React Components: Update Uncontrolled Mode
  concepts/50 React Components/20 State Management/7 Uncontrolled Mode.md
Labels: 25_1

#7890 Diagram: Fix links in Data Binding
  concepts/05 UI Components/Diagram/10 Data Binding/35 Diagram Layout.md
Labels: 25_1

#7893 Editors: Add notes about onInput validation (#7867)
  api-reference/10 UI Components/dxDateBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxTextArea/1 Configuration/onInput.md
  api-reference/10 UI Components/dxTextArea/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxTextBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxTextBox/1 Configuration/onValueChanged.md
  includes/editors-oninput-validation-note.md
  includes/editors-onvaluechanged-validation-note.md
Labels: cherry-pick, 24_2

#7894 Editors: Add notes about onInput validation (#7867)
  api-reference/10 UI Components/dxDateBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxDateBox/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxDateRangeBox/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxDropDownBox/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxNumberBox/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxTextArea/1 Configuration/onInput.md
  api-reference/10 UI Components/dxTextArea/1 Configuration/onValueChanged.md
  api-reference/10 UI Components/dxTextBox/1 Configuration/onInput.md
  api-reference/10 UI Components/dxTextBox/1 Configuration/onValueChanged.md
  includes/editors-oninput-validation-note.md
  includes/editors-onvaluechanged-validation-note.md
Labels: cherry-pick, 25_2

#7889 React Components: Update Uncontrolled Mode (#7886)
  concepts/50 React Components/20 State Management/7 Uncontrolled Mode.md
Labels: cherry-pick, 25_2

#7892 Diagram: Fix links in Data Binding (#7890)
  concepts/05 UI Components/Diagram/10 Data Binding/35 Diagram Layout.md
Labels: cherry-pick, 25_2

#7888 React Components: Update Uncontrolled Mode (#7886)
  concepts/50 React Components/20 State Management/7 Uncontrolled Mode.md
Labels: cherry-pick, 24_2

#7897 Remove DOMComponentOptions.bindingOptions
  api-reference/_hidden/bindingOptions.md
Labels: cherry-pick, 25_1

#7904 Gantt: Add minor Getting Started update
  concepts/05 UI Components/Gantt/00 Getting Started with Gantt/30 Add Columns to the Gantt.md
Labels: 25_1

#7907 Grids: Add W1028 error description
  api-reference/10 UI Components/Errors and Warnings/W1028.md
Labels: 25_1

#7909 Grids: Add W1028 error description (#7907)
  api-reference/10 UI Components/Errors and Warnings/W1028.md
Labels: cherry-pick, 25_2

#7919 Chat: Update emptyViewTemplate param field desc.
  api-reference/10 UI Components/dxChat/1 Configuration/emptyViewTemplate.md
Labels: 25_2

#7908 Troubleshooting: Add DevExtreme CLI New App topic
  concepts/80 Troubleshooting/03 DevExtreme CLI Issues/00 Create a New Application.md
  concepts/Common/DevExtreme CLI/20 DevExtreme Application/10 Create a New Application.md
Labels: 25_1

#7924 Add Splitter to the main component list
  applications/ComponentList/index.html
Labels: 25_1

#7912 HtmlEditor: Add identical tag merging notes
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/value.md
  concepts/05 UI Components/HtmlEditor/05 Tags and Attributes.md
  concepts/05 UI Components/HtmlEditor/90 Limitations.md
Labels: 25_1
