Repository DevExpress/devextreme-documentation, pull requests merged in 2025-01, with the labels that each got.

#6957 Application templates: fix paths
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
  concepts/50 React Components/50 Application Template/35 Add a Custom Toolbar Item.md
  concepts/55 Vue Components/50 Application Template/05 Generate a New Application.md
Labels: 24_2

#6958 Application templates: fix paths (#6957)
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
  concepts/50 React Components/50 Application Template/35 Add a Custom Toolbar Item.md
  concepts/55 Vue Components/50 Application Template/05 Generate a New Application.md
Labels: cherry-pick, 24_1

#6959 Application templates: fix paths (#6957)
  concepts/50 React Components/50 Application Template/05 Generate a New Application.md
  concepts/50 React Components/50 Application Template/35 Add a Custom Toolbar Item.md
  concepts/55 Vue Components/50 Application Template/05 Generate a New Application.md
Labels: cherry-pick, 25_1

#6961 FileManager: fix demo link
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Remote/Remote.md
Labels: 24_2

#6963 FileManager: fix demo link (#6961)
  api-reference/10 UI Components/dxFileManager/5 File System Providers/Remote/Remote.md
Labels: cherry-pick, 25_1

#6964 PivotGrid: update Integration with Chart
  .gitignore
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/10 Integration with Chart.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/15 Bind the Chart.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/20 Convert Grid Fields into Chart Series.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/30 Customize the Chart/10 Customize the Chart.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/30 Customize the Chart/20 Customize the Series.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/30 Customize the Chart/30 Customize the Value Axes and Panes.md
Labels: 24_2

#6965 PivotGrid: update Integration with Chart (#6964)
  .gitignore
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/10 Integration with Chart.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/15 Bind the Chart.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/20 Convert Grid Fields into Chart Series.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/30 Customize the Chart/10 Customize the Chart.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/30 Customize the Chart/20 Customize the Series.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/30 Customize the Chart/30 Customize the Value Axes and Panes.md
Labels: cherry-pick, 24_1

#6966 PivotGrid: update Integration with Chart (#6964)
  .gitignore
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/10 Integration with Chart.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/15 Bind the Chart.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/20 Convert Grid Fields into Chart Series.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/30 Customize the Chart/10 Customize the Chart.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/30 Customize the Chart/20 Customize the Series.md
  concepts/05 UI Components/PivotGrid/150 Integration with Chart/30 Customize the Chart/30 Customize the Value Axes and Panes.md
Labels: cherry-pick, 25_1

#6967 Toast: update 'position' table
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: 24_2

#6968 Toast: update 'position' table (#6967)
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: cherry-pick, 24_1

#6969 Toast: update 'position' table (#6967)
  api-reference/50 Common/utils/ui/notify(message_stack).md
  api-reference/50 Common/utils/ui/notify(options_stack).md
Labels: cherry-pick, 25_1

#6973 CI: setup dotnet 6, update external actions
  .github/workflows/nodejs.yml
Labels: cherry-pick, 24_2

#6970 Angular: add info about standalone and directives
  concepts/40 Angular Components/20 Component Configuration Syntax/90 Using Directives.md
  includes/ng-import-devextreme-modules.md
Labels: 24_2

#6974 Angular: add info about standalone and directives (#6970)
  concepts/40 Angular Components/20 Component Configuration Syntax/90 Using Directives.md
  includes/ng-import-devextreme-modules.md
Labels: cherry-pick, 24_1

#6975 Angular: add info about standalone and directives (#6970)
  concepts/40 Angular Components/20 Component Configuration Syntax/90 Using Directives.md
  includes/ng-import-devextreme-modules.md
Labels: cherry-pick, 25_1

#6977 CI: Setup dotnet 6 in docgen
  .github/workflows/docgen.yml
Labels: 25_1

#6979 ThemeBuilder: remove mentions of Bootstrap < 5
  concepts/60 Themes and Styles/08 ThemeBuilder/01 Get Started/7 Import an Existing Theme.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/10 Command-Line Arguments.md
Labels: 24_2

#6980 Update component count on main pages
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
Labels: 24_2

#6981 ThemeBuilder: remove mentions of Bootstrap < 5 (#6979)
  concepts/60 Themes and Styles/08 ThemeBuilder/01 Get Started/7 Import an Existing Theme.md
  concepts/Common/DevExtreme CLI/50 ThemeBuilder/10 Command-Line Arguments.md
Labels: cherry-pick, 25_1

#6982 Update component count on main pages (#6980)
  concepts/40 Angular Components/00 DevExtreme Angular Components.md
  concepts/50 React Components/00 DevExtreme React Components.md
  concepts/55 Vue Components/00 DevExtreme Vue Components.md
  concepts/58 jQuery Components/00 DevExtreme jQuery Components.md
Labels: cherry-pick, 25_1

#6983 Grids: add a note about filtering and data type
  api-reference/_hidden/GridBaseColumn/filterOperations.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/1 Filter Row.md
Labels: 24_2

#6987 Grids: add a note about filtering and data type (#6983)
  api-reference/_hidden/GridBaseColumn/filterOperations.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/1 Filter Row.md
Labels: cherry-pick, 24_1

#6988 Grids: add a note about filtering and data type (#6983)
  api-reference/_hidden/GridBaseColumn/filterOperations.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/1 Filter Row.md
Labels: cherry-pick, 25_1

#6984 Tabs: update items
  api-reference/10 UI Components/dxTabs/1 Configuration/items/items.md
Labels: 24_2

#6990 Tabs: update items (#6984)
  api-reference/10 UI Components/dxTabs/1 Configuration/items/items.md
Labels: cherry-pick, 25_1

#6985 Angular Templates: add info about ng-content
  concepts/40 Angular Components/20 Component Configuration Syntax/37 Templates/37 Templates.md
Labels: 24_2

#6992 Angular Templates: add info about ng-content (#6985)
  concepts/40 Angular Components/20 Component Configuration Syntax/37 Templates/37 Templates.md
Labels: cherry-pick, 25_1

#6986 Grids: update 'changes' in onSaved/onSaving
  api-reference/10 UI Components/GridBase/1 Configuration/onSaved.md
  api-reference/10 UI Components/GridBase/1 Configuration/onSaving.md
Labels: 24_2

#6993 Grids: update 'changes' in onSaved/onSaving (#6986)
  api-reference/10 UI Components/GridBase/1 Configuration/onSaved.md
  api-reference/10 UI Components/GridBase/1 Configuration/onSaving.md
Labels: cherry-pick, 24_1

#6994 Grids: update 'changes' in onSaved/onSaving (#6986)
  api-reference/10 UI Components/GridBase/1 Configuration/onSaved.md
  api-reference/10 UI Components/GridBase/1 Configuration/onSaving.md
Labels: cherry-pick, 25_1

#6996 CI: improve DocGen scheduler
  .github/workflows/docgen-scheduler.yml
Labels: 25_1

#6997 CI: improve DocGen
  .github/workflows/docgen.yml
Labels: 25_1

#6998 CI: improve DocGen
  .github/workflows/docgen.yml
Labels: cherry-pick, 24_2

#7003 CI: Improve DocGen
  .github/workflows/docgen.yml
Labels: cherry-pick, 24_1

#6978 Data Layer section overhaul
  concepts/70 Data Binding/5 Data Layer/0 Overview.md
  concepts/70 Data Binding/5 Data Layer/05 Asynchrony.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/0 From Array.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/1 From url.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/2 From Store.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/Creating DataSource.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/0 Paging.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/1 Sorting.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/0 Binary Filter Operations.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/05 Unary Filter Operation.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/1 Group Filter Operations.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/2 Custom Filter Conditions.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/Filtering.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/2 Search Api.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/3 Data Transformation/0 Select Expressions.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/3 Data Transformation/1 Item Mapping.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/3 Data Transformation/2 Post Processing.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/3 Data Transformation/Data Transformation.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/4 Grouping.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/Reading Data.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/0 Data Modification.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/0 Insertion.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/05 Insertion.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/1 Update.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/2 Removing.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/3 Data Modification.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/30 Integration with Push Services.md
  concepts/70 Data Binding/5 Data Layer/9 Getters And Setters/0 Creating Getters And Setters.md
  concepts/70 Data Binding/5 Data Layer/9 Getters And Setters/1 Getter And Setter Calling Options.md
  concepts/70 Data Binding/5 Data Layer/9 Getters And Setters/Getters And Setters.md
Labels: 24_2

#7005 Data Layer section overhaul (#6978)
  concepts/70 Data Binding/5 Data Layer/0 Overview.md
  concepts/70 Data Binding/5 Data Layer/05 Asynchrony.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/0 From Array.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/1 From url.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/2 From Store.md
  concepts/70 Data Binding/5 Data Layer/1 Creating DataSource/Creating DataSource.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/0 Paging.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/1 Sorting.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/0 Binary Filter Operations.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/05 Unary Filter Operation.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/1 Group Filter Operations.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/2 Custom Filter Conditions.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/15 Filtering/Filtering.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/2 Search Api.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/3 Data Transformation/0 Select Expressions.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/3 Data Transformation/1 Item Mapping.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/3 Data Transformation/2 Post Processing.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/3 Data Transformation/Data Transformation.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/4 Grouping.md
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/Reading Data.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/0 Data Modification.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/0 Insertion.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/05 Insertion.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/1 Update.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/2 Removing.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/3 Data Modification.md
  concepts/70 Data Binding/5 Data Layer/3 Data Modification/30 Integration with Push Services.md
  concepts/70 Data Binding/5 Data Layer/9 Getters And Setters/0 Creating Getters And Setters.md
  concepts/70 Data Binding/5 Data Layer/9 Getters And Setters/1 Getter And Setter Calling Options.md
  concepts/70 Data Binding/5 Data Layer/9 Getters And Setters/Getters And Setters.md
Labels: cherry-pick, 25_1

#6976 Validator Event Handlers Types (T1269388)
  api-reference/10 UI Components/dxValidationGroup/9 Validation Result/Validation Result.md
  api-reference/10 UI Components/dxValidator/1 Configuration/onDisposing.md
  api-reference/10 UI Components/dxValidator/1 Configuration/onInitialized.md
  api-reference/10 UI Components/dxValidator/1 Configuration/onOptionChanged.md
  api-reference/10 UI Components/dxValidator/1 Configuration/onValidated.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/AsyncRule/AsyncRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/CompareRule/CompareRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/CustomRule/CustomRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/EmailRule/EmailRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/NumericRule/NumericRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/PatternRule/PatternRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/RangeRule/RangeRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/RequiredRule/RequiredRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/StringLengthRule/StringLengthRule.md
  api-reference/10 UI Components/dxValidator/9 Validation Result/Validation Result.md
  api-reference/10 UI Components/dxValidator/99 Types/DisposingEvent/DisposingEvent.md
  api-reference/10 UI Components/dxValidator/99 Types/InitializedEvent/InitializedEvent.md
  api-reference/10 UI Components/dxValidator/99 Types/OptionChangedEvent/OptionChangedEvent.md
  api-reference/10 UI Components/dxValidator/99 Types/Types.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/ValidatedEvent.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/brokenRule.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/brokenRules.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/isValid.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/name.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/status.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/validationRules.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/value.md
  api-reference/40 Common Types/ValidationRule.md
  api-reference/40 Common Types/ValidationStatus.md
  metadata/syntax-data.json
Labels: 24_2

#7008 Validator Event Handlers Types (T1269388)
  api-reference/10 UI Components/dxValidationGroup/9 Validation Result/Validation Result.md
  api-reference/10 UI Components/dxValidator/1 Configuration/onDisposing.md
  api-reference/10 UI Components/dxValidator/1 Configuration/onInitialized.md
  api-reference/10 UI Components/dxValidator/1 Configuration/onOptionChanged.md
  api-reference/10 UI Components/dxValidator/1 Configuration/onValidated.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/AsyncRule/AsyncRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/CompareRule/CompareRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/CustomRule/CustomRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/EmailRule/EmailRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/NumericRule/NumericRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/PatternRule/PatternRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/RangeRule/RangeRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/RequiredRule/RequiredRule.md
  api-reference/10 UI Components/dxValidator/8 Validation Rules/StringLengthRule/StringLengthRule.md
  api-reference/10 UI Components/dxValidator/9 Validation Result/Validation Result.md
  api-reference/10 UI Components/dxValidator/99 Types/DisposingEvent/DisposingEvent.md
  api-reference/10 UI Components/dxValidator/99 Types/InitializedEvent/InitializedEvent.md
  api-reference/10 UI Components/dxValidator/99 Types/OptionChangedEvent/OptionChangedEvent.md
  api-reference/10 UI Components/dxValidator/99 Types/Types.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/ValidatedEvent.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/brokenRule.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/brokenRules.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/isValid.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/name.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/status.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/validationRules.md
  api-reference/10 UI Components/dxValidator/99 Types/ValidatedEvent/value.md
  api-reference/40 Common Types/ValidationRule.md
  api-reference/40 Common Types/ValidationStatus.md
  metadata/syntax-data.json
Labels: cherry-pick, 25_1

#7009 List: update showSelectionControls
  api-reference/10 UI Components/dxList/1 Configuration/showSelectionControls.md
Labels: 24_2

#7010 List: update showSelectionControls (#7009)
  api-reference/10 UI Components/dxList/1 Configuration/showSelectionControls.md
Labels: cherry-pick, 24_1

#7011 List: update showSelectionControls (#7009)
  api-reference/10 UI Components/dxList/1 Configuration/showSelectionControls.md
Labels: cherry-pick, 25_1

#7014 CI: setup dotnet 6 in DocGen
  .github/workflows/docgen.yml
Labels: 24_1

#7015 FileUploader: add code to onValueChanged
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onUploaded.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onValueChanged.md
Labels: 24_2

#7018 FileUploader: add code to onValueChanged (#7015)
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onUploaded.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onValueChanged.md
Labels: cherry-pick, 24_1

#7019 FileUploader: add code to onValueChanged (#7015)
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onUploaded.md
  api-reference/10 UI Components/dxFileUploader/1 Configuration/onValueChanged.md
Labels: cherry-pick, 25_1

#7020 Rename HTML Editor
  api-reference/10 UI Components/Errors and Warnings/W1016.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/converter.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/customizeModules.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/stylingMode.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/toolbar/toolbar.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/value.md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/Methods.md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/get(componentPath).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getLength().md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getText(index_length).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/insertText(index_text_formatName_formatValue).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/register(components).md
  api-reference/10 UI Components/dxHtmlEditor/4 Events/Events.md
  api-reference/10 UI Components/dxHtmlEditor/9 Types/Converter/fromHtml.md
  api-reference/10 UI Components/dxHtmlEditor/9 Types/Converter/toHtml.md
  api-reference/10 UI Components/dxHtmlEditor/9 Types/HtmlEditorImageUploadMode.md
  api-reference/10 UI Components/dxHtmlEditor/dxHtmlEditor.md
  api-reference/_hidden/dxHtmlEditorImageUpload/fileUploadMode.md
  api-reference/_hidden/dxHtmlEditorTableContextMenu/dxHtmlEditorTableContextMenu.md
  applications/GettingStartedWith/HtmlEditor/index.html
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/02 Create an HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/10 Set the Initial Value.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/30 Work with Tables.md
  concepts/05 UI Components/HtmlEditor/02 Overview/00 Overview.md
  concepts/40 Angular Components/20 Component Configuration Syntax/36 Declare Content in the Markup.md
  concepts/50 React Components/40 Component Configuration Syntax/45 Declare Content in the Markup.md
  concepts/55 Vue Components/20 Component Configuration Syntax/36 Declare Content in the Markup.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
  concepts/Common/Accessibility/05 Documentation for Components.md
  concepts/Common/Distribution Channels/05 CDN/05 CDN.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/1 Deprecated Properties and Methods.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/ui/html_editor.md
  concepts/Common/Security Considerations/20 HTML Encoding/10 Encode User Input.md
Labels: 24_2

#7022 Rename HTML Editor (#7020)
  api-reference/10 UI Components/Errors and Warnings/W1016.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/customizeModules.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/stylingMode.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/toolbar/toolbar.md
  api-reference/10 UI Components/dxHtmlEditor/1 Configuration/value.md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/Methods.md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/get(componentPath).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getLength().md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/getText(index_length).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/insertText(index_text_formatName_formatValue).md
  api-reference/10 UI Components/dxHtmlEditor/3 Methods/register(components).md
  api-reference/10 UI Components/dxHtmlEditor/4 Events/Events.md
  api-reference/10 UI Components/dxHtmlEditor/9 Types/HtmlEditorImageUploadMode.md
  api-reference/10 UI Components/dxHtmlEditor/dxHtmlEditor.md
  api-reference/_hidden/dxHtmlEditorImageUpload/fileUploadMode.md
  api-reference/_hidden/dxHtmlEditorTableContextMenu/dxHtmlEditorTableContextMenu.md
  applications/GettingStartedWith/HtmlEditor/index.html
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/02 Create an HtmlEditor.md
  concepts/05 UI Components/HtmlEditor/00 Getting Started with HtmlEditor/30 Work with Tables.md
  concepts/40 Angular Components/20 Component Configuration Syntax/36 Declare Content in the Markup.md
  concepts/50 React Components/40 Component Configuration Syntax/45 Declare Content in the Markup.md
  concepts/55 Vue Components/20 Component Configuration Syntax/36 Declare Content in the Markup.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/05 CDN Files.md
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
  concepts/Common/Accessibility/05 Documentation for Components.md
  concepts/Common/Distribution Channels/05 CDN/05 CDN.md
  concepts/Common/Migrate to the New Version/50 Learn Breaking Changes and Deprecated API/1 Deprecated Properties and Methods.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/ui/html_editor.md
  concepts/Common/Security Considerations/20 HTML Encoding/10 Encode User Input.md
Labels: cherry-pick, 24_1
