Repository DevExpress/devextreme-documentation, pull requests merged in 2025-02, with the labels that each got.

#7028 CI: Update actions to v4
  .github/workflows/codeql-analysis.yml
  .github/workflows/nodejs.yml
Labels: 25_1

#7030 CI: Update actions to v4
  .github/workflows/codeql-analysis.yml
  .github/workflows/docgen.yml
  .github/workflows/nodejs.yml
Labels: 24_2

#7027 PivotGrid: add Export section
  concepts/05 UI Components/PivotGrid/090 Export/00 Export.md
  concepts/05 UI Components/PivotGrid/090 Export/05 Install Dependencies.md
  concepts/05 UI Components/PivotGrid/090 Export/10 Enable the Export Button.md
  concepts/05 UI Components/PivotGrid/090 Export/15 Export to XLSX.md
  concepts/05 UI Components/PivotGrid/090 Export/20 Export to CSV.md
  concepts/05 UI Components/PivotGrid/090 Export/25 Export Field Panel.md
  concepts/05 UI Components/PivotGrid/090 Export/30 Customize Cells.md
Labels: 24_2

#7032 PivotGrid: add Export section (#7027)
  concepts/05 UI Components/PivotGrid/090 Export/00 Export.md
  concepts/05 UI Components/PivotGrid/090 Export/05 Install Dependencies.md
  concepts/05 UI Components/PivotGrid/090 Export/10 Enable the Export Button.md
  concepts/05 UI Components/PivotGrid/090 Export/15 Export to XLSX.md
  concepts/05 UI Components/PivotGrid/090 Export/20 Export to CSV.md
  concepts/05 UI Components/PivotGrid/090 Export/25 Export Field Panel.md
  concepts/05 UI Components/PivotGrid/090 Export/30 Customize Cells.md
Labels: cherry-pick, 25_1

#7031 CI: Update actions to v4
  .github/workflows/codeql-analysis.yml
  .github/workflows/nodejs.yml
Labels: cherry-pick, 24_1

#7035 PivotGrid: add Export section (#7027)
  concepts/05 UI Components/PivotGrid/090 Export/00 Export.md
  concepts/05 UI Components/PivotGrid/090 Export/05 Install Dependencies.md
  concepts/05 UI Components/PivotGrid/090 Export/10 Enable the Export Button.md
  concepts/05 UI Components/PivotGrid/090 Export/15 Export to XLSX.md
  concepts/05 UI Components/PivotGrid/090 Export/20 Export to CSV.md
  concepts/05 UI Components/PivotGrid/090 Export/25 Export Field Panel.md
  concepts/05 UI Components/PivotGrid/090 Export/30 Customize Cells.md
Labels: cherry-pick, 24_1

#7036 HTML Editor: add a copy-paste image limitation
  concepts/05 UI Components/HtmlEditor/90 Limitations.md
Labels: 24_2

#7037 HTML Editor: add a copy-paste image limitation
  concepts/05 UI Components/HtmlEditor/90 Limitations.md
Labels: cherry-pick, 24_1

#7038 HTML Editor: add a copy-paste image limitation (#7036)
  concepts/05 UI Components/HtmlEditor/90 Limitations.md
Labels: cherry-pick, 25_1

#7039 App Templates: add info about theme switching (#7029)
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/20 Create a Custom Theme.md
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/30 Apply a Color Swatch.md
  concepts/40 Angular Components/30 Application Template/40 Configure Themes/40 Apply Theme Variables to Custom Elements.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/20 Create a Custom Theme.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/30 Apply a Color Swatch.md
  concepts/50 React Components/50 Application Template/40 Configure Themes/40 Apply Theme Variables to Custom Elements.md
  concepts/55 Vue Components/50 Application Template/40 Configure Themes/10 Switch the Theme.md
  concepts/55 Vue Components/50 Application Template/40 Configure Themes/20 Create a Custom Theme.md
  concepts/55 Vue Components/50 Application Template/40 Configure Themes/30 Apply a Color Swatch.md
  concepts/55 Vue Components/50 Application Template/40 Configure Themes/40 Apply Theme Variables to Custom Elements.md
Labels: cherry-pick, 25_1

#7043 DataGrid: update Customize the Appearance
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/Customize Cells.md
  concepts/05 UI Components/DataGrid/20 Editing/40 Customize Editors.md
  concepts/05 UI Components/DataGrid/67 Customize the Appearance.md
Labels: 24_2

#7045 DataGrid: update Customize the Appearance (#7043)
  concepts/05 UI Components/DataGrid/15 Columns/40 Customize Cells/Customize Cells.md
  concepts/05 UI Components/DataGrid/20 Editing/40 Customize Editors.md
  concepts/05 UI Components/DataGrid/67 Customize the Appearance.md
Labels: cherry-pick, 25_1

#7050 NumberBox: update format
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
Labels: 24_2

#7052 NumberBox: update format (#7050)
  api-reference/10 UI Components/dxNumberBox/1 Configuration/format.md
Labels: cherry-pick, 25_1

#7049 Chat: add Markdown Support topic
  MenuConfig.xml
  concepts/05 UI Components/Chat/13 Markdown Support.md
Labels: 24_2

#7053 Chat: add Markdown Support topic (#7049)
  MenuConfig.xml
  concepts/05 UI Components/Chat/13 Markdown Support.md
Labels: cherry-pick, 25_1

#7057 Add a note about `dx-viewport`
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/03 Configure Stylesheets.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/40 Import Stylesheets.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/40 Import Stylesheets.md
Labels: 24_2

#7059 Add a note about `dx-viewport` (#7057)
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/03 Configure Stylesheets.md
  concepts/50 React Components/05 Add DevExtreme to a React Application/40 Import Stylesheets.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/40 Import Stylesheets.md
Labels: cherry-pick, 25_1

#7061 Data Binding: update code in Search API
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/2 Search Api.md
Labels: 24_2

#7062 Data Binding: update code in Search API (#7061)
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/2 Search Api.md
Labels: cherry-pick, 24_1

#7063 Data Binding: update code in Search API (#7061)
  concepts/70 Data Binding/5 Data Layer/2 Reading Data/2 Search Api.md
Labels: cherry-pick, 25_1

#7060 DataGrid: update Map Data Source Fields
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
Labels: 24_2

#7064 DataGrid: update Map Data Source Fields (#7060)
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
Labels: cherry-pick, 24_1

#7065 DataGrid: update Map Data Source Fields (#7060)
  concepts/05 UI Components/DataGrid/99 How To/Customize Header Filter Data Source/20 Map Data Source Fields.md
Labels: cherry-pick, 25_1

#7066 List: update Keyboard Navigation
  concepts/05 UI Components/List/03 Accessibility/15 Keyboard Navigation.md
Labels: 24_2

#7067 List: update Keyboard Navigation (#7066)
  concepts/05 UI Components/List/03 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 24_1

#7068 List: update Keyboard Navigation (#7066)
  concepts/05 UI Components/List/03 Accessibility/15 Keyboard Navigation.md
Labels: cherry-pick, 25_1

#7069 Form: remove colSpan from tabs
  concepts/05 UI Components/Form/10 Organize Simple Items/10 In Tabs/05 Columns within a Tab.md
Labels: 24_2

#7070 Form: remove colSpan from tabs (#7069)
  concepts/05 UI Components/Form/10 Organize Simple Items/10 In Tabs/05 Columns within a Tab.md
Labels: cherry-pick, 24_1

#7071 Form: remove colSpan from tabs (#7069)
  concepts/05 UI Components/Form/10 Organize Simple Items/10 In Tabs/05 Columns within a Tab.md
Labels: cherry-pick, 25_1

#7076 CI: Update actions to v4
  .github/workflows/codeql-analysis.yml
  .github/workflows/docgen.yml
  .github/workflows/nodejs.yml
Labels: cherry-pick, 23_2

#7077 CI: Update actions to v4
  .github/workflows/codeql-analysis.yml
  .github/workflows/docgen.yml
  .github/workflows/nodejs.yml
Labels: cherry-pick, 23_1

#7080 Popup, Popover, Tooltip: update Vue templates
  concepts/05 UI Components/Popover/00 Overview.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/20 Specify Toolbar Items.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/30 Color the Shading of the Background.md
  concepts/05 UI Components/Popover/10 Show and Hide the Popover/01 User Interaction.md
  concepts/05 UI Components/Popover/10 Show and Hide the Popover/05 API.md
  concepts/05 UI Components/Popover/15 Resize and Relocate.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/10 Customize the Title.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/20 Specify Toolbar Items.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/30 Color the Shading of the Background.md
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/01 API.md
  concepts/05 UI Components/TagBox/12 Limit the Tag Count/10 Selected Tags.md
  concepts/05 UI Components/Tooltip/00 Overview.md
  concepts/05 UI Components/Tooltip/05 Show and Hide the Tooltip/01 User Interaction.md
  concepts/05 UI Components/Tooltip/05 Show and Hide the Tooltip/05 API.md
  concepts/05 UI Components/Tooltip/10 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Tooltip/15 Resize and Relocate.md
Labels: 24_2

#7081 Popup, Popover, Tooltip: update Vue templates (#7080)
  concepts/05 UI Components/Popover/00 Overview.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/20 Specify Toolbar Items.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/30 Color the Shading of the Background.md
  concepts/05 UI Components/Popover/10 Show and Hide the Popover/01 User Interaction.md
  concepts/05 UI Components/Popover/10 Show and Hide the Popover/05 API.md
  concepts/05 UI Components/Popover/15 Resize and Relocate.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/10 Customize the Title.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/20 Specify Toolbar Items.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/30 Color the Shading of the Background.md
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/01 API.md
  concepts/05 UI Components/TagBox/12 Limit the Tag Count/10 Selected Tags.md
  concepts/05 UI Components/Tooltip/00 Overview.md
  concepts/05 UI Components/Tooltip/05 Show and Hide the Tooltip/01 User Interaction.md
  concepts/05 UI Components/Tooltip/05 Show and Hide the Tooltip/05 API.md
  concepts/05 UI Components/Tooltip/10 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Tooltip/15 Resize and Relocate.md
Labels: cherry-pick, 24_1

#7082 Popup, Popover, Tooltip: update Vue templates (#7080)
  concepts/05 UI Components/Popover/00 Overview.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/20 Specify Toolbar Items.md
  concepts/05 UI Components/Popover/05 Customize the Appearance/30 Color the Shading of the Background.md
  concepts/05 UI Components/Popover/10 Show and Hide the Popover/01 User Interaction.md
  concepts/05 UI Components/Popover/10 Show and Hide the Popover/05 API.md
  concepts/05 UI Components/Popover/15 Resize and Relocate.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/05 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/10 Customize the Title.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/20 Specify Toolbar Items.md
  concepts/05 UI Components/Popup/05 Customize the Appearance/30 Color the Shading of the Background.md
  concepts/05 UI Components/Popup/10 Show and Hide the Popup/01 API.md
  concepts/05 UI Components/TagBox/12 Limit the Tag Count/10 Selected Tags.md
  concepts/05 UI Components/Tooltip/00 Overview.md
  concepts/05 UI Components/Tooltip/05 Show and Hide the Tooltip/01 User Interaction.md
  concepts/05 UI Components/Tooltip/05 Show and Hide the Tooltip/05 API.md
  concepts/05 UI Components/Tooltip/10 Customize the Content/1 Specifying the Content Template.md
  concepts/05 UI Components/Tooltip/15 Resize and Relocate.md
Labels: cherry-pick, 25_1

#7083 Angular: update Use Signals article
  concepts/40 Angular Components/40 Common Features/20 Using Angular Signals with DevExtreme.md
Labels: 24_2

#7084 Angular: update Use Signals article (#7083)
  concepts/40 Angular Components/40 Common Features/20 Using Angular Signals with DevExtreme.md
Labels: cherry-pick, 24_1

#7085 Angular: update Use Signals article (#7083)
  concepts/40 Angular Components/40 Common Features/20 Using Angular Signals with DevExtreme.md
Labels: cherry-pick, 25_1

#7087 Chat: add Popup Integration topic
  concepts/05 UI Components/Chat/20 Popup Integration.md
Labels: 24_2

#7089 Chat: add Popup Integration topic (#7087)
  concepts/05 UI Components/Chat/20 Popup Integration.md
Labels: cherry-pick, 25_1

#7094 jQuery: update Local Files
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
Labels: 24_2

#7095 jQuery: update Local Files (#7094)
  concepts/58 jQuery Components/05 Add DevExtreme to a jQuery Application/10 Local Files.md
Labels: cherry-pick, 24_1

#7093 Map: describe location
  api-reference/10 UI Components/dxMap/1 Configuration/onClick.md
  api-reference/10 UI Components/dxMap/9 Types/ClickEvent/location.md
  api-reference/10 UI Components/dxMap/9 Types/MapLocation/MapLocation.md
Labels: 25_1
