Repository DevExpress/devextreme-documentation, pull requests merged in 2025-06, with the labels that each got.

#7385 Stepper: add Read-Only Stepper How To topic
  MenuConfig.xml
  concepts/05 UI Components/Stepper/15 Configure a Read-Only Stepper.md
Labels: 25_1

#7387 Angular: Update Angular Forms Support topic
  concepts/40 Angular Components/20 Component Configuration Syntax/75 Angular Forms Support.md
Labels: 24_2

#7382 Stepper: update Overview
  concepts/05 UI Components/Stepper/00 Overview/05 Elements.md
  concepts/05 UI Components/Stepper/00 Overview/10 Key Features.md
  images/Stepper/stepper-elements.png
Labels: 25_1

#7391 Validator: add multiple messages code snippet
  api-reference/10 UI Components/dxValidator/8 Validation Rules/CustomRule/validationCallback.md
Labels: 24_2

#7400 Validator: add multiple messages code snippet (#7391)
  api-reference/10 UI Components/dxValidator/8 Validation Rules/CustomRule/validationCallback.md
Labels: cherry-pick, 25_1

#7403 Angular TS: Update Common Types import declaration (#7402)
  concepts/Common/TypeScript Guides/05 Scopes of Types/15 Common Types.md
Labels: cherry-pick, 25_1

#7404 Tabs: Update KBN enter/space section
  concepts/05 UI Components/Tabs/05 Accessibility/15 Keyboard Navigation.md
Labels: 24_2

#7408 Troubleshooting: fix 3rd-Party Framework Issues visibility in Angular…
  concepts/80 Troubleshooting/30 3rd-Party Framework Issues/00 3rd-Party Framework Issues.md
Labels: cherry-pick, 24_1

#7410 Stepper: add Customize Connectors How To topic
  concepts/05 UI Components/Stepper/20 Customize Step Connectors.md
Labels: 25_1

#7394 CardView: describe API (part 7 - types)
  api-reference/10 UI Components/dxCardView/9 Types/ContextMenuTarget.md
  api-reference/10 UI Components/dxCardView/9 Types/FieldTemplateData/FieldTemplateData.md
  api-reference/10 UI Components/dxCardView/9 Types/FieldTemplateData/field.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewFieldInfo/card.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewFieldInfo/column.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewFieldInfo/displayValue.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewFieldInfo/dxCardViewFieldInfo.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewFieldInfo/index.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewFieldInfo/text.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewFieldInfo/value.md
Labels: 25_1

#7419 Form: add SimpleItem.dataField name limitations (#7415)
  api-reference/10 UI Components/dxForm/5 Item Types/SimpleItem/dataField.md
Labels: cherry-pick, 24_1

#7421 Icons: update topic (#7414)
  concepts/60 Themes and Styles/30 Icons/20 Icons in DevExtreme UI Components.md
  concepts/60 Themes and Styles/30 Icons/30 Icons in Other HTML Elements.md
  concepts/60 Themes and Styles/30 Icons/35 Customize Icons.md
  concepts/60 Themes and Styles/30 Icons/40 Custom Images as Icons.md
  concepts/60 Themes and Styles/30 Icons/50 External Icon Libraries.md
  concepts/60 Themes and Styles/30 Icons/60 SVG Icons.md
Labels: cherry-pick, 24_1

#7426 Add demo links for release
  api-reference/10 UI Components/dxCardView/1 Configuration/allowColumnReordering.md
  api-reference/10 UI Components/dxCardView/1 Configuration/cardFooterTemplate.md
  api-reference/10 UI Components/dxCardView/1 Configuration/cardTemplate.md
  api-reference/10 UI Components/dxCardView/1 Configuration/columnChooser.md
  api-reference/10 UI Components/dxCardView/1 Configuration/filterPanel.md
  api-reference/10 UI Components/dxCardView/1 Configuration/headerFilter.md
  api-reference/10 UI Components/dxCardView/1 Configuration/searchPanel.md
  api-reference/10 UI Components/dxCardView/1 Configuration/sorting.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/allowReordering.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/fieldTemplate.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/fieldValueTemplate.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/validationRules.md
  api-reference/10 UI Components/dxCardView/9 Types/SelectionConfiguration/SelectionConfiguration.md
  api-reference/10 UI Components/dxCardView/9 Types/SelectionConfiguration/mode.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/dxCardViewEditing.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/popup.md
  api-reference/10 UI Components/dxCardView/dxCardView.md
  api-reference/10 UI Components/dxChat/1 Configuration/editing/editing.md
  api-reference/10 UI Components/dxChat/9 Types/MessageBase/isDeleted.md
  api-reference/10 UI Components/dxChat/9 Types/TextMessage/isEdited.md
  api-reference/10 UI Components/dxScheduler/1 Configuration/toolbar.md
  api-reference/10 UI Components/dxScheduler/7 Interfaces/dxSchedulerToolbar/dxSchedulerToolbar.md
  api-reference/10 UI Components/dxStepper/1 Configuration/linear.md
  api-reference/10 UI Components/dxStepper/1 Configuration/orientation.md
  api-reference/10 UI Components/dxStepper/1 Configuration/selectOnFocus.md
  api-reference/10 UI Components/dxStepper/7 Interfaces/dxStepperItem/isValid.md
  api-reference/10 UI Components/dxStepper/dxStepper.md
Labels: 25_1

#7427 Grids: add calculateFilterExpression selector info
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: 24_2

#7428 Grids: add calculateFilterExpression selector info (#7427)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: cherry-pick, 24_1

#7429 Grids: add calculateFilterExpression selector info (#7427)
  api-reference/_hidden/GridBaseColumn/calculateFilterExpression.md
Labels: cherry-pick, 25_1

#7396 Chat: add Custom Deleted Message how-to topic
  concepts/05 UI Components/Chat/25 Custom Deleted Message.md
Labels: 25_1

#7434 PivotGridDataSource: update selector
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/selector.md
Labels: 24_2

#7436 PivotGridDataSource: update selector (#7434)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/selector.md
Labels: cherry-pick, 24_1

#7437 PivotGridDataSource: update selector (#7434)
  api-reference/30 Data Layer/PivotGridDataSource/1 Configuration/fields/selector.md
Labels: cherry-pick, 25_1

#7441 Chart: rename Color Gradients and Patterns (#7440)
  concepts/05 UI Components/Chart/02 Overview/10 Key Features.md
  concepts/05 UI Components/Chart/10 Series/60 Color Gradients and Patterns.md
Labels: cherry-pick, 24_1

#7442 Chart: rename Color Gradients and Patterns (#7440)
  concepts/05 UI Components/Chart/02 Overview/10 Key Features.md
  concepts/05 UI Components/Chart/10 Series/60 Color Gradients and Patterns.md
Labels: cherry-pick, 25_1

#7430 CardView: Add API code snippets
  api-reference/10 UI Components/dxCardView/1 Configuration/cardCover.md
  api-reference/10 UI Components/dxCardView/1 Configuration/cardFooterTemplate.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/calculateFieldValue.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/calculateFilterExpression.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/fieldValueTemplate.md
Labels: 25_1

#7443 Chat: add Editing Messages with Functions
  concepts/05 UI Components/Chat/30 Editing Messages with Functions.md
Labels: 25_1

#7438 Stepper: Add Cancel Step Change How To topic
  concepts/05 UI Components/Stepper/25 Cancel a Step Change.md
Labels: 25_1

#7449 Chart: update visualRangeUpdateMode topics
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/visualRangeUpdateMode.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/visualRangeUpdateMode.md
Labels: 24_2

#7450 Chart: update visualRangeUpdateMode topics (#7449)
  api-reference/10 UI Components/dxChart/1 Configuration/argumentAxis/visualRangeUpdateMode.md
  api-reference/10 UI Components/dxChart/1 Configuration/valueAxis/visualRangeUpdateMode.md
Labels: cherry-pick, 24_1

#7458 CardView: Add Card Elements How To topic
  MenuConfig.xml
  concepts/05 UI Components/CardView/15 Card Elements.md
  images/CardView/cardview-card-elements.png
Labels: 25_1

#7478 Remove copyRootClassesToWrapper.md (#7477)
  api-reference/10 UI Components/dxLoadPanel/1 Configuration/copyRootClassesToWrapper.md
  api-reference/10 UI Components/dxOverlay/1 Configuration/copyRootClassesToWrapper.md
  api-reference/10 UI Components/dxPopover/1 Configuration/copyRootClassesToWrapper.md
  api-reference/10 UI Components/dxPopup/1 Configuration/copyRootClassesToWrapper.md
  api-reference/10 UI Components/dxToast/1 Configuration/copyRootClassesToWrapper.md
  api-reference/10 UI Components/dxTooltip/1 Configuration/copyRootClassesToWrapper.md
Labels: cherry-pick, 24_1

#7479 Chart: Update category aggregation info (#7472)
  concepts/05 UI Components/Chart/88 Data Aggregation/05 Specify the Aggregation Interval.md
Labels: cherry-pick, 24_1

#7480 Chart: Update category aggregation info (#7472)
  concepts/05 UI Components/Chart/88 Data Aggregation/05 Specify the Aggregation Interval.md
Labels: cherry-pick, 25_1

#7474 CardView: add API code snippets (part 3)
  api-reference/10 UI Components/dxCardView/1 Configuration/cardHeader.md
  api-reference/10 UI Components/dxCardView/1 Configuration/pager.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/calculateSortValue.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/customizeText.md
  api-reference/10 UI Components/dxCardView/9 Types/ColumnProperties/setFieldValue.md
  api-reference/_hidden/GridBaseColumn/customizeText.md
Labels: 25_1

#7486 DataGrid: Update Deferred Selection notes (#7481)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/selection/deferred.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/015 Deferred Selection.md
Labels: cherry-pick, 24_1

#7487 DataGrid: Update Deferred Selection notes (#7481)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/selection/deferred.md
  concepts/05 UI Components/DataGrid/10 Enhance Performance on Large Datasets/015 Deferred Selection.md
Labels: cherry-pick, 25_1

#7491 CardView: describe scrolling and dragging API
  api-reference/10 UI Components/dxCardView/1 Configuration/scrollByThumb.md
  api-reference/10 UI Components/dxCardView/1 Configuration/scrolling/scrollByContent.md
  api-reference/10 UI Components/dxCardView/1 Configuration/scrolling/scrollByThumb.md
  api-reference/10 UI Components/dxCardView/1 Configuration/scrolling/scrolling.md
  api-reference/10 UI Components/dxCardView/1 Configuration/scrolling/showScrollbar.md
  api-reference/10 UI Components/dxCardView/1 Configuration/scrolling/useNative.md
  api-reference/10 UI Components/dxCardView/1 Configuration/useNative.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/dragging.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/dropFeedbackMode.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/onDragChange.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/onDragEnd.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/onDragMove.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/onDragStart.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/onRemove.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/onReorder.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/scrollSensitivity.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dragging/scrollSpeed.md
  api-reference/10 UI Components/dxCardView/9 Types/HeaderPanel/dropFeedbackMode.md
Labels: 25_1

#7496 CardView: Update Overview
  concepts/05 UI Components/CardView/00 Overview/00 Overview.md
  concepts/05 UI Components/CardView/00 Overview/05 Elements.md
  concepts/05 UI Components/CardView/00 Overview/10 Key Features.md
Labels: 25_1

#7500 Grids: Add Lookup dataSource function note (#7498)
  api-reference/_hidden/GridBaseColumn/lookup/dataSource.md
Labels: cherry-pick, 24_2

#7499 DateBox: Add "native" pickerType note
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: 25_1

#7501 DateBox: Add "native" pickerType note (#7499)
  api-reference/10 UI Components/dxDateBox/1 Configuration/pickerType.md
Labels: cherry-pick, 24_2

#7492 Chart: Add Enhance Performance How To topic
  concepts/05 UI Components/Chart/93 Enhance Performance on Large Datasets.md
Labels: 25_1

#7505 Chart: Add Enhance Performance How To topic (#7492)
  concepts/05 UI Components/Chart/93 Enhance Performance on Large Datasets.md
Labels: cherry-pick, 24_2

#7506 CardView Popups and Toolbars
  api-reference/10 UI Components/dxCardView/1 Configuration/filterBuilderPopup.md
  api-reference/10 UI Components/dxCardView/1 Configuration/toolbar.md
  api-reference/10 UI Components/dxCardView/9 Types/PredefinedToolbarItem.md
  api-reference/10 UI Components/dxCardView/9 Types/Toolbar/Toolbar.md
  api-reference/10 UI Components/dxCardView/9 Types/Toolbar/disabled.md
  api-reference/10 UI Components/dxCardView/9 Types/Toolbar/items.md
  api-reference/10 UI Components/dxCardView/9 Types/Toolbar/multiline.md
  api-reference/10 UI Components/dxCardView/9 Types/Toolbar/visible.md
  api-reference/10 UI Components/dxCardView/9 Types/ToolbarItem/ToolbarItem.md
  api-reference/10 UI Components/dxCardView/9 Types/ToolbarItem/location.md
  api-reference/10 UI Components/dxCardView/9 Types/ToolbarItem/name.md
  api-reference/10 UI Components/dxCardView/9 Types/dxCardViewEditing/popup.md
  api-reference/40 Common Types/ToolbarItemLocation.md
  metadata/syntax-data.json
Labels: 25_1

#7503 Chart: Update axis label.alignment topic
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/label/alignment.md
Labels: 25_1

#7510 LoadPanel: Add Show on Page Load How To topic (#7504)
  concepts/05 UI Components/LoadPanel/20 Show on Page Load.md
Labels: cherry-pick, 24_2

#7511 CardView: Update Overview (Part 2)
  concepts/05 UI Components/CardView/00 Overview/10 Key Features.md
Labels: 25_1

#7464 Stepper: Add Form Integration How To topic
  concepts/05 UI Components/Stepper/30 Implement a Wizard/00 Implement a Wizard.md
  concepts/05 UI Components/Stepper/30 Implement a Wizard/05 Set Up App Layout.md
  concepts/05 UI Components/Stepper/30 Implement a Wizard/10 Synchronize Steps and Navigation Panel.md
  concepts/05 UI Components/Stepper/30 Implement a Wizard/15 Implement Validation.md
  images/Stepper/stepper-wizard.png
Labels: 25_1

#7509 Chart: Update maxValueMargin & label.position info
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/maxValueMargin.md
  api-reference/10 UI Components/dxChart/1 Configuration/commonAxisSettings/minValueMargin.md
  api-reference/10 UI Components/dxChart/5 Series Types/CommonSeries/label/position.md
Labels: 25_1

#7517 Validation: Fix message code snippet for React
  includes/uiwidgets-ref-validation-message.md
Labels: 25_1

#7518 Validation: Fix message code snippet for React (#7517)
  includes/uiwidgets-ref-validation-message.md
Labels: cherry-pick, 24_2

#7524 Grids: Add dataSource summary & sort info to note (#7516)
  api-reference/10 UI Components/GridBase/1 Configuration/dataSource.md
  includes/common-dataSource-description.md
Labels: cherry-pick, 24_2

#7527 FileUploader: update Overview (#7519)
  concepts/05 UI Components/FileUploader/00 Overview/05 Elements.md
  concepts/05 UI Components/FileUploader/00 Overview/10 Key Features.md
Labels: cherry-pick, 24_2

#7521 Grids: Update onEditorPreparing & columns.formItem
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onEditorPreparing.md
  api-reference/_hidden/GridBaseColumn/formItem.md
Labels: 25_1

#7529 Grids: Update onEditorPreparing & columns.formItem (#7521)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onEditorPreparing.md
  api-reference/_hidden/GridBaseColumn/formItem.md
Labels: cherry-pick, 24_2

#7526 Grids: Update columns.calculateSortValue note
  api-reference/_hidden/GridBaseColumn/calculateSortValue.md
Labels: 25_1

#7530 PivotGrid: update Overview
  concepts/05 UI Components/PivotGrid/02 Overview/05 Elements.md
  concepts/05 UI Components/PivotGrid/02 Overview/10 Key Features.md
Labels: 25_1

#7533 DataGrid: Add pageSize info to scrolling.mode
  api-reference/10 UI Components/dxDataGrid/1 Configuration/scrolling/mode.md
Labels: 25_1

#7537 PivotGrid: update Overview (#7530)
  concepts/05 UI Components/PivotGrid/02 Overview/05 Elements.md
  concepts/05 UI Components/PivotGrid/02 Overview/10 Key Features.md
Labels: cherry-pick, 24_2

#7532 Grids: Add headerFilter blank item note
  api-reference/10 UI Components/GridBase/1 Configuration/headerFilter/headerFilter.md
  api-reference/_hidden/GridBaseColumn/lookup/displayExpr.md
Labels: 25_1
