Repository DevExpress/devextreme-documentation, pull requests merged in 2025-03, with the labels that each got.

#7100 DataGrid: add info about (Blanks) in headerFilter
  api-reference/10 UI Components/GridBase/1 Configuration/headerFilter/headerFilter.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/2 Header Filter.md
Labels: 24_2

#7101 Form: add a useActionState submitting example
  concepts/05 UI Components/Form/01 Getting Started with Form/80 Submit the Form.md
Labels: 24_2

#7103 DataGrid: add info about (Blanks) in headerFilter (#7100)
  api-reference/10 UI Components/GridBase/1 Configuration/headerFilter/headerFilter.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/2 Header Filter.md
Labels: cherry-pick, 24_1

#7104 DataGrid: add info about (Blanks) in headerFilter (#7100)
  api-reference/10 UI Components/GridBase/1 Configuration/headerFilter/headerFilter.md
  concepts/05 UI Components/DataGrid/30 Filtering and Searching/2 Header Filter.md
Labels: cherry-pick, 25_1

#7105 Form: add a useActionState submitting example (#7101)
  concepts/05 UI Components/Form/01 Getting Started with Form/80 Submit the Form.md
Labels: cherry-pick, 24_1

#7106 Form: add a useActionState submitting example (#7101)
  concepts/05 UI Components/Form/01 Getting Started with Form/80 Submit the Form.md
Labels: cherry-pick, 25_1

#7099 DataGrid: update onEditorPreparing
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onEditorPreparing.md
Labels: 24_2

#7112 DataGrid: update onEditorPreparing (#7099)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onEditorPreparing.md
Labels: cherry-pick, 24_1

#7113 DataGrid: update onEditorPreparing (#7099)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/onEditorPreparing.md
Labels: cherry-pick, 25_1

#7114 Remove the insecure word
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/08 Register 3rd-Party Dependencies/02 Globalize Registration.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/63 Register 3rd-Party Dependencies/2 Globalize Registration.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/localization/globalize/globalize.md
Labels: 24_2

#7116 Remove the insecure word (#7114)
  concepts/40 Angular Components/10 Getting Started/03 Add DevExtreme to an Angular CLI Application/08 Register 3rd-Party Dependencies/02 Globalize Registration.md
  concepts/55 Vue Components/05 Add DevExtreme to a Vue Application/63 Register 3rd-Party Dependencies/2 Globalize Registration.md
  concepts/Common/Localization/05 Localize Dates, Numbers, and Currencies/10 Using Globalize.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/localization/globalize/globalize.md
Labels: cherry-pick, 25_1

#7117 Chart: add a note to animation
  api-reference/10 UI Components/BaseChart/1 Configuration/animation/animation.md
Labels: 24_2

#7119 Chart: add a note to animation (#7117)
  api-reference/10 UI Components/BaseChart/1 Configuration/animation/animation.md
Labels: cherry-pick, 25_1

#7128 FilterBuilder: add the FieldInfo type (#7127)
  api-reference/10 UI Components/dxFilterBuilder/9 Types/FieldInfo/FieldInfo.md
  api-reference/10 UI Components/dxFilterBuilder/9 Types/FieldInfo/field.md
  api-reference/10 UI Components/dxFilterBuilder/9 Types/FieldInfo/value.md
  api-reference/10 UI Components/dxFilterBuilder/9 Types/FieldInfo/valueText.md
  api-reference/NewTopics/FieldInfo/valueText.md
Labels: cherry-pick, 25_1

#7132 Troubleshooting: remove 'Bootstrap 4 or earlier'
  concepts/80 Troubleshooting/30 3rd-Party Framework Issues/05 Bootstrap/05 Modals.md
Labels: 24_2

#7133 Troubleshooting: remove 'Bootstrap 4 or earlier' (#7132)
  concepts/80 Troubleshooting/30 3rd-Party Framework Issues/05 Bootstrap/05 Modals.md
Labels: cherry-pick, 24_1

#7134 Troubleshooting: remove 'Bootstrap 4 or earlier' (#7132)
  concepts/80 Troubleshooting/30 3rd-Party Framework Issues/05 Bootstrap/05 Modals.md
Labels: cherry-pick, 25_1

#7131 DataGrid: add a note about _DX_KEY_
  api-reference/10 UI Components/dxDataGrid/1 Configuration/editing/changes/key.md
Labels: 24_2

#7135 DataGrid: add a note about _DX_KEY_ (#7131)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/editing/changes/key.md
Labels: cherry-pick, 24_1

#7136 DataGrid: add a note about _DX_KEY_ (#7131)
  api-reference/10 UI Components/dxDataGrid/1 Configuration/editing/changes/key.md
Labels: cherry-pick, 25_1

#7123 Chat: add Data Binding section
  concepts/05 UI Components/Chat/11 Data Binding.md
Labels: 24_2

#7137 Chat: add Data Binding section (#7123)
  concepts/05 UI Components/Chat/11 Data Binding.md
Labels: cherry-pick, 25_1

#7097 Licensing: change the structure
  api-reference/50 Common/Object Structures/GlobalConfig/licenseKey.md
  concepts/Common/Licensing/00 Licensing.md
  concepts/Common/Licensing/09 Obtain Your License Key.md
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
  concepts/Common/Licensing/10 Validate Your License Key/00 Validate Your License Key.md
  concepts/Common/Licensing/10 Validate Your License Key/10 Manual Configuration/00 Manual Configuration.md
  concepts/Common/Licensing/10 Validate Your License Key/10 Manual Configuration/05 Modular.md
  concepts/Common/Licensing/10 Validate Your License Key/10 Manual Configuration/10 Non-Modular.md
  concepts/Common/Licensing/10 Validate Your License Key/15 Automated License Key File Creation.md
  concepts/Common/Licensing/10 Validate Your License Key/20 Storing the License Key in a Global Window Object.md
  concepts/Common/Licensing/10 Validate Your License Key/25 Module Federation Specifics.md
  concepts/Common/Licensing/10 Validate Your License Key/30 Next.js Specifics.md
Labels: 24_2

#7142 Licensing: change the structure (#7097)
  api-reference/50 Common/Object Structures/GlobalConfig/licenseKey.md
  concepts/Common/Licensing/00 Licensing.md
  concepts/Common/Licensing/09 Obtain Your License Key.md
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
  concepts/Common/Licensing/10 Validate Your License Key/00 Validate Your License Key.md
  concepts/Common/Licensing/10 Validate Your License Key/10 Manual Configuration/00 Manual Configuration.md
  concepts/Common/Licensing/10 Validate Your License Key/10 Manual Configuration/05 Modular.md
  concepts/Common/Licensing/10 Validate Your License Key/10 Manual Configuration/10 Non-Modular.md
  concepts/Common/Licensing/10 Validate Your License Key/15 Automated License Key File Creation.md
  concepts/Common/Licensing/10 Validate Your License Key/20 Storing the License Key in a Global Window Object.md
  concepts/Common/Licensing/10 Validate Your License Key/25 Module Federation Specifics.md
  concepts/Common/Licensing/10 Validate Your License Key/30 Next.js Specifics.md
Labels: cherry-pick, 25_1

#7143 Licensing: change the structure (#7097)
  api-reference/50 Common/Object Structures/GlobalConfig/licenseKey.md
  concepts/Common/Licensing/00 Licensing.md
  concepts/Common/Licensing/09 Obtain Your License Key.md
  concepts/Common/Licensing/10 How to Obtain and Validate Your License Key.md
  concepts/Common/Licensing/10 Validate Your License Key/00 Validate Your License Key.md
  concepts/Common/Licensing/10 Validate Your License Key/10 Manual Configuration/00 Manual Configuration.md
  concepts/Common/Licensing/10 Validate Your License Key/10 Manual Configuration/05 Modular.md
  concepts/Common/Licensing/10 Validate Your License Key/10 Manual Configuration/10 Non-Modular.md
  concepts/Common/Licensing/10 Validate Your License Key/15 Automated License Key File Creation.md
  concepts/Common/Licensing/10 Validate Your License Key/20 Storing the License Key in a Global Window Object.md
  concepts/Common/Licensing/10 Validate Your License Key/25 Module Federation Specifics.md
  concepts/Common/Licensing/10 Validate Your License Key/30 Next.js Specifics.md
Labels: cherry-pick, 24_1

#7138 Add topics for Stepper
  api-reference/10 UI Components/dxStepper/1 Configuration/Configuration.md
  api-reference/10 UI Components/dxStepper/1 Configuration/activeStateEnabled.md
  api-reference/10 UI Components/dxStepper/1 Configuration/dataSource.md
  api-reference/10 UI Components/dxStepper/1 Configuration/focusStateEnabled.md
  api-reference/10 UI Components/dxStepper/1 Configuration/hoverStateEnabled.md
  api-reference/10 UI Components/dxStepper/1 Configuration/itemHoldTimeout.md
  api-reference/10 UI Components/dxStepper/1 Configuration/items.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onContentReady.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onDisposing.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onInitialized.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onItemClick.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onItemContextMenu.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onItemHold.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onItemRendered.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onOptionChanged.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onSelectionChanged.md
  api-reference/10 UI Components/dxStepper/1 Configuration/onSelectionChanging.md
  api-reference/10 UI Components/dxStepper/1 Configuration/orientation.md
  api-reference/10 UI Components/dxStepper/1 Configuration/selectOnFocus.md
  api-reference/10 UI Components/dxStepper/1 Configuration/selectedItems.md
  api-reference/10 UI Components/dxStepper/1 Configuration/selectionMode.md
  api-reference/10 UI Components/dxStepper/4 Events/Events.md
  api-reference/10 UI Components/dxStepper/4 Events/contentReady.md
  api-reference/10 UI Components/dxStepper/4 Events/itemHold.md
  api-reference/10 UI Components/dxStepper/7 Interfaces/Interfaces.md
  api-reference/10 UI Components/dxStepper/7 Interfaces/dxStepperItem/dxStepperItem.md
  api-reference/10 UI Components/dxStepper/7 Interfaces/dxStepperItem/html.md
  api-reference/10 UI Components/dxStepper/7 Interfaces/dxStepperItem/visible.md
  api-reference/10 UI Components/dxStepper/9 Types/DisposingEvent/DisposingEvent.md
  api-reference/10 UI Components/dxStepper/9 Types/InitializedEvent/InitializedEvent.md
  api-reference/10 UI Components/dxStepper/9 Types/ItemClickEvent/ItemClickEvent.md
  api-reference/10 UI Components/dxStepper/9 Types/ItemContextMenuEvent/ItemContextMenuEvent.md
  api-reference/10 UI Components/dxStepper/9 Types/ItemRenderedEvent/ItemRenderedEvent.md
  api-reference/10 UI Components/dxStepper/9 Types/OptionChangedEvent/OptionChangedEvent.md
  api-reference/10 UI Components/dxStepper/9 Types/SelectionChangedEvent/SelectionChangedEvent.md
  api-reference/10 UI Components/dxStepper/9 Types/SelectionChangingEvent/SelectionChangingEvent.md
  api-reference/10 UI Components/dxStepper/9 Types/Types.md
  api-reference/10 UI Components/dxStepper/dxStepper.md
  api-reference/40 Common Types/Orientation.md
  concepts/Common/Modularity/02 DevExtreme Modules Structure/ui/stepper.md
  metadata/syntax-data.json
  typesPathMap.json
Labels: 25_1

#7151 TreeView: update createChildren
  api-reference/10 UI Components/dxTreeView/1 Configuration/createChildren.md
Labels: 24_2

#7152 TreeView: update createChildren (#7151)
  api-reference/10 UI Components/dxTreeView/1 Configuration/createChildren.md
Labels: cherry-pick, 24_1

#6930 Update doc structure
  MenuConfig.xml
Labels: 24_2

#7155 Update doc structure (#6930)
  MenuConfig.xml
Labels: cherry-pick, 25_1

#7149 Icons: add addpackagebox,checkmarkcircle, clipboardtasklist, csv icons to project
  applications/Icons/script.js
Labels: 25_1

#7160 Map: remove "text" from addMarker
  api-reference/10 UI Components/dxMap/3 Methods/addMarker(markerOptions).md
Labels: 24_2

#7162 Map: remove "text" from addMarker (#7160)
  api-reference/10 UI Components/dxMap/3 Methods/addMarker(markerOptions).md
Labels: cherry-pick, 25_1

#7163 Grids: update defaultSetCellValue
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: 24_2

#7165 Grids: update defaultSetCellValue (#7163)
  api-reference/_hidden/GridBaseColumn/setCellValue.md
Labels: cherry-pick, 25_1

#7167 Add today icon
  applications/Icons/script.js
Labels: 25_1

#7169 Form: add info about label location (#7168)
  api-reference/10 UI Components/dxForm/1 Configuration/alignItemLabels.md
  api-reference/10 UI Components/dxForm/1 Configuration/alignItemLabelsInAllGroups.md
Labels: cherry-pick, 24_1

#7170 Form: add info about label location (#7168)
  api-reference/10 UI Components/dxForm/1 Configuration/alignItemLabels.md
  api-reference/10 UI Components/dxForm/1 Configuration/alignItemLabelsInAllGroups.md
Labels: cherry-pick, 25_1
